"""Venue error classifications for prediction markets, sports, and analytics platforms."""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_SPORTS: dict[str, list[VenueErrorClassification]] = {
    "instadapp": [
        ve(
            "instadapp",
            "DS_PROXY_EXEC_FAILED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="DSProxy execution failed — revert in spell",
        ),
        ve(
            "instadapp",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "instadapp",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "instadapp",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "instadapp",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "defillama": [
        ve(
            "defillama",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "defillama",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Protocol or chain not found",
        ),
        ve(
            "defillama",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "defillama",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
    ],
    # --- Plan-specified additional venues ---
    "polymarket": [
        ve(
            "polymarket",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "polymarket",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key or signature",
        ),
        ve(
            "polymarket",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "polymarket",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "betfair": [
        ve(
            "betfair",
            "INVALID_SESSION_INFORMATION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Session token invalid or expired — reauthenticate",
        ),
        ve(
            "betfair",
            "NO_SESSION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="No active session — reauthenticate",
        ),
        ve(
            "betfair",
            "TOO_MUCH_DATA",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Response too large — reduce request scope",
        ),
        ve(
            "betfair",
            "SERVICE_BUSY",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Betfair API service busy — retry with backoff",
        ),
        ve(
            "betfair",
            "TIMEOUT_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Request timed out on Betfair side",
        ),
        ve(
            "betfair",
            "REQUEST_SIZE_EXCEEDS_LIMIT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Request payload exceeds size limit",
        ),
    ],
    "kalshi": [
        ve(
            "kalshi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "kalshi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid or expired token",
        ),
        ve(
            "kalshi",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — insufficient permissions",
        ),
        ve(
            "kalshi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "kalshi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "kalshi",
            "MARKET_NOT_OPEN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market is not open for trading",
        ),
        ve(
            "kalshi",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Account balance insufficient for order",
        ),
    ],
    "smarkets": [
        ve(
            "smarkets",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "smarkets",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        ve(
            "smarkets",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "smarkets",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "smarkets",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        ve(
            "smarkets",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
    "betdaq": [
        ve(
            "betdaq",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "betdaq",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        ve(
            "betdaq",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "betdaq",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "betdaq",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        ve(
            "betdaq",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
    "glassnode": [
        ve(
            "glassnode",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "glassnode",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "glassnode",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — metric requires higher tier",
        ),
        ve(
            "glassnode",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid metric or parameter",
        ),
        ve(
            "glassnode",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "arkham": [
        ve(
            "arkham",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "arkham",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "arkham",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid address or parameter",
        ),
        ve(
            "arkham",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Entity or address not found",
        ),
        ve(
            "arkham",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- Generic / cross-cutting error groups ---
    "onchain_revert": [
        ve(
            "onchain_revert",
            "EXECUTION_REVERTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="EVM transaction reverted — contract logic rejected the call",
        ),
        ve(
            "onchain_revert",
            "OUT_OF_GAS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction ran out of gas — increase gas limit",
        ),
        ve(
            "onchain_revert",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Sender has insufficient ETH for gas + value",
        ),
        ve(
            "onchain_revert",
            "NONCE_TOO_LOW",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction nonce already used — resync nonce",
        ),
    ],
    "sports_generic": [
        ve(
            "sports_generic",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        ve(
            "sports_generic",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
        ve(
            "sports_generic",
            "COMPETITION_CLOSED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Competition closed — all markets settled",
        ),
        ve(
            "sports_generic",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "sports_generic",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "sports_generic",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
}
