"""
Cloud SDK Type Protocols and Pydantic Schemas

Protocol definitions for AWS (boto3) and GCP cloud SDK clients.
Pydantic request/response schemas for AWS APIs (EC2, ECS, Lambda, S3, Glue, Service Quotas).
Quota broker schemas for centralized quota management.
"""

from .aws import S3ClientProtocol, SecretsManagerClientProtocol
from .aws_schemas import (
    EC2DescribeInstancesRequest,
    EC2DescribeInstancesResponse,
    EC2Instance,
    EC2RunInstancesRequest,
    EC2RunInstancesResponse,
    ECSDescribeTasksRequest,
    ECSDescribeTasksResponse,
    ECSRunTaskRequest,
    ECSRunTaskResponse,
    GlueCreateTableRequest,
    GlueCreateTableResponse,
    GlueGetDatabaseRequest,
    GlueGetDatabaseResponse,
    GlueGetTableRequest,
    GlueGetTableResponse,
    GlueGetTablesRequest,
    GlueGetTablesResponse,
    LambdaInvokeRequest,
    LambdaInvokeResponse,
    S3CreateBucketRequest,
    S3CreateBucketResponse,
    S3GetObjectRequest,
    S3GetObjectResponse,
    S3ListObjectsV2Request,
    S3ListObjectsV2Response,
    S3PutObjectRequest,
    S3PutObjectResponse,
    ServiceQuota,
    ServiceQuotasGetServiceQuotaRequest,
    ServiceQuotasGetServiceQuotaResponse,
    ServiceQuotasListServiceQuotasRequest,
    ServiceQuotasListServiceQuotasResponse,
)
from .gcp import (
    BigQueryClientProtocol,
    SecretManagerServiceClientProtocol,
    StorageClientProtocol,
)
from .quota_broker import (
    QuotaBrokerAcquireRequest,
    QuotaBrokerAcquireResult,
    QuotaBrokerLiveQuotasRequest,
    QuotaBrokerLiveQuotasResponse,
    QuotaBrokerReleaseRequest,
    QuotaBrokerReleaseResponse,
    QuotaExceededMessage,
)
from .schemas import (
    ArtifactRegistryQuotaUsage,
    BqQuotaUsage,
    CloudLoggingQuotaUsage,
    GcpCloudRunQuotaUsage,
    GcpComputeQuotaUsage,
    GcsQuotaUsage,
)

__all__ = [
    "ArtifactRegistryQuotaUsage",
    "BigQueryClientProtocol",
    "BqQuotaUsage",
    "CloudLoggingQuotaUsage",
    "EC2DescribeInstancesRequest",
    "EC2DescribeInstancesResponse",
    "EC2Instance",
    "EC2RunInstancesRequest",
    "EC2RunInstancesResponse",
    "ECSDescribeTasksRequest",
    "ECSDescribeTasksResponse",
    "ECSRunTaskRequest",
    "ECSRunTaskResponse",
    "GcpCloudRunQuotaUsage",
    "GcpComputeQuotaUsage",
    "GcsQuotaUsage",
    "GlueCreateTableRequest",
    "GlueCreateTableResponse",
    "GlueGetDatabaseRequest",
    "GlueGetDatabaseResponse",
    "GlueGetTableRequest",
    "GlueGetTableResponse",
    "GlueGetTablesRequest",
    "GlueGetTablesResponse",
    "LambdaInvokeRequest",
    "LambdaInvokeResponse",
    "QuotaBrokerAcquireRequest",
    "QuotaBrokerAcquireResult",
    "QuotaBrokerLiveQuotasRequest",
    "QuotaBrokerLiveQuotasResponse",
    "QuotaBrokerReleaseRequest",
    "QuotaBrokerReleaseResponse",
    "QuotaExceededMessage",
    "S3ClientProtocol",
    "S3CreateBucketRequest",
    "S3CreateBucketResponse",
    "S3GetObjectRequest",
    "S3GetObjectResponse",
    "S3ListObjectsV2Request",
    "S3ListObjectsV2Response",
    "S3PutObjectRequest",
    "S3PutObjectResponse",
    "SecretManagerServiceClientProtocol",
    "SecretsManagerClientProtocol",
    "ServiceQuota",
    "ServiceQuotasGetServiceQuotaRequest",
    "ServiceQuotasGetServiceQuotaResponse",
    "ServiceQuotasListServiceQuotasRequest",
    "ServiceQuotasListServiceQuotasResponse",
    "StorageClientProtocol",
]
