"""
AWS Cloud SDK (boto3) backward-compat re-exports.

All concrete schema classes have been moved to sub-modules under aws/.
This module re-exports everything for consumers that imported from aws_schemas.
"""

from __future__ import annotations

from api_contracts.api_contracts_external.cloud_sdks.aws.cloudwatch import (
    CloudWatchAlarm,
    CloudWatchFilterLogEventsRequest,
    CloudWatchGetLogEventsRequest,
    CloudWatchGetMetricStatisticsRequest,
    CloudWatchInsightsQuery,
    CloudWatchLogEvent,
    CloudWatchLogGroup,
    CloudWatchLogsQuotaUsage,
    CloudWatchLogStream,
    CloudWatchMetricDatapoint,
    CloudWatchMetricDimension,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.codebuild import (
    CodeBuildBuild,
    CodeBuildProject,
    CodeBuildStartBuildRequest,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.cognito import (
    CognitoAuthRequest,
    CognitoAuthResponse,
    CognitoGetCredentialsResponse,
    CognitoIdentityPool,
    CognitoUser,
    CognitoUserPool,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.common import (
    AwsErrorResponse,
    AwsQuotaUsage,
    EC2QuotaInfo,
    ECSQuotaInfo,
    LambdaQuotaInfo,
    S3QuotaInfo,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.cost_explorer import (
    CostExplorerBudget,
    CostExplorerDateInterval,
    CostExplorerGetCostRequest,
    CostExplorerGetCostResponse,
    CostExplorerResultByTime,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.dynamodb import (
    DynamoDbGetItemRequest,
    DynamoDbPutItemRequest,
    DynamoDbQueryRequest,
    DynamoDbQueryResponse,
    DynamoDbQuotaUsage,
    DynamoDbStreamRecord,
    DynamoDbTableDescription,
    DynamoDbTransactWriteRequest,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.ec2 import (
    EC2DescribeInstancesRequest,
    EC2DescribeInstancesResponse,
    EC2Instance,
    EC2InstanceState,
    EC2InstanceStateChange,
    EC2Reservation,
    EC2RunInstancesRequest,
    EC2RunInstancesResponse,
    EC2StartInstancesRequest,
    EC2StartStopTerminateResponse,
    EC2StopInstancesRequest,
    EC2TerminateInstancesRequest,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.ecr import (
    EcrGetAuthorizationTokenResponse,
    EcrImage,
    EcrLifecyclePolicy,
    EcrRepository,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.ecs import (
    ECSDescribeTasksRequest,
    ECSDescribeTasksResponse,
    ECSRunTaskRequest,
    ECSRunTaskResponse,
    ECSTask,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.eventbridge import (
    EventBridgePutEventsRequest,
    EventBridgePutEventsResponse,
    EventBridgeRule,
    EventBridgeTarget,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.glue import (
    GlueCreateTableRequest,
    GlueCreateTableResponse,
    GlueDatabase,
    GlueGetDatabaseRequest,
    GlueGetDatabaseResponse,
    GlueGetTableRequest,
    GlueGetTableResponse,
    GlueGetTablesRequest,
    GlueGetTablesResponse,
    GlueTable,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.iam import (
    AwsAssumeRoleRequest,
    AwsAssumeRoleResponse,
    AwsIamAccessKey,
    AwsIamPolicy,
    AwsIamPolicyDocument,
    AwsIamRole,
    AwsIamUser,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.lambda_ import (
    LambdaInvokeRequest,
    LambdaInvokeResponse,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.s3 import (
    S3CreateBucketRequest,
    S3CreateBucketResponse,
    S3GetObjectRequest,
    S3GetObjectResponse,
    S3ListObjectsV2Request,
    S3ListObjectsV2Response,
    S3ObjectOwner,
    S3ObjectSummary,
    S3PutObjectRequest,
    S3PutObjectResponse,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.secrets_manager import (
    SecretsManagerCreateSecretRequest,
    SecretsManagerGetSecretValueRequest,
    SecretsManagerGetSecretValueResponse,
    SecretsManagerSecret,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.service_quotas import (
    ServiceQuota,
    ServiceQuotasErrorDetail,
    ServiceQuotasErrorResponse,
    ServiceQuotasGetServiceQuotaRequest,
    ServiceQuotasGetServiceQuotaResponse,
    ServiceQuotasListServiceQuotasRequest,
    ServiceQuotasListServiceQuotasResponse,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.sns import (
    SnsPublishRequest,
    SnsSubscription,
    SnsTopic,
)
from api_contracts.api_contracts_external.cloud_sdks.aws.sqs import (
    SqsMessage,
    SqsQueueAttributes,
    SqsReceiveMessageRequest,
    SqsSendMessageRequest,
    SqsSendMessageResponse,
)

__all__ = [
    "AwsAssumeRoleRequest",
    "AwsAssumeRoleResponse",
    "AwsErrorResponse",
    "AwsIamAccessKey",
    "AwsIamPolicy",
    "AwsIamPolicyDocument",
    "AwsIamRole",
    "AwsIamUser",
    "AwsQuotaUsage",
    "CloudWatchAlarm",
    "CloudWatchFilterLogEventsRequest",
    "CloudWatchGetLogEventsRequest",
    "CloudWatchGetMetricStatisticsRequest",
    "CloudWatchInsightsQuery",
    "CloudWatchLogEvent",
    "CloudWatchLogGroup",
    "CloudWatchLogStream",
    "CloudWatchLogsQuotaUsage",
    "CloudWatchMetricDatapoint",
    "CloudWatchMetricDimension",
    "CodeBuildBuild",
    "CodeBuildProject",
    "CodeBuildStartBuildRequest",
    "CognitoAuthRequest",
    "CognitoAuthResponse",
    "CognitoGetCredentialsResponse",
    "CognitoIdentityPool",
    "CognitoUser",
    "CognitoUserPool",
    "CostExplorerBudget",
    "CostExplorerDateInterval",
    "CostExplorerGetCostRequest",
    "CostExplorerGetCostResponse",
    "CostExplorerResultByTime",
    "DynamoDbGetItemRequest",
    "DynamoDbPutItemRequest",
    "DynamoDbQueryRequest",
    "DynamoDbQueryResponse",
    "DynamoDbQuotaUsage",
    "DynamoDbStreamRecord",
    "DynamoDbTableDescription",
    "DynamoDbTransactWriteRequest",
    "EC2DescribeInstancesRequest",
    "EC2DescribeInstancesResponse",
    "EC2Instance",
    "EC2InstanceState",
    "EC2InstanceStateChange",
    "EC2QuotaInfo",
    "EC2Reservation",
    "EC2RunInstancesRequest",
    "EC2RunInstancesResponse",
    "EC2StartInstancesRequest",
    "EC2StartStopTerminateResponse",
    "EC2StopInstancesRequest",
    "EC2TerminateInstancesRequest",
    "ECSDescribeTasksRequest",
    "ECSDescribeTasksResponse",
    "ECSQuotaInfo",
    "ECSRunTaskRequest",
    "ECSRunTaskResponse",
    "ECSTask",
    "EcrGetAuthorizationTokenResponse",
    "EcrImage",
    "EcrLifecyclePolicy",
    "EcrRepository",
    "EventBridgePutEventsRequest",
    "EventBridgePutEventsResponse",
    "EventBridgeRule",
    "EventBridgeTarget",
    "GlueCreateTableRequest",
    "GlueCreateTableResponse",
    "GlueDatabase",
    "GlueGetDatabaseRequest",
    "GlueGetDatabaseResponse",
    "GlueGetTableRequest",
    "GlueGetTableResponse",
    "GlueGetTablesRequest",
    "GlueGetTablesResponse",
    "GlueTable",
    "LambdaInvokeRequest",
    "LambdaInvokeResponse",
    "LambdaQuotaInfo",
    "S3CreateBucketRequest",
    "S3CreateBucketResponse",
    "S3GetObjectRequest",
    "S3GetObjectResponse",
    "S3ListObjectsV2Request",
    "S3ListObjectsV2Response",
    "S3ObjectOwner",
    "S3ObjectSummary",
    "S3PutObjectRequest",
    "S3PutObjectResponse",
    "S3QuotaInfo",
    "SecretsManagerCreateSecretRequest",
    "SecretsManagerGetSecretValueRequest",
    "SecretsManagerGetSecretValueResponse",
    "SecretsManagerSecret",
    "ServiceQuota",
    "ServiceQuotasErrorDetail",
    "ServiceQuotasErrorResponse",
    "ServiceQuotasGetServiceQuotaRequest",
    "ServiceQuotasGetServiceQuotaResponse",
    "ServiceQuotasListServiceQuotasRequest",
    "ServiceQuotasListServiceQuotasResponse",
    "SnsPublishRequest",
    "SnsSubscription",
    "SnsTopic",
    "SqsMessage",
    "SqsQueueAttributes",
    "SqsReceiveMessageRequest",
    "SqsSendMessageRequest",
    "SqsSendMessageResponse",
]
