"""Canonical normalised schemas: one-hop normalisation from raw venue responses.

Domain: CanonicalOrderBook, CanonicalTrade, InstrumentWarehouseRow, etc.
Execution: CanonicalOrder, CanonicalFill, ExecutionInstruction, etc.
Errors: CanonicalError, CanonicalRateLimitError (grouped).

Self-contained: no imports from unified_api_contracts.internal.

Note: InstrumentWarehouseRow was renamed from InstrumentRecord to avoid collision
with UIC's InstrumentRecord (31-field, Decimal, normalized adapter contract).
"""

from .domain import (
    BookLevel,
    CanonicalAccountSnapshot,
    CanonicalBalance,
    CanonicalBetMarket,
    CanonicalBetOrder,
    CanonicalBondData,
    CanonicalCdsSpread,
    CanonicalComboBet,
    CanonicalComboLeg,
    CanonicalDerivativeTicker,
    CanonicalFee,
    CanonicalFundingRate,
    CanonicalLiquidation,
    CanonicalLiquidationCluster,
    CanonicalMarketInfo,
    CanonicalMarketStateEvent,
    CanonicalOdds,
    CanonicalOhlcvBar,
    CanonicalOnChainMetric,
    CanonicalOptionsChainEntry,
    CanonicalOraclePriceFeed,
    CanonicalOrderBook,
    CanonicalPosition,
    CanonicalSettlement,
    CanonicalTicker,
    CanonicalTrade,
    CanonicalWebSocketLifecycle,
    CanonicalWsMessage,
    CanonicalYieldCurvePoint,
    FeeType,
    InstructionType,
    InstrumentType,
    InstrumentWarehouseRow,
    MarketState,
    MarketTrade,
    OddsFormat,
    OptionType,
    OrderBookSnapshot5,
    ProcessedCandle,
    WebSocketEvent,
)
from .errors import CanonicalError, CanonicalRateLimitError
from .execution import (
    CanonicalAccountState,
    CanonicalFill,
    CanonicalMarginState,
    CanonicalOrder,
    CanonicalOrderAmendment,
    CanonicalOrderRejection,
    ExecutionInstruction,
    ExecutionResult,
    OrderSide,
    OrderStatus,
    OrderType,
)
from .odds import american_to_decimal, decimal_to_american

__all__ = [
    "BookLevel",
    "CanonicalAccountSnapshot",
    "CanonicalAccountState",
    "CanonicalBalance",
    "CanonicalBetMarket",
    "CanonicalBetOrder",
    "CanonicalBondData",
    "CanonicalCdsSpread",
    "CanonicalComboBet",
    "CanonicalComboLeg",
    "CanonicalDerivativeTicker",
    "CanonicalError",
    "CanonicalFee",
    "CanonicalFill",
    "CanonicalFundingRate",
    "CanonicalLiquidation",
    "CanonicalLiquidationCluster",
    "CanonicalMarginState",
    "CanonicalMarketInfo",
    "CanonicalMarketStateEvent",
    "CanonicalOdds",
    "CanonicalOhlcvBar",
    "CanonicalOnChainMetric",
    "CanonicalOptionsChainEntry",
    "CanonicalOraclePriceFeed",
    "CanonicalOrder",
    "CanonicalOrderAmendment",
    "CanonicalOrderBook",
    "CanonicalOrderRejection",
    "CanonicalPosition",
    "CanonicalRateLimitError",
    "CanonicalSettlement",
    "CanonicalTicker",
    "CanonicalTrade",
    "CanonicalWebSocketLifecycle",
    "CanonicalWsMessage",
    "CanonicalYieldCurvePoint",
    "ExecutionInstruction",
    "ExecutionResult",
    "FeeType",
    "InstructionType",
    "InstrumentType",
    # InstrumentWarehouseRow — renamed from InstrumentRecord to avoid collision with UIC's InstrumentRecord
    "InstrumentWarehouseRow",
    "MarketState",
    "MarketTrade",
    "OddsFormat",
    "OptionType",
    "OrderBookSnapshot5",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "ProcessedCandle",
    "WebSocketEvent",
    "american_to_decimal",
    "decimal_to_american",
]
