"""API-Football contracts."""

from .schemas import (
    ApiFootballError,
    ApiFootballEvent,
    ApiFootballEventTime,
    ApiFootballFixture,
    ApiFootballFixtureStatistics,
    ApiFootballFixtureStatus,
    ApiFootballInjury,
    ApiFootballLeague,
    ApiFootballLineup,
    ApiFootballLineupPlayer,
    ApiFootballOdds,
    ApiFootballOddsBet,
    ApiFootballOddsBookmaker,
    ApiFootballOddsValue,
    ApiFootballPeriods,
    ApiFootballPlayerStat,
    ApiFootballRateLimit,
    ApiFootballScore,
    ApiFootballScoreFull,
    ApiFootballStanding,
    ApiFootballStat,
    ApiFootballTeam,
    ApiFootballTeamWithWinner,
    ApiFootballVenue,
)

__all__ = [
    "ApiFootballError",
    "ApiFootballEvent",
    "ApiFootballEventTime",
    "ApiFootballFixture",
    "ApiFootballFixtureStatistics",
    "ApiFootballFixtureStatus",
    "ApiFootballInjury",
    "ApiFootballLeague",
    "ApiFootballLineup",
    "ApiFootballLineupPlayer",
    "ApiFootballOdds",
    "ApiFootballOddsBet",
    "ApiFootballOddsBookmaker",
    "ApiFootballOddsValue",
    "ApiFootballPeriods",
    "ApiFootballPlayerStat",
    "ApiFootballRateLimit",
    "ApiFootballScore",
    "ApiFootballScoreFull",
    "ApiFootballStanding",
    "ApiFootballStat",
    "ApiFootballTeam",
    "ApiFootballTeamWithWinner",
    "ApiFootballVenue",
]
