"""ImmediateSev0Override — closed set of conditions that bypass the normal state machine."""

from __future__ import annotations

from enum import StrEnum


class ImmediateSev0Override(StrEnum):
    UNKNOWN_NET_EXPOSURE = "UNKNOWN_NET_EXPOSURE"
    OPEN_ORDERS_UNCONFIRMABLE = "OPEN_ORDERS_UNCONFIRMABLE"
    KILL_SWITCH_CANNOT_CONFIRM_CANCEL = "KILL_SWITCH_CANNOT_CONFIRM_CANCEL"
    VENUE_INTERNAL_BALANCE_MISMATCH = "VENUE_INTERNAL_BALANCE_MISMATCH"
    POSITION_EXISTS_EXTERNALLY_UNKNOWN_INTERNALLY = "POSITION_EXISTS_EXTERNALLY_UNKNOWN_INTERNALLY"
    MATERIAL_BALANCE_MOVEMENT_UNEXPLAINED = "MATERIAL_BALANCE_MOVEMENT_UNEXPLAINED"
    MARGIN_COLLATERAL_SAFETY_UNCERTAIN = "MARGIN_COLLATERAL_SAFETY_UNCERTAIN"
