"""Internal request/response/error schemas."""

from unified_api_contracts.internal.schemas.contracts import (
    CEFI_FUTURES_CHAIN_TRADES,
    CEFI_OPTIONS_CHAIN_TRADES,
    CEFI_PERPETUAL_BOOK_SNAPSHOT_5,
    CEFI_PERPETUAL_TRADES,
    CONTRACT_REGISTRY,
    DEFI_DEX_POOL_DEX_POOL_SWAPS,
    DEFI_LENDING_POSITION_LENDING_INDICES,
    DEFI_LST_LST_RATES,
    TRADFI_EQUITY_TRADES,
    TRADFI_FUTURE_TRADES,
    TRADFI_OPTIONS_CHAIN_TRADES,
    ColumnSpec,
    SchemaContract,
    Violation,
    validate_dataframe,
)
from unified_api_contracts.internal.schemas.errors import (
    DeadLetterRecord,
    EnhancedError,
    ErrorCategory,
    ErrorContext,
    ErrorRecoveryStrategy,
    ErrorSeverity,
    StartupValidationError,
)
from unified_api_contracts.internal.schemas.rbac import (
    ROLE_PERMISSIONS,
    TIER_ENTITLEMENTS,
    Entitlement,
    OrgType,
    Permission,
    ProvisioningRole,
    SubscriptionTier,
    UserProfile,
    UserRole,
    has_role_permission,
)
from unified_api_contracts.internal.schemas.strategy import (
    StrategySpec,
    StrategyType,
)

__all__ = [
    "CEFI_FUTURES_CHAIN_TRADES",
    "CEFI_OPTIONS_CHAIN_TRADES",
    "CEFI_PERPETUAL_BOOK_SNAPSHOT_5",
    "CEFI_PERPETUAL_TRADES",
    "CONTRACT_REGISTRY",
    "DEFI_DEX_POOL_DEX_POOL_SWAPS",
    "DEFI_LENDING_POSITION_LENDING_INDICES",
    "DEFI_LST_LST_RATES",
    "ROLE_PERMISSIONS",
    "TIER_ENTITLEMENTS",
    "TRADFI_EQUITY_TRADES",
    "TRADFI_FUTURE_TRADES",
    "TRADFI_OPTIONS_CHAIN_TRADES",
    "ColumnSpec",
    "DeadLetterRecord",
    "EnhancedError",
    "Entitlement",
    "ErrorCategory",
    "ErrorContext",
    "ErrorRecoveryStrategy",
    "ErrorSeverity",
    "OrgType",
    "Permission",
    "ProvisioningRole",
    "SchemaContract",
    "StartupValidationError",
    "StrategySpec",
    "StrategyType",
    "SubscriptionTier",
    "UserProfile",
    "UserRole",
    "Violation",
    "has_role_permission",
    "validate_dataframe",
]
