"""Internal service contracts: inter-service communication and cloud infrastructure."""

from __future__ import annotations

from typing import TypedDict


class ContractEntry(TypedDict, total=False):
    module: str
    description: str
    is_internal: bool
    sub_modules: dict[str, str]
    response_schema_classes: list[str]
    error_schema_classes: list[str]
    pubsub_topics: dict[str, str]
    sor_schemas: list[str]
    has_rest: bool
    has_websocket: bool
    has_fix: bool
    has_vcr_cassettes: bool
    cassette_schema_version: str
    fix_versions: list[str]
    msg_type_map: dict[str, str]
    supported_providers: list[str]
    regimes: list[str]
    config_secret_field: str
    example_schema_map: dict[str, str]


INTERNAL_CONTRACTS: dict[str, ContractEntry] = {
    "internal": {
        "module": "api_contracts.internal",
        "description": (
            "Typed schemas for all data flowing between internal services: "
            "lifecycle events, Pub/Sub messages, domain data, orders/fills, "
            "risk alerts, feature vectors, ML predictions, health checks, "
            "circuit breakers, and config change notifications."
        ),
        "is_internal": True,
        "sub_modules": {
            "events": "Lifecycle event envelopes and per-event metadata (GCS JSONL + Pub/Sub)",
            "domain": "Instrument records, market ticks, order books, OHLCV, candles",
            "execution": "Orders, fills, execution instructions, execution results",
            "signals": "Strategy instructions, DeFi signals, GCS output records",
            "risk": "Risk metrics, alerts, exposure summaries, pre-trade checks, positions",
            "features": "Delta-one feature vectors, vol surface, futures term structure",
            "ml": "Model metadata, inference requests/results, training jobs",
            "health": "Health status, dependency checks, circuit breakers, error envelopes",
            "config": "Config store records, change notifications, active pointers",
            "pubsub": "Typed Pub/Sub message bodies for every internal topic",
        },
        "response_schema_classes": [
            "LifecycleEventEnvelope",
            "PubSubLifecycleEventMessage",
            "LifecycleEventType",
            "EventMetadata",
            "AuthFailureEvent",
            "ConfigChangedEvent",
            "SecretAccessedEvent",
            "StartedEvent",
            "FailedEvent",
            "InstrumentRecord",
            "MarketTrade",
            "OrderBookSnapshot5",
            "DerivativeTicker",
            "LiquidationRecord",
            "OhlcvBar",
            "QuoteRecord",
            "CanonicalOrderBook",
            "CanonicalTrade",
            "ProcessedCandle",
            "CanonicalOrder",
            "CanonicalFill",
            "FillEventPubSubPayload",
            "ExecutionInstruction",
            "ExecutionResult",
            "ManualInstructionRequest",
            "ManualInstructionResponse",
            "StrategyInstruction",
            "DeFiSignal",
            "InstructionRecord",
            "DeFiSignalRecord",
            "RiskMetrics",
            "AlertMessage",
            "PreTradeCheckRequest",
            "PreTradeCheckResponse",
            "ExposureSummary",
            "AccountState",
            "MarginState",
            "InternalPosition",
            "Balance",
            "DeltaOneFeatureRecord",
            "OptionsIvRecord",
            "FuturesTermStructureRecord",
            "ModelMetadata",
            "InferenceRequest",
            "InferenceResult",
            "TrainingJobRequest",
            "TrainingJobResult",
            "ServiceHealthStatus",
            "DependencyReport",
            "EnhancedError",
            "CircuitBreakerState",
            "ConfigStoreRecord",
            "ConfigChangeNotification",
            "ConfigStoreActivePointer",
            "InternalPubSubTopic",
            "PubSubMessageEnvelope",
            "FillEventMessage",
            "PositionUpdateMessage",
            "RiskAlertMessage",
            "MarketTickMessage",
            "StrategySignalMessage",
            "MLPredictionMessage",
            "ServiceLifecycleEventMessage",
            "HealthAlertMessage",
            "CircuitBreakerEventMessage",
        ],
        "pubsub_topics": {
            "fill-events-{venue}": "FillEventMessage",
            "order-requests": "OrderRequestMessage",
            "execution-results": "ExecutionResultMessage",
            "position-updates": "PositionUpdateMessage",
            "positions": "PositionUpdateMessage",
            "risk-alerts": "RiskAlertMessage",
            "margin-warnings": "RiskAlertMessage",
            "market-ticks": "MarketTickMessage",
            "order-book-updates": "PubSubMessageEnvelope",
            "derivative-tickers": "DerivativeTickerMessage",
            "liquidations": "LiquidationMessage",
            "feature-updates": "FeatureUpdateMessage",
            "strategy-signals": "StrategySignalMessage",
            "ml-predictions": "MLPredictionMessage",
            "service-lifecycle-events": "ServiceLifecycleEventMessage",
            "health-alerts": "HealthAlertMessage",
            "circuit-breaker-events": "CircuitBreakerEventMessage",
        },
        "sor_schemas": [
            "SorVenueScore",
            "SorRouteDecision",
            "SorChildOrder",
            "SorTwapSlice",
            "SorExecutionSummary",
            "SorVenueCapacity",
        ],
    },
    "fix": {
        "module": "api_contracts.fix.schemas",
        "description": (
            "FIX 4.2 / 4.4 / 5.0 message schemas for institutional order routing. "
            "Covers order management (NewOrderSingle, ExecutionReport, Cancel), "
            "market data (Snapshot, IncrementalRefresh), and admin messages. "
            "Venues: IBKR (FIX 4.2), Databento (FIX 4.4), institutional CeFi."
        ),
        "is_internal": False,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "fix_versions": ["FIX.4.2", "FIX.4.4", "FIX.5.0"],
        "response_schema_classes": [
            "FixNewOrderSingle",
            "FixExecutionReport",
            "FixOrderCancelRequest",
            "FixOrderCancelReject",
            "FixMarketDataRequest",
            "FixMarketDataSnapshot",
            "FixMarketDataIncrementalRefresh",
            "FixLogon",
            "FixLogout",
            "FixHeartbeat",
            "FixReject",
            "FixSessionConfig",
        ],
        "msg_type_map": {
            "D": "FixNewOrderSingle",
            "8": "FixExecutionReport",
            "F": "FixOrderCancelRequest",
            "9": "FixOrderCancelReject",
            "V": "FixMarketDataRequest",
            "W": "FixMarketDataSnapshot",
            "X": "FixMarketDataIncrementalRefresh",
            "A": "FixLogon",
            "5": "FixLogout",
            "0": "FixHeartbeat",
            "3": "FixReject",
        },
    },
    "prime_broker": {
        "module": "api_contracts.prime_broker.schemas",
        "description": (
            "Prime broker integration schemas — HiddenRoad / Talos / FalconX style. "
            "Covers credit accounts, cross-venue position netting, margin calls, "
            "net clearing instructions, and cleared fills."
        ),
        "is_internal": False,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "supported_providers": ["hidden_road", "talos", "falconx", "genesis", "cumberland"],
        "response_schema_classes": [
            "PrimeBrokerAccount",
            "PrimeBrokerPosition",
            "PrimeBrokerMarginCall",
            "NetClearingInstruction",
            "CrossMarginNettingResult",
            "PrimeBrokerFill",
            "CollateralAsset",
        ],
        "error_schema_classes": ["PrimeBrokerError"],
    },
    "regulatory": {
        "module": "api_contracts.regulatory.schemas",
        "description": (
            "Regulatory reporting schemas: MiFID II (RTS 22/27/28), EMIR, Dodd-Frank, "
            "trade surveillance, and best execution monitoring."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "regimes": ["mifid_ii", "emir", "dodd_frank", "mas", "asic", "cftc", "sec"],
        "response_schema_classes": [
            "MifidIITradeReport",
            "BestExecutionRecord",
            "BestExecutionMonitoringRecord",
            "EmirTradeReport",
            "DoddFrankSwapReport",
            "TradeSurveillanceAlert",
        ],
        "error_schema_classes": ["TradeReportingError"],
    },
    "risk_analytics": {
        "module": "api_contracts.schemas.risk",
        "description": (
            "Advanced quantitative risk schemas: VaR (historical, parametric, Monte Carlo), "
            "CVaR, stress testing, SPAN multi-asset margin, P&L attribution."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "VaRRequest",
            "VaRResult",
            "StressScenario",
            "StressTestResult",
            "MultiAssetMarginCalculation",
            "PnLAttributionRecord",
            "RealTimePnLRecord",
            "RiskLimitBreach",
        ],
    },
    "latency": {
        "module": "api_contracts.schemas.latency",
        "description": (
            "HFT and latency measurement schemas: tick-to-trade, co-location performance, "
            "sub-millisecond operation timing, order latency percentiles."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "TickToTradeMetric",
            "OrderLatencyRecord",
            "CoLocationPerformanceMetric",
            "NetworkJitterMetric",
            "SubMillisecondLatencyRecord",
            "LatencyPercentile",
            "LatencyBenchmarkReport",
        ],
    },
    "analytics": {
        "module": "api_contracts.schemas.analytics",
        "description": (
            "Advanced analytics schemas: factor attribution (momentum, value, carry, etc.), "
            "cross-asset correlation matrices, regime detection, alternative data signals "
            "(sentiment, satellite, options flow, dark pool)."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "FactorAttributionRecord",
            "FactorAttributionModel",
            "CrossAssetCorrelationMatrix",
            "CorrelationRegimeChange",
            "SentimentScore",
            "AlternativeDataSignal",
            "SatelliteObservation",
            "OptionsFlowRecord",
            "DarkPoolPrintRecord",
        ],
    },
    "cloud_sdks": {
        "has_rest": False,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "AlertPolicy",
            "ArtifactPackage",
            "ArtifactRegistryQuotaUsage",
            "ArtifactRepository",
            "ArtifactTag",
            "ArtifactVersion",
            "BlobDownloadRequest",
            "BlobListRequest",
            "BlobListResponse",
            "BlobUploadRequest",
            "BqQuotaUsage",
            "BucketCreateRequest",
            "CloudBuildBuild",
            "CloudBuildConfig",
            "CloudBuildGitHubConfig",
            "CloudBuildListBuildsResponse",
            "CloudBuildQuotaUsage",
            "CloudBuildRunTriggerRequest",
            "CloudBuildStep",
            "CloudBuildTrigger",
            "CloudBuildTriggerListResponse",
            "CloudLoggingQuotaUsage",
            "CloudSchedulerAttempt",
            "CloudSchedulerCreateJobRequest",
            "CloudSchedulerJob",
            "CloudSchedulerListJobsResponse",
            "CloudSchedulerPauseJobRequest",
            "CloudSchedulerResumeJobRequest",
            "CloudSchedulerRunJobRequest",
            "CloudRunRevision",
            "CloudRunService",
            "ComputeInstance",
            "ComputeOperation",
            "CreateServiceRequest",
            "DeleteInstanceRequest",
            "ExternalTableConfig",
            "ExternalTableCreateRequest",
            "GcpCloudRunQuotaUsage",
            "GcpComputeQuotaUsage",
            "GcsBlobInfo",
            "GcsQuotaUsage",
            "GetInstanceRequest",
            "HivePartitioningOptions",
            "IamBinding",
            "IamPolicy",
            "InsertInstanceRequest",
            "InstanceListResponse",
            "ListInstancesRequest",
            "ListTimeSeriesRequest",
            "ListTimeSeriesResponse",
            "ListLogEntriesRequest",
            "ListLogEntriesResponse",
            "ListPackagesResponse",
            "ListRepositoriesResponse",
            "ListRevisionsRequest",
            "ListSecretsResponse",
            "LogEntry",
            "LogMetric",
            "LogSink",
            "MonitoringCreateTimeSeriesRequest",
            "MonitoringPoint",
            "MonitoringTimeSeries",
            "PubSubAcknowledgeRequest",
            "PubSubMessage",
            "PubSubPublishRequest",
            "PubSubPublishResponse",
            "PubSubPullRequest",
            "PubSubPullResponse",
            "PubSubQuotaUsage",
            "PubSubReceivedMessage",
            "PubSubSeekRequest",
            "PubSubSubscription",
            "PubSubTopic",
            "PythonPackage",
            "QueryJobResult",
            "QueryRequest",
            "RevisionListResponse",
            "SecretAccessRequest",
            "SecretAccessResponse",
            "SecretAddVersionRequest",
            "SecretAddVersionResponse",
            "SecretCreateRequest",
            "SecretManagerQuotaUsage",
            "SecretVersion",
            "ServiceAccount",
            "ServiceAccountKey",
            "SetIamPolicyRequest",
            "StartInstanceRequest",
            "StopInstanceRequest",
            "TableCreateRequest",
            "TableInfo",
            "TestIamPermissionsRequest",
            "TestIamPermissionsResponse",
            "TrafficTarget",
            "UpdateServiceRequest",
            "UpdateTrafficSplitRequest",
            "UptimeCheckConfig",
            "WriteLogEntriesRequest",
        ],
        "error_schema_classes": [],
        "example_schema_map": {"bq_quota_usage_example.json": "BqQuotaUsage"},
    },
}
