"""Odds API key and region mappings — split from venue_constants to stay under line limit.

Keys use string literals matching the venue constant values defined in venue_constants.py.
"""

from __future__ import annotations

# Canonical Venue Key -> The Odds API bookmaker key(s) -- for VCR recording

ODDS_API_KEY_MAP: dict[str, list[str]] = {
    "BETFAIR": ["betfair_ex_uk", "betfair_ex_eu", "betfair_ex_au"],
    "SMARKETS": ["smarkets"],
    "MATCHBOOK": ["matchbook"],
    "POLYMARKET": ["polymarket"],
    "KALSHI": ["kalshi"],
    "NOVIG": ["novig"],
    "BETOPENLY": ["betopenly"],
    "PROPHETX": ["prophetx"],
    "PINNACLE": ["pinnacle"],
    "ONEXBET": ["onexbet"],
    "DRAFTKINGS": ["draftkings"],
    "FANDUEL": ["fanduel"],
    "BETMGM": ["betmgm"],
    "BOVADA": ["bovada"],
    "CAESARS": ["williamhill_us"],
    "BETRIVERS": ["betrivers"],
    "BETONLINEAG": ["betonlineag"],
    "BETUS": ["betus"],
    "LOWVIG": ["lowvig"],
    "MYBOOKIEAG": ["mybookieag"],
    "FANATICS": ["fanatics"],
    "BALLYBET": ["ballybet"],
    "BETANYSPORTS": ["betanysports"],
    "BETPARX": ["betparx"],
    "ESPNBET": ["espnbet"],
    "FLIFF": ["fliff"],
    "HARDROCKBET": ["hardrockbet"],
    "REBET": ["rebet"],
    "PRIZEPICKS": ["prizepicks"],
    "UNDERDOG": ["underdog"],
    "DRAFTKINGS_PICK6": ["pick6"],
    "BETR_DFS": ["betr_us_dfs"],
    "BET365": ["bet365_au"],
    "WILLIAMHILL": ["williamhill"],
    "LADBROKES": ["ladbrokes_uk", "ladbrokes_au"],
    "CORAL": ["coral"],
    "PADDYPOWER": ["paddypower"],
    "SKYBET": ["skybet"],
    "BETWAY": ["betway"],
    "BETVICTOR": ["betvictor"],
    "BOYLESPORTS": ["boylesports"],
    "BET888SPORT": ["sport888", "sport888_se"],
    "UNIBET": ["unibet_uk", "unibet_fr", "unibet_it", "unibet_nl", "unibet_se", "unibet"],
    "CASUMO": ["casumo"],
    "GROSVENOR": ["grosvenor"],
    "LEOVEGAS": ["leovegas", "leovegas_se"],
    "LIVESCOREBET": ["livescorebet"],
    "VIRGINBET": ["virginbet"],
    "BETCLIC": ["betclic_fr"],
    "BETSSON": ["betsson"],
    "COOLBET": ["coolbet"],
    "EVERYGAME": ["everygame"],
    "GTBETS": ["gtbets"],
    "MARATHONBET": ["marathonbet"],
    "NORDICBET": ["nordicbet"],
    "PARIONSSPORT": ["parionssport_fr"],
    "PMU": ["pmu_fr"],
    "SUPRABETS": ["suprabets"],
    "TIPICO": ["tipico_de"],
    "WINAMAX": ["winamax_fr", "winamax_de"],
    "CODERE": ["codere_it"],
    "NETBET": ["netbet_fr"],
    "ATG": ["atg_se"],
    "MRGREEN": ["mrgreen_se"],
    "SVENSKASPEL": ["svenskaspel_se"],
    "BETR_AU": ["betr_au"],
    "BETRIGHT": ["betright"],
    "DABBLE": ["dabble_au"],
    "NEDS": ["neds"],
    "PLAYUP": ["playup"],
    "POINTSBET": ["pointsbetau"],
    "SPORTSBET_AU": ["sportsbet"],
    "TAB": ["tab"],
    "TABTOUCH": ["tabtouch"],
}

ODDS_API_REGION_MAP: dict[str, list[str]] = {
    "BETFAIR": ["uk", "eu", "au"],
    "SMARKETS": ["uk"],
    "MATCHBOOK": ["uk", "eu"],
    "POLYMARKET": ["us_ex"],
    "KALSHI": ["us_ex"],
    "NOVIG": ["us_ex"],
    "BETOPENLY": ["us_ex"],
    "PROPHETX": ["us_ex"],
    "PINNACLE": ["eu"],
    "ONEXBET": ["eu"],
    "DRAFTKINGS": ["us"],
    "FANDUEL": ["us"],
    "BETMGM": ["us"],
    "BOVADA": ["us"],
    "CAESARS": ["us"],
    "BETRIVERS": ["us"],
    "BETONLINEAG": ["us", "eu"],
    "BETUS": ["us"],
    "LOWVIG": ["us"],
    "MYBOOKIEAG": ["us", "eu"],
    "FANATICS": ["us"],
    "BALLYBET": ["us2"],
    "BETANYSPORTS": ["us2", "eu"],
    "BETPARX": ["us2"],
    "ESPNBET": ["us2"],
    "FLIFF": ["us2"],
    "HARDROCKBET": ["us2"],
    "REBET": ["us2"],
    "PRIZEPICKS": ["us_dfs"],
    "UNDERDOG": ["us_dfs"],
    "DRAFTKINGS_PICK6": ["us_dfs"],
    "BETR_DFS": ["us_dfs"],
    "BET365": ["au"],
    "WILLIAMHILL": ["uk", "eu"],
    "LADBROKES": ["uk", "au"],
    "CORAL": ["uk"],
    "PADDYPOWER": ["uk"],
    "SKYBET": ["uk"],
    "BETWAY": ["uk"],
    "BETVICTOR": ["uk", "eu"],
    "BOYLESPORTS": ["uk"],
    "BET888SPORT": ["uk", "se"],
    "UNIBET": ["uk", "eu", "fr", "se", "au"],
    "CASUMO": ["uk"],
    "GROSVENOR": ["uk"],
    "LEOVEGAS": ["uk", "se"],
    "LIVESCOREBET": ["uk"],
    "VIRGINBET": ["uk"],
    "BETCLIC": ["eu", "fr"],
    "BETSSON": ["eu", "se"],
    "COOLBET": ["eu"],
    "EVERYGAME": ["eu"],
    "GTBETS": ["eu"],
    "MARATHONBET": ["eu"],
    "NORDICBET": ["eu", "se"],
    "PARIONSSPORT": ["eu", "fr"],
    "PMU": ["eu", "fr"],
    "SUPRABETS": ["eu"],
    "TIPICO": ["eu"],
    "WINAMAX": ["eu", "fr"],
    "CODERE": ["eu"],
    "NETBET": ["fr"],
    "ATG": ["se"],
    "MRGREEN": ["se"],
    "SVENSKASPEL": ["se"],
    "BETR_AU": ["au"],
    "BETRIGHT": ["au"],
    "DABBLE": ["au"],
    "NEDS": ["au"],
    "PLAYUP": ["au"],
    "POINTSBET": ["au"],
    "SPORTSBET_AU": ["au"],
    "TAB": ["au"],
    "TABTOUCH": ["au"],
}
