"""TradFi ticker universe registry — canonical lists of equity tickers by category.

These lists are used by instruments-service config_reloaders to seed the ticker
cache for TickerUniverseConfig hot-reload and fallback. They represent the full
investable universe for each category.

These lists are the SSOT for which symbols the instruments-service will attempt to
fetch instrument definitions for when no cloud config is available.
"""

from __future__ import annotations

# Full current S&P 500 constituent list — 503 tickers (500 companies; GOOGL/GOOG,
# FOX/FOXA, NWS/NWSA are dual share classes of the same company) — restored from the
# prior 200-ticker curated subset to the REAL current membership (operator 2026-07-08:
# "since we're only doing OHLCV for Databento, we can afford to grab all [~600]
# equities... going back to all the components of the S&P 500 would give us a bigger
# universe to do perps against on Binance as well"). Source: Wikipedia "List of S&P 500
# companies" constituents table (en.wikipedia.org/wiki/List_of_S%26P_500_companies),
# fetched + parsed directly from the live page 2026-07-08 (503 rows, cross-checked
# against each row's NYSE/Nasdaq/Cboe BZX symbol-template link — not from memory).
# Multi-class tickers use dot notation (BRK.B) per the existing file convention.
SP500_TICKERS: list[str] = [
    "A",
    "AAPL",
    "ABBV",
    "ABNB",
    "ABT",
    "ACGL",
    "ACN",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "ADSK",
    "AEE",
    "AEP",
    "AES",
    "AFL",
    "AIG",
    "AIZ",
    "AJG",
    "AKAM",
    "ALB",
    "ALGN",
    "ALL",
    "ALLE",
    "AMAT",
    "AMCR",
    "AMD",
    "AME",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "ANET",
    "AON",
    "AOS",
    "APA",
    "APD",
    "APH",
    "APO",
    "APP",
    "APTV",
    "ARE",
    "ARES",
    "ATO",
    "AVB",
    "AVGO",
    "AVY",
    "AWK",
    "AXON",
    "AXP",
    "AZO",
    "BA",
    "BAC",
    "BALL",
    "BAX",
    "BBY",
    "BDX",
    "BEN",
    "BF.B",
    "BG",
    "BIIB",
    "BKNG",
    "BKR",
    "BLDR",
    "BLK",
    "BMY",
    "BNY",
    "BR",
    "BRK.B",
    "BRO",
    "BSX",
    "BX",
    "BXP",
    "C",
    "CAH",
    "CARR",
    "CASY",
    "CAT",
    "CB",
    "CBOE",
    "CBRE",
    "CCI",
    "CCL",
    "CDNS",
    "CDW",
    "CEG",
    "CF",
    "CFG",
    "CHD",
    "CHRW",
    "CHTR",
    "CI",
    "CIEN",
    "CINF",
    "CL",
    "CLX",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNP",
    "COF",
    "COHR",
    "COIN",
    "COO",
    "COP",
    "COR",
    "COST",
    "CPAY",
    "CPRT",
    "CPT",
    "CRH",
    "CRL",
    "CRM",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTSH",
    "CTVA",
    "CVNA",
    "CVS",
    "CVX",
    "D",
    "DAL",
    "DASH",
    "DD",
    "DDOG",
    "DE",
    "DECK",
    "DELL",
    "DG",
    "DGX",
    "DHI",
    "DHR",
    "DIS",
    "DLR",
    "DLTR",
    "DOC",
    "DOV",
    "DOW",
    "DPZ",
    "DRI",
    "DTE",
    "DUK",
    "DVA",
    "DVN",
    "DXCM",
    "EA",
    "EBAY",
    "ECHO",
    "ECL",
    "ED",
    "EFX",
    "EG",
    "EIX",
    "EL",
    "ELV",
    "EME",
    "EMR",
    "EOG",
    "EQIX",
    "EQR",
    "EQT",
    "ERIE",
    "ES",
    "ESS",
    "ETN",
    "ETR",
    "EVRG",
    "EW",
    "EXC",
    "EXE",
    "EXPD",
    "EXPE",
    "EXR",
    "F",
    "FANG",
    "FAST",
    "FCX",
    "FDS",
    "FDX",
    "FDXF",
    "FE",
    "FFIV",
    "FICO",
    "FIS",
    "FISV",
    "FITB",
    "FIX",
    "FLEX",
    "FOX",
    "FOXA",
    "FRT",
    "FSLR",
    "FTNT",
    "FTV",
    "GD",
    "GDDY",
    "GE",
    "GEHC",
    "GEN",
    "GEV",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GNRC",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GRMN",
    "GS",
    "GWW",
    "HAL",
    "HAS",
    "HBAN",
    "HCA",
    "HD",
    "HIG",
    "HII",
    "HLT",
    "HON",
    "HONA",
    "HOOD",
    "HPE",
    "HPQ",
    "HRL",
    "HSIC",
    "HST",
    "HSY",
    "HUBB",
    "HUM",
    "HWM",
    "IBKR",
    "IBM",
    "ICE",
    "IDXX",
    "IEX",
    "IFF",
    "INCY",
    "INTC",
    "INTU",
    "INVH",
    "IP",
    "IQV",
    "IR",
    "IRM",
    "ISRG",
    "IT",
    "ITW",
    "IVZ",
    "J",
    "JBHT",
    "JBL",
    "JCI",
    "JKHY",
    "JNJ",
    "JPM",
    "KDP",
    "KEY",
    "KEYS",
    "KHC",
    "KIM",
    "KKR",
    "KLAC",
    "KMB",
    "KMI",
    "KO",
    "KR",
    "KVUE",
    "L",
    "LDOS",
    "LEN",
    "LH",
    "LHX",
    "LII",
    "LIN",
    "LITE",
    "LLY",
    "LMT",
    "LNT",
    "LOW",
    "LRCX",
    "LULU",
    "LUV",
    "LVS",
    "LYB",
    "LYV",
    "MA",
    "MAA",
    "MAR",
    "MAS",
    "MCD",
    "MCHP",
    "MCK",
    "MCO",
    "MDLZ",
    "MDT",
    "MET",
    "META",
    "MGM",
    "MKC",
    "MLM",
    "MMM",
    "MNST",
    "MO",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRNA",
    "MRSH",
    "MRVL",
    "MS",
    "MSCI",
    "MSFT",
    "MSI",
    "MTB",
    "MTD",
    "MU",
    "NCLH",
    "NDAQ",
    "NDSN",
    "NEE",
    "NEM",
    "NFLX",
    "NI",
    "NKE",
    "NOC",
    "NOW",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NVR",
    "NWS",
    "NWSA",
    "NXPI",
    "O",
    "ODFL",
    "OKE",
    "OMC",
    "ON",
    "ORCL",
    "ORLY",
    "OTIS",
    "OXY",
    "PANW",
    "PAYX",
    "PCAR",
    "PCG",
    "PEG",
    "PEP",
    "PFE",
    "PFG",
    "PG",
    "PGR",
    "PH",
    "PHM",
    "PKG",
    "PLD",
    "PLTR",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "PODD",
    "PPG",
    "PPL",
    "PRU",
    "PSA",
    "PSKY",
    "PSX",
    "PTC",
    "PWR",
    "PYPL",
    "Q",
    "QCOM",
    "RCL",
    "REG",
    "REGN",
    "RF",
    "RJF",
    "RL",
    "RMD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RSG",
    "RTX",
    "RVTY",
    "SBAC",
    "SBUX",
    "SCHW",
    "SHW",
    "SJM",
    "SLB",
    "SMCI",
    "SNA",
    "SNDK",
    "SNPS",
    "SO",
    "SOLV",
    "SPG",
    "SPGI",
    "SRE",
    "STE",
    "STLD",
    "STT",
    "STX",
    "STZ",
    "SW",
    "SWK",
    "SWKS",
    "SYF",
    "SYK",
    "SYY",
    "T",
    "TAP",
    "TDG",
    "TDY",
    "TECH",
    "TEL",
    "TER",
    "TFC",
    "TGT",
    "TJX",
    "TKO",
    "TMO",
    "TMUS",
    "TPL",
    "TPR",
    "TRGP",
    "TRMB",
    "TROW",
    "TRV",
    "TSCO",
    "TSLA",
    "TSN",
    "TT",
    "TTD",
    "TTWO",
    "TXN",
    "TXT",
    "TYL",
    "UAL",
    "UBER",
    "UDR",
    "UHS",
    "ULTA",
    "UNH",
    "UNP",
    "UPS",
    "URI",
    "USB",
    "V",
    "VEEV",
    "VICI",
    "VLO",
    "VLTO",
    "VMC",
    "VRSK",
    "VRSN",
    "VRT",
    "VRTX",
    "VST",
    "VTR",
    "VTRS",
    "VZ",
    "WAB",
    "WAT",
    "WBD",
    "WDAY",
    "WDC",
    "WEC",
    "WELL",
    "WFC",
    "WM",
    "WMB",
    "WMT",
    "WRB",
    "WSM",
    "WST",
    "WTW",
    "WY",
    "WYNN",
    "XEL",
    "XOM",
    "XYL",
    "XYZ",
    "YUM",
    "ZBH",
    "ZBRA",
    "ZTS",
]

# UBER and VEEV removed 2026-07-08 (SP500_TICKERS restoration cross-check):
# both are actually NYSE-listed (confirmed via the live Wikipedia "List of
# S&P 500 companies" per-row NYSE/Nasdaq symbol-template link, not memory) —
# the prior placement here was a stale hand-curated assumption. Both remain
# fully covered via SP500_TICKERS -> ticker_registry.py `_NYSE`.
NASDAQ_TICKERS: list[str] = [
    "AAPL",
    "MSFT",
    "AMZN",
    "NVDA",
    "META",
    "GOOGL",
    "GOOG",
    "TSLA",
    "AVGO",
    "COST",
    "NFLX",
    "AMD",
    "ADBE",
    "QCOM",
    "CSCO",
    "TXN",
    "INTU",
    "AMAT",
    "AMGN",
    "HON",
    "ISRG",
    "BKNG",
    "ADI",
    "LRCX",
    "KLAC",
    "SNPS",
    "CDNS",
    "REGN",
    "VRTX",
    "MU",
    "MRVL",
    "PANW",
    "INTC",
    "CRWD",
    "ABNB",
    "FTNT",
    "MCHP",
    "NXPI",
    "ON",
    "MNST",
    "DXCM",
    "IDXX",
    "ROST",
    "FAST",
    "CTAS",
    "CPRT",
    "BIIB",
    "ILMN",
    "MTCH",
    "ALGN",
    "DOCU",
    "SIRI",
    "WDAY",
    "ZM",
    "ZS",
    "OKTA",
    "TEAM",
    "DDOG",
    "SNOW",
    "RBLX",
    "HOOD",
    "SOFI",
    "RIVN",
    "LCID",
    "PINS",
    "SNAP",
    "LYFT",
    "BYND",
    "ROKU",
    "TWLO",
    "NET",
    "BILL",
    "FIVN",
    "GTLB",
    # Binance TradFi-perp single stocks listed on NASDAQ (basis-arb superset,
    # 2026-06-24). Required so BINANCE-FUTURES PERPETUAL tradfi underlyings
    # each map to a captured/enumerated DBEQ.BASIC equity. NASDAQ listing →
    # the adapter routes canonical_venue=NASDAQ off this set.
    "ARM",  # Arm Holdings ADR
    "ASML",  # ASML ADR
    "AAOI",  # Applied Optoelectronics
    "ALAB",  # Astera Labs
    "ASTS",  # AST SpaceMobile
    "AXTI",  # AXT Inc
    "COIN",  # Coinbase
    "CRDO",  # Credo Technology
    "CRWV",  # CoreWeave
    "DKNG",  # DraftKings
    "EBAY",  # eBay
    "FLNC",  # Fluence Energy
    "IREN",  # IREN Limited
    "LITE",  # Lumentum
    "MSTR",  # Strategy (MicroStrategy)
    "NBIS",  # Nebius Group
    "ONDS",  # Ondas Holdings
    "PAYP",  # PayPay ADR
    "PLTR",  # Palantir
    "RKLB",  # Rocket Lab
    "SMCI",  # Super Micro
    "SNDK",  # Sandisk
    "SPCX",  # SpaceX-tracking vehicle
    "USAR",  # USA Rare Earth
    "WDC",  # Western Digital
]

# Binance TradFi-perp single stocks / ADRs listed on NYSE (basis-arb superset,
# 2026-06-24). NYSE listing → adapter default routes canonical_venue=NYSE, so
# these only need to be in the fetched symbol list (added via the universe dict
# below), not in NASDAQ_TICKERS. Kept as a discrete list for provenance.
NYSE_TRADFI_PERP_TICKERS: list[str] = [
    "BE",  # Bloom Energy
    "BMNR",  # BitMine Immersion
    "CFG",  # Citizens Financial
    "CIEN",  # Ciena
    "COHR",  # Coherent
    "CRCL",  # Circle Internet
    "DELL",  # Dell Technologies
    "DIS",  # Walt Disney
    "GLW",  # Corning
    "GME",  # GameStop
    "HIMS",  # Hims & Hers
    "HPE",  # Hewlett Packard Enterprise
    "NOW",  # ServiceNow
    "BABA",  # Alibaba ADR
    "NOK",  # Nokia ADR
    "NVO",  # Novo Nordisk ADR
    "SONY",  # Sony ADR
    "TSM",  # TSMC ADR
]

ETF_TICKERS: list[str] = [
    "SPY",
    "QQQ",
    "IWM",
    "VTI",
    "DIA",
    "EEM",
    "VEA",
    "VWO",
    "GLD",
    "SLV",
    "USO",
    "UNG",
    "TLT",
    "IEF",
    "SHY",
    "LQD",
    "HYG",
    "JNK",
    "XLF",
    "XLE",
    "XLK",
    "XLV",
    "XLI",
    "XLY",
    "XLP",
    "XLB",
    "XLU",
    "XLRE",
    "VNQ",
    "IBB",
    "SMH",
    "ARKK",
    "ARKG",
    "ARKW",
    "ARKF",
    "ARKQ",
    # BTC spot ETFs (all 10 US listings post-2024-01-11)
    "IBIT",
    "FBTC",
    "BITB",
    "ARKB",
    "BTCO",
    "BRRR",
    "HODL",
    "EZBC",
    "GBTC",
    "BITO",
    # ETH spot ETFs (all 8 US listings post-2024-07-23)
    "ETHA",
    "FETH",
    "ETHE",
    "ETHV",
    "ETHW",
    "CETH",
    "QETH",
    "EZET",
    "VIG",
    "VXUS",
    "AGG",
    "BND",
    "VCIT",
    "VCSH",
    "BSV",
    "BNDX",
    "EFA",
    "EWJ",
    "EWZ",
    "FXI",
    "ASHR",
    "MCHI",
    # Binance TradFi-perp index/sector ETFs (basis-arb superset, 2026-06-24).
    "EWT",  # iShares MSCI Taiwan
    "EWY",  # iShares MSCI South Korea
    "ROBO",  # ROBO Global Robotics & Automation
    "SLX",  # VanEck Steel
    "URNM",  # Sprott Uranium Miners
    "UVXY",  # ProShares Ultra VIX Short-Term Futures
    # Commodity/crypto REPRESENTATIVE ETFs for the Binance commodity/crypto perps
    # (operator 2026-06-24): the perp carry trade (short Binance perp + long
    # underlying) works via an ETF too (ETF ~ underlying), so these are valid
    # basis-arb underlyings alongside the CME futures roots. All DBEQ.BASIC-covered
    # (databento primary; verified ohlcv-1m). GLD/SLV/USO/UNG/IBIT/ETHA already
    # above; IAU/PPLT/PALL/CPER are the missing platinum-group + copper + alt-gold.
    "IAU",  # iShares Gold (XAU alt to GLD)
    "PPLT",  # abrdn Physical Platinum (XPT)
    "PALL",  # abrdn Physical Palladium (XPD)
    "CPER",  # United States Copper Index (COPPER)
]

TRADFI_FUTURES_PRODUCTS: list[str] = [
    # CME equity-index
    "ES",
    "MES",
    # CME crypto
    "BTC",
    "MBT",
    "ETH",
    "MET",
    # NYMEX energy
    "CL",
    "MCL",
    "NG",
    "QG",
    # COMEX metals
    "GC",
    "MGC",
    # COMEX platinum-group metals — Binance XPT/XPD perp coverage (2026-06-24).
    "PL",  # platinum (XPT)
    "PA",  # palladium (XPD)
]


TRADFI_TICKER_UNIVERSE: dict[str, list[str]] = {
    "sp500_tickers": SP500_TICKERS,
    "nasdaq_tickers": NASDAQ_TICKERS,
    "nyse_tradfi_perp_tickers": NYSE_TRADFI_PERP_TICKERS,
    "etf_tickers": ETF_TICKERS,
    "futures_products": TRADFI_FUTURES_PRODUCTS,
}

# ──────────────────────────────────────────────────────────────────────────
# TradFi equity/ETF MVP basis universe — the cash-equity twins of the Binance
# (BINANCE-FUTURES PERPETUAL) tradfi-perp underlyings (2026-06-24). These are
# the DBEQ.BASIC equities/ETFs that BACK a crypto-venue equity-perp, so they
# are the BASIS-REFERENCE leg of the equity-basis arb archetype and MUST be
# MVP-scoped (the cash leg the perp is measured against). Index-perps map to
# their ETF proxy (SPX/SPY→SPY, SOXL→SMH, …). Commodities are roots in
# TRADFI_FUTURES_PRODUCTS (PA/PL/GC/SI/HG/NG/CL), gated by the futures rule.
# KRX-only names (HYUNDAI 005380 / SAMSUNG 005930 / SKHYNIX 000660) are now
# UNBLOCKED (2026-06-24): sourced DIRECTLY via venue=KRX / source=yahoo (the
# ``.KS`` tickers in KRX_EQUITIES) — NOT a US-listed ADR twin. They join the
# basis universe by their canonical bare symbol (the KRX numeric code).
# Consumed by the tradfi MVP rule's equity carve-out (mvp_scope.is_mvp).
# Operator 2026-06-24: every Binance tradfi-perp underlying is captured — NOT LESS.
TRADFI_EQUITY_PERP_BASIS_UNIVERSE: frozenset[str] = frozenset(
    {
        "AAOI",
        "AAPL",
        "ADBE",
        "ALAB",
        "AMAT",
        "AMD",
        "AMZN",
        "ARM",
        "ASML",
        "ASTS",
        "AVGO",
        "AXTI",
        "BABA",
        "BE",
        "BMNR",
        "BRK.B",
        "BRKB",
        "CFG",
        "CIEN",
        "COHR",
        "COIN",
        "COST",
        "CRCL",
        "CRDO",
        "CRM",
        "CRWD",
        "CRWV",
        "CSCO",
        "DELL",
        "DIA",
        "DIS",
        "DKNG",
        "EBAY",
        "EWJ",
        "EWT",
        "EWY",
        "EWZ",
        "FLNC",
        "GLW",
        "GME",
        "GOOGL",
        "HD",
        "HIMS",
        "HOOD",
        "HPE",
        "IBM",
        "INTC",
        "IREN",
        "IWM",
        "JPM",
        "KLAC",
        "LITE",
        "LLY",
        "LRCX",
        "META",
        "MRVL",
        "MSFT",
        "MSTR",
        "MU",
        "NBIS",
        "NFLX",
        "NOK",
        "NOW",
        "NVDA",
        "NVO",
        "ONDS",
        "ORCL",
        "PAYP",
        "PLTR",
        "QCOM",
        "QQQ",
        "RIVN",
        "RKLB",
        "ROBO",
        "SLX",
        "SMCI",
        "SMH",
        "SNDK",
        "SONY",
        "SPCX",
        "SPY",
        "TSLA",
        "TSM",
        "UBER",
        "URNM",
        "USAR",
        "UVXY",
        "V",
        "WDC",
        "WMT",
        "XLE",
        "ZM",
        # Commodity/crypto representative ETFs (operator 2026-06-24) — the perp
        # carry trade also works long-ETF (ETF ~ underlying), so these are valid
        # basis-arb cash-leg underlyings for the Binance commodity/crypto perps:
        # XAU→GLD/IAU, XAG→SLV, XPT→PPLT, XPD→PALL, COPPER→CPER, CL→USO,
        # NATGAS→UNG, BTC→IBIT, ETH→ETHA. All DBEQ.BASIC-covered (databento primary).
        "GLD",
        "IAU",
        "SLV",
        "PPLT",
        "PALL",
        "CPER",
        "USO",
        "UNG",
        "IBIT",
        "ETHA",
        # KRX (Korea Exchange) single stocks — venue=KRX, source=yahoo (2026-06-24).
        # The Korean underliers of the Binance tradfi-perps, sourced via Yahoo
        # ``.KS`` tickers (see KRX_EQUITIES). Bare KRX numeric codes; → 103/103.
        "005380",  # Hyundai Motor (005380.KS)
        "005930",  # Samsung Electronics (005930.KS)
        "000660",  # SK Hynix (000660.KS)
    }
)
