"""TradFi symbology reference data (SSOT).

Databento parent/options symbol validation, exchange code mappings,
ETF classification, and TradFi venue instrument definitions.

Previously scattered across instruments-service config files.
Centralized here as the system SSOT per UAC registry pattern.
"""

from __future__ import annotations

# --- Databento parent symbol validation ---
# Maps canonical underlying names (both exchange codes and human-readable aliases)
# to (databento_parent_symbol, dataset) tuples.
DATABENTO_VALID_PARENT_SYMBOLS: dict[str, tuple[str, str]] = {
    # CME Index Futures
    "ES": ("ES.FUT", "GLBX.MDP3"),
    "SP500": ("ES.FUT", "GLBX.MDP3"),
    "NQ": ("NQ.FUT", "GLBX.MDP3"),
    "NASDAQ100": ("NQ.FUT", "GLBX.MDP3"),
    "RTY": ("RTY.FUT", "GLBX.MDP3"),
    "RUSSELL2000": ("RTY.FUT", "GLBX.MDP3"),
    "YM": ("YM.FUT", "GLBX.MDP3"),
    "DOW": ("YM.FUT", "GLBX.MDP3"),
    # CME Energy
    "CL": ("CL.FUT", "GLBX.MDP3"),
    "CRUDE": ("CL.FUT", "GLBX.MDP3"),
    "NG": ("NG.FUT", "GLBX.MDP3"),
    "NATGAS": ("NG.FUT", "GLBX.MDP3"),
    "RB": ("RB.FUT", "GLBX.MDP3"),
    "GASOLINE": ("RB.FUT", "GLBX.MDP3"),
    "HO": ("HO.FUT", "GLBX.MDP3"),
    "HEATINGOIL": ("HO.FUT", "GLBX.MDP3"),
    # CME Metals
    "GC": ("GC.FUT", "GLBX.MDP3"),
    "GOLD": ("GC.FUT", "GLBX.MDP3"),
    "SI": ("SI.FUT", "GLBX.MDP3"),
    "SILVER": ("SI.FUT", "GLBX.MDP3"),
    "HG": ("HG.FUT", "GLBX.MDP3"),
    "COPPER": ("HG.FUT", "GLBX.MDP3"),
    "PL": ("PL.FUT", "GLBX.MDP3"),
    "PLATINUM": ("PL.FUT", "GLBX.MDP3"),
    # CME Grains
    "ZC": ("ZC.FUT", "GLBX.MDP3"),
    "CORN": ("ZC.FUT", "GLBX.MDP3"),
    "ZW": ("ZW.FUT", "GLBX.MDP3"),
    "WHEAT": ("ZW.FUT", "GLBX.MDP3"),
    "ZS": ("ZS.FUT", "GLBX.MDP3"),
    "SOYBEAN": ("ZS.FUT", "GLBX.MDP3"),
    "ZM": ("ZM.FUT", "GLBX.MDP3"),
    "SOYMEAL": ("ZM.FUT", "GLBX.MDP3"),
    "ZL": ("ZL.FUT", "GLBX.MDP3"),
    "SOYOIL": ("ZL.FUT", "GLBX.MDP3"),
    # CME Interest Rates
    "ZB": ("ZB.FUT", "GLBX.MDP3"),
    "TBOND": ("ZB.FUT", "GLBX.MDP3"),
    "ZN": ("ZN.FUT", "GLBX.MDP3"),
    "TNOTE10Y": ("ZN.FUT", "GLBX.MDP3"),
    "ZF": ("ZF.FUT", "GLBX.MDP3"),
    "TNOTE5Y": ("ZF.FUT", "GLBX.MDP3"),
    "ZT": ("ZT.FUT", "GLBX.MDP3"),
    "TNOTE2Y": ("ZT.FUT", "GLBX.MDP3"),
    # CME Currencies
    "6E": ("6E.FUT", "GLBX.MDP3"),
    "EUR": ("6E.FUT", "GLBX.MDP3"),
    "6J": ("6J.FUT", "GLBX.MDP3"),
    "JPY": ("6J.FUT", "GLBX.MDP3"),
    "6B": ("6B.FUT", "GLBX.MDP3"),
    "GBP": ("6B.FUT", "GLBX.MDP3"),
    "6C": ("6C.FUT", "GLBX.MDP3"),
    "CAD": ("6C.FUT", "GLBX.MDP3"),
    "6A": ("6A.FUT", "GLBX.MDP3"),
    "AUD": ("6A.FUT", "GLBX.MDP3"),
    "6S": ("6S.FUT", "GLBX.MDP3"),
    "CHF": ("6S.FUT", "GLBX.MDP3"),
    "6M": ("6M.FUT", "GLBX.MDP3"),
    "MXN": ("6M.FUT", "GLBX.MDP3"),
    "6N": ("6N.FUT", "GLBX.MDP3"),
    "NZD": ("6N.FUT", "GLBX.MDP3"),
    "6L": ("6L.FUT", "GLBX.MDP3"),
    "BRL": ("6L.FUT", "GLBX.MDP3"),
    "6Z": ("6Z.FUT", "GLBX.MDP3"),
    "ZAR": ("6Z.FUT", "GLBX.MDP3"),
    # CME Livestock
    "LE": ("LE.FUT", "GLBX.MDP3"),
    "LIVECATTLE": ("LE.FUT", "GLBX.MDP3"),
    "HE": ("HE.FUT", "GLBX.MDP3"),
    "LEANHOGS": ("HE.FUT", "GLBX.MDP3"),
    # CFE (CBOE Futures Exchange) - Volatility Futures
    "VX": ("VX.FUT", "XCBF.MDP3"),
    "VIX_FUT": ("VX.FUT", "XCBF.MDP3"),
    # ICE Futures US (IFUS.IMPACT)
    "CT": ("CT.FUT", "IFUS.IMPACT"),
    "COTTON": ("CT.FUT", "IFUS.IMPACT"),
    "CC": ("CC.FUT", "IFUS.IMPACT"),
    "COCOA": ("CC.FUT", "IFUS.IMPACT"),
    "KC": ("KC.FUT", "IFUS.IMPACT"),
    "COFFEE": ("KC.FUT", "IFUS.IMPACT"),
    "SB": ("SB.FUT", "IFUS.IMPACT"),
    "SUGAR": ("SB.FUT", "IFUS.IMPACT"),
    "OJ": ("OJ.FUT", "IFUS.IMPACT"),
    "ORANGEJUICE": ("OJ.FUT", "IFUS.IMPACT"),
    "DX": ("DX.FUT", "IFUS.IMPACT"),
    "DOLLARINDEX": ("DX.FUT", "IFUS.IMPACT"),
    # ICE Futures Europe
    "BRN": ("BRN.FUT", "IFEU.IMPACT"),
    "BRENT": ("BRN.FUT", "IFEU.IMPACT"),
    "G": ("G.FUT", "IFEU.IMPACT"),
    "GASOIL": ("G.FUT", "IFEU.IMPACT"),
    "T": ("T.FUT", "IFEU.IMPACT"),
    "WTI": ("T.FUT", "IFEU.IMPACT"),
}

# --- Databento options symbol validation ---
DATABENTO_VALID_OPTIONS_SYMBOLS: dict[str, tuple[str, str]] = {
    "ES": ("ES.OPT", "GLBX.MDP3"),
    "SP500": ("ES.OPT", "GLBX.MDP3"),
    "NQ": ("NQ.OPT", "GLBX.MDP3"),
    "NASDAQ100": ("NQ.OPT", "GLBX.MDP3"),
    "CL": ("CL.OPT", "GLBX.MDP3"),
    "CRUDE": ("CL.OPT", "GLBX.MDP3"),
    "GC": ("GC.OPT", "GLBX.MDP3"),
    "GOLD": ("GC.OPT", "GLBX.MDP3"),
}

# --- Exchange code to human-readable name ---
EXCHANGE_CODE_TO_NAME: dict[str, str] = {
    "ES": "SP500",
    "NQ": "NASDAQ100",
    "RTY": "RUSSELL2000",
    "YM": "DOW",
    "CL": "CRUDE",
    "NG": "NATGAS",
    "RB": "GASOLINE",
    "HO": "HEATINGOIL",
    "GC": "GOLD",
    "SI": "SILVER",
    "HG": "COPPER",
    "PL": "PLATINUM",
    "ZC": "CORN",
    "ZW": "WHEAT",
    "ZS": "SOYBEAN",
    "ZM": "SOYMEAL",
    "ZL": "SOYOIL",
    "ZB": "TBOND",
    "ZN": "TNOTE10Y",
    "ZF": "TNOTE5Y",
    "ZT": "TNOTE2Y",
    "6E": "EUR",
    "6J": "JPY",
    "6B": "GBP",
    "6C": "CAD",
    "6A": "AUD",
    "6S": "CHF",
    "6L": "BRL",
    "6N": "NZD",
    "6Z": "ZAR",
    "6M": "MXN",
    "LE": "LIVECATTLE",
    "HE": "LEANHOGS",
    "VX": "VIX",
    "EW1": "SP500",
    "EW2": "SP500",
    "EW3": "SP500",
    "EW4": "SP500",
    "CT": "COTTON",
    "CC": "COCOA",
    "KC": "COFFEE",
    "SB": "SUGAR",
    "OJ": "ORANGEJUICE",
    "DX": "DOLLARINDEX",
    "BRN": "BRENT",
    "G": "GASOIL",
    "T": "WTI",
}

# --- TradFi venue instrument definitions ---
# Databento symbols to venues/datasets (from instruments-service Issue #90)
TRADFI_VENUE_MAPPINGS: list[dict[str, str | None]] = [
    {
        "symbol": "ES.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "RTY.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "RUSSELL2000",
        "code": "RTY",
    },
    {
        "symbol": "YM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "DOW",
        "code": "YM",
    },
    {
        "symbol": "CL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "NG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NATGAS",
        "code": "NG",
    },
    {
        "symbol": "RB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GASOLINE",
        "code": "RB",
    },
    {
        "symbol": "HO.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "HEATINGOIL",
        "code": "HO",
    },
    {
        "symbol": "GC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "SI.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SILVER",
        "code": "SI",
    },
    {
        "symbol": "HG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "COPPER",
        "code": "HG",
    },
    {
        "symbol": "PL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "PLATINUM",
        "code": "PL",
    },
    {
        "symbol": "ZC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CORN",
        "code": "ZC",
    },
    {
        "symbol": "ZW.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "WHEAT",
        "code": "ZW",
    },
    {
        "symbol": "ZS.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYBEAN",
        "code": "ZS",
    },
    {
        "symbol": "ZM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYMEAL",
        "code": "ZM",
    },
    {
        "symbol": "ZL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYOIL",
        "code": "ZL",
    },
    {
        "symbol": "ZB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TBOND",
        "code": "ZB",
    },
    {
        "symbol": "ZN.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE10Y",
        "code": "ZN",
    },
    {
        "symbol": "ZF.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE5Y",
        "code": "ZF",
    },
    {
        "symbol": "ZT.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE2Y",
        "code": "ZT",
    },
    {
        "symbol": "6E.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "EUR",
        "code": "6E",
    },
    {
        "symbol": "6J.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "JPY",
        "code": "6J",
    },
    {
        "symbol": "6B.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GBP",
        "code": "6B",
    },
    {
        "symbol": "6C.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CAD",
        "code": "6C",
    },
    {
        "symbol": "6A.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "AUD",
        "code": "6A",
    },
    {
        "symbol": "6S.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CHF",
        "code": "6S",
    },
    {
        "symbol": "6L.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "BRL",
        "code": "6L",
    },
    {
        "symbol": "6N.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NZD",
        "code": "6N",
    },
    {
        "symbol": "6Z.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "ZAR",
        "code": "6Z",
    },
    {
        "symbol": "6M.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "MXN",
        "code": "6M",
    },
    # CME Livestock
    {
        "symbol": "LE.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "LIVECATTLE",
        "code": "LE",
    },
    {
        "symbol": "HE.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "LEANHOGS",
        "code": "HE",
    },
    # CBOE (Chicago Board Options Exchange) - Volatility Index
    {
        "symbol": "VIX-USD",
        "venue": "CBOE",
        "type": "INDEX",
        "instrument_key": "CBOE:INDEX:VIX-USD",  # canonical key used in GCS and feature services
        "yahoo_ticker": "^VIX",  # Yahoo Finance ticker for 15m intraday data
        "fred_series": "VIXCLS",  # FRED series for daily historical data
        "base": "VIX",
        "description": "CBOE Volatility Index — measures 30-day implied volatility of S&P 500 options. "
        "Calculated index (not traded). Data: Barchart CSV 2020-01-02→2025-11-12 in GCS, "
        "then Yahoo Finance 15m rolling window. See data_source_continuity.py.",
    },
    # CFE (CBOE Futures Exchange) - Volatility Futures
    {
        "symbol": "VX.FUT",
        "venue": "CFE",
        "type": "FUTURE",
        "dataset": "XCBF.MDP3",
        "stype": "parent",
        "base": "VIX",
        "code": "VX",
    },
    {
        "symbol": "ES.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "CL.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "GC.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "EW1.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW1",
        "underlying": "ES",
    },
    {
        "symbol": "EW2.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW2",
        "underlying": "ES",
    },
    {
        "symbol": "EW3.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW3",
        "underlying": "ES",
    },
    {
        "symbol": "EW4.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW4",
        "underlying": "ES",
    },
    {
        "symbol": "CT.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COTTON",
        "code": "CT",
    },
    {
        "symbol": "CC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COCOA",
        "code": "CC",
    },
    {
        "symbol": "KC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COFFEE",
        "code": "KC",
    },
    {
        "symbol": "SB.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "SUGAR",
        "code": "SB",
    },
    {
        "symbol": "OJ.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "ORANGEJUICE",
        "code": "OJ",
    },
    {
        "symbol": "DX.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "DOLLARINDEX",
        "code": "DX",
    },
    {
        "symbol": "BRN.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "BRENT",
        "code": "BRN",
    },
    {
        "symbol": "G.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "GASOIL",
        "code": "G",
    },
    {
        "symbol": "T.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "WTI",
        "code": "T",
    },
]

# --- Known ETF tickers ---
KNOWN_ETFS: set[str] = {
    "SPY",
    "QQQ",
    "IVV",
    "VOO",
    "VTI",
    "DIA",
    "IWM",
    "EEM",
    "VEA",
    "VWO",
    "GLD",
    "SLV",
    "USO",
    "UNG",
    "TLT",
    "IEF",
    "SHY",
    "LQD",
    "HYG",
    "JNK",
    "XLF",
    "XLE",
    "XLK",
    "XLV",
    "XLI",
    "XLY",
    "XLP",
    "XLB",
    "XLU",
    "XLRE",
    "VNQ",
    "IBB",
    "SMH",
    "ARKK",
    "ARKG",
    "ARKW",
    "ARKF",
    "ARKQ",
    "IBIT",
    "FBTC",
    "ARKB",
    "GBTC",
    "BITO",
}

# --- Space-to-dot symbol normalization ---
SPACE_TO_DOT_SYMBOLS: dict[str, str] = {
    "BRK B": "BRK.B",
    "BF B": "BF.B",
    "BRK A": "BRK.A",
    "BF A": "BF.A",
}

# Backward-compatible alias
TRADFI_INSTRUMENTS_CONFIG: list[dict[str, str | None]] = TRADFI_VENUE_MAPPINGS

# Named constant for the VIX index instrument definition — import this directly
# rather than scanning TRADFI_VENUE_MAPPINGS.
VIX_INDEX_INSTRUMENT: dict[str, str] = next(
    d
    for d in TRADFI_VENUE_MAPPINGS  # type: ignore[assignment]
    if d.get("instrument_key") == "CBOE:INDEX:VIX-USD"
)
