"""Sentiment data source schemas (CryptoPanic, LunarCrush)."""

from unified_api_contracts.unified_api_contracts_external.sentiment.cryptopanic import (
    CRYPTOPANIC_BASE_URL,
    CRYPTOPANIC_RATE_LIMIT_FREE,
    CRYPTOPANIC_RATE_LIMIT_PRO,
    SENTIMENT_NEGATIVE_THRESHOLD,
    SENTIMENT_NEUTRAL_RANGE,
    SENTIMENT_POSITIVE_THRESHOLD,
    CryptoPanicCurrency,
    CryptoPanicError,
    CryptoPanicPost,
    CryptoPanicPostsResponse,
    CryptoPanicRequestParams,
    CryptoPanicVote,
)
from unified_api_contracts.unified_api_contracts_external.sentiment.lunarcrush import (
    LUNARCRUSH_BASE_URL,
    LUNARCRUSH_GALAXY_SCORE_STRONG,
    LUNARCRUSH_GALAXY_SCORE_WEAK,
    LUNARCRUSH_RATE_LIMIT_FREE,
    LUNARCRUSH_RATE_LIMIT_PRO,
    LUNARCRUSH_SENTIMENT_BEARISH,
    LUNARCRUSH_SENTIMENT_BULLISH,
    LUNARCRUSH_SENTIMENT_NEUTRAL_HIGH,
    LUNARCRUSH_SENTIMENT_NEUTRAL_LOW,
    LunarCrushAssetMetrics,
    LunarCrushAssetsResponse,
    LunarCrushError,
    LunarCrushFeed,
    LunarCrushFeedResponse,
    LunarCrushInfluencer,
    LunarCrushInfluencersResponse,
    LunarCrushRequestParams,
)

__all__ = [
    "CRYPTOPANIC_BASE_URL",
    "CRYPTOPANIC_RATE_LIMIT_FREE",
    "CRYPTOPANIC_RATE_LIMIT_PRO",
    "LUNARCRUSH_BASE_URL",
    "LUNARCRUSH_GALAXY_SCORE_STRONG",
    "LUNARCRUSH_GALAXY_SCORE_WEAK",
    "LUNARCRUSH_RATE_LIMIT_FREE",
    "LUNARCRUSH_RATE_LIMIT_PRO",
    "LUNARCRUSH_SENTIMENT_BEARISH",
    "LUNARCRUSH_SENTIMENT_BULLISH",
    "LUNARCRUSH_SENTIMENT_NEUTRAL_HIGH",
    "LUNARCRUSH_SENTIMENT_NEUTRAL_LOW",
    "SENTIMENT_NEGATIVE_THRESHOLD",
    "SENTIMENT_NEUTRAL_RANGE",
    "SENTIMENT_POSITIVE_THRESHOLD",
    # CryptoPanic
    "CryptoPanicCurrency",
    "CryptoPanicError",
    "CryptoPanicPost",
    "CryptoPanicPostsResponse",
    "CryptoPanicRequestParams",
    "CryptoPanicVote",
    # LunarCrush
    "LunarCrushAssetMetrics",
    "LunarCrushAssetsResponse",
    "LunarCrushError",
    "LunarCrushFeed",
    "LunarCrushFeedResponse",
    "LunarCrushInfluencer",
    "LunarCrushInfluencersResponse",
    "LunarCrushRequestParams",
]
