"""Strategy Architecture v2 canonical schemas.

Single source of truth for the 8-family / 18-archetype / 7-axis /
10-cross-cutting taxonomy. See codex/09-strategy/architecture-v2/README.md
and the 60-doc v2 corpus for the full architectural narrative.

Split across enums.py + schemas.py to stay under the 900-line QG limit.
"""

from __future__ import annotations

from unified_api_contracts.internal.architecture_v2.allocator_access import (
    allocator_access_control,
    user_context_for_allocator,
)
from unified_api_contracts.internal.architecture_v2.archetype_capability import (
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    ArchetypeCapabilityCell,
    ArchetypeInstrumentType,
    CoverageStatus,
    RollMode,
    all_capabilities,
    archetypes_for_pair,
    archetypes_for_venue,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.artifact_registry import (
    ArtifactKind,
    ArtifactMetadata,
    ArtifactPublishedPayload,
    ArtifactRef,
)
from unified_api_contracts.internal.architecture_v2.capability_claims import (
    CapabilityClaims,
)
from unified_api_contracts.internal.architecture_v2.client_contract import (
    ClientContract,
)
from unified_api_contracts.internal.architecture_v2.compliance import (
    ComplianceEvent,
    ComplianceSink,
    RuleId,
    ViolationCode,
    combo_id_for,
)
from unified_api_contracts.internal.architecture_v2.cross_venue_routing_policy import (
    CROSS_VENUE_ROUTING_POLICIES,
    CrossVenueLegRole,
    CrossVenueRoutingPolicy,
    RoutingPriority,
    policies_for_settlement_currency,
    policies_for_venue_pair,
    routing_policy_for,
)
from unified_api_contracts.internal.architecture_v2.cross_venue_routing_policy import (
    PolicyNotFoundError as CrossVenuePolicyNotFoundError,
)
from unified_api_contracts.internal.architecture_v2.derivation import (
    AccessDecision,
    ClientAudience,
    ClientContext,
    ClientPackage,
    Combo,
    CommercialPath,
    DemoFlavour,
    DemoUniverse,
    DenialReason,
    DimensionQuery,
    IntegrationDepth,
    InternalCostLeakageError,
    ItemRef,
    Persona,
    Phase,
    PriceQuote,
    PricingTier,
    ProductionRestrictions,
    QuoteLine,
    RestrictionProfile,
    RouteDescriptor,
    Rule08Violation,
    SlotFilter,
    TileLockState,
    UserContext,
    combo,
    prod_restrictions,
)
from unified_api_contracts.internal.architecture_v2.derivation_access import (
    access_control,
)
from unified_api_contracts.internal.architecture_v2.derivation_cost import (
    cost,
)
from unified_api_contracts.internal.architecture_v2.derivation_demo import (
    demo_universe,
)
from unified_api_contracts.internal.architecture_v2.enums import (
    ARCHETYPE_TO_FAMILY,
    AccountActionV2,
    AllocatorArchetype,
    AtomicExecutionMode,
    BacktestGroup,
    BenchmarkFillMode,
    CommissionStructureType,
    CompensationPolicy,
    EdgeMethod,
    FillSource,
    HoldPolicy,
    InstructionActionV2,
    KillSwitchReason,
    MarginMode,
    MevSubmissionMode,
    RiskGateDecision,
    RiskGateLayer,
    ShareClass,
    StakingMethod,
    StrategyArchetype,
    StrategyFamily,
    TransferType,
    Urgency,
    VenueCategoryV2,
    VenueFeature,
    VenueRoutingMode,
    VenueType,
)
from unified_api_contracts.internal.architecture_v2.fund_business_unit import (
    FUND_BUSINESS_UNIT_REGISTRY,
    BusinessUnit,
    CustodyModel,
    FundBusinessUnitEntry,
    FundNotFoundError,
    ServiceFamilyTag,
    fund_for,
    funds_for_business_unit,
    reserving_business_unit_for,
)
from unified_api_contracts.internal.architecture_v2.leveraged_legs import (
    CashSweepPolicy,
    LegDrift,
    LegPortfolioState,
    LegSizingStrategy,
    LegSnapshot,
    LeveragedLeg,
)
from unified_api_contracts.internal.architecture_v2.multi_leg_order_capability import (
    MULTI_LEG_ORDER_CAPABILITY_REGISTRY,
    ListedComboType,
    MultiLegOrderCapability,
    multi_leg_capability_for,
    venues_supporting_combo_type,
    venues_supporting_legs,
)
from unified_api_contracts.internal.architecture_v2.multi_leg_order_capability import (
    VenueNotRegisteredError as MultiLegVenueNotRegisteredError,
)
from unified_api_contracts.internal.architecture_v2.restaking_rewards import (
    LST_REWARD_STREAMS,
    REWARD_TOKEN_ECONOMICS,
    ConvertDustInstruction,
    ConvertedTokenLeg,
    DeferredTokenLeg,
    DustConversionResult,
    DustRouterResult,
    DustToken,
    LSTRewardStream,
    LstSeasonalRewardRow,
    RewardPnLLayer,
    RewardStreamRegistry,
    RewardTokenEconomics,
    TokenAddressMetadata,
    TokenStreamMetadata,
)
from unified_api_contracts.internal.architecture_v2.restriction_profiles import (
    RESTRICTION_PROFILE_REGISTRY,
    Env,
    ProfileYaml,
    QuestionnaireCategory,
    QuestionnaireFundStructure,
    QuestionnaireInstrumentType,
    QuestionnaireLicenceRegion,
    QuestionnaireResponse,
    QuestionnaireServiceFamily,
    QuestionnaireStrategyStyle,
    known_persona_ids,
    resolve_profile,
)
from unified_api_contracts.internal.architecture_v2.schemas import (
    COMPATIBILITY_SEED,
    AccountInstruction,
    AllocationDirective,
    AtomicInstruction,
    AtomicLeg,
    BorrowInstruction,
    BridgeInstructionV2,
    CancelInstruction,
    ChildVenueDecl,
    CollateralRulesV2,
    CommissionStructureV2,
    CommissionTier,
    CompatibilityEntry,
    LendInstruction,
    LtvAndHaircut,
    MarginSpec,
    NettingRule,
    QuoteInstruction,
    RateLimitsV2,
    RegionalRestrictions,
    RiskGateResult,
    StakeInstruction,
    StrategyEquityDirective,
    StrategyInstanceDefinition,
    StrategyInstanceIdentity,
    StrategyInstructionEnvelope,
    SwapInstruction,
    TradeInstruction,
    TransferInstructionV2,
    UnityChildVenue,
    UnstakeInstruction,
    VenueCapabilityV2,
    VenueConstraints,
)
from unified_api_contracts.internal.architecture_v2.service_family_scope import (
    SERVICE_FAMILY_SCOPE_RULES,
    ScopeAllow,
    ScopeDecision,
    ScopeDeny,
    ServiceFamily,
    ServiceFamilyScopeRule,
    check_service_family_scope,
    service_family_from_audience,
)
from unified_api_contracts.internal.architecture_v2.strategy_availability import (
    ALLOCATION_MIN_MATURITY,
    EXTERNAL_VISIBILITY_MIN_MATURITY,
    STRATEGY_AVAILABILITY_REGISTRY,
    Audience,
    LockState,
    StrategyAvailabilityChangedEvent,
    StrategyAvailabilityEntry,
    StrategyMaturity,
    StrategyMaturityTransitionEvent,
    StrategyNotAvailableError,
    StrategyRetiredError,
    availability_for,
    maturity_rank,
    slots_visible_to,
    validate_allocation_authorised,
)
from unified_api_contracts.internal.architecture_v2.usage_meter import (
    MeterKind,
    UsageMeterRow,
)
from unified_api_contracts.internal.architecture_v2.venue_tokens import (
    KNOWN_VENUE_TOKENS,
    is_venue_token,
    split_scope_tokens,
)

# StrategyInstructionV2 is a union — exposed as a type alias here to let
# consumers import it from the sub-package root rather than reaching into
# schemas.py. We inline the alias to avoid Pydantic reimport races.
StrategyInstructionV2 = (
    TradeInstruction
    | SwapInstruction
    | LendInstruction
    | BorrowInstruction
    | StakeInstruction
    | UnstakeInstruction
    | QuoteInstruction
    | TransferInstructionV2
    | BridgeInstructionV2
    | AtomicInstruction
    | CancelInstruction
)


__all__ = [
    "ALLOCATION_MIN_MATURITY",
    "ARCHETYPE_CAPABILITY_REGISTRY",
    "ARCHETYPE_TO_FAMILY",
    "COMPATIBILITY_SEED",
    "CROSS_VENUE_ROUTING_POLICIES",
    "EXTERNAL_VISIBILITY_MIN_MATURITY",
    "FUND_BUSINESS_UNIT_REGISTRY",
    "KNOWN_VENUE_TOKENS",
    "LST_REWARD_STREAMS",
    "MULTI_LEG_ORDER_CAPABILITY_REGISTRY",
    "RESTRICTION_PROFILE_REGISTRY",
    "REWARD_TOKEN_ECONOMICS",
    "SERVICE_FAMILY_SCOPE_RULES",
    "STRATEGY_AVAILABILITY_REGISTRY",
    "AccessDecision",
    "AccountActionV2",
    "AccountInstruction",
    "AllocationDirective",
    "AllocatorArchetype",
    "ArchetypeCapability",
    "ArchetypeCapabilityCell",
    "ArchetypeInstrumentType",
    "ArtifactKind",
    "ArtifactMetadata",
    "ArtifactPublishedPayload",
    "ArtifactRef",
    "AtomicExecutionMode",
    "AtomicInstruction",
    "AtomicLeg",
    "Audience",
    "BacktestGroup",
    "BenchmarkFillMode",
    "BorrowInstruction",
    "BridgeInstructionV2",
    "BusinessUnit",
    "CancelInstruction",
    "CapabilityClaims",
    "CashSweepPolicy",
    "ChildVenueDecl",
    "ClientAudience",
    "ClientContext",
    "ClientContract",
    "ClientPackage",
    "CollateralRulesV2",
    "Combo",
    "CommercialPath",
    "CommissionStructureType",
    "CommissionStructureV2",
    "CommissionTier",
    "CompatibilityEntry",
    "CompensationPolicy",
    "ComplianceEvent",
    "ComplianceSink",
    "ConvertDustInstruction",
    "ConvertedTokenLeg",
    "CoverageStatus",
    "CrossVenueLegRole",
    "CrossVenuePolicyNotFoundError",
    "CrossVenueRoutingPolicy",
    "CustodyModel",
    "DeferredTokenLeg",
    "DemoFlavour",
    "DemoUniverse",
    "DenialReason",
    "DimensionQuery",
    "DustConversionResult",
    "DustRouterResult",
    "DustToken",
    "EdgeMethod",
    "Env",
    "FillSource",
    "FundBusinessUnitEntry",
    "FundNotFoundError",
    "HoldPolicy",
    "InstructionActionV2",
    "IntegrationDepth",
    "InternalCostLeakageError",
    "ItemRef",
    "KillSwitchReason",
    "LSTRewardStream",
    "LegDrift",
    "LegPortfolioState",
    "LegSizingStrategy",
    "LegSnapshot",
    "LendInstruction",
    "LeveragedLeg",
    "ListedComboType",
    "LockState",
    "LstSeasonalRewardRow",
    "LtvAndHaircut",
    "MarginMode",
    "MarginSpec",
    "MeterKind",
    "MevSubmissionMode",
    "MultiLegOrderCapability",
    "MultiLegVenueNotRegisteredError",
    "NettingRule",
    "Persona",
    "Phase",
    "PriceQuote",
    "PricingTier",
    "ProductionRestrictions",
    "ProfileYaml",
    "QuestionnaireCategory",
    "QuestionnaireFundStructure",
    "QuestionnaireInstrumentType",
    "QuestionnaireLicenceRegion",
    "QuestionnaireResponse",
    "QuestionnaireServiceFamily",
    "QuestionnaireStrategyStyle",
    "QuoteInstruction",
    "QuoteLine",
    "RateLimitsV2",
    "RegionalRestrictions",
    "RestrictionProfile",
    "RewardPnLLayer",
    "RewardStreamRegistry",
    "RewardTokenEconomics",
    "RiskGateDecision",
    "RiskGateLayer",
    "RiskGateResult",
    "RollMode",
    "RouteDescriptor",
    "RoutingPriority",
    "Rule08Violation",
    "RuleId",
    "ScopeAllow",
    "ScopeDecision",
    "ScopeDeny",
    "ServiceFamily",
    "ServiceFamilyScopeRule",
    "ServiceFamilyTag",
    "ShareClass",
    "SlotFilter",
    "StakeInstruction",
    "StakingMethod",
    "StrategyArchetype",
    "StrategyAvailabilityChangedEvent",
    "StrategyAvailabilityEntry",
    "StrategyEquityDirective",
    "StrategyFamily",
    "StrategyInstanceDefinition",
    "StrategyInstanceIdentity",
    "StrategyInstructionEnvelope",
    "StrategyInstructionV2",
    "StrategyMaturity",
    "StrategyMaturityTransitionEvent",
    "StrategyNotAvailableError",
    "StrategyRetiredError",
    "SwapInstruction",
    "TileLockState",
    "TokenAddressMetadata",
    "TokenStreamMetadata",
    "TradeInstruction",
    "TransferInstructionV2",
    "TransferType",
    "UnityChildVenue",
    "UnstakeInstruction",
    "Urgency",
    "UsageMeterRow",
    "UserContext",
    "VenueCapabilityV2",
    "VenueCategoryV2",
    "VenueConstraints",
    "VenueFeature",
    "VenueRoutingMode",
    "VenueType",
    "ViolationCode",
    "access_control",
    "all_capabilities",
    "allocator_access_control",
    "archetypes_for_pair",
    "archetypes_for_venue",
    "availability_for",
    "capability_for",
    "check_service_family_scope",
    "combo",
    "combo_id_for",
    "cost",
    "demo_universe",
    "fund_for",
    "funds_for_business_unit",
    "is_venue_token",
    "known_persona_ids",
    "maturity_rank",
    "multi_leg_capability_for",
    "policies_for_settlement_currency",
    "policies_for_venue_pair",
    "prod_restrictions",
    "reserving_business_unit_for",
    "resolve_profile",
    "routing_policy_for",
    "service_family_from_audience",
    "slots_visible_to",
    "split_scope_tokens",
    "user_context_for_allocator",
    "validate_allocation_authorised",
    "venues_supporting_combo_type",
    "venues_supporting_legs",
]
