"""Strategy Architecture v2 canonical schemas.

Single source of truth for the 8-family / 18-archetype / 7-axis /
10-cross-cutting taxonomy. See codex/09-strategy/architecture-v2/README.md
and the 60-doc v2 corpus for the full architectural narrative.

Split across enums.py + schemas.py to stay under the 900-line QG limit.
"""

from __future__ import annotations

from unified_api_contracts.internal.architecture_v2.archetype_capability import (
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    ArchetypeCapabilityCell,
    ArchetypeInstrumentType,
    CoverageStatus,
    RollMode,
    all_capabilities,
    archetypes_for_pair,
    archetypes_for_venue,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.artifact_registry import (
    ArtifactKind,
    ArtifactMetadata,
    ArtifactPublishedPayload,
    ArtifactRef,
)
from unified_api_contracts.internal.architecture_v2.derivation import (
    AccessDecision,
    ClientAudience,
    ClientContext,
    ClientPackage,
    Combo,
    CommercialPath,
    DemoFlavour,
    DemoUniverse,
    DenialReason,
    DimensionQuery,
    IntegrationDepth,
    InternalCostLeakageError,
    ItemRef,
    Persona,
    Phase,
    PriceQuote,
    PricingTier,
    ProductionRestrictions,
    QuoteLine,
    RestrictionProfile,
    RouteDescriptor,
    Rule08Violation,
    SlotFilter,
    TileLockState,
    UserContext,
    access_control,
    combo,
    cost,
    demo_universe,
    prod_restrictions,
)
from unified_api_contracts.internal.architecture_v2.enums import (
    ARCHETYPE_TO_FAMILY,
    AccountActionV2,
    AllocatorArchetype,
    AtomicExecutionMode,
    BacktestGroup,
    BenchmarkFillMode,
    CommissionStructureType,
    CompensationPolicy,
    EdgeMethod,
    FillSource,
    HoldPolicy,
    InstructionActionV2,
    KillSwitchReason,
    MarginMode,
    MevSubmissionMode,
    RiskGateDecision,
    RiskGateLayer,
    ShareClass,
    StakingMethod,
    StrategyArchetypeV2,
    StrategyFamilyV2,
    TransferType,
    Urgency,
    VenueCategoryV2,
    VenueFeature,
    VenueRoutingMode,
    VenueType,
)
from unified_api_contracts.internal.architecture_v2.restriction_profiles import (
    RESTRICTION_PROFILE_REGISTRY,
    Env,
    ProfileYaml,
    QuestionnaireCategory,
    QuestionnaireFundStructure,
    QuestionnaireInstrumentType,
    QuestionnaireResponse,
    QuestionnaireServiceFamily,
    QuestionnaireStrategyStyle,
    known_persona_ids,
    resolve_profile,
)
from unified_api_contracts.internal.architecture_v2.schemas import (
    COMPATIBILITY_SEED,
    AccountInstruction,
    AllocationDirective,
    AtomicInstruction,
    AtomicLeg,
    BorrowInstruction,
    BridgeInstructionV2,
    CancelInstruction,
    ChildVenueDecl,
    CollateralRulesV2,
    CommissionStructureV2,
    CommissionTier,
    CompatibilityEntry,
    LendInstruction,
    LtvAndHaircut,
    MarginSpec,
    NettingRule,
    QuoteInstruction,
    RateLimitsV2,
    RegionalRestrictions,
    RiskGateResult,
    StakeInstruction,
    StrategyEquityDirective,
    StrategyInstanceDefinition,
    StrategyInstanceIdentity,
    StrategyInstructionEnvelope,
    SwapInstruction,
    TradeInstruction,
    TransferInstructionV2,
    UnityChildVenue,
    UnstakeInstruction,
    VenueCapabilityV2,
    VenueConstraints,
)
from unified_api_contracts.internal.architecture_v2.service_family_scope import (
    SERVICE_FAMILY_SCOPE_RULES,
    ScopeAllow,
    ScopeDecision,
    ScopeDeny,
    ServiceFamily,
    ServiceFamilyScopeRule,
    check_service_family_scope,
    service_family_from_audience,
)
from unified_api_contracts.internal.architecture_v2.strategy_availability import (
    ALLOCATION_MIN_MATURITY,
    EXTERNAL_VISIBILITY_MIN_MATURITY,
    STRATEGY_AVAILABILITY_REGISTRY,
    Audience,
    LockState,
    StrategyAvailabilityChangedEvent,
    StrategyAvailabilityEntry,
    StrategyMaturity,
    StrategyMaturityTransitionEvent,
    StrategyNotAvailableError,
    StrategyRetiredError,
    availability_for,
    maturity_rank,
    slots_visible_to,
    validate_allocation_authorised,
)
from unified_api_contracts.internal.architecture_v2.venue_tokens import (
    KNOWN_VENUE_TOKENS,
    is_venue_token,
    split_scope_tokens,
)

# StrategyInstructionV2 is a union — exposed as a type alias here to let
# consumers import it from the sub-package root rather than reaching into
# schemas.py. We inline the alias to avoid Pydantic reimport races.
StrategyInstructionV2 = (
    TradeInstruction
    | SwapInstruction
    | LendInstruction
    | BorrowInstruction
    | StakeInstruction
    | UnstakeInstruction
    | QuoteInstruction
    | TransferInstructionV2
    | BridgeInstructionV2
    | AtomicInstruction
    | CancelInstruction
)


__all__ = [
    "ALLOCATION_MIN_MATURITY",
    "ARCHETYPE_CAPABILITY_REGISTRY",
    "ARCHETYPE_TO_FAMILY",
    "COMPATIBILITY_SEED",
    "EXTERNAL_VISIBILITY_MIN_MATURITY",
    "KNOWN_VENUE_TOKENS",
    "RESTRICTION_PROFILE_REGISTRY",
    "SERVICE_FAMILY_SCOPE_RULES",
    "STRATEGY_AVAILABILITY_REGISTRY",
    "AccessDecision",
    "AccountActionV2",
    "AccountInstruction",
    "AllocationDirective",
    "AllocatorArchetype",
    "ArchetypeCapability",
    "ArchetypeCapabilityCell",
    "ArchetypeInstrumentType",
    "ArtifactKind",
    "ArtifactMetadata",
    "ArtifactPublishedPayload",
    "ArtifactRef",
    "AtomicExecutionMode",
    "AtomicInstruction",
    "AtomicLeg",
    "Audience",
    "BacktestGroup",
    "BenchmarkFillMode",
    "BorrowInstruction",
    "BridgeInstructionV2",
    "CancelInstruction",
    "ChildVenueDecl",
    "ClientAudience",
    "ClientContext",
    "ClientPackage",
    "CollateralRulesV2",
    "Combo",
    "CommercialPath",
    "CommissionStructureType",
    "CommissionStructureV2",
    "CommissionTier",
    "CompatibilityEntry",
    "CompensationPolicy",
    "CoverageStatus",
    "DemoFlavour",
    "DemoUniverse",
    "DenialReason",
    "DimensionQuery",
    "EdgeMethod",
    "Env",
    "FillSource",
    "HoldPolicy",
    "InstructionActionV2",
    "IntegrationDepth",
    "InternalCostLeakageError",
    "ItemRef",
    "KillSwitchReason",
    "LendInstruction",
    "LockState",
    "LtvAndHaircut",
    "MarginMode",
    "MarginSpec",
    "MevSubmissionMode",
    "NettingRule",
    "Persona",
    "Phase",
    "PriceQuote",
    "PricingTier",
    "ProductionRestrictions",
    "ProfileYaml",
    "QuestionnaireCategory",
    "QuestionnaireFundStructure",
    "QuestionnaireInstrumentType",
    "QuestionnaireResponse",
    "QuestionnaireServiceFamily",
    "QuestionnaireStrategyStyle",
    "QuoteInstruction",
    "QuoteLine",
    "RateLimitsV2",
    "RegionalRestrictions",
    "RestrictionProfile",
    "RiskGateDecision",
    "RiskGateLayer",
    "RiskGateResult",
    "RollMode",
    "RouteDescriptor",
    "Rule08Violation",
    "ScopeAllow",
    "ScopeDecision",
    "ScopeDeny",
    "ServiceFamily",
    "ServiceFamilyScopeRule",
    "ShareClass",
    "SlotFilter",
    "StakeInstruction",
    "StakingMethod",
    "StrategyArchetypeV2",
    "StrategyAvailabilityChangedEvent",
    "StrategyAvailabilityEntry",
    "StrategyEquityDirective",
    "StrategyFamilyV2",
    "StrategyInstanceDefinition",
    "StrategyInstanceIdentity",
    "StrategyInstructionEnvelope",
    "StrategyInstructionV2",
    "StrategyMaturity",
    "StrategyMaturityTransitionEvent",
    "StrategyNotAvailableError",
    "StrategyRetiredError",
    "SwapInstruction",
    "TileLockState",
    "TradeInstruction",
    "TransferInstructionV2",
    "TransferType",
    "UnityChildVenue",
    "UnstakeInstruction",
    "Urgency",
    "UserContext",
    "VenueCapabilityV2",
    "VenueCategoryV2",
    "VenueConstraints",
    "VenueFeature",
    "VenueRoutingMode",
    "VenueType",
    "access_control",
    "all_capabilities",
    "archetypes_for_pair",
    "archetypes_for_venue",
    "availability_for",
    "capability_for",
    "check_service_family_scope",
    "combo",
    "cost",
    "demo_universe",
    "is_venue_token",
    "known_persona_ids",
    "maturity_rank",
    "prod_restrictions",
    "resolve_profile",
    "service_family_from_audience",
    "slots_visible_to",
    "split_scope_tokens",
    "validate_allocation_authorised",
]
