"""Strategy Architecture v2 canonical schemas.

Single source of truth for the 8-family / 18-archetype / 7-axis /
10-cross-cutting taxonomy. See codex/09-strategy/architecture-v2/README.md
and the 60-doc v2 corpus for the full architectural narrative.

Split across enums.py + schemas.py to stay under the 900-line QG limit.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Archetype leg-spec registry — structural per-leg restriction model (F22,
# capability_wizard_and_manifest_2026_06_11.md). The NEW SSOT for leg truth;
# dual-represented alongside ARCHETYPE_CAPABILITY_REGISTRY (see the module
# docstring). ADDITIVE — no existing exports moved or renamed.
# ---------------------------------------------------------------------------
from unified_api_contracts.internal.architecture_v2.algo_compatibility import (
    ALGOS_BY_INSTRUCTION_TYPE,
    ARCHETYPE_ALGO_COMPATIBILITY,
    DEFAULT_ALGO_BY_INSTRUCTION_TYPE,
    EXECUTION_ALGOS,
    SELECTOR_CONTRADICTIONS,
    AlgoVerdict,
    ArchetypeAlgoCompatibility,
    ExecutionAlgo,
    SelectorContradiction,
    VenueExecutionKind,
    algo_compatibility_for,
    all_algo_compatibility,
    instruction_type_for,
    venue_kinds_for_asset_group,
)
from unified_api_contracts.internal.architecture_v2.allocator_access import (
    allocator_access_control,
    user_context_for_allocator,
)
from unified_api_contracts.internal.architecture_v2.archetype_capability import (
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    ArchetypeCapabilityCell,
    ArchetypeInstrumentType,
    CoverageStatus,
    RollMode,
    all_capabilities,
    archetypes_for_pair,
    archetypes_for_venue,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.archetype_leg_spec import (
    ARCHETYPE_LEG_STRUCTURES,
    ArchetypeLegRole,
    ArchetypeLegSpec,
    ArchetypeLegStructure,
    LegConstraint,
    LegConstraintKind,
    all_leg_structures,
    archetypes_without_leg_structures,
    leg_structure_for,
    registered_leg_structures,
)
from unified_api_contracts.internal.architecture_v2.artifact_registry import (
    ArtifactKind,
    ArtifactMetadata,
    ArtifactPublishedPayload,
    ArtifactRef,
)
from unified_api_contracts.internal.architecture_v2.broker_routes import (
    BROKER_ROUTES,
    BrokerKind,
    BrokerRoute,
    broker_for_venue,
    is_broker,
    routed_venue_ids,
)
from unified_api_contracts.internal.architecture_v2.capability_claims import (
    CapabilityClaims,
)

# ---------------------------------------------------------------------------
# Capability manifest + gap registries (Phase 1 + Phase 2 schemas,
# capability_wizard_and_manifest_2026_06_11.md).
# ADDITIVE — no existing exports moved or renamed.
# ---------------------------------------------------------------------------
from unified_api_contracts.internal.architecture_v2.capability_manifest import (
    AgentAnnotation,
    CapabilityEdge,
    CapabilityEdgeStatus,
    CapabilityGapType,
    CapabilityManifest,
    CapabilityNode,
    CapabilityNodeKind,
    GapSummary,
)
from unified_api_contracts.internal.architecture_v2.client_contract import (
    ClientContract,
)
from unified_api_contracts.internal.architecture_v2.collateral_registry import (
    BROKER_REGISTRY,
    COLLATERAL_REGISTRY,
    TREASURY_SPLIT_POLICIES,
    AssetHaircut,
    BrokerEntry,
    CollateralAsset,
    CollateralPolicy,
    LiquidationProtocol,
    TreasurySplitPolicy,
    WalletTier,
)
from unified_api_contracts.internal.architecture_v2.compliance import (
    ComplianceEvent,
    ComplianceSink,
    RuleId,
    ViolationCode,
    combo_id_for,
)

# ---------------------------------------------------------------------------
# Cost & capacity model (Wave-2 #8, capability_wizard_and_manifest_2026_06_11.md).
# Consumes FEES_REGISTRY + the lifecycle_class taxonomy. ADDITIVE.
# ---------------------------------------------------------------------------
from unified_api_contracts.internal.architecture_v2.cost_capacity import (
    CostCapacityModel,
    VenueFeeBreakdown,
    compute_cost_capacity,
)
from unified_api_contracts.internal.architecture_v2.cross_venue_routing_policy import (
    CROSS_VENUE_ROUTING_POLICIES,
    CrossVenueLegRole,
    CrossVenueRoutingPolicy,
    RoutingPriority,
    policies_for_settlement_currency,
    policies_for_venue_pair,
    routing_policy_for,
)
from unified_api_contracts.internal.architecture_v2.cross_venue_routing_policy import (
    PolicyNotFoundError as CrossVenuePolicyNotFoundError,
)

# ---------------------------------------------------------------------------
# Custody / signing-surface registry (Wave A, F49 re-kind — exporter abused
# custody_provider as a catch-all). Sibling pattern to collateral_registry /
# order_semantics. REUSES SigningSurface (no duplicate enum). ADDITIVE.
# ---------------------------------------------------------------------------
from unified_api_contracts.internal.architecture_v2.custody_surfaces import (
    CEFFU_ROUTES_VIA_COPPER_NOTE,
    OFFERED_SIGNING_SURFACES,
    SigningSurfacePolicy,
    SigningSurfaceStatus,
    surface_policy_for,
)
from unified_api_contracts.internal.architecture_v2.derivation import (
    AccessDecision,
    ClientAudience,
    ClientContext,
    ClientPackage,
    Combo,
    CommercialPath,
    DemoFlavour,
    DemoUniverse,
    DenialReason,
    DimensionQuery,
    IntegrationDepth,
    InternalCostLeakageError,
    ItemRef,
    Persona,
    Phase,
    PriceQuote,
    PricingTier,
    ProductionRestrictions,
    QuoteLine,
    RestrictionProfile,
    RouteDescriptor,
    Rule08Violation,
    SlotFilter,
    TileLockState,
    UserContext,
    combo,
    prod_restrictions,
)
from unified_api_contracts.internal.architecture_v2.derivation_access import (
    access_control,
)
from unified_api_contracts.internal.architecture_v2.derivation_cost import (
    cost,
)
from unified_api_contracts.internal.architecture_v2.derivation_demo import (
    demo_universe,
)
from unified_api_contracts.internal.architecture_v2.enums import (
    ARCHETYPE_TO_FAMILY,
    BENCHMARK_FILL_MODE_BY_ACTION,
    AccountActionV2,
    AllocatorArchetype,
    AtomicExecutionMode,
    BacktestGroup,
    BenchmarkFillMode,
    CommissionStructureType,
    CompensationPolicy,
    EdgeMethod,
    FillSource,
    HoldPolicy,
    InstructionActionV2,
    KillSwitchReason,
    MarginMode,
    MevSubmissionMode,
    RiskGateDecision,
    RiskGateLayer,
    ShareClass,
    StakingMethod,
    StrategyArchetype,
    StrategyFamily,
    TransferType,
    Urgency,
    VenueCategoryV2,
    VenueFeature,
    VenueRoutingMode,
    VenueType,
)
from unified_api_contracts.internal.architecture_v2.fees_registry import (
    FEES_REGISTRY,
    FeeComponent,
    FeeSchedule,
    FeeUnit,
)
from unified_api_contracts.internal.architecture_v2.fund_business_unit import (
    FUND_BUSINESS_UNIT_REGISTRY,
    BusinessUnit,
    CustodyModel,
    FundBusinessUnitEntry,
    FundNotFoundError,
    ServiceFamilyTag,
    fund_for,
    funds_for_business_unit,
    reserving_business_unit_for,
)
from unified_api_contracts.internal.architecture_v2.fund_structures import (
    OFFERED_FUND_STRUCTURES,
    CadenceKind,
    FundStructureKind,
    FundStructureOffering,
)
from unified_api_contracts.internal.architecture_v2.jurisdiction_overlay import (
    JURISDICTION_VENUE_POLICIES,
    KNOWN_VENUE_IDS,
    Jurisdiction,
    JurisdictionAccess,
    JurisdictionVenuePolicy,
    allowed_venues_for_jurisdiction,
    is_venue_allowed,
)
from unified_api_contracts.internal.architecture_v2.leveraged_legs import (
    CashSweepPolicy,
    LegDrift,
    LegPortfolioState,
    LegSizingStrategy,
    LegSnapshot,
    LeveragedLeg,
)
from unified_api_contracts.internal.architecture_v2.multi_leg_order_capability import (
    MULTI_LEG_ORDER_CAPABILITY_REGISTRY,
    ListedComboType,
    MultiLegOrderCapability,
    multi_leg_capability_for,
    venues_supporting_combo_type,
    venues_supporting_legs,
)
from unified_api_contracts.internal.architecture_v2.multi_leg_order_capability import (
    VenueNotRegisteredError as MultiLegVenueNotRegisteredError,
)
from unified_api_contracts.internal.architecture_v2.order_semantics import (
    VENUE_ORDER_SEMANTICS,
    MultiLegDeltaOwner,
    RefPricingMode,
    TimeInForce,
    VenueOrderSemantics,
)
from unified_api_contracts.internal.architecture_v2.paired_dispersion_catalog import (
    PAIRED_DISPERSION_CATALOG,
    PairedDispersionCatalogRow,
)
from unified_api_contracts.internal.architecture_v2.restaking_rewards import (
    LST_REWARD_STREAMS,
    REWARD_TOKEN_ECONOMICS,
    ConvertDustInstruction,
    ConvertedTokenLeg,
    DeferredTokenLeg,
    DustConversionResult,
    DustRouterResult,
    DustToken,
    LSTRewardStream,
    LstSeasonalRewardRow,
    RewardPnLLayer,
    RewardStreamRegistry,
    RewardTokenEconomics,
    TokenAddressMetadata,
    TokenStreamMetadata,
)
from unified_api_contracts.internal.architecture_v2.restriction_profiles import (
    RESTRICTION_PROFILE_REGISTRY,
    Env,
    ProfileYaml,
    QuestionnaireCategory,
    QuestionnaireFundStructure,
    QuestionnaireInstrumentType,
    QuestionnaireLicenceRegion,
    QuestionnaireResponse,
    QuestionnaireServiceFamily,
    QuestionnaireStrategyStyle,
    known_persona_ids,
    resolve_profile,
)
from unified_api_contracts.internal.architecture_v2.scenario_step import (
    RiskGateDecisionRecord,
    ScenarioConfigRef,
    ScenarioSession,
    StepFill,
    StepInput,
    StepReport,
    TriggerEvaluation,
    TriggerKind,
)
from unified_api_contracts.internal.architecture_v2.schemas import (
    COMPATIBILITY_SEED,
    AccountInstruction,
    AllocationDirective,
    AtomicInstruction,
    AtomicLeg,
    BorrowInstruction,
    BridgeInstructionV2,
    CancelInstruction,
    ChildVenueDecl,
    CollateralRulesV2,
    CommissionStructureV2,
    CommissionTier,
    CompatibilityEntry,
    LendInstruction,
    LtvAndHaircut,
    MarginSpec,
    NettingRule,
    QuoteInstruction,
    RateLimitsV2,
    RegionalRestrictions,
    RiskGateResult,
    StakeInstruction,
    StrategyEquityDirective,
    StrategyInstanceDefinition,
    StrategyInstanceIdentity,
    StrategyInstructionEnvelope,
    SwapInstruction,
    TradeInstruction,
    TransferInstructionV2,
    UnityChildVenue,
    UnstakeInstruction,
    VenueCapabilityV2,
    VenueConstraints,
)
from unified_api_contracts.internal.architecture_v2.service_family_scope import (
    SERVICE_FAMILY_SCOPE_RULES,
    ScopeAllow,
    ScopeDecision,
    ScopeDeny,
    ServiceFamily,
    ServiceFamilyScopeRule,
    check_service_family_scope,
    service_family_from_audience,
)
from unified_api_contracts.internal.architecture_v2.simulation_assumptions import (
    MATCHING_MODEL_TO_BENCHMARK_FILL,
    SIM_ASSUMPTIONS_REGISTRY,
    MatchingModel,
    SimulationAssumption,
)
from unified_api_contracts.internal.architecture_v2.strategy_availability import (
    ALLOCATION_MIN_MATURITY,
    EXTERNAL_VISIBILITY_MIN_MATURITY,
    STRATEGY_AVAILABILITY_REGISTRY,
    Audience,
    LockState,
    StrategyAvailabilityChangedEvent,
    StrategyAvailabilityEntry,
    StrategyMaturity,
    StrategyMaturityTransitionEvent,
    StrategyNotAvailableError,
    StrategyRetiredError,
    availability_for,
    maturity_rank,
    slots_visible_to,
    validate_allocation_authorised,
)
from unified_api_contracts.internal.architecture_v2.trading_agent_capability import (
    TRADING_AGENT_CAPABILITIES,
    TradingAgentCapability,
)
from unified_api_contracts.internal.architecture_v2.usage_meter import (
    MeterKind,
    UsageMeterRow,
)
from unified_api_contracts.internal.architecture_v2.venue_tokens import (
    KNOWN_VENUE_TOKENS,
    is_venue_token,
    split_scope_tokens,
)

# StrategyInstructionV2 is a union — exposed as a type alias here to let
# consumers import it from the sub-package root rather than reaching into
# schemas.py. We inline the alias to avoid Pydantic reimport races.
StrategyInstructionV2 = (
    TradeInstruction
    | SwapInstruction
    | LendInstruction
    | BorrowInstruction
    | StakeInstruction
    | UnstakeInstruction
    | QuoteInstruction
    | TransferInstructionV2
    | BridgeInstructionV2
    | AtomicInstruction
    | CancelInstruction
)


__all__ = [
    "ALGOS_BY_INSTRUCTION_TYPE",
    "ALLOCATION_MIN_MATURITY",
    "ARCHETYPE_ALGO_COMPATIBILITY",
    "ARCHETYPE_CAPABILITY_REGISTRY",
    "ARCHETYPE_LEG_STRUCTURES",
    "ARCHETYPE_TO_FAMILY",
    "BENCHMARK_FILL_MODE_BY_ACTION",
    "BROKER_REGISTRY",
    "BROKER_ROUTES",
    "CEFFU_ROUTES_VIA_COPPER_NOTE",
    "COLLATERAL_REGISTRY",
    "COMPATIBILITY_SEED",
    "CROSS_VENUE_ROUTING_POLICIES",
    "DEFAULT_ALGO_BY_INSTRUCTION_TYPE",
    "EXECUTION_ALGOS",
    "EXTERNAL_VISIBILITY_MIN_MATURITY",
    "FEES_REGISTRY",
    "FUND_BUSINESS_UNIT_REGISTRY",
    "JURISDICTION_VENUE_POLICIES",
    "KNOWN_VENUE_IDS",
    "KNOWN_VENUE_TOKENS",
    "LST_REWARD_STREAMS",
    "MATCHING_MODEL_TO_BENCHMARK_FILL",
    "MULTI_LEG_ORDER_CAPABILITY_REGISTRY",
    "OFFERED_FUND_STRUCTURES",
    "OFFERED_SIGNING_SURFACES",
    "PAIRED_DISPERSION_CATALOG",
    "RESTRICTION_PROFILE_REGISTRY",
    "REWARD_TOKEN_ECONOMICS",
    "SELECTOR_CONTRADICTIONS",
    "SERVICE_FAMILY_SCOPE_RULES",
    "SIM_ASSUMPTIONS_REGISTRY",
    "STRATEGY_AVAILABILITY_REGISTRY",
    "TRADING_AGENT_CAPABILITIES",
    "TREASURY_SPLIT_POLICIES",
    "VENUE_ORDER_SEMANTICS",
    "AccessDecision",
    "AccountActionV2",
    "AccountInstruction",
    "AgentAnnotation",
    "AlgoVerdict",
    "AllocationDirective",
    "AllocatorArchetype",
    "ArchetypeAlgoCompatibility",
    "ArchetypeCapability",
    "ArchetypeCapabilityCell",
    "ArchetypeInstrumentType",
    "ArchetypeLegRole",
    "ArchetypeLegSpec",
    "ArchetypeLegStructure",
    "ArtifactKind",
    "ArtifactMetadata",
    "ArtifactPublishedPayload",
    "ArtifactRef",
    "AssetHaircut",
    "AtomicExecutionMode",
    "AtomicInstruction",
    "AtomicLeg",
    "Audience",
    "BacktestGroup",
    "BenchmarkFillMode",
    "BorrowInstruction",
    "BridgeInstructionV2",
    "BrokerEntry",
    "BrokerKind",
    "BrokerRoute",
    "BusinessUnit",
    "CadenceKind",
    "CancelInstruction",
    "CapabilityClaims",
    "CapabilityEdge",
    "CapabilityEdgeStatus",
    "CapabilityGapType",
    "CapabilityManifest",
    "CapabilityNode",
    "CapabilityNodeKind",
    "CashSweepPolicy",
    "ChildVenueDecl",
    "ClientAudience",
    "ClientContext",
    "ClientContract",
    "ClientPackage",
    "CollateralAsset",
    "CollateralPolicy",
    "CollateralRulesV2",
    "Combo",
    "CommercialPath",
    "CommissionStructureType",
    "CommissionStructureV2",
    "CommissionTier",
    "CompatibilityEntry",
    "CompensationPolicy",
    "ComplianceEvent",
    "ComplianceSink",
    "ConvertDustInstruction",
    "ConvertedTokenLeg",
    "CostCapacityModel",
    "CoverageStatus",
    "CrossVenueLegRole",
    "CrossVenuePolicyNotFoundError",
    "CrossVenueRoutingPolicy",
    "CustodyModel",
    "DeferredTokenLeg",
    "DemoFlavour",
    "DemoUniverse",
    "DenialReason",
    "DimensionQuery",
    "DustConversionResult",
    "DustRouterResult",
    "DustToken",
    "EdgeMethod",
    "Env",
    "ExecutionAlgo",
    "FeeComponent",
    "FeeSchedule",
    "FeeUnit",
    "FillSource",
    "FundBusinessUnitEntry",
    "FundNotFoundError",
    "FundStructureKind",
    "FundStructureOffering",
    "GapSummary",
    "HoldPolicy",
    "InstructionActionV2",
    "IntegrationDepth",
    "InternalCostLeakageError",
    "ItemRef",
    "Jurisdiction",
    "JurisdictionAccess",
    "JurisdictionVenuePolicy",
    "KillSwitchReason",
    "LSTRewardStream",
    "LegConstraint",
    "LegConstraintKind",
    "LegDrift",
    "LegPortfolioState",
    "LegSizingStrategy",
    "LegSnapshot",
    "LendInstruction",
    "LeveragedLeg",
    "LiquidationProtocol",
    "ListedComboType",
    "LockState",
    "LstSeasonalRewardRow",
    "LtvAndHaircut",
    "MarginMode",
    "MarginSpec",
    "MatchingModel",
    "MeterKind",
    "MevSubmissionMode",
    "MultiLegDeltaOwner",
    "MultiLegOrderCapability",
    "MultiLegVenueNotRegisteredError",
    "NettingRule",
    "PairedDispersionCatalogRow",
    "Persona",
    "Phase",
    "PriceQuote",
    "PricingTier",
    "ProductionRestrictions",
    "ProfileYaml",
    "QuestionnaireCategory",
    "QuestionnaireFundStructure",
    "QuestionnaireInstrumentType",
    "QuestionnaireLicenceRegion",
    "QuestionnaireResponse",
    "QuestionnaireServiceFamily",
    "QuestionnaireStrategyStyle",
    "QuoteInstruction",
    "QuoteLine",
    "RateLimitsV2",
    "RefPricingMode",
    "RegionalRestrictions",
    "RestrictionProfile",
    "RewardPnLLayer",
    "RewardStreamRegistry",
    "RewardTokenEconomics",
    "RiskGateDecision",
    "RiskGateDecisionRecord",
    "RiskGateLayer",
    "RiskGateResult",
    "RollMode",
    "RouteDescriptor",
    "RoutingPriority",
    "Rule08Violation",
    "RuleId",
    "ScenarioConfigRef",
    "ScenarioSession",
    "ScopeAllow",
    "ScopeDecision",
    "ScopeDeny",
    "SelectorContradiction",
    "ServiceFamily",
    "ServiceFamilyScopeRule",
    "ServiceFamilyTag",
    "ShareClass",
    "SigningSurfacePolicy",
    "SigningSurfaceStatus",
    "SimulationAssumption",
    "SlotFilter",
    "StakeInstruction",
    "StakingMethod",
    "StepFill",
    "StepInput",
    "StepReport",
    "StrategyArchetype",
    "StrategyAvailabilityChangedEvent",
    "StrategyAvailabilityEntry",
    "StrategyEquityDirective",
    "StrategyFamily",
    "StrategyInstanceDefinition",
    "StrategyInstanceIdentity",
    "StrategyInstructionEnvelope",
    "StrategyInstructionV2",
    "StrategyMaturity",
    "StrategyMaturityTransitionEvent",
    "StrategyNotAvailableError",
    "StrategyRetiredError",
    "SwapInstruction",
    "TileLockState",
    "TimeInForce",
    "TokenAddressMetadata",
    "TokenStreamMetadata",
    "TradeInstruction",
    "TradingAgentCapability",
    "TransferInstructionV2",
    "TransferType",
    "TreasurySplitPolicy",
    "TriggerEvaluation",
    "TriggerKind",
    "UnityChildVenue",
    "UnstakeInstruction",
    "Urgency",
    "UsageMeterRow",
    "UserContext",
    "VenueCapabilityV2",
    "VenueCategoryV2",
    "VenueConstraints",
    "VenueExecutionKind",
    "VenueFeature",
    "VenueFeeBreakdown",
    "VenueOrderSemantics",
    "VenueRoutingMode",
    "VenueType",
    "ViolationCode",
    "WalletTier",
    "access_control",
    "algo_compatibility_for",
    "all_algo_compatibility",
    "all_capabilities",
    "all_leg_structures",
    "allocator_access_control",
    "allowed_venues_for_jurisdiction",
    "archetypes_for_pair",
    "archetypes_for_venue",
    "archetypes_without_leg_structures",
    "availability_for",
    "broker_for_venue",
    "capability_for",
    "check_service_family_scope",
    "combo",
    "combo_id_for",
    "compute_cost_capacity",
    "cost",
    "demo_universe",
    "fund_for",
    "funds_for_business_unit",
    "instruction_type_for",
    "is_broker",
    "is_venue_allowed",
    "is_venue_token",
    "known_persona_ids",
    "leg_structure_for",
    "maturity_rank",
    "multi_leg_capability_for",
    "policies_for_settlement_currency",
    "policies_for_venue_pair",
    "prod_restrictions",
    "registered_leg_structures",
    "reserving_business_unit_for",
    "resolve_profile",
    "routed_venue_ids",
    "routing_policy_for",
    "service_family_from_audience",
    "slots_visible_to",
    "split_scope_tokens",
    "surface_policy_for",
    "user_context_for_allocator",
    "validate_allocation_authorised",
    "venue_kinds_for_asset_group",
    "venues_supporting_combo_type",
    "venues_supporting_legs",
]
