"""Capability manifest schema — the typed graph of what the system can do.

Every edge in the manifest carries a status (available/partial/not_available/
not_registered) and, where applicable, a typed gap reason and an optional
agent annotation written back by the agent-orchestrator so questions are
answered once and cached.

The manifest is generated by
``unified-trading-pm/scripts/openapi/generate_capability_manifest.py``.
This module owns only the schema; the generator populates it.

Codex SSOT:
  ``codex/09-strategy/architecture-v2/capability-wizard.md``
Plan:
  ``plans/active/capability_wizard_and_manifest_2026_06_11.md``
  Phase 1 [SPEC] P0.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Node kinds
# ---------------------------------------------------------------------------


class CapabilityNodeKind(StrEnum):
    """Vocabulary of node types in the capability graph.

    Each value corresponds to a dimension of the wizard walkthrough (Stage A-J
    in ``capability-wizard-question-bank.md``).
    """

    ARCHETYPE = "archetype"
    """A ``StrategyArchetype`` entry (53 total)."""

    LEG = "leg"
    """A structural leg of a multi-leg archetype (``ArchetypeLegSpec``).

    Sourced from ``ARCHETYPE_LEG_STRUCTURES`` (F22 leg-truth SSOT). An
    ``archetype --has_leg--> leg`` edge carries the leg ``role`` + ``required``
    flag; ``leg --trades_instrument--> instrument_type`` and
    ``leg --supports--> venue`` edges give the per-leg restriction surface the
    flat ``(asset_group, instrument_type)`` cell model cannot express.
    """

    FAMILY = "family"
    """A ``StrategyFamily`` entry (9 total)."""

    VENUE = "venue"
    """A named trading venue / DEX / lending protocol."""

    CHAIN = "chain"
    """A blockchain network (Ethereum, Solana, Arbitrum, …)."""

    INSTRUMENT_TYPE = "instrument_type"
    """An ``ArchetypeInstrumentType`` value (spot/perp/dated_future/…)."""

    EXECUTION_ALGO = "execution_algo"
    """An execution algorithm (SOR, sor_twap, swap_twap, …)."""

    INSTRUCTION_TYPE = "instruction_type"
    """An ``InstructionActionV2`` value (TRADE/SWAP/LEND/…)."""

    FEATURE_GROUP = "feature_group"
    """A feature group from the features-service registry (~34 groups)."""

    ML_MODEL = "ml_model"
    """A registered ML model from ml-service model_registry."""

    DATA_SOURCE = "data_source"
    """A named data source / vendor (hyperliquid, databento, polymarket_clob, …)."""

    FUND_STRUCTURE = "fund_structure"
    """A fund-structure offering (pooled/SMA/prop)."""

    WALLET = "wallet"
    """A wallet type in the hierarchy (treasury/hot) per share class."""

    BROKER = "broker"
    """A TradFi broker usable for execution or custody."""

    CUSTODY_PROVIDER = "custody_provider"
    """A custody provider (Copper, CEFFU, CLOUD_KMS_ENCRYPTED, …).

    Historically abused as a catch-all (F49); the additive kinds below let the
    PM exporter (Wave B) re-kind the surfaces it was overloading onto this.
    """

    SIGNING_SURFACE = "signing_surface"
    """A real custody / transaction-signing surface (``SigningSurface`` enum —
    CLOUD_KMS_ENCRYPTED / COPPER_MPC / FIREBLOCKS_MPC / LOCAL_KEY / MOCK).

    Sourced from ``custody_surfaces.OFFERED_SIGNING_SURFACES`` (F49 re-kind):
    these are the HSM/MPC tiers a wallet signs through, NOT the higher-level
    ``custody_provider`` business relationship. May-23 ships CLOUD_KMS_ENCRYPTED;
    June-1 flips per-wallet to COPPER_MPC."""

    RISK_GATE_LAYER = "risk_gate_layer"
    """A risk-gate / pre-flight check layer in the execution pipeline."""

    KILL_SWITCH_REASON = "kill_switch_reason"
    """A kill-switch / circuit-breaker trigger reason."""

    GAP_REGISTRY = "gap_registry"
    """A capability gap registry (the forcing-function registries that surface
    unregistered cells)."""

    COLLATERAL_POLICY = "collateral_policy"
    """A per-venue collateral / margin / liquidation policy
    (``collateral_registry.CollateralPolicy``)."""


# ---------------------------------------------------------------------------
# Edge statuses + gap types
# ---------------------------------------------------------------------------


class CapabilityEdgeStatus(StrEnum):
    """Availability status of a capability edge.

    The wizard renders these as visual indicators:
    - ``available``      → green tick
    - ``partial``        → amber tick (supported but with caveats)
    - ``not_available``  → red cross (logical dead-end or known limitation)
    - ``not_registered`` → grey question mark (registry gap — schematically
      possible but no registry entry yet; the forcing-function state)
    """

    AVAILABLE = "available"
    PARTIAL = "partial"
    NOT_AVAILABLE = "not_available"
    NOT_REGISTERED = "not_registered"


class CapabilityGapType(StrEnum):
    """Typed reason why an edge carries a gap status.

    Used by the escalation pipeline:
    - ``missing_registry``   → gap in a UAC registry (fill the registry)
    - ``missing_extraction`` → registry may exist but the exporter cannot yet
      extract / derive the value
    - ``needs_code_scan``    → requires an agent-orchestrator code scan to
      determine definitively; answer is written back as ``agent_annotation``
    - ``logical_dead_end``   → structurally impossible (e.g. options on a
      sports venue); correct and expected, not a build gap
    """

    MISSING_REGISTRY = "missing_registry"
    MISSING_EXTRACTION = "missing_extraction"
    NEEDS_CODE_SCAN = "needs_code_scan"
    LOGICAL_DEAD_END = "logical_dead_end"


# ---------------------------------------------------------------------------
# Node + Edge models
# ---------------------------------------------------------------------------


class CapabilityNode(BaseModel):
    """A single node in the capability graph."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    kind: CapabilityNodeKind = Field(description="Vocabulary category of this node (archetype, venue, chain, …).")
    node_id: str = Field(
        description=(
            "Stable, unique identifier for this node within its ``kind``. "
            "Should match the StrEnum value where one exists (e.g. "
            "``CARRY_STAKED_BASIS``, ``hyperliquid``). Never reassigned."
        )
    )
    label: str = Field(
        description=(
            "Human-readable display label used by the wizard UI. "
            "May differ from ``node_id`` for readability (e.g. "
            "``node_id='CARRY_STAKED_BASIS'`` → ``label='Carry: Staked Basis'``)."
        )
    )
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Arbitrary key-value metadata attached to the node. "
            "Used for extra context surfaced in side-by-side help text. "
            "Keys must be valid Python identifiers; values are strings."
        ),
    )


class AgentAnnotation(BaseModel):
    """An agent-orchestrator answer written back into a capability edge.

    Once written, the edge's ``gap_type`` should be cleared (the gap is
    resolved) and the edge status updated accordingly. Annotations are
    append-only and keyed by ``annotated_at`` UTC datetime.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    annotated_by: str = Field(
        description=(
            "Agent or script identity that produced the annotation "
            "(e.g. ``'agent-orchestrator/slot-3'``, ``'generate_capability_manifest.py'``)."
        )
    )
    annotated_at: datetime = Field(
        description=(
            "UTC datetime when the annotation was written. "
            "Must be timezone-aware (``timezone.utc``). "
            "Credits are spent once — the manifest caches the answer."
        )
    )
    answer: str = Field(description="Free-text answer or reasoning produced by the agent.")
    resolved_status: CapabilityEdgeStatus = Field(
        description=(
            "The edge status the agent concluded after scanning. The manifest exporter uses this to update the edge."
        )
    )


class CapabilityEdge(BaseModel):
    """A directed, typed edge in the capability graph."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    from_node_id: str = Field(
        description=("``node_id`` of the source node. Must match an entry in ``CapabilityManifest.nodes``.")
    )
    to_node_id: str = Field(
        description=("``node_id`` of the target node. Must match an entry in ``CapabilityManifest.nodes``.")
    )
    relation: str = Field(
        description=(
            "Named relation describing the edge semantics. Free-text but "
            "should be drawn from a controlled vocabulary "
            "(e.g. ``'supports'``, ``'requires'``, ``'uses_algo'``, "
            "``'min_data_to_run'``, ``'emits_instruction'``). "
            "The wizard renders this as the edge label."
        )
    )
    status: CapabilityEdgeStatus = Field(
        description=(
            "Availability status of this capability edge. "
            "``not_registered`` is the honest baseline when a registry gap "
            "means the exporter cannot yet populate the edge."
        )
    )
    gap_type: CapabilityGapType | None = Field(
        default=None,
        description=(
            "Typed gap reason. Must be set when ``status`` is "
            "``not_registered`` or when the edge is known-broken. "
            "Cleared once an ``agent_annotation`` resolves the gap."
        ),
    )
    reason: str | None = Field(
        default=None,
        description=(
            "Human-readable explanation of the status, especially for "
            "``not_available`` (logical dead-end) and ``partial`` (caveats). "
            "The wizard renders this as the greyed-option tooltip."
        ),
    )
    readiness: str | None = Field(
        default=None,
        description=(
            "Operational maturity label: "
            "``'backtest-only'`` | ``'shadow-observed'`` | "
            "``'staging-proven'`` | ``'live-proven'``. "
            "Derived from the deployments registry + archived plans."
        ),
    )
    agent_annotation: AgentAnnotation | None = Field(
        default=None,
        description=(
            "Agent-orchestrator answer for a ``needs_code_scan`` gap. "
            "Written back by the agent once the scan completes. "
            "Credits are spent once — consumers read from here, never re-scan."
        ),
    )


# ---------------------------------------------------------------------------
# Manifest summary + top-level model
# ---------------------------------------------------------------------------


class GapSummary(BaseModel):
    """Aggregate counts of gap edges by type, for quick triage."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    missing_registry: int = Field(
        default=0,
        description="Count of edges with ``gap_type=missing_registry``.",
    )
    missing_extraction: int = Field(
        default=0,
        description="Count of edges with ``gap_type=missing_extraction``.",
    )
    needs_code_scan: int = Field(
        default=0,
        description="Count of edges with ``gap_type=needs_code_scan``.",
    )
    logical_dead_end: int = Field(
        default=0,
        description="Count of edges with ``gap_type=logical_dead_end``.",
    )
    not_registered_total: int = Field(
        default=0,
        description="Total edges with ``status=not_registered``.",
    )


class ParamSchemaSpec(BaseModel):
    """One config parameter of an archetype engine — the flat schema the wizard
    renders a numeric/enum form field from.

    The exporter sources these from the strategy-service engine SSOT
    (``strategy_service.engine.strategies.v2.param_schema.PARAM_SCHEMA_REGISTRY``,
    probed in the service's own venv). Defaults are the ENGINE defaults (never
    the e2e-smoke constants). One row per param; required params with no literal
    default carry ``default=None``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(description="Param key as read from the flat engine params dict (e.g. ``entry_bps``).")
    type: str = Field(description="One of ``int`` | ``float`` | ``decimal`` | ``str`` | ``enum`` | ``bool``.")
    default: str | None = Field(
        default=None,
        description="Engine default (stringified). ``None`` for a required param with no literal default.",
    )
    required: bool = Field(
        default=False,
        description="True iff the engine raises / no-ops (returns ``[]``) when the param is absent.",
    )
    units: str | None = Field(default=None, description="Unit label (``bps``/``fraction``/``ms``/``vega``/…).")
    enum_values: list[str] = Field(default_factory=list, description="Allowed values when ``type == 'enum'``.")
    min: str | None = Field(default=None, description="Inclusive lower bound (stringified), when known.")
    max: str | None = Field(default=None, description="Inclusive upper bound (stringified), when known.")
    source: str | None = Field(default=None, description="Engine ``file:line`` provenance for the default.")


class CapabilityManifest(BaseModel):
    """Root capability manifest — the machine-generated SSOT of what the
    system can do, expressed as a typed graph of nodes and edges.

    The wizard UI drives its dropdowns and availability answers entirely from
    this manifest. No silent omissions: every dimension either has a populated
    edge or a typed gap (never dropped).

    Serialised deterministically by ``to_canonical_dict()`` (nodes and edges
    sorted by stable keys) for JSON commit-tracking and drift detection.
    """

    model_config = ConfigDict(frozen=False, extra="forbid")

    manifest_version: str = Field(
        description=(
            "Monotonically increasing version string (e.g. ``'1.0.0'``). "
            "Bumped by the generator on any schema-breaking change."
        )
    )
    generated_from_commit: str | None = Field(
        default=None,
        description=(
            "Git SHA of the UAC + PM commits used to generate this manifest. "
            "Set by the generator; absent in hand-constructed test fixtures."
        ),
    )
    nodes: list[CapabilityNode] = Field(
        default_factory=list,
        description="All nodes in the capability graph.",
    )
    edges: list[CapabilityEdge] = Field(
        default_factory=list,
        description="All directed edges in the capability graph.",
    )
    gaps: GapSummary = Field(
        default_factory=GapSummary,
        description="Aggregate gap counts, recomputed on serialisation.",
    )
    param_schema: dict[str, list[ParamSchemaSpec]] = Field(
        default_factory=dict,
        description=(
            "Per-archetype flat config PARAM SCHEMA, keyed by archetype node_id "
            "(``StrategyArchetype`` value, e.g. ``CARRY_STAKED_BASIS``). The wizard "
            "renders each archetype's numeric/enum param form from this block. "
            "Sourced from the strategy-service engine SSOT (engine defaults — F4). "
            "Empty when the strategy-service probe is unavailable (the manifest still "
            "generates honestly without it)."
        ),
    )

    def to_canonical_dict(self) -> dict[str, object]:
        """Deterministic serialisation for JSON drift detection.

        Nodes are sorted by ``(kind, node_id)``.
        Edges are sorted by ``(from_node_id, to_node_id, relation)``.
        Gap summary is recomputed from the current edge list.

        Returns a plain ``dict`` whose JSON representation is stable across
        Python runs (no set iteration order dependencies).
        """
        sorted_nodes = sorted(
            (n.model_dump() for n in self.nodes),
            key=lambda d: (d["kind"], d["node_id"]),
        )
        sorted_edges = sorted(
            (e.model_dump() for e in self.edges),
            key=lambda d: (d["from_node_id"], d["to_node_id"], d["relation"]),
        )
        # Recompute gap summary from current edges.
        gap_counts: dict[str, int] = {
            "missing_registry": 0,
            "missing_extraction": 0,
            "needs_code_scan": 0,
            "logical_dead_end": 0,
            "not_registered_total": 0,
        }
        for edge in self.edges:
            if edge.status == CapabilityEdgeStatus.NOT_REGISTERED:
                gap_counts["not_registered_total"] += 1
            if edge.gap_type is not None:
                key = str(edge.gap_type)
                if key in gap_counts:
                    gap_counts[key] += 1
        # Per-archetype param schema — sorted by archetype id; each param list keeps
        # the engine's declaration order (stable across runs).
        sorted_param_schema = {
            archetype: [spec.model_dump() for spec in self.param_schema[archetype]]
            for archetype in sorted(self.param_schema)
        }
        return {
            "manifest_version": self.manifest_version,
            "generated_from_commit": self.generated_from_commit,
            "nodes": sorted_nodes,
            "edges": sorted_edges,
            "gaps": gap_counts,
            "param_schema": sorted_param_schema,
        }


# ---------------------------------------------------------------------------
# Decimal sentinel — not used directly here but referenced in docstrings
# ---------------------------------------------------------------------------
_DECIMAL_EXAMPLE: Decimal = Decimal("0")
"""Sentinel to confirm Decimal is imported (used by gap registries below)."""


__all__ = [
    "AgentAnnotation",
    "CapabilityEdge",
    "CapabilityEdgeStatus",
    "CapabilityGapType",
    "CapabilityManifest",
    "CapabilityNode",
    "CapabilityNodeKind",
    "GapSummary",
    "ParamSchemaSpec",
]
