"""Strategy Architecture v2 — StrEnums (family, archetype, axes, routing).

Split from architecture_v2.py to keep each file under the 900-line QG limit.
"""

from __future__ import annotations

from enum import StrEnum


class StrategyFamilyV2(StrEnum):
    """8 orthogonal families — a strategy belongs to exactly one."""

    ML_DIRECTIONAL = "ML_DIRECTIONAL"
    RULES_DIRECTIONAL = "RULES_DIRECTIONAL"
    CARRY_AND_YIELD = "CARRY_AND_YIELD"
    ARBITRAGE_STRUCTURAL = "ARBITRAGE_STRUCTURAL"
    MARKET_MAKING = "MARKET_MAKING"
    EVENT_DRIVEN = "EVENT_DRIVEN"
    VOL_TRADING = "VOL_TRADING"
    STAT_ARB_PAIRS = "STAT_ARB_PAIRS"


class StrategyArchetypeV2(StrEnum):
    """18 archetypes. No category prefixes (no CEFI_/DEFI_/SPORTS_/TRADFI_)."""

    ML_DIRECTIONAL_CONTINUOUS = "ML_DIRECTIONAL_CONTINUOUS"
    ML_DIRECTIONAL_EVENT_SETTLED = "ML_DIRECTIONAL_EVENT_SETTLED"
    RULES_DIRECTIONAL_CONTINUOUS = "RULES_DIRECTIONAL_CONTINUOUS"
    RULES_DIRECTIONAL_EVENT_SETTLED = "RULES_DIRECTIONAL_EVENT_SETTLED"
    CARRY_BASIS_DATED = "CARRY_BASIS_DATED"
    CARRY_BASIS_PERP = "CARRY_BASIS_PERP"
    CARRY_STAKED_BASIS = "CARRY_STAKED_BASIS"
    CARRY_RECURSIVE_STAKED = "CARRY_RECURSIVE_STAKED"
    YIELD_ROTATION_LENDING = "YIELD_ROTATION_LENDING"
    YIELD_STAKING_SIMPLE = "YIELD_STAKING_SIMPLE"
    ARBITRAGE_PRICE_DISPERSION = "ARBITRAGE_PRICE_DISPERSION"
    LIQUIDATION_CAPTURE = "LIQUIDATION_CAPTURE"
    MARKET_MAKING_CONTINUOUS = "MARKET_MAKING_CONTINUOUS"
    MARKET_MAKING_EVENT_SETTLED = "MARKET_MAKING_EVENT_SETTLED"
    EVENT_DRIVEN = "EVENT_DRIVEN"
    VOL_TRADING_OPTIONS = "VOL_TRADING_OPTIONS"
    STAT_ARB_PAIRS_FIXED = "STAT_ARB_PAIRS_FIXED"
    STAT_ARB_CROSS_SECTIONAL = "STAT_ARB_CROSS_SECTIONAL"


ARCHETYPE_TO_FAMILY: dict[StrategyArchetypeV2, StrategyFamilyV2] = {
    StrategyArchetypeV2.ML_DIRECTIONAL_CONTINUOUS: StrategyFamilyV2.ML_DIRECTIONAL,
    StrategyArchetypeV2.ML_DIRECTIONAL_EVENT_SETTLED: StrategyFamilyV2.ML_DIRECTIONAL,
    StrategyArchetypeV2.RULES_DIRECTIONAL_CONTINUOUS: StrategyFamilyV2.RULES_DIRECTIONAL,
    StrategyArchetypeV2.RULES_DIRECTIONAL_EVENT_SETTLED: StrategyFamilyV2.RULES_DIRECTIONAL,
    StrategyArchetypeV2.CARRY_BASIS_DATED: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.CARRY_BASIS_PERP: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.CARRY_STAKED_BASIS: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.CARRY_RECURSIVE_STAKED: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.YIELD_ROTATION_LENDING: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.YIELD_STAKING_SIMPLE: StrategyFamilyV2.CARRY_AND_YIELD,
    StrategyArchetypeV2.ARBITRAGE_PRICE_DISPERSION: StrategyFamilyV2.ARBITRAGE_STRUCTURAL,
    StrategyArchetypeV2.LIQUIDATION_CAPTURE: StrategyFamilyV2.ARBITRAGE_STRUCTURAL,
    StrategyArchetypeV2.MARKET_MAKING_CONTINUOUS: StrategyFamilyV2.MARKET_MAKING,
    StrategyArchetypeV2.MARKET_MAKING_EVENT_SETTLED: StrategyFamilyV2.MARKET_MAKING,
    StrategyArchetypeV2.EVENT_DRIVEN: StrategyFamilyV2.EVENT_DRIVEN,
    StrategyArchetypeV2.VOL_TRADING_OPTIONS: StrategyFamilyV2.VOL_TRADING,
    StrategyArchetypeV2.STAT_ARB_PAIRS_FIXED: StrategyFamilyV2.STAT_ARB_PAIRS,
    StrategyArchetypeV2.STAT_ARB_CROSS_SECTIONAL: StrategyFamilyV2.STAT_ARB_PAIRS,
}


class AllocatorArchetype(StrEnum):
    FIXED = "FIXED"
    PNL_WEIGHTED = "PNL_WEIGHTED"
    SHARPE_WEIGHTED = "SHARPE_WEIGHTED"
    RISK_PARITY = "RISK_PARITY"
    KELLY = "KELLY"
    MIN_CVAR = "MIN_CVAR"
    REGIME_AWARE = "REGIME_AWARE"
    MANUAL = "MANUAL"


class HoldPolicy(StrEnum):
    SAME_CANDLE_EXIT = "SAME_CANDLE_EXIT"
    HOLD_UNTIL_FLIP = "HOLD_UNTIL_FLIP"
    CONTINUOUS = "CONTINUOUS"
    ONE_SHOT = "ONE_SHOT"
    EXPIRY_DRIVEN = "EXPIRY_DRIVEN"
    CONVERGENCE_DRIVEN = "CONVERGENCE_DRIVEN"
    REBALANCE_DRIVEN = "REBALANCE_DRIVEN"


class ShareClass(StrEnum):
    USDT = "USDT"
    USDC = "USDC"
    FDUSD = "FDUSD"
    USD = "USD"
    GBP = "GBP"
    EUR = "EUR"
    ETH = "ETH"
    BTC = "BTC"
    SOL = "SOL"


class VenueRoutingMode(StrEnum):
    SOR_AT_EXECUTION = "SOR_AT_EXECUTION"
    STRATEGY_PICKED = "STRATEGY_PICKED"
    META_BROKER = "META_BROKER"


class StakingMethod(StrEnum):
    FRACTIONAL_KELLY = "FRACTIONAL_KELLY"
    FULL_KELLY = "FULL_KELLY"
    CONFIDENCE_SCALED = "CONFIDENCE_SCALED"
    FIXED_PCT = "FIXED_PCT"
    FIXED_NOTIONAL = "FIXED_NOTIONAL"
    VOL_SCALED = "VOL_SCALED"
    DELTA_NEUTRAL_PAIRED = "DELTA_NEUTRAL_PAIRED"
    INVENTORY_SKEWED = "INVENTORY_SKEWED"
    VEGA_NOTIONAL = "VEGA_NOTIONAL"
    GAMMA_NOTIONAL = "GAMMA_NOTIONAL"
    TIER_BASED = "TIER_BASED"
    RANK_WEIGHTED = "RANK_WEIGHTED"
    EQUAL_WEIGHT = "EQUAL_WEIGHT"


class EdgeMethod(StrEnum):
    VALUE_PROB_VS_IMPLIED = "VALUE_PROB_VS_IMPLIED"
    THRESHOLD_CROSSED = "THRESHOLD_CROSSED"
    RATE_DIFFERENTIAL_SUSTAINED = "RATE_DIFFERENTIAL_SUSTAINED"
    SPREAD_CAPTURE = "SPREAD_CAPTURE"
    ARBITRAGE_DISPERSION_GT_COST = "ARBITRAGE_DISPERSION_GT_COST"
    STRUCTURAL_BONUS = "STRUCTURAL_BONUS"
    Z_SCORE_MEAN_REVERSION = "Z_SCORE_MEAN_REVERSION"
    MOMENTUM_TREND = "MOMENTUM_TREND"
    VOL_METRIC_DISLOCATION = "VOL_METRIC_DISLOCATION"
    SURPRISE_DIRECTION = "SURPRISE_DIRECTION"


class Urgency(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    IMMEDIATE = "IMMEDIATE"


class InstructionActionV2(StrEnum):
    TRADE = "TRADE"
    SWAP = "SWAP"
    LEND = "LEND"
    BORROW = "BORROW"
    STAKE = "STAKE"
    UNSTAKE = "UNSTAKE"
    QUOTE = "QUOTE"
    TRANSFER = "TRANSFER"
    BRIDGE = "BRIDGE"
    ATOMIC = "ATOMIC"
    CANCEL = "CANCEL"


class AccountActionV2(StrEnum):
    CLOSE_ALL = "CLOSE_ALL"
    CLOSE_ALL_FOR_STRATEGY = "CLOSE_ALL_FOR_STRATEGY"
    SET_MARGIN_MODE = "SET_MARGIN_MODE"
    SET_LEVERAGE = "SET_LEVERAGE"
    EMERGENCY_LIQUIDATE = "EMERGENCY_LIQUIDATE"
    TRANSFER_SUBACCOUNT = "TRANSFER_SUBACCOUNT"
    WITHDRAW = "WITHDRAW"
    DEPOSIT_ACK = "DEPOSIT_ACK"
    ROTATE_CREDENTIAL = "ROTATE_CREDENTIAL"
    PAUSE = "PAUSE"
    RESUME = "RESUME"


class AtomicExecutionMode(StrEnum):
    ATOMIC = "ATOMIC"
    LEADER_HEDGE = "LEADER_HEDGE"
    SEQUENCED_WITH_PACING = "SEQUENCED_WITH_PACING"
    ATOMIC_ON_CHAIN = "ATOMIC_ON_CHAIN"


class CompensationPolicy(StrEnum):
    CLOSE_LEADER_IF_HEDGE_FAILS = "CLOSE_LEADER_IF_HEDGE_FAILS"
    HOLD_LEG_AND_ALERT = "HOLD_LEG_AND_ALERT"
    RETRY_HEDGE_UNTIL_DEADLINE = "RETRY_HEDGE_UNTIL_DEADLINE"


class MevSubmissionMode(StrEnum):
    PUBLIC_MEMPOOL = "PUBLIC_MEMPOOL"
    FLASHBOTS_PROTECT = "FLASHBOTS_PROTECT"
    MEV_BLOCKER = "MEV_BLOCKER"
    MANIFOLD = "MANIFOLD"
    CUSTOM_PRIVATE_RPC = "CUSTOM_PRIVATE_RPC"


class VenueType(StrEnum):
    SINGLE_VENUE = "SINGLE_VENUE"
    META_BROKER = "META_BROKER"
    DATA_AGGREGATOR = "DATA_AGGREGATOR"


class VenueCategoryV2(StrEnum):
    """Derived category label. Uppercase values to match slot-label grammar."""

    CEFI = "CEFI"
    DEFI = "DEFI"
    SPORTS = "SPORTS"
    TRADFI = "TRADFI"
    PREDICTION = "PREDICTION"


class MarginMode(StrEnum):
    ISOLATED = "ISOLATED"
    CROSS = "CROSS"
    PORTFOLIO = "PORTFOLIO"
    REG_T = "REG_T"
    SPAN = "SPAN"


class CommissionStructureType(StrEnum):
    FLAT = "FLAT"
    TIERED = "TIERED"
    PERCENT = "PERCENT"
    COMMISSION_ON_WIN = "COMMISSION_ON_WIN"
    MAKER_TAKER = "MAKER_TAKER"


class KillSwitchReason(StrEnum):
    DISABLED = "DISABLED"
    DAILY_LOSS_BREACH = "DAILY_LOSS_BREACH"
    MAX_DRAWDOWN_BREACH = "MAX_DRAWDOWN_BREACH"
    DATA_STALE = "DATA_STALE"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    COINTEGRATION_BREAKDOWN = "COINTEGRATION_BREAKDOWN"
    GREEK_LIMIT_BREACH = "GREEK_LIMIT_BREACH"
    VENUE_UNAVAILABLE = "VENUE_UNAVAILABLE"


class VenueFeature(StrEnum):
    CROSS_MARGIN = "CROSS_MARGIN"
    PORTFOLIO_MARGIN = "PORTFOLIO_MARGIN"
    SUBACCOUNT = "SUBACCOUNT"
    ATOMIC_MULTI_LEG = "ATOMIC_MULTI_LEG"
    FLASH_LOAN = "FLASH_LOAN"
    NATIVE_STAKING = "NATIVE_STAKING"
    LP_PROVISION = "LP_PROVISION"
    OPTIONS_TRADING = "OPTIONS_TRADING"
    PERPS_TRADING = "PERPS_TRADING"
    SPOT_TRADING = "SPOT_TRADING"
    DARK_POOL = "DARK_POOL"
    BACK_LAY_EXCHANGE = "BACK_LAY_EXCHANGE"


class FillSource(StrEnum):
    VENUE = "VENUE"
    BENCHMARK = "BENCHMARK"
    MATCHING_ENGINE = "MATCHING_ENGINE"


class BenchmarkFillMode(StrEnum):
    ARRIVAL_MID = "ARRIVAL_MID"
    TWAP_WINDOW = "TWAP_WINDOW"
    VWAP_WINDOW = "VWAP_WINDOW"
    PASSIVE_BBO = "PASSIVE_BBO"
    POOL_MID_AT_BLOCK = "POOL_MID_AT_BLOCK"
    LIQUIDATION_BONUS = "LIQUIDATION_BONUS"
    FUNDING_SNAPSHOT = "FUNDING_SNAPSHOT"


class BacktestGroup(StrEnum):
    A_ML_TRAINING = "A_ML_TRAINING"
    B_STRATEGY = "B_STRATEGY"
    C_EXECUTION_ALPHA = "C_EXECUTION_ALPHA"


class RiskGateLayer(StrEnum):
    STRATEGY_SELF_CHECK = "STRATEGY_SELF_CHECK"
    RISK_PREFLIGHT = "RISK_PREFLIGHT"
    EXECUTION_PRETRADE = "EXECUTION_PRETRADE"
    VENUE_SIDE = "VENUE_SIDE"


class RiskGateDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RESIZED = "RESIZED"
    DEFERRED = "DEFERRED"


class TransferType(StrEnum):
    INTERNAL_SUBACCOUNT = "INTERNAL_SUBACCOUNT"
    CEX_WITHDRAWAL_DEPOSIT = "CEX_WITHDRAWAL_DEPOSIT"
    ON_CHAIN_TRANSFER = "ON_CHAIN_TRANSFER"
    BRIDGE = "BRIDGE"
    WRAP_UNWRAP = "WRAP_UNWRAP"
    UNITY_WALLET_OP = "UNITY_WALLET_OP"
    IBKR_FUND_MOVE = "IBKR_FUND_MOVE"


__all__ = [
    "ARCHETYPE_TO_FAMILY",
    "AccountActionV2",
    "AllocatorArchetype",
    "AtomicExecutionMode",
    "BacktestGroup",
    "BenchmarkFillMode",
    "CommissionStructureType",
    "CompensationPolicy",
    "EdgeMethod",
    "FillSource",
    "HoldPolicy",
    "InstructionActionV2",
    "KillSwitchReason",
    "MarginMode",
    "MevSubmissionMode",
    "RiskGateDecision",
    "RiskGateLayer",
    "ShareClass",
    "StakingMethod",
    "StrategyArchetypeV2",
    "StrategyFamilyV2",
    "TransferType",
    "Urgency",
    "VenueCategoryV2",
    "VenueFeature",
    "VenueRoutingMode",
    "VenueType",
]
