"""Fund + business_unit + reserving_business_unit_id registry — G2.8.

Stage 3E § 2.8. Stage-3a § 3.2 flagged the missing typed registry mapping
each IM Pooled fund / Reg Umbrella fund / SMA / admin + IM-desk to its
canonical ``business_unit`` + ``reserving_business_unit_id`` + custody
model. Today allocator call-sites and reporting surfaces use free-form
strings; ``StrategyAvailabilityEntry.reserving_business_unit_id`` is a
free ``str | None`` with no registry validation.

This module ships the typed registry. Consumers:

* ``strategy-service/portfolio_allocator/service.py`` — look up the
  reserving business unit for a fund instead of concatenating strings.
* Reporting surfaces (per-fund breakdowns, commercial-path slicing).
* UI mirror at ``unified-trading-system-ui/lib/admin/fund-business-unit.ts``
  (generated by ``sync-fund-business-unit-to-ui.sh``, G1.8 pattern).

Custody model is load-bearing for the IM commercial split:

* **IM Pooled** funds are custodied by Copper (third-party custodian);
  Odum never touches the coins / cash. Subs / redemptions flow via the
  Odum portal but settle via Copper.
* **IM SMA** + **DART** clients retain custody on the venue in the
  client's own account; Odum holds execute+read scoped API keys.
* **Reg Umbrella** also uses client-owned-venue custody (the client
  operates their own stack under Odum's FCA permissions).

The POD affiliate referenced in the custody memo is **internal-only**;
registry rows for IM Pooled carry ``custody_model=COPPER_CUSTODIAN``
and must not surface POD anywhere in public UI strings.

SSOT:

* Plan: ``plans/active/refactor_g2_8_fund_business_unit_registry_2026_04_20.md``
* Custody memo:
  ``memory/project_custody_model_per_path_2026_04_20.md``
* Codex:
  ``codex/14-playbooks/shared-core/fund-administration-and-custody.md``
  ``codex/14-playbooks/cross-cutting/sma-vs-pooled.md``
"""

from __future__ import annotations

from collections.abc import Iterable
from enum import StrEnum
from typing import Final, Literal

from pydantic import BaseModel, ConfigDict


class CustodyModel(StrEnum):
    """Who holds the underlying assets."""

    CLIENT_OWNED_VENUE = "CLIENT_OWNED_VENUE"
    """Client retains custody on the venue in their own account.
    Odum holds scoped API keys (execute + read) — not read-only.
    Applies to IM SMA, DART, and Reg Umbrella paths."""

    COPPER_CUSTODIAN = "COPPER_CUSTODIAN"
    """Third-party custodian (Copper). Applies to IM Pooled funds.
    Subs / redemptions via the Odum portal; settlement via Copper.
    Odum never custodies directly. POD affiliate is the internal
    operating entity but MUST NOT surface in public UI strings."""

    NOT_APPLICABLE = "NOT_APPLICABLE"
    """Admin + IM-desk rows — no client-facing custody relationship.
    The BU exists purely for internal capacity reservation semantics."""


BusinessUnit = Literal["saas", "im_desk", "admin"]
"""Matches ``StrategyAvailabilityEntry.business_unit`` literal.

Kept deliberately narrow; fund-level granularity lives in
``reserving_business_unit_id`` (e.g. ``im_desk_pooled_alpha``,
``im_desk_sma_acme``, ``im_desk_reg_umbrella``)."""


ServiceFamilyTag = Literal["IM", "DART", "RegUmbrella"]
"""Prospect-facing service family the fund belongs to. Narrower than
rule 12's internal ``ServiceFamily`` — a fund never maps to the
internal-only values (``admin``, ``IM_desk``, ``DART_reporting_only``)
because a fund is a commercial product, not an internal role."""


class FundBusinessUnitEntry(BaseModel):
    """One record per (fund_id, business_unit) pair.

    ``fund_id`` is the stable external identifier (e.g. ``imp_alpha``,
    ``sma_acme_llc``, ``reg_umbrella_odum_fca``). ``fund_name`` is the
    human-readable marketing name (e.g. "Odum IM Alpha Pooled Fund").
    ``reserving_business_unit_id`` is the internal capacity-budget key
    used by the allocator; conventionally ``{bu}_{fund_short_id}``.

    ``notes`` is a free-form string for registry-authors; not surfaced
    in prospect-facing UI. Must not contain POD affiliate references
    in any row carrying ``custody_model=COPPER_CUSTODIAN``.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    fund_id: str
    fund_name: str
    business_unit: BusinessUnit
    reserving_business_unit_id: str
    custody_model: CustodyModel
    service_family: ServiceFamilyTag | None = None
    notes: str = ""


FUND_BUSINESS_UNIT_REGISTRY: Final[tuple[FundBusinessUnitEntry, ...]] = (
    # ── IM Pooled — Copper-custodied ──────────────────────────────────
    FundBusinessUnitEntry(
        fund_id="imp_alpha",
        fund_name="Odum IM Alpha Pooled Fund",
        business_unit="im_desk",
        reserving_business_unit_id="im_desk_pooled_alpha",
        custody_model=CustodyModel.COPPER_CUSTODIAN,
        service_family="IM",
        notes="Seed IM Pooled fund for 2026. Copper custody per fund-administration-and-custody.md.",
    ),
    # ── IM SMA fixtures — client-owned venue, scoped keys ──────────────
    FundBusinessUnitEntry(
        fund_id="sma_acme_llc",
        fund_name="Acme LLC SMA",
        business_unit="im_desk",
        reserving_business_unit_id="im_desk_sma_acme",
        custody_model=CustodyModel.CLIENT_OWNED_VENUE,
        service_family="IM",
        notes="Reference SMA fixture (Phase 10 catalogue). Odum holds execute+read keys; client custodies on-venue.",
    ),
    FundBusinessUnitEntry(
        fund_id="sma_bridgestone_capital",
        fund_name="Bridgestone Capital SMA",
        business_unit="im_desk",
        reserving_business_unit_id="im_desk_sma_bridgestone",
        custody_model=CustodyModel.CLIENT_OWNED_VENUE,
        service_family="IM",
        notes="Second SMA fixture demonstrating multi-SMA allocator isolation.",
    ),
    # ── Reg Umbrella — client-owned venue under Odum FCA wrapper ──────
    FundBusinessUnitEntry(
        fund_id="reg_umbrella_odum_fca",
        fund_name="Odum Regulatory Umbrella (FCA)",
        business_unit="im_desk",
        reserving_business_unit_id="im_desk_reg_umbrella",
        custody_model=CustodyModel.CLIENT_OWNED_VENUE,
        service_family="RegUmbrella",
        notes="Reg Umbrella funds route client trades under Odum's FCA permissions; client retains venue custody.",
    ),
    # ── DART — SaaS signal-plus-execution for prospect-operated desks ─
    FundBusinessUnitEntry(
        fund_id="dart_saas_default",
        fund_name="DART Default SaaS Pool",
        business_unit="saas",
        reserving_business_unit_id="saas_dart_default",
        custody_model=CustodyModel.CLIENT_OWNED_VENUE,
        service_family="DART",
        notes="Catch-all reserving BU for DART SaaS subscribers without a bespoke fund mapping.",
    ),
    # ── Admin + IM-desk internal rows (not client-facing funds) ────────
    FundBusinessUnitEntry(
        fund_id="admin",
        fund_name="Odum Admin (internal)",
        business_unit="admin",
        reserving_business_unit_id="admin",
        custody_model=CustodyModel.NOT_APPLICABLE,
        service_family=None,
        notes="Admin role row — capacity reservation for internal bring-up / chaos tests. Not a fund.",
    ),
    FundBusinessUnitEntry(
        fund_id="im_desk_trading",
        fund_name="IM-Desk Trading (internal)",
        business_unit="im_desk",
        reserving_business_unit_id="im_desk_internal",
        custody_model=CustodyModel.NOT_APPLICABLE,
        service_family=None,
        notes="Internal IM-desk capacity row. Not a fund; used for prop / seed capital reservations.",
    ),
)


class FundNotFoundError(LookupError):
    """Raised when ``fund_for(fund_id)`` can't resolve the fund."""


def fund_for(
    fund_id: str,
    *,
    registry: Iterable[FundBusinessUnitEntry] = FUND_BUSINESS_UNIT_REGISTRY,
) -> FundBusinessUnitEntry:
    """Look up a fund record by ID. Raises ``FundNotFoundError`` on miss.

    Fail-loud: no ``str | None`` return. Consumers that want optional
    behaviour wrap the call in ``try / except FundNotFoundError``.
    """

    for entry in registry:
        if entry.fund_id == fund_id:
            return entry
    raise FundNotFoundError(
        f"fund_id={fund_id!r} not found in FUND_BUSINESS_UNIT_REGISTRY",
    )


def funds_for_business_unit(
    business_unit: BusinessUnit,
    *,
    registry: Iterable[FundBusinessUnitEntry] = FUND_BUSINESS_UNIT_REGISTRY,
) -> tuple[FundBusinessUnitEntry, ...]:
    """All fund records bound to a given business_unit literal."""

    return tuple(entry for entry in registry if entry.business_unit == business_unit)


def reserving_business_unit_for(
    fund_id: str,
    *,
    registry: Iterable[FundBusinessUnitEntry] = FUND_BUSINESS_UNIT_REGISTRY,
) -> str:
    """Resolve a fund's canonical ``reserving_business_unit_id``.

    Shortcut for ``fund_for(fund_id).reserving_business_unit_id``.
    Allocator call-sites use this to stop concatenating strings.
    """

    return fund_for(fund_id, registry=registry).reserving_business_unit_id


def _validate_registry_invariants(
    registry: Iterable[FundBusinessUnitEntry] = FUND_BUSINESS_UNIT_REGISTRY,
) -> None:
    """Invariants enforced at import time (via the ``__init__`` call below).

    * ``fund_id`` must be unique across the registry.
    * ``reserving_business_unit_id`` must be unique (the allocator keys
      capacity budgets on it — collisions would silently merge
      reservations).
    * A row with ``custody_model=COPPER_CUSTODIAN`` must NOT mention
      the POD affiliate in ``notes`` (public-copy invariant).
    """

    seen_fund_ids: set[str] = set()
    seen_reserving_ids: set[str] = set()
    for entry in registry:
        if entry.fund_id in seen_fund_ids:
            raise ValueError(
                f"duplicate fund_id in registry: {entry.fund_id!r}",
            )
        if entry.reserving_business_unit_id in seen_reserving_ids:
            raise ValueError(
                f"duplicate reserving_business_unit_id: {entry.reserving_business_unit_id!r}",
            )
        seen_fund_ids.add(entry.fund_id)
        seen_reserving_ids.add(entry.reserving_business_unit_id)
        if entry.custody_model is CustodyModel.COPPER_CUSTODIAN and "pod" in entry.notes.lower():
            raise ValueError(
                f"COPPER_CUSTODIAN rows must not surface POD affiliate in notes: {entry.fund_id!r}",
            )


_validate_registry_invariants()


__all__ = [
    "FUND_BUSINESS_UNIT_REGISTRY",
    "BusinessUnit",
    "CustodyModel",
    "FundBusinessUnitEntry",
    "FundNotFoundError",
    "ServiceFamilyTag",
    "fund_for",
    "funds_for_business_unit",
    "reserving_business_unit_for",
]
