"""Venue error classifications for alternative data providers and DeFi infrastructure."""

from __future__ import annotations

from unified_api_contracts.schemas._errors_types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_ALTDATA: dict[str, list[VenueErrorClassification]] = {
    "hyperliquid": [
        ve(
            "hyperliquid",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "hyperliquid",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unavailable",
        ),
        ve(
            "hyperliquid",
            "RATE_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        ve(
            "hyperliquid",
            "INSUFFICIENT_MARGIN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Margin",
        ),
    ],
    "aster": [
        ve(
            "aster",
            "-1003",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        ve(
            "aster",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "aster",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
    "bloxroute": [
        ve(
            "bloxroute",
            "-32600",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid request",
        ),
        ve(
            "bloxroute",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        ve(
            "bloxroute",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
    "versifi": [
        ve(
            "versifi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "versifi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "versifi",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order not found",
        ),
        ve(
            "versifi",
            "409",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Conflict/duplicate order",
        ),
        ve(
            "versifi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- CeFi: missing registry venues ---
    "coinglass": [
        ve(
            "coinglass",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "coinglass",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "coinglass",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "coinglass",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "hyblock": [
        ve(
            "hyblock",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "hyblock",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "hyblock",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "hyblock",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- TradFi: missing registry venues ---
    "barchart": [
        ve(
            "barchart",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "barchart",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "barchart",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid symbol or parameter",
        ),
        ve(
            "barchart",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "barchart",
            "NO_DATA_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for symbol",
        ),
    ],
    "fred": [
        ve(
            "fred",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "fred",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid series ID or parameter",
        ),
        ve(
            "fred",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "fred",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "ecb": [
        ve(
            "ecb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ecb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid key or flow",
        ),
        ve(
            "ecb",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for series",
        ),
        ve(
            "ecb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "ecb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
    ],
    "ofr": [
        ve(
            "ofr",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ofr",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "ofr",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Dataset or series not found",
        ),
        ve(
            "ofr",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "openbb": [
        ve(
            "openbb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "openbb",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid token",
        ),
        ve(
            "openbb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "openbb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "openbb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
    # --- DeFi: all 14 registry venues ---
    "aave_v3": [
        ve(
            "aave_v3",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Health factor below 1 — liquidation risk",
        ),
        ve(
            "aave_v3",
            "BORROW_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow cap for asset reached",
        ),
        ve(
            "aave_v3",
            "SUPPLY_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Supply cap for asset reached",
        ),
        ve(
            "aave_v3",
            "PRICE_ORACLE_SENTINEL",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Oracle price feed stale — retry",
        ),
        ve(
            "aave_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "aave_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
}
