"""Venue error classifications for DeFi protocols."""

from __future__ import annotations

from unified_api_contracts.schemas._errors_types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_DEFI: dict[str, list[VenueErrorClassification]] = {
    "balancer": [
        ve(
            "balancer",
            "BAL#001",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — caller not authorised",
        ),
        ve(
            "balancer",
            "BAL#304",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Swap limit exceeded",
        ),
        ve(
            "balancer",
            "BAL#508",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool paused",
        ),
        ve(
            "balancer",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "balancer",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "curve": [
        ve(
            "curve",
            "SLIPPAGE_TOO_HIGH",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage exceeds allowed tolerance",
        ),
        ve(
            "curve",
            "POOL_IMBALANCED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Pool reserves severely imbalanced — retry later",
        ),
        ve(
            "curve",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "curve",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "curve",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="API server error",
        ),
    ],
    "ethena": [
        ve(
            "ethena",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ethena",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "ethena",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "ethena",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "euler": [
        ve(
            "euler",
            "E_INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral insufficient for borrow",
        ),
        ve(
            "euler",
            "E_BORROW_ISOLATION_VIOLATION",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow violates isolation mode",
        ),
        ve(
            "euler",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "euler",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "fluid": [
        ve(
            "fluid",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "fluid",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "fluid",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "fluid",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "etherfi": [
        ve(
            "etherfi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "etherfi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "etherfi",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "etherfi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "lido": [
        ve(
            "lido",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "lido",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "lido",
            "WITHDRAWAL_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Withdrawal request not found",
        ),
        ve(
            "lido",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "lido",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "morpho": [
        ve(
            "morpho",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral value below required threshold",
        ),
        ve(
            "morpho",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "morpho",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "morpho",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "uniswap_v2": [
        ve(
            "uniswap_v2",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pair has insufficient liquidity",
        ),
        ve(
            "uniswap_v2",
            "INSUFFICIENT_OUTPUT_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Output amount below minimum — slippage exceeded",
        ),
        ve(
            "uniswap_v2",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v2",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v3": [
        ve(
            "uniswap_v3",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool tick range has no liquidity",
        ),
        ve(
            "uniswap_v3",
            "TOO_LITTLE_RECEIVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage tolerance exceeded",
        ),
        ve(
            "uniswap_v3",
            "PRICE_SLIPPAGE_CHECK",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="sqrtPriceLimitX96 violated",
        ),
        ve(
            "uniswap_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v4": [
        ve(
            "uniswap_v4",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook or pool has no liquidity",
        ),
        ve(
            "uniswap_v4",
            "HOOK_DELTA_EXCEEDS_SWAP_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook delta exceeds swap amount",
        ),
        ve(
            "uniswap_v4",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v4",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
}
