"""Error classification schemas for venue-specific API errors."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from pydantic import BaseModel, Field


class ErrorAction(StrEnum):
    RETRY = "retry"
    RECONNECT = "reconnect"
    SKIP = "skip"
    FAIL = "fail"


@dataclass
class VenueErrorClassification:
    venue: str
    error_code: str
    retry_safe: bool
    reconnect: bool
    action: ErrorAction
    description: str | None = None


@dataclass
class DatabentoError:
    code: str
    message: str
    retry_safe: bool
    reconnect: bool


class RateLimitResponse(BaseModel):
    """HTTP 429 rate limit response schema (REST venues).

    Common headers: Retry-After (seconds or HTTP-date), X-RateLimit-Limit,
    X-RateLimit-Remaining, X-RateLimit-Reset (Unix timestamp).
    """

    retry_after: int | None = Field(None, description="Seconds to wait (Retry-After header)")
    x_rate_limit_limit: int | None = Field(None, alias="X-RateLimit-Limit")
    x_rate_limit_remaining: int | None = Field(None, alias="X-RateLimit-Remaining")
    x_rate_limit_reset: int | None = Field(None, alias="X-RateLimit-Reset")
    message: str | None = None
    code: str | int | None = None

    model_config = {"populate_by_name": True}


class WebSocketCloseInfo(BaseModel):
    """WebSocket close frame (RFC 6455): code + reason.

    Common codes: 1000=normal, 1006=abnormal, 1008=policy, 1011=server error.
    """

    code: int = Field(..., description="Close code (1000-1015)")
    reason: str | None = Field(None, description="Close reason string")
    message: str | None = None


DATABENTO_ERROR_MAP: dict[str, DatabentoError] = {
    "RATE_LIMIT": DatabentoError("RATE_LIMIT", "Rate limit exceeded", retry_safe=True, reconnect=False),
    "AUTH_FAILURE": DatabentoError("AUTH_FAILURE", "Authentication failed", retry_safe=False, reconnect=False),
    "CONNECTION_RESET": DatabentoError("CONNECTION_RESET", "Connection reset", retry_safe=True, reconnect=True),
    "SUBSCRIPTION_ERROR": DatabentoError("SUBSCRIPTION_ERROR", "Subscription failed", retry_safe=True, reconnect=False),
}


def _v(
    venue: str, code: str, *, retry: bool, reconnect: bool, action: ErrorAction, desc: str
) -> VenueErrorClassification:
    return VenueErrorClassification(venue, code, retry_safe=retry, reconnect=reconnect, action=action, description=desc)


VENUE_ERROR_MAP: dict[str, list[VenueErrorClassification]] = {
    "binance": [
        _v(
            "binance",
            "-1003",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        _v(
            "binance",
            "-1021",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Timestamp recv window",
        ),
        _v(
            "binance",
            "-1000",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unknown error",
        ),
        _v(
            "binance",
            "-1006",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Connection closed",
        ),
        _v(
            "binance",
            "-2011",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unknown order",
        ),
        _v(
            "binance",
            "-1013",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid lot size",
        ),
    ],
    "bybit": [
        _v(
            "bybit",
            "10006",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "bybit",
            "10000",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        _v(
            "bybit",
            "10001",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Parameter error",
        ),
        _v(
            "bybit",
            "10019",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="WS restarting",
        ),
        _v(
            "bybit",
            "33004",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid",
        ),
    ],
    "okx": [
        _v(
            "okx",
            "50004",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="WebSocket closed",
        ),
        _v(
            "okx",
            "50011",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "okx",
            "50026",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="System busy",
        ),
        _v(
            "okx",
            "51008",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Insufficient funds",
        ),
    ],
    "deribit": [
        _v(
            "deribit",
            "10028",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        _v(
            "deribit",
            "10040",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        _v(
            "deribit",
            "11044",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Not enough funds",
        ),
        _v(
            "deribit",
            "13009",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Invalid token",
        ),
        _v(
            "deribit",
            "13010",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Token revoked",
        ),
    ],
    "coinbase": [
        _v(
            "coinbase",
            "RATE_LIMIT_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        _v(
            "coinbase",
            "INTERNAL_SERVICE_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server",
        ),
        _v(
            "coinbase",
            "TEMPORARILY_UNAVAILABLE",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Temp",
        ),
    ],
    "tardis": [
        _v(
            "tardis",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "tardis",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "tardis",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "alchemy": [
        _v(
            "alchemy",
            "-32600",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid request",
        ),
        _v(
            "alchemy",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        _v(
            "alchemy",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
    "yahoo_finance": [
        _v(
            "yahoo_finance",
            "RATE_LIMIT_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate",
        ),
        _v(
            "yahoo_finance",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
    ],
    "upbit": [
        _v(
            "upbit",
            "invalid_access_key",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid key",
        ),
        _v(
            "upbit",
            "invalid_query_payload",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid",
        ),
        _v(
            "upbit",
            "too_many_requests",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
    ],
    "ibkr": [
        _v(
            "ibkr",
            "100",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Market data farm",
        ),
        _v(
            "ibkr",
            "1100",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Connectivity lost",
        ),
        _v(
            "ibkr",
            "1300",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order rejected",
        ),
    ],
    "thegraph": [
        _v(
            "thegraph",
            "Subgraph not found",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Not found",
        ),
        _v(
            "thegraph",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
    "ccxt": [
        _v(
            "ccxt",
            "RateLimitExceeded",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        _v(
            "ccxt",
            "ExchangeNotAvailable",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unavail",
        ),
        _v(
            "ccxt",
            "ExchangeError",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Transient",
        ),
    ],
    "databento": [
        _v(
            "databento",
            "RATE_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        _v(
            "databento",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Auth failed",
        ),
        _v(
            "databento",
            "CONNECTION_RESET",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Reset",
        ),
    ],
    "hyperliquid": [
        _v(
            "hyperliquid",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        _v(
            "hyperliquid",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unavailable",
        ),
        _v(
            "hyperliquid",
            "RATE_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        _v(
            "hyperliquid",
            "INSUFFICIENT_MARGIN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Margin",
        ),
    ],
    "aster": [
        _v(
            "aster",
            "-1003",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        _v(
            "aster",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "aster",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
    "bloxroute": [
        _v(
            "bloxroute",
            "-32600",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid request",
        ),
        _v(
            "bloxroute",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        _v(
            "bloxroute",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
    "versifi": [
        _v(
            "versifi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        _v(
            "versifi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "versifi",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order not found",
        ),
        _v(
            "versifi",
            "409",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Conflict/duplicate order",
        ),
        _v(
            "versifi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- CeFi: missing registry venues ---
    "coinglass": [
        _v(
            "coinglass",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "coinglass",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "coinglass",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        _v(
            "coinglass",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "hyblock": [
        _v(
            "hyblock",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "hyblock",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "hyblock",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        _v(
            "hyblock",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- TradFi: missing registry venues ---
    "barchart": [
        _v(
            "barchart",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "barchart",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "barchart",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid symbol or parameter",
        ),
        _v(
            "barchart",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "barchart",
            "NO_DATA_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for symbol",
        ),
    ],
    "fred": [
        _v(
            "fred",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "fred",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid series ID or parameter",
        ),
        _v(
            "fred",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "fred",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "ecb": [
        _v(
            "ecb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "ecb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid key or flow",
        ),
        _v(
            "ecb",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for series",
        ),
        _v(
            "ecb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "ecb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
    ],
    "ofr": [
        _v(
            "ofr",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "ofr",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        _v(
            "ofr",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Dataset or series not found",
        ),
        _v(
            "ofr",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "openbb": [
        _v(
            "openbb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "openbb",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid token",
        ),
        _v(
            "openbb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        _v(
            "openbb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "openbb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
    # --- DeFi: all 14 registry venues ---
    "aave_v3": [
        _v(
            "aave_v3",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Health factor below 1 — liquidation risk",
        ),
        _v(
            "aave_v3",
            "BORROW_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow cap for asset reached",
        ),
        _v(
            "aave_v3",
            "SUPPLY_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Supply cap for asset reached",
        ),
        _v(
            "aave_v3",
            "PRICE_ORACLE_SENTINEL",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Oracle price feed stale — retry",
        ),
        _v(
            "aave_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "aave_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
    ],
    "balancer": [
        _v(
            "balancer",
            "BAL#001",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — caller not authorised",
        ),
        _v(
            "balancer",
            "BAL#304",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Swap limit exceeded",
        ),
        _v(
            "balancer",
            "BAL#508",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool paused",
        ),
        _v(
            "balancer",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "balancer",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "curve": [
        _v(
            "curve",
            "SLIPPAGE_TOO_HIGH",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage exceeds allowed tolerance",
        ),
        _v(
            "curve",
            "POOL_IMBALANCED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Pool reserves severely imbalanced — retry later",
        ),
        _v(
            "curve",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "curve",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "curve",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="API server error",
        ),
    ],
    "ethena": [
        _v(
            "ethena",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "ethena",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "ethena",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "ethena",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "euler": [
        _v(
            "euler",
            "E_INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral insufficient for borrow",
        ),
        _v(
            "euler",
            "E_BORROW_ISOLATION_VIOLATION",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow violates isolation mode",
        ),
        _v(
            "euler",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "euler",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "fluid": [
        _v(
            "fluid",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "fluid",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "fluid",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "fluid",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "etherfi": [
        _v(
            "etherfi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "etherfi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "etherfi",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "etherfi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "lido": [
        _v(
            "lido",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "lido",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "lido",
            "WITHDRAWAL_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Withdrawal request not found",
        ),
        _v(
            "lido",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "lido",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "morpho": [
        _v(
            "morpho",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral value below required threshold",
        ),
        _v(
            "morpho",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "morpho",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "morpho",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "uniswap_v2": [
        _v(
            "uniswap_v2",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pair has insufficient liquidity",
        ),
        _v(
            "uniswap_v2",
            "INSUFFICIENT_OUTPUT_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Output amount below minimum — slippage exceeded",
        ),
        _v(
            "uniswap_v2",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "uniswap_v2",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v3": [
        _v(
            "uniswap_v3",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool tick range has no liquidity",
        ),
        _v(
            "uniswap_v3",
            "TOO_LITTLE_RECEIVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage tolerance exceeded",
        ),
        _v(
            "uniswap_v3",
            "PRICE_SLIPPAGE_CHECK",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="sqrtPriceLimitX96 violated",
        ),
        _v(
            "uniswap_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "uniswap_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v4": [
        _v(
            "uniswap_v4",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook or pool has no liquidity",
        ),
        _v(
            "uniswap_v4",
            "HOOK_DELTA_EXCEEDS_SWAP_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook delta exceeds swap amount",
        ),
        _v(
            "uniswap_v4",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "uniswap_v4",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "instadapp": [
        _v(
            "instadapp",
            "DS_PROXY_EXEC_FAILED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="DSProxy execution failed — revert in spell",
        ),
        _v(
            "instadapp",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "instadapp",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "instadapp",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        _v(
            "instadapp",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "defillama": [
        _v(
            "defillama",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "defillama",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Protocol or chain not found",
        ),
        _v(
            "defillama",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "defillama",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
    ],
    # --- Plan-specified additional venues ---
    "polymarket": [
        _v(
            "polymarket",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "polymarket",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key or signature",
        ),
        _v(
            "polymarket",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        _v(
            "polymarket",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "betfair": [
        _v(
            "betfair",
            "INVALID_SESSION_INFORMATION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Session token invalid or expired — reauthenticate",
        ),
        _v(
            "betfair",
            "NO_SESSION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="No active session — reauthenticate",
        ),
        _v(
            "betfair",
            "TOO_MUCH_DATA",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Response too large — reduce request scope",
        ),
        _v(
            "betfair",
            "SERVICE_BUSY",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Betfair API service busy — retry with backoff",
        ),
        _v(
            "betfair",
            "TIMEOUT_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Request timed out on Betfair side",
        ),
        _v(
            "betfair",
            "REQUEST_SIZE_EXCEEDS_LIMIT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Request payload exceeds size limit",
        ),
    ],
    "kalshi": [
        _v(
            "kalshi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "kalshi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid or expired token",
        ),
        _v(
            "kalshi",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — insufficient permissions",
        ),
        _v(
            "kalshi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        _v(
            "kalshi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "kalshi",
            "MARKET_NOT_OPEN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market is not open for trading",
        ),
        _v(
            "kalshi",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Account balance insufficient for order",
        ),
    ],
    "smarkets": [
        _v(
            "smarkets",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "smarkets",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        _v(
            "smarkets",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        _v(
            "smarkets",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "smarkets",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        _v(
            "smarkets",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
    "betdaq": [
        _v(
            "betdaq",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "betdaq",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        _v(
            "betdaq",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        _v(
            "betdaq",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        _v(
            "betdaq",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        _v(
            "betdaq",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
    ],
    "glassnode": [
        _v(
            "glassnode",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "glassnode",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "glassnode",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — metric requires higher tier",
        ),
        _v(
            "glassnode",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid metric or parameter",
        ),
        _v(
            "glassnode",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "arkham": [
        _v(
            "arkham",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "arkham",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        _v(
            "arkham",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid address or parameter",
        ),
        _v(
            "arkham",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Entity or address not found",
        ),
        _v(
            "arkham",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # --- Generic / cross-cutting error groups ---
    "onchain_revert": [
        _v(
            "onchain_revert",
            "EXECUTION_REVERTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="EVM transaction reverted — contract logic rejected the call",
        ),
        _v(
            "onchain_revert",
            "OUT_OF_GAS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction ran out of gas — increase gas limit",
        ),
        _v(
            "onchain_revert",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Sender has insufficient ETH for gas + value",
        ),
        _v(
            "onchain_revert",
            "NONCE_TOO_LOW",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Transaction nonce already used — resync nonce",
        ),
    ],
    "sports_generic": [
        _v(
            "sports_generic",
            "MARKET_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market suspended — no new orders accepted",
        ),
        _v(
            "sports_generic",
            "SELECTION_REMOVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Selection removed from market",
        ),
        _v(
            "sports_generic",
            "COMPETITION_CLOSED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Competition closed — all markets settled",
        ),
        _v(
            "sports_generic",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        _v(
            "sports_generic",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        _v(
            "sports_generic",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
}


def classify_venue_error(venue: str, error_code: str) -> VenueErrorClassification | None:
    """Classify a venue error code using normalized VENUE_ERROR_MAP.

    Returns VenueErrorClassification with retry_safe, reconnect, action, or
    None when the code is not found in the map.  Callers that receive None
    must emit UNKNOWN_VENUE_ERROR_RECEIVED and raise CanonicalUnknownVenueError
    so the ops backlog can track novel codes.
    """
    venue_key = venue.lower()
    classifications = VENUE_ERROR_MAP.get(venue_key, [])
    code_str = str(error_code)
    for c in classifications:
        if c.error_code == code_str:
            return c
    return None
