"""Parquet column schema for InstrumentRecord serialisation.

Extracted from ``__init__.py`` to keep the parent module under the
900-line file-size cap. Single source of truth for column names, types,
default values, and nullability — used by storage writers, validators,
and the parquet reader (`build_canonical_instruments_dataframe`).

Schema fields are aligned 1:1 with the ``InstrumentRecord`` pydantic
model in ``unified_api_contracts.internal.reference.instrument``.

Plan extending the schema with DeFi metadata fields (contract_address,
token_a/b_*, fee_bps, atoken_address, debt_token_address): plans/active/
``instruments_service_metadata_refactor_2026_04_29.plan``.
"""

from __future__ import annotations

INSTRUMENTS_PARQUET_SCHEMA: list[dict[str, str | bool]] = [
    {
        "name": "instrument_key",
        "type": "string",
        "required": True,
        "description": "Canonical instrument key: VENUE:INSTRUMENT_TYPE:SYMBOL",
    },
    {
        "name": "venue",
        "type": "string",
        "required": True,
        "description": "Venue identifier. Must match first part of instrument_key",
    },
    {
        "name": "instrument_type",
        "type": "string",
        "required": True,
        "description": "Instrument type. Must match second part of instrument_key",
    },
    {
        "name": "symbol",
        "type": "string",
        "required": True,
        "description": "Symbol string. Extracted from instrument_key",
    },
    {
        "name": "available_from_datetime",
        "type": "datetime64[ns]",
        "required": True,
        "description": "ISO datetime (timezone-naive UTC) when instrument became available",
    },
    {
        "name": "venue_type",
        "type": "string",
        "required": False,
        "default": "exchange",
        "description": "Type of venue: 'exchange', 'protocol', or 'wallet'",
    },
    {
        "name": "tardis_exchange",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Tardis exchange identifier",
    },
    {
        "name": "data_provider",
        "type": "string",
        "required": False,
        "default": "tardis",
        "description": "Data provider source: 'tardis' or 'databento'",
    },
    {
        "name": "asset_class",
        "type": "string",
        "required": False,
        "default": "crypto",
        "description": "Asset class: 'crypto' or 'traditional'",
    },
    {
        "name": "available_to_datetime",
        "type": "datetime64[ns]",
        "required": False,
        "nullable": True,
        "description": "ISO datetime when instrument expires. Empty/None for SPOT/PERPETUAL",
    },
    {
        "name": "base_asset",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Base asset symbol",
    },
    {
        "name": "quote_asset",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Quote asset symbol",
    },
    {
        "name": "settle_asset",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Settlement asset symbol",
    },
    {
        "name": "exchange_raw_symbol",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Raw exchange code from exchange API",
    },
    {
        "name": "databento_symbol",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Databento query symbol format",
    },
    {
        "name": "tardis_symbol",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Symbol format used by Tardis API",
    },
    {
        "name": "margin_type",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Settlement/margin type: LINEAR, INVERSE, or QUANTO",
    },
    {
        "name": "strike",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Strike price for options",
    },
    {
        "name": "option_type",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Option type: 'CALL' or 'PUT'",
    },
    {
        "name": "exercise_style",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Option exercise style: 'AMERICAN' or 'EUROPEAN'. None for non-options.",
    },
    {
        "name": "expiry",
        "type": "datetime64[ns]",
        "required": False,
        "nullable": True,
        "description": "Expiry datetime for futures/options. None for SPOT/PERPETUAL",
    },
    {
        "name": "contract_size",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Contract size/multiplier",
    },
    {
        "name": "tick_size",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Minimum price increment",
    },
    {
        "name": "underlying",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Underlying asset for derivatives",
    },
    # Canonical product identity (additive — aligned 1:1 with InstrumentRecord
    # .canonical_instrument_id / .product_root; populated by the TradFi/Databento
    # adapter from the UAC exchange-code registry). raw_symbol stays the raw code.
    {
        "name": "canonical_instrument_id",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Human-canonical instrument id (e.g. CME:OPTION:SP500:2025-10:5000C). None when unresolved.",
    },
    {
        "name": "product_root",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Human-canonical product root from the exchange-code registry (e.g. ES → SP500).",
    },
    {
        "name": "min_size",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Minimum order size",
    },
    {
        "name": "ccxt_symbol",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Symbol format for CCXT library",
    },
    {
        "name": "ccxt_exchange",
        "type": "string",
        "required": False,
        "default": "",
        "description": "Exchange identifier for CCXT library",
    },
    {
        "name": "base_asset_contract_address",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "ERC-20 contract address for base asset (DeFi only)",
    },
    {
        "name": "quote_asset_contract_address",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "ERC-20 contract address for quote asset (DeFi only)",
    },
    {
        "name": "pool_id",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Full pool ID for API queries",
    },
    {
        "name": "pool_address",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Pool contract address (DEX pairs)",
    },
    {
        "name": "pool_fee_tier",
        "type": "int64",
        "required": False,
        "nullable": True,
        "description": "Pool fee in basis points. Only for DEX pools",
    },
    {
        "name": "flash_loan_providers",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Comma-separated flash loan provider addresses",
    },
    {
        "name": "instadapp_routing",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Instadapp routing configuration",
    },
    {
        "name": "ltv",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Loan-to-Value ratio",
    },
    {
        "name": "liquidation_threshold",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Liquidation threshold",
    },
    {
        "name": "liquidation_bonus",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Liquidation bonus",
    },
    {
        "name": "reserve_factor",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Reserve factor",
    },
    {
        "name": "emode_category_id",
        "type": "int64",
        "required": False,
        "nullable": True,
        "description": "E-mode category ID",
    },
    {
        "name": "emode_label",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "E-mode category label",
    },
    {
        "name": "emode_underlying",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "E-mode underlying asset symbol",
    },
    {
        "name": "emode_liquidation_threshold",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "E-mode liquidation threshold",
    },
    {
        "name": "emode_liquidation_bonus",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "E-mode liquidation bonus",
    },
    {
        "name": "optimal_utilization_rate",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Optimal utilization rate",
    },
    {
        "name": "base_variable_borrow_rate",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Base variable borrow rate",
    },
    {
        "name": "variable_rate_slope1",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Variable rate slope 1",
    },
    {
        "name": "variable_rate_slope2",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Variable rate slope 2",
    },
    {
        "name": "max_position_size",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Maximum position size in quote currency",
    },
    {
        "name": "max_leverage",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Maximum leverage available",
    },
    {
        "name": "initial_margin_rate",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Initial margin rate",
    },
    {
        "name": "maintenance_margin_rate",
        "type": "float64",
        "required": False,
        "nullable": True,
        "description": "Maintenance margin rate",
    },
    {
        "name": "leverage_tiers_json",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "JSON string of all leverage tiers",
    },
    {
        "name": "trading_hours_open",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Trading hours open time (TradFi only)",
    },
    {
        "name": "trading_hours_close",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Trading hours close time (TradFi only)",
    },
    {
        "name": "trading_session",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Trading session identifier (TradFi only)",
    },
    {
        "name": "is_trading_day",
        "type": "bool",
        "required": False,
        "nullable": True,
        "description": "Whether instrument trades on given date (TradFi only)",
    },
    {
        "name": "holiday_calendar",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Exchange holiday calendar identifier (TradFi only)",
    },
    {
        "name": "pre_market_open_utc",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Pre-market session open as ISO datetime in UTC (TradFi only)",
    },
    {
        "name": "post_market_close_utc",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Post-market session close as ISO datetime in UTC (TradFi only)",
    },
    {
        "name": "timezone",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Exchange timezone e.g. America/New_York (TradFi only, UTC for CeFi/DeFi)",
    },
    {
        "name": "legs",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "JSON array of leg definitions for COMBO instruments. Each leg: {instrument_key, side, ratio}",
    },
    # ── DeFi metadata block (additions; existing pool_address / pool_fee_tier /
    #     base_asset_contract_address / quote_asset_contract_address / ltv / e-mode
    #     params / etc. live higher up in this same schema list and are unchanged) ──
    # Plan: instruments_service_metadata_refactor_2026_04_29
    {
        "name": "base_asset_decimals",
        "type": "int64",
        "required": False,
        "nullable": True,
        "description": "Decimals for base_asset ERC-20 (typically 6, 8, or 18)",
    },
    {
        "name": "base_asset_symbol_onchain",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "On-chain ERC-20 symbol for base_asset (may differ from canonical base_asset)",
    },
    {
        "name": "quote_asset_decimals",
        "type": "int64",
        "required": False,
        "nullable": True,
        "description": "Decimals for quote_asset ERC-20",
    },
    {
        "name": "quote_asset_symbol_onchain",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "On-chain ERC-20 symbol for quote_asset",
    },
    {
        "name": "atoken_address",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Aave aToken address (interest-bearing supply receipt)",
    },
    {
        "name": "debt_token_address",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "Aave variable-debt token address",
    },
    {
        "name": "rate_method_selector",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "On-chain method selector for rate queries (LST contracts); optional parity field",
    },
    # Archive metadata columns (is_mtds_contract_audit_2026_05_20 Phase 1)
    {
        "name": "source_archive_url_template",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "URL template for historical data archive. MTDS handlers derive URLs from here.",
    },
    {
        "name": "source_record_types",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "JSON: data_type → archive record-type name (e.g. {'trades': 'tradeRecords'})",
    },
    {
        "name": "source_coverage_start",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "JSON: data_type → ISO date string for archive coverage start",
    },
    {
        "name": "source_coverage_end",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "JSON: data_type → ISO date. After this → EXPECTED_PAST_SOURCE_COVERAGE_END.",
    },
    {
        "name": "listed_at",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "ISO date YYYY-MM-DD when listed. Pre-listing → EXPECTED_INSTRUMENT_NOT_LISTED.",
    },
    {
        "name": "delisted_at",
        "type": "string",
        "required": False,
        "nullable": True,
        "description": "ISO date YYYY-MM-DD when delisted. Post-delisting → EXPECTED_INSTRUMENT_DELISTED.",
    },
    {
        "name": "timestamp",
        "type": "datetime64[ns]",
        "required": True,
        "description": ("Generation timestamp (timezone-naive UTC). Added automatically during storage"),
    },
]

__all__ = ["INSTRUMENTS_PARQUET_SCHEMA"]
