"""Capability-matrix CLI (P4.10 -- workspace audit 2026-05-01).

Run::

    python -m unified_api_contracts.tools.print_capability_matrix
    python -m unified_api_contracts.tools.print_capability_matrix --markdown
    python -m unified_api_contracts.tools.print_capability_matrix --archetype CARRY_BASIS_PERP

Reads ``ARCHETYPE_CAPABILITY_REGISTRY`` and pretty-prints every
``(archetype, asset_group, instrument_type)`` cell with status, venues,
and signal variants. Single management surface for "what coverage do we
ship today?" so gaps don't get rediscovered manually.

Exit code is always 0 -- this is a reporting tool, not a validator.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterable
from typing import cast

from unified_api_contracts.internal.architecture_v2.archetype_capability import (  # qg-deep-import: symbol not yet on library root facade  # noqa: E501
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    CoverageStatus,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.enums import (  # qg-deep-import: symbol not yet on library root facade  # noqa: E501
    StrategyArchetype,
)

_STATUS_GLYPH: dict[CoverageStatus, str] = {
    CoverageStatus.SUPPORTED: "OK",
    CoverageStatus.PARTIAL: "~",
    CoverageStatus.BLOCKED: "X",
}


def _select_archetypes(
    archetype_filter: str | None,
) -> tuple[ArchetypeCapability, ...]:
    if archetype_filter is None:
        return ARCHETYPE_CAPABILITY_REGISTRY
    try:
        archetype = StrategyArchetype(archetype_filter)
    except ValueError:
        sys.stderr.write(
            f"Unknown archetype: {archetype_filter!r}. Valid values: {sorted(a.value for a in StrategyArchetype)}\n"
        )
        sys.exit(2)
    entry = capability_for(archetype)
    if entry is None:
        sys.stderr.write(f"No capability row for {archetype.value}\n")
        sys.exit(0)
    return (entry,)


def _aggregate_counts(rows: Iterable[ArchetypeCapability]) -> dict[CoverageStatus, int]:
    counts: dict[CoverageStatus, int] = dict.fromkeys(CoverageStatus, 0)
    for row in rows:
        for cell in row.cells:
            counts[cell.status] += 1
    return counts


def _emit_text(rows: Iterable[ArchetypeCapability]) -> None:
    rows = tuple(rows)
    sys.stdout.write("Capability matrix (archetype x asset_group x instrument_type)\n")
    sys.stdout.write("=" * 72 + "\n")
    for row in rows:
        sys.stdout.write(
            f"\n{row.archetype_id.value} (family={row.family.value}, rolling_futures={row.uses_rolling_futures})\n"
        )
        if not row.cells:
            sys.stdout.write("  (no cells declared)\n")
            continue
        for cell in row.cells:
            glyph = _STATUS_GLYPH[cell.status]
            venues = ",".join(cell.venue_ids) if cell.venue_ids else "-"
            variants = ",".join(cell.signal_variants) if cell.signal_variants else "-"
            sys.stdout.write(
                f"  [{glyph}] {cell.asset_group.value:<10} "
                f"{cell.instrument_type.value:<14} "
                f"venues={venues} variants={variants}"
            )
            if cell.notes:
                sys.stdout.write(f"  notes={cell.notes}")
            sys.stdout.write("\n")

    counts = _aggregate_counts(rows)
    total = sum(counts.values())
    sys.stdout.write("\n" + "-" * 72 + "\n")
    sys.stdout.write(
        f"Total cells: {total}  "
        f"SUPPORTED={counts[CoverageStatus.SUPPORTED]}  "
        f"PARTIAL={counts[CoverageStatus.PARTIAL]}  "
        f"BLOCKED={counts[CoverageStatus.BLOCKED]}\n"
    )


def _emit_markdown(rows: Iterable[ArchetypeCapability]) -> None:
    rows = tuple(rows)
    sys.stdout.write("# Capability matrix\n\n")
    sys.stdout.write("Generated by `python -m unified_api_contracts.tools.print_capability_matrix`.\n\n")
    sys.stdout.write("| archetype | asset_group | instrument_type | status | venues | variants |\n")
    sys.stdout.write("|---|---|---|---|---|---|\n")
    for row in rows:
        for cell in row.cells:
            venues = ", ".join(cell.venue_ids) if cell.venue_ids else "—"
            variants = ", ".join(cell.signal_variants) if cell.signal_variants else "—"
            sys.stdout.write(
                f"| `{row.archetype_id.value}` | `{cell.asset_group.value}` | "
                f"`{cell.instrument_type.value}` | {cell.status.value} | "
                f"{venues} | {variants} |\n"
            )
    counts = _aggregate_counts(rows)
    total = sum(counts.values())
    sys.stdout.write(
        f"\n**Totals**: {total} cells "
        f"(SUPPORTED={counts[CoverageStatus.SUPPORTED]}, "
        f"PARTIAL={counts[CoverageStatus.PARTIAL]}, "
        f"BLOCKED={counts[CoverageStatus.BLOCKED]}).\n"
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Print the workspace archetype capability matrix.",
    )
    parser.add_argument(
        "--archetype",
        default=None,
        help="Filter to one archetype (e.g. CARRY_BASIS_PERP). Default: all.",
    )
    parser.add_argument(
        "--markdown",
        action="store_true",
        help="Emit Markdown instead of plain text.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    rows = _select_archetypes(cast(str | None, args.archetype))
    if cast(bool, args.markdown):
        _emit_markdown(rows)
    else:
        _emit_text(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
