"""API contracts: Pydantic schemas and VCR mocks for external APIs (Databento, Tardis, CCXT, The Graph, etc.)."""

from .canonical_mappings import (
    DATA_SOURCE_TO_SECRET,
    DATA_SOURCE_TO_VENUES,
    DATASET_TO_CANONICAL_VENUE,
    SYMBOL_MAPPINGS,
    VENUE_TO_DATA_SOURCE,
    DataSourceMapping,
)
from .schemas import (
    DATABENTO_ERROR_MAP,
    VENUE_ERROR_MAP,
    DatabentoError,
    ErrorAction,
    FundingRate,
    HeartbeatMessage,
    LendingRate,
    Liquidation,
    LiquidityPool,
    OptionContract,
    OptionGreeks,
    OptionsChain,
    OraclePrice,
    SettlementPrice,
    StakingRate,
    SubscribeRequest,
    Swap,
    UnsubscribeRequest,
    VenueErrorClassification,
    WebSocketConnectionState,
    classify_venue_error,
)
from .trading_schemas import (
    CONFIG_REQUIRED_FIELDS,
    CONFIG_SCHEMA,
    INSTRUCTION_SCHEMA,
    INSTRUMENT_SCHEMA,
    OPTIONAL_CONFIG_FIELDS,
    REQUIRED_CONFIG_FIELDS,
    VALID_ALGORITHMS,
    VALID_BOOK_TYPES,
    VALID_CATEGORIES,
    VALID_INSTRUCTION_TYPES,
    VALID_MODES,
    VALID_TIMEFRAMES,
)
from .venue_constants import (
    CLOB_VENUES,
    DEX_VENUES,
    INSTRUMENT_TYPE_FOLDER_MAP,
    INSTRUMENT_TYPES_BY_VENUE,
    VENUE_CATEGORY_MAP,
    ZERO_ALPHA_VENUES,
)

__all__ = [
    "CLOB_VENUES",
    "CONFIG_REQUIRED_FIELDS",
    "CONFIG_SCHEMA",
    "DATABENTO_ERROR_MAP",
    "DATASET_TO_CANONICAL_VENUE",
    "DATA_SOURCE_TO_SECRET",
    "DATA_SOURCE_TO_VENUES",
    "DEX_VENUES",
    "INSTRUCTION_SCHEMA",
    "INSTRUMENT_SCHEMA",
    "INSTRUMENT_TYPES_BY_VENUE",
    "INSTRUMENT_TYPE_FOLDER_MAP",
    "OPTIONAL_CONFIG_FIELDS",
    "REQUIRED_CONFIG_FIELDS",
    "SYMBOL_MAPPINGS",
    "VALID_ALGORITHMS",
    "VALID_BOOK_TYPES",
    "VALID_CATEGORIES",
    "VALID_INSTRUCTION_TYPES",
    "VALID_MODES",
    "VALID_TIMEFRAMES",
    "VENUE_CATEGORY_MAP",
    "VENUE_ERROR_MAP",
    "VENUE_TO_DATA_SOURCE",
    "ZERO_ALPHA_VENUES",
    "DataSourceMapping",
    "DatabentoError",
    "ErrorAction",
    "FundingRate",
    "HeartbeatMessage",
    "LendingRate",
    "Liquidation",
    "LiquidityPool",
    "OptionContract",
    "OptionGreeks",
    "OptionsChain",
    "OraclePrice",
    "SettlementPrice",
    "StakingRate",
    "SubscribeRequest",
    "Swap",
    "UnsubscribeRequest",
    "VenueErrorClassification",
    "WebSocketConnectionState",
    "classify_venue_error",
]

# Backward compat: alias venue subpackages to api_contracts_external
import sys
from types import ModuleType
from typing import cast

_VENUES = [
    "alchemy",
    "api_football",
    "arkham",
    "aster",
    "barchart",
    "betfair",
    "binance",
    "bloxroute",
    "bybit",
    "ccxt",
    "cloud_sdks",
    "coinbase",
    "databento",
    "defi",
    "defillama",
    "deribit",
    "fear_greed",
    "footystats",
    "github",
    "glassnode",
    "hyperliquid",
    "ibkr",
    "kalshi",
    "mev",
    "odds_api",
    "okx",
    "open_meteo",
    "pinnacle",
    "polymarket",
    "soccer_football_info",
    "tardis",
    "thegraph",
    "transfermarkt",
    "understat",
    "upbit",
    "yahoo_finance",
]
for _v in _VENUES:
    _mod = cast(ModuleType, __import__(f"{__name__}.api_contracts_external.{_v}", fromlist=[_v]))
    sys.modules[f"{__name__}.{_v}"] = _mod
