"""Canonical sports feature vector — ML feature schema for a single fixture."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict


class SportsFeatureVector(BaseModel):
    """Complete ML feature vector for a single fixture."""

    model_config = ConfigDict(frozen=False)

    fixture_id: str
    computed_at_utc: datetime

    # ── Team features (TeamFeatureCalculator) ──
    # Form (points per game over rolling windows)
    home_form_5: float | None = None
    away_form_5: float | None = None
    home_ppg_last3: float | None = None
    away_ppg_last3: float | None = None
    home_ppg_season: float | None = None
    away_ppg_season: float | None = None
    # Win / draw / loss rates
    home_win_rate_season: float | None = None
    away_win_rate_season: float | None = None
    home_win_rate_last5: float | None = None
    away_win_rate_last5: float | None = None
    # Goals
    home_goals_scored_avg: float | None = None
    away_goals_scored_avg: float | None = None
    home_goals_conceded_avg: float | None = None
    away_goals_conceded_avg: float | None = None
    home_goal_diff_season: float | None = None
    away_goal_diff_season: float | None = None
    # xG (team-level rolling averages)
    home_xg_season: float | None = None
    away_xg_season: float | None = None
    home_xg_conceded_season: float | None = None
    away_xg_conceded_season: float | None = None
    # Home advantage
    home_home_advantage_factor: float | None = None
    # Rest & congestion
    home_rest_days: int | None = None
    away_rest_days: int | None = None
    home_congestion_score: float | None = None
    away_congestion_score: float | None = None
    # Streaks
    home_current_streak: int | None = None
    away_current_streak: int | None = None
    home_unbeaten_run: int | None = None
    away_unbeaten_run: int | None = None
    # Clean sheets & BTTS
    home_clean_sheet_rate: float | None = None
    away_clean_sheet_rate: float | None = None
    home_btts_rate: float | None = None
    away_btts_rate: float | None = None
    # Over/Under
    home_over_25_rate: float | None = None
    away_over_25_rate: float | None = None
    # Consistency
    home_goal_variance: float | None = None
    away_goal_variance: float | None = None

    # ── H2H features (H2HFeatureCalculator) ──
    # Basic H2H stats (all-time)
    h2h_home_wins: int | None = None
    h2h_draws: int | None = None
    h2h_away_wins: int | None = None
    h2h_avg_goals: float | None = None
    h2h_matches_played: int | None = None
    h2h_home_goals_avg: float | None = None
    h2h_away_goals_avg: float | None = None
    h2h_home_win_pct: float | None = None
    h2h_away_win_pct: float | None = None
    h2h_home_goals_conceded_avg: float | None = None
    h2h_away_goals_conceded_avg: float | None = None
    # H2H patterns
    h2h_btts_rate: float | None = None
    h2h_over_25_rate: float | None = None
    # Streaks
    h2h_home_current_streak: int | None = None
    h2h_away_current_streak: int | None = None
    # Time since last meeting
    h2h_days_since_last_meeting: int | None = None
    # Recent H2H (last meeting)
    h2h_last_home_wins: int | None = None
    h2h_last_away_wins: int | None = None
    h2h_last_draws: int | None = None
    h2h_last_home_goals_avg: float | None = None
    h2h_last_away_goals_avg: float | None = None
    # Recent H2H (last 3 meetings)
    h2h_last3_home_wins: int | None = None
    h2h_last3_away_wins: int | None = None
    h2h_last3_draws: int | None = None
    h2h_last3_home_goals_avg: float | None = None
    h2h_last3_away_goals_avg: float | None = None
    # Recent H2H (last 5 meetings)
    h2h_last5_home_wins: int | None = None
    h2h_last5_away_wins: int | None = None
    h2h_last5_draws: int | None = None
    h2h_last5_home_goals_avg: float | None = None
    h2h_last5_away_goals_avg: float | None = None
    # Venue-specific H2H (home team)
    h2h_home_at_home_venue_wins: int | None = None
    h2h_home_at_home_venue_draws: int | None = None
    h2h_home_at_away_venue_wins: int | None = None
    h2h_home_at_away_venue_draws: int | None = None
    # Venue-specific H2H (away team)
    h2h_away_at_away_venue_wins: int | None = None
    h2h_away_at_away_venue_draws: int | None = None
    h2h_away_at_home_venue_wins: int | None = None
    h2h_away_at_home_venue_draws: int | None = None
    # Advanced H2H stats (possession and xG)
    h2h_possession_home_avg: float | None = None
    h2h_possession_away_avg: float | None = None
    h2h_xg_home_avg: float | None = None
    h2h_xg_away_avg: float | None = None

    # ── League features (LeagueFeatureCalculator) ──
    league_avg_goals_per_game: float | None = None
    league_home_win_rate: float | None = None
    league_btts_rate: float | None = None
    league_over_25_rate: float | None = None
    league_draw_rate: float | None = None
    league_avg_cards_per_game: float | None = None
    league_avg_corners_per_game: float | None = None
    # Attack/defense strength relative to league average
    home_attack_strength: float | None = None
    away_attack_strength: float | None = None
    home_defense_strength: float | None = None
    away_defense_strength: float | None = None
    # Games played per team in league (season context)
    home_league_games_played: int | None = None
    away_league_games_played: int | None = None
    # Derived league aggregates
    league_home_advantage: float | None = None
    league_avg_goals_per_team: float | None = None

    # ── Halftime features (HalfTimeFeatureCalculator) ──
    home_ht_goal_rate: float | None = None
    away_ht_goal_rate: float | None = None
    home_ht_concede_rate: float | None = None
    away_ht_concede_rate: float | None = None
    home_ht_lead_rate: float | None = None
    away_ht_lead_rate: float | None = None
    # Extended HT features (from old system)
    home_ht_goals_avg: float | None = None
    away_ht_goals_avg: float | None = None
    home_ht_conceded_avg: float | None = None
    away_ht_conceded_avg: float | None = None
    home_ht_clean_sheet_rate: float | None = None
    away_ht_clean_sheet_rate: float | None = None
    home_ht_win_conversion_rate: float | None = None
    away_ht_win_conversion_rate: float | None = None
    home_ht_comeback_rate: float | None = None
    away_ht_comeback_rate: float | None = None
    home_ht_scoring_rate: float | None = None
    away_ht_scoring_rate: float | None = None

    # ── Goal timing features (GoalTimingFeatureCalculator) ──
    home_early_goal_rate: float | None = None
    home_late_goal_rate: float | None = None
    away_early_goal_rate: float | None = None
    away_late_concede_rate: float | None = None
    home_first_goal_rate: float | None = None
    away_first_goal_rate: float | None = None

    # ── Season context (SeasonContextFeatureCalculator) ──
    match_week: int | None = None
    season_stage: str | None = None
    home_relegation_pressure: float | None = None
    away_relegation_pressure: float | None = None
    home_title_pressure: float | None = None
    season_progress_pct: float | None = None

    # ── Venue context (VenueContextFeatureCalculator) ──
    venue_capacity: int | None = None
    venue_altitude_m: float | None = None
    venue_surface: str | None = None
    attendance_rate: float | None = None
    venue_home_win_rate: float | None = None
    venue_avg_goals: float | None = None

    # ── Referee features (RefereeFeatureCalculator) ──
    ref_cards_per_game: float | None = None
    ref_penalty_rate: float | None = None
    ref_home_bias_score: float | None = None
    ref_fouls_per_game: float | None = None
    ref_avg_added_time: float | None = None
    ref_matches_count: int | None = None

    # ── Player lineup features (PlayerLineupFeatureCalculator) ──
    home_key_player_absent: bool | None = None
    away_key_player_absent: bool | None = None
    home_lineup_strength: float | None = None
    away_lineup_strength: float | None = None
    home_missing_key_players: int | None = None
    away_missing_key_players: int | None = None

    # ── Odds features (OddsFeatureCalculator) ──
    # Implied probabilities
    market_home_implied_prob: float | None = None
    market_draw_implied_prob: float | None = None
    market_away_implied_prob: float | None = None
    # Market efficiency
    market_overround: float | None = None
    market_consensus_home_prob: float | None = None
    market_consensus_draw_prob: float | None = None
    market_consensus_away_prob: float | None = None
    market_vig_pct: float | None = None
    market_num_bookmakers: int | None = None
    # Raw 1X2 odds
    odds_home_win: float | None = None
    odds_draw: float | None = None
    odds_away_win: float | None = None
    odds_home_away_ratio: float | None = None
    market_home_away_odds_ratio: float | None = None
    # Over/Under lines
    odds_over_2_5: float | None = None
    odds_under_2_5: float | None = None
    market_over_25_implied_prob: float | None = None
    market_under_25_implied_prob: float | None = None
    odds_over_1_5: float | None = None
    odds_under_1_5: float | None = None
    odds_over_3_5: float | None = None
    odds_under_3_5: float | None = None
    # Market consensus (cross-bookmaker)
    market_home_odds_best: float | None = None
    market_away_odds_best: float | None = None
    market_home_odds_variance: float | None = None
    market_away_odds_variance: float | None = None
    # Odds movement (opening / closing)
    odds_home_opening: float | None = None
    odds_home_closing: float | None = None
    odds_home_movement: float | None = None
    odds_home_movement_pct: float | None = None
    odds_away_opening: float | None = None
    odds_away_closing: float | None = None
    odds_away_movement: float | None = None
    odds_away_movement_pct: float | None = None
    # Sharp money indicators
    odds_sharp_money_on_home: int | None = None
    odds_sharp_money_on_away: int | None = None

    # ── xG features (MultiSourceXGFeatureCalculator + PoissonXGFeatureCalculator) ──
    understat_home_xg: float | None = None
    understat_away_xg: float | None = None
    footystats_home_xg: float | None = None
    footystats_away_xg: float | None = None
    consensus_home_xg: float | None = None
    consensus_away_xg: float | None = None
    poisson_home_win_prob: float | None = None
    poisson_draw_prob: float | None = None
    poisson_away_win_prob: float | None = None
    poisson_over_25_prob: float | None = None
    poisson_btts_prob: float | None = None

    # ── Advanced stats (AdvancedStatsFeatureCalculator) ──
    home_shots_on_target_avg: float | None = None
    away_shots_on_target_avg: float | None = None
    home_total_shots_avg: float | None = None
    away_total_shots_avg: float | None = None
    home_shot_accuracy: float | None = None
    away_shot_accuracy: float | None = None
    home_corners_avg: float | None = None
    away_corners_avg: float | None = None
    home_possession_avg: float | None = None
    away_possession_avg: float | None = None
    home_fouls_avg: float | None = None
    away_fouls_avg: float | None = None
    home_yellow_cards_avg: float | None = None
    away_yellow_cards_avg: float | None = None

    # ── Weather features (WeatherFeatureCalculator) ──
    weather_temp_c: float | None = None
    weather_wind_speed_ms: float | None = None
    weather_precipitation_mm: float | None = None
    weather_condition: str | None = None

    # -- Team Extended (TeamFeatureCalculator) --
    away_aerials_won_pct: float | None = None
    away_avg_opponent_rank: float | None = None
    away_away_goals_avg: float | None = None
    away_away_ppg_season: float | None = None
    away_away_xg_avg: float | None = None
    away_big_chances_created: float | None = None
    away_blocks_per_game: float | None = None
    away_btts_rate_last5: float | None = None
    away_cards_season: int | None = None
    away_clean_sheet_rate_last5: float | None = None
    away_clearances_per_game: float | None = None
    away_conversion_rate_season: float | None = None
    away_corners_last3: float | None = None
    away_corners_last5: float | None = None
    away_corners_season: float | None = None
    away_cup_ppg: float | None = None
    away_current_clean_sheet_streak: int | None = None
    away_current_scoring_streak: int | None = None
    away_current_unbeaten_streak: int | None = None
    away_current_win_streak: int | None = None
    away_dangerous_attacks_last3: float | None = None
    away_dangerous_attacks_last5: float | None = None
    away_dangerous_attacks_season: float | None = None
    away_draw_rate_last5: float | None = None
    away_duels_won_pct: float | None = None
    away_elo: int | None = None
    away_european_ppg: float | None = None
    away_failed_to_score_rate_last5: float | None = None
    away_first_half_goals_avg: float | None = None
    away_form_momentum: float | None = None
    away_form_string: float | None = None
    away_fouls_per_game: float | None = None
    away_games_last_14d: int | None = None
    away_goals_avg_last_5: float | None = None
    away_goals_conceded_last1: int | None = None
    away_goals_conceded_last3: float | None = None
    away_goals_conceded_last5: float | None = None
    away_goals_conceded_season: float | None = None
    away_goals_last1: int | None = None
    away_goals_last3: float | None = None
    away_goals_last5: float | None = None
    away_goals_season: float | None = None
    away_goals_std_last10: float | None = None
    away_goals_trend_last10: float | None = None
    away_interceptions_per_game: float | None = None
    away_key_passes_per_game: float | None = None
    away_late_goals_rate: float | None = None
    away_league_ppg: float | None = None
    away_loss_rate_last5: float | None = None
    away_offsides_per_game: float | None = None
    away_over_2_5_rate_last5: float | None = None
    away_pass_accuracy_season: float | None = None
    away_passes_per_game_season: float | None = None
    away_performance_under_pressure: float | None = None
    away_possession_last1: float | None = None
    away_possession_last3: float | None = None
    away_possession_last5: float | None = None
    away_possession_season: float | None = None
    away_ppg_last1: float | None = None
    away_ppg_last5: float | None = None
    away_ppg_trend_last10: float | None = None
    away_ppg_vs_bottom6: float | None = None
    away_ppg_vs_top6: float | None = None
    away_red_cards_last5: int | None = None
    away_save_pct_season: float | None = None
    away_saves_per_game: float | None = None
    away_second_half_goals_avg: float | None = None
    away_shot_accuracy_season: float | None = None
    away_shots_inside_box_pct: float | None = None
    away_shots_last1: float | None = None
    away_shots_last3: float | None = None
    away_shots_last5: float | None = None
    away_shots_on_target_last3: float | None = None
    away_shots_on_target_last5: float | None = None
    away_shots_on_target_season: float | None = None
    away_shots_per_goal_season: float | None = None
    away_shots_season: float | None = None
    away_tackles_per_game: float | None = None
    away_xg_conceded_last1: float | None = None
    away_xg_conceded_last3: float | None = None
    away_xg_conceded_last5: float | None = None
    away_xg_diff_season: float | None = None
    away_xg_last1: float | None = None
    away_xg_last3: float | None = None
    away_xg_last5: float | None = None
    away_xg_trend_last10: float | None = None
    away_yellow_cards_last5: float | None = None
    home_aerials_won_pct: float | None = None
    home_avg_opponent_rank: float | None = None
    home_big_chances_created: float | None = None
    home_blocks_per_game: float | None = None
    home_btts_rate_last5: float | None = None
    home_cards_season: int | None = None
    home_clean_sheet_rate_last5: float | None = None
    home_clearances_per_game: float | None = None
    home_conversion_rate_season: float | None = None
    home_corners_last3: float | None = None
    home_corners_last5: float | None = None
    home_corners_season: float | None = None
    home_cup_ppg: float | None = None
    home_current_clean_sheet_streak: int | None = None
    home_current_scoring_streak: int | None = None
    home_current_unbeaten_streak: int | None = None
    home_current_win_streak: int | None = None
    home_dangerous_attacks_last3: float | None = None
    home_dangerous_attacks_last5: float | None = None
    home_dangerous_attacks_season: float | None = None
    home_draw_rate_last5: float | None = None
    home_duels_won_pct: float | None = None
    home_elo: int | None = None
    home_european_ppg: float | None = None
    home_failed_to_score_rate_last5: float | None = None
    home_first_half_goals_avg: float | None = None
    home_form_momentum: float | None = None
    home_form_string: float | None = None
    home_fouls_per_game: float | None = None
    home_games_last_14d: int | None = None
    home_goals_avg_last_5: float | None = None
    home_goals_conceded_last1: int | None = None
    home_goals_conceded_last3: float | None = None
    home_goals_conceded_last5: float | None = None
    home_goals_conceded_season: float | None = None
    home_goals_last1: int | None = None
    home_goals_last3: float | None = None
    home_goals_last5: float | None = None
    home_goals_season: float | None = None
    home_goals_std_last10: float | None = None
    home_goals_trend_last10: float | None = None
    home_home_goals_avg: float | None = None
    home_home_ppg_season: float | None = None
    home_home_xg_avg: float | None = None
    home_interceptions_per_game: float | None = None
    home_key_passes_per_game: float | None = None
    home_late_goals_rate: float | None = None
    home_league_ppg: float | None = None
    home_loss_rate_last5: float | None = None
    home_offsides_per_game: float | None = None
    home_over_2_5_rate_last5: float | None = None
    home_pass_accuracy_season: float | None = None
    home_passes_per_game_season: float | None = None
    home_performance_under_pressure: float | None = None
    home_possession_last1: float | None = None
    home_possession_last3: float | None = None
    home_possession_last5: float | None = None
    home_possession_season: float | None = None
    home_ppg_last1: float | None = None
    home_ppg_last5: float | None = None
    home_ppg_trend_last10: float | None = None
    home_ppg_vs_bottom6: float | None = None
    home_ppg_vs_top6: float | None = None
    home_red_cards_last5: int | None = None
    home_save_pct_season: float | None = None
    home_saves_per_game: float | None = None
    home_second_half_goals_avg: float | None = None
    home_shot_accuracy_season: float | None = None
    home_shots_inside_box_pct: float | None = None
    home_shots_last1: float | None = None
    home_shots_last3: float | None = None
    home_shots_last5: float | None = None
    home_shots_on_target_last3: float | None = None
    home_shots_on_target_last5: float | None = None
    home_shots_on_target_season: float | None = None
    home_shots_per_goal_season: float | None = None
    home_shots_season: float | None = None
    home_tackles_per_game: float | None = None
    home_xg_conceded_last1: float | None = None
    home_xg_conceded_last3: float | None = None
    home_xg_conceded_last5: float | None = None
    home_xg_diff_season: float | None = None
    home_xg_last1: float | None = None
    home_xg_last3: float | None = None
    home_xg_last5: float | None = None
    home_xg_trend_last10: float | None = None
    home_yellow_cards_last5: float | None = None
    ppg_diff: float | None = None
    xg_diff_season: float | None = None

    # -- League (LeagueFeatureCalculator) --
    away_goals_conceded_vs_league_avg: float | None = None
    away_goals_vs_league_avg: float | None = None
    away_is_bottom_6: bool | None = None
    away_is_top_6: bool | None = None
    away_is_top_half: bool | None = None
    away_league_position: int | None = None
    away_points_from_leader: float | None = None
    away_position_pct: float | None = None
    away_xg_conceded_vs_league_avg: float | None = None
    away_xg_vs_league_avg: float | None = None
    home_goals_conceded_vs_league_avg: float | None = None
    home_goals_vs_league_avg: float | None = None
    home_is_bottom_6: bool | None = None
    home_is_top_6: bool | None = None
    home_is_top_half: bool | None = None
    home_league_position: int | None = None
    home_points_from_leader: float | None = None
    home_position_pct: float | None = None
    home_xg_conceded_vs_league_avg: float | None = None
    home_xg_vs_league_avg: float | None = None
    league_avg_possession: float | None = None
    league_avg_shots_per_game: float | None = None
    league_avg_xg_per_game: float | None = None
    league_over_2_5_rate: float | None = None
    league_position_diff: int | None = None

    # -- Halftime (HalfTimeFeatureCalculator) --
    ht_away_comeback_rate_history: float | None = None
    ht_away_corners: int | None = None
    ht_away_goals: int | None = None
    ht_away_goals_vs_xg: float | None = None
    ht_away_hold_lead_rate: float | None = None
    ht_away_momentum_score: float | None = None
    ht_away_outperforming: bool | None = None
    ht_away_possession: float | None = None
    ht_away_red_cards: int | None = None
    ht_away_scored_early: bool | None = None
    ht_away_scored_late: bool | None = None
    ht_away_shots: int | None = None
    ht_away_shots_on_target: int | None = None
    ht_away_subs_made: int | None = None
    ht_away_tactical_sub: bool | None = None
    ht_away_winning: bool | None = None
    ht_away_xg: float | None = None
    ht_away_yellow_cards: int | None = None
    ht_dominance_score_away: float | None = None
    ht_dominance_score_home: float | None = None
    ht_efficiency_score_away: float | None = None
    ht_efficiency_score_home: float | None = None
    ht_game_state_code: str | None = None
    ht_goal_diff: int | None = None
    ht_has_red_card: bool | None = None
    ht_home_comeback_rate_history: float | None = None
    ht_home_corners: int | None = None
    ht_home_goals: int | None = None
    ht_home_goals_vs_xg: float | None = None
    ht_home_hold_lead_rate: float | None = None
    ht_home_momentum_score: float | None = None
    ht_home_outperforming: bool | None = None
    ht_home_possession: float | None = None
    ht_home_red_cards: int | None = None
    ht_home_scored_early: bool | None = None
    ht_home_scored_late: bool | None = None
    ht_home_shots: int | None = None
    ht_home_shots_on_target: int | None = None
    ht_home_subs_made: int | None = None
    ht_home_tactical_sub: bool | None = None
    ht_home_winning: bool | None = None
    ht_home_xg: float | None = None
    ht_home_yellow_cards: int | None = None
    ht_is_draw: bool | None = None
    ht_last_goal_minute: int | None = None
    ht_last_goal_team: str | None = None
    ht_league_avg_2h_goals: float | None = None
    ht_match_tempo: float | None = None
    ht_odds_away_win: float | None = None
    ht_odds_draw: float | None = None
    ht_odds_home_win: float | None = None
    ht_odds_movement_away: float | None = None
    ht_odds_movement_home: float | None = None
    ht_possession_trend_away: float | None = None
    ht_possession_trend_home: float | None = None
    ht_predicted_2h_away_goals: float | None = None
    ht_predicted_2h_home_goals: float | None = None
    ht_predicted_ft_away_goals: float | None = None
    ht_predicted_ft_home_goals: float | None = None
    ht_predicted_ft_total_goals: float | None = None
    ht_shots_trend_away: float | None = None
    ht_shots_trend_home: float | None = None
    ht_total_goals: int | None = None
    ht_win_prob_away: float | None = None
    ht_win_prob_draw: float | None = None
    ht_win_prob_home: float | None = None

    # -- HT Sequencing (HTSequencingFeatureCalculator) --
    away_attack_dominance_late: float | None = None
    away_dangerous_attacks_last_10: int | None = None
    away_event_rate_decline: float | None = None
    away_game_state_xg_modifier: float | None = None
    away_late_surge: bool | None = None
    away_match_intensity: float | None = None
    away_max_momentum: float | None = None
    away_momentum_at_35: float | None = None
    away_momentum_score_ht: float | None = None
    away_momentum_trend: float | None = None
    away_response_when_ahead: float | None = None
    away_response_when_behind: float | None = None
    away_shot_pressure_ratio: float | None = None
    away_shots_last_10min_ht: int | None = None
    away_shots_last_5min_ht: int | None = None
    away_xg_acceleration: float | None = None
    away_xg_first_15min: float | None = None
    away_xg_first_half_trend: float | None = None
    away_xg_last_15min: float | None = None
    away_xg_middle_15min: float | None = None
    comeback_attempted: bool | None = None
    game_state_at_ht: str | None = None
    high_intensity_match: bool | None = None
    home_attack_dominance_late: float | None = None
    home_dangerous_attacks_last_10: int | None = None
    home_event_rate_decline: float | None = None
    home_game_state_xg_modifier: float | None = None
    home_late_surge: bool | None = None
    home_match_intensity: float | None = None
    home_max_momentum: float | None = None
    home_momentum_at_35: float | None = None
    home_momentum_score_ht: float | None = None
    home_momentum_trend: float | None = None
    home_response_when_ahead: float | None = None
    home_response_when_behind: float | None = None
    home_shot_pressure_ratio: float | None = None
    home_shots_last_10min_ht: int | None = None
    home_shots_last_5min_ht: int | None = None
    home_xg_acceleration: float | None = None
    home_xg_first_15min: float | None = None
    home_xg_first_half_trend: float | None = None
    home_xg_last_15min: float | None = None
    home_xg_middle_15min: float | None = None
    lead_changes: int | None = None
    time_in_lead: int | None = None

    # -- Goal Timing (GoalTimingFeatureCalculator) --
    away_avg_first_goal_minute: float | None = None
    away_comeback_rate: float | None = None
    away_first_goal_before_30min_rate: float | None = None
    away_goals_0_15_min_avg: float | None = None
    away_goals_15_30_min_avg: float | None = None
    away_goals_30_45_min_avg: float | None = None
    away_goals_45_60_min_avg: float | None = None
    away_goals_60_75_min_avg: float | None = None
    away_goals_75_90_min_avg: float | None = None
    away_late_goal_rate: float | None = None
    away_scores_first_win_rate: float | None = None
    home_avg_first_goal_minute: float | None = None
    home_comeback_rate: float | None = None
    home_first_goal_before_30min_rate: float | None = None
    home_goals_0_15_min_avg: float | None = None
    home_goals_15_30_min_avg: float | None = None
    home_goals_30_45_min_avg: float | None = None
    home_goals_45_60_min_avg: float | None = None
    home_goals_60_75_min_avg: float | None = None
    home_goals_75_90_min_avg: float | None = None
    home_scores_first_win_rate: float | None = None

    # -- Season Context (SeasonContextFeatureCalculator) --
    away_days_rest: float | None = None
    days_since_season_start: int | None = None
    games_played_season_away: int | None = None
    games_played_season_home: int | None = None
    home_days_rest: float | None = None
    home_rest_advantage: float | None = None
    is_early_season: bool | None = None
    is_first_3_games: bool | None = None
    is_season_finale: bool | None = None

    # -- Venue Context (VenueContextFeatureCalculator) --
    attendance_pct_capacity: float | None = None
    expected_attendance: float | None = None
    is_derby: bool | None = None
    is_european_spot_contest: bool | None = None
    is_relegation_battle: bool | None = None
    is_sellout_expected: bool | None = None
    is_title_decider: bool | None = None
    kickoff_day_of_week: int | None = None
    kickoff_hour: int | None = None
    kickoff_is_afternoon: bool | None = None
    kickoff_is_early: bool | None = None
    kickoff_is_evening: bool | None = None
    kickoff_is_midweek: bool | None = None
    kickoff_is_weekend: bool | None = None
    match_importance_away: float | None = None
    match_importance_home: float | None = None
    stakes_differential: float | None = None
    venue_age: int | None = None
    venue_altitude_meters: float | None = None
    venue_avg_attendance_season: float | None = None
    venue_has_roof: bool | None = None
    venue_is_artificial_turf: bool | None = None
    venue_is_high_altitude: bool | None = None
    venue_pitch_length: float | None = None
    venue_pitch_size: float | None = None
    venue_pitch_width: float | None = None
    venue_surface_type: str | None = None

    # -- Referee (RefereeFeatureCalculator) --
    referee_fouls_per_game: float | None = None
    referee_games_with_away_team: int | None = None
    referee_games_with_home_team: int | None = None
    referee_has_red_card_rate: float | None = None
    referee_home_foul_bias: float | None = None
    referee_home_penalty_bias: float | None = None
    referee_home_team_win_rate: float | None = None
    referee_home_yellow_card_bias: float | None = None
    referee_is_lenient: bool | None = None
    referee_is_strict: bool | None = None
    referee_penalties_per_game: float | None = None
    referee_penalty_rate_season: float | None = None
    referee_red_cards_per_game: float | None = None
    referee_red_cards_season: int | None = None
    referee_total_cards_per_game: float | None = None
    referee_yellow_card_rate: float | None = None
    referee_yellow_cards_per_game: float | None = None
    referee_yellow_cards_season: int | None = None

    # -- Referee Interaction (RefereeInteractionFeatureCalculator) --
    away_card_diff_under_ref: float | None = None
    away_cards_under_ref: float | None = None
    away_discipline_risk: float | None = None
    away_pen_attack_style: float | None = None
    away_penalty_propensity: float | None = None
    away_reds_under_ref: float | None = None
    away_ref_foul_rate: float | None = None
    away_ref_home_bias: float | None = None
    away_ref_penalty_rate: float | None = None
    away_ref_style_match: float | None = None
    away_yellows_under_ref: float | None = None
    home_card_diff_under_ref: float | None = None
    home_cards_under_ref: float | None = None
    home_discipline_risk: float | None = None
    home_pen_attack_style: float | None = None
    home_penalty_propensity: float | None = None
    home_reds_under_ref: float | None = None
    home_ref_foul_rate: float | None = None
    home_ref_home_bias: float | None = None
    home_ref_penalty_rate: float | None = None
    home_ref_style_match: float | None = None
    home_yellows_under_ref: float | None = None

    # -- Player Lineup (PlayerLineupFeatureCalculator) --
    away_bench_avg_rating: float | None = None
    away_formation_consistency: float | None = None
    away_gk_clean_sheet_rate: float | None = None
    away_gk_save_percentage: float | None = None
    away_gk_saves_per_game: float | None = None
    away_goal_concentration: float | None = None
    away_injured_players_count: int | None = None
    away_key_players_available: int | None = None
    away_key_players_missing: int | None = None
    away_lineup_changes_from_last: int | None = None
    away_players_on_yellow_card_warning: int | None = None
    away_squad_depth_score: float | None = None
    away_suspended_players_count: int | None = None
    away_top_assist_provider_assists: int | None = None
    away_top_scorer_available: bool | None = None
    away_top_scorer_form_last5: int | None = None
    away_top_scorer_goals: int | None = None
    away_top_scorer_goals_per_game: float | None = None
    away_xi_avg_age: float | None = None
    away_xi_avg_appearances: float | None = None
    away_xi_avg_goals_per_game: float | None = None
    away_xi_avg_rating: float | None = None
    away_xi_interceptions_per_game: float | None = None
    away_xi_key_passes_per_game: float | None = None
    away_xi_tackles_per_game: float | None = None
    away_xi_total_assists: int | None = None
    away_xi_yellow_cards_season: int | None = None
    home_bench_avg_rating: float | None = None
    home_formation_consistency: float | None = None
    home_gk_clean_sheet_rate: float | None = None
    home_gk_save_percentage: float | None = None
    home_gk_saves_per_game: float | None = None
    home_goal_concentration: float | None = None
    home_injured_players_count: int | None = None
    home_key_players_available: int | None = None
    home_key_players_missing: int | None = None
    home_lineup_changes_from_last: int | None = None
    home_players_on_yellow_card_warning: int | None = None
    home_squad_depth_score: float | None = None
    home_suspended_players_count: int | None = None
    home_top_assist_provider_assists: int | None = None
    home_top_scorer_available: bool | None = None
    home_top_scorer_form_last5: int | None = None
    home_top_scorer_goals: int | None = None
    home_top_scorer_goals_per_game: float | None = None
    home_xi_avg_age: float | None = None
    home_xi_avg_appearances: float | None = None
    home_xi_avg_goals_per_game: float | None = None
    home_xi_avg_rating: float | None = None
    home_xi_interceptions_per_game: float | None = None
    home_xi_key_passes_per_game: float | None = None
    home_xi_tackles_per_game: float | None = None
    home_xi_total_assists: int | None = None
    home_xi_yellow_cards_season: int | None = None

    # -- Odds (OddsFeatureCalculator) --
    asian_handicap_line: float | None = None
    ev_away_win: float | None = None
    ev_home_win: float | None = None
    implied_prob_btts_no: float | None = None
    implied_prob_btts_yes: float | None = None
    odds_asian_handicap_away: float | None = None
    odds_asian_handicap_home: float | None = None
    odds_btts_no: float | None = None
    odds_btts_yes: float | None = None
    value_away_win: float | None = None
    value_btts: float | None = None
    value_home_win: float | None = None
    value_over_2_5: float | None = None

    # -- Multi-Source xG (MultiSourceXGFeatureCalculator) --
    away_xg_af: float | None = None
    away_xg_consensus: float | None = None
    away_xg_consensus_std: float | None = None
    away_xg_ft: float | None = None
    away_xg_ft_prematch: float | None = None
    away_xg_ft_vs_af: float | None = None
    away_xg_max_provider: float | None = None
    away_xg_min_provider: float | None = None
    away_xg_sf_kickoff: float | None = None
    away_xg_sf_vs_af: float | None = None
    away_xg_spread: float | None = None
    away_xg_us: float | None = None
    away_xg_us_vs_af: float | None = None
    away_xg_variance: float | None = None
    home_xg_af: float | None = None
    home_xg_consensus: float | None = None
    home_xg_consensus_std: float | None = None
    home_xg_ft: float | None = None
    home_xg_ft_prematch: float | None = None
    home_xg_ft_vs_af: float | None = None
    home_xg_max_provider: float | None = None
    home_xg_min_provider: float | None = None
    home_xg_sf_kickoff: float | None = None
    home_xg_sf_vs_af: float | None = None
    home_xg_spread: float | None = None
    home_xg_us: float | None = None
    home_xg_us_vs_af: float | None = None
    home_xg_variance: float | None = None
    xg_providers_agree: bool | None = None
    xg_providers_count: int | None = None

    # -- Poisson xG (PoissonXGFeatureCalculator) --
    away_attack_lambda: float | None = None
    away_defense_lambda: float | None = None
    away_expected_regression: float | None = None
    away_xg_overperformance: float | None = None
    away_xg_overperformance_pct: float | None = None
    away_xg_std_last10: float | None = None
    away_xg_trend: float | None = None
    dixon_coles_away_win_prob: float | None = None
    dixon_coles_draw_prob: float | None = None
    dixon_coles_home_win_prob: float | None = None
    dixon_coles_rho: float | None = None
    home_attack_lambda: float | None = None
    home_defense_lambda: float | None = None
    home_expected_regression: float | None = None
    home_xg_overperformance: float | None = None
    home_xg_overperformance_pct: float | None = None
    home_xg_std_last10: float | None = None
    home_xg_trend: float | None = None
    hybrid_away_expected_goals: float | None = None
    hybrid_btts_prob: float | None = None
    hybrid_home_expected_goals: float | None = None
    hybrid_over_2_5_prob: float | None = None
    poisson_away_expected_goals: float | None = None
    poisson_home_expected_goals: float | None = None
    poisson_over_0_5_prob: float | None = None
    poisson_over_1_5_prob: float | None = None
    poisson_over_2_5_prob: float | None = None
    poisson_over_3_5_prob: float | None = None
    poisson_total_expected_goals: float | None = None

    # -- Advanced Stats (AdvancedStatsFeatureCalculator) --
    away_attacking_momentum: float | None = None
    away_defense_percentile_league: float | None = None
    away_defensive_momentum: float | None = None
    away_goals_autocorr: float | None = None
    away_goals_entropy: float | None = None
    away_goals_ewma_14d: float | None = None
    away_goals_ewma_60d: float | None = None
    away_goals_percentile_league: float | None = None
    away_goals_volatility_last10: float | None = None
    away_goals_xg_correlation: float | None = None
    away_is_outlier_performance: bool | None = None
    away_luck_factor: float | None = None
    away_momentum_composite: float | None = None
    away_possession_goals_correlation: float | None = None
    away_ppg_autocorr: float | None = None
    away_ppg_volatility_season: float | None = None
    away_regression_pressure: float | None = None
    away_result_entropy: float | None = None
    away_xg_ewma_14d: float | None = None
    away_xg_percentile_league: float | None = None
    away_xg_volatility_last10: float | None = None
    home_attacking_momentum: float | None = None
    home_defense_percentile_league: float | None = None
    home_defensive_momentum: float | None = None
    home_goals_autocorr: float | None = None
    home_goals_entropy: float | None = None
    home_goals_ewma_14d: float | None = None
    home_goals_ewma_60d: float | None = None
    home_goals_percentile_league: float | None = None
    home_goals_volatility_last10: float | None = None
    home_goals_xg_correlation: float | None = None
    home_is_outlier_performance: bool | None = None
    home_luck_factor: float | None = None
    home_momentum_composite: float | None = None
    home_possession_goals_correlation: float | None = None
    home_ppg_autocorr: float | None = None
    home_ppg_volatility_season: float | None = None
    home_regression_pressure: float | None = None
    home_result_entropy: float | None = None
    home_xg_ewma_14d: float | None = None
    home_xg_percentile_league: float | None = None
    home_xg_volatility_last10: float | None = None

    # -- Weather (WeatherFeatureCalculator) --
    cloud_cover_pct: float | None = None
    humidity_pct: float | None = None
    is_adverse_weather: bool | None = None
    is_cold_weather: bool | None = None
    is_heavy_rain: bool | None = None
    is_hot_weather: bool | None = None
    is_raining: bool | None = None
    is_windy: bool | None = None
    precipitation_mm: float | None = None
    temperature_celsius: float | None = None
    weather_severity_score: float | None = None
    wind_speed_kmh: float | None = None

    # -- Team Style (TeamStyleFeatureCalculator) --
    away_aerial_dominance: float | None = None
    away_attack_directness: float | None = None
    away_attack_width: float | None = None
    away_attacking_style_clash: float | None = None
    away_counter_attack_opportunity: float | None = None
    away_counter_attack_ratio: float | None = None
    away_cross_reliance: float | None = None
    away_defensive_block_height: float | None = None
    away_defensive_style_clash: float | None = None
    away_game_control: float | None = None
    away_interception_rate: float | None = None
    away_match_tempo: float | None = None
    away_pass_tempo: float | None = None
    away_physical_mismatch: float | None = None
    away_possession_battle: float | None = None
    away_possession_style: float | None = None
    away_ppda_style: float | None = None
    away_press_vs_build: float | None = None
    away_set_piece_reliance: float | None = None
    away_style_similarity: float | None = None
    away_tackle_aggression: float | None = None
    away_tempo_differential: float | None = None
    away_transition_speed: float | None = None
    away_xg_per_shot: float | None = None
    home_aerial_dominance: float | None = None
    home_attack_directness: float | None = None
    home_attack_width: float | None = None
    home_attacking_style_clash: float | None = None
    home_counter_attack_opportunity: float | None = None
    home_counter_attack_ratio: float | None = None
    home_cross_reliance: float | None = None
    home_defensive_block_height: float | None = None
    home_defensive_style_clash: float | None = None
    home_game_control: float | None = None
    home_interception_rate: float | None = None
    home_match_tempo: float | None = None
    home_pass_tempo: float | None = None
    home_physical_mismatch: float | None = None
    home_possession_battle: float | None = None
    home_possession_style: float | None = None
    home_ppda_style: float | None = None
    home_press_vs_build: float | None = None
    home_set_piece_reliance: float | None = None
    home_style_similarity: float | None = None
    home_tackle_aggression: float | None = None
    home_tempo_differential: float | None = None
    home_transition_speed: float | None = None
    home_xg_per_shot: float | None = None

    # -- Manager (ManagerFeatureCalculator) --
    away_days_since_manager_change: int | None = None
    away_games_under_manager: int | None = None
    away_manager_attack_style: float | None = None
    away_manager_avg_possession: float | None = None
    away_manager_avg_ppda: float | None = None
    away_manager_clean_sheet_rate: float | None = None
    away_manager_defensive_style: float | None = None
    away_manager_goals_per_game: float | None = None
    away_manager_honeymoon: bool | None = None
    away_manager_ppg_last5: float | None = None
    away_manager_set_piece_focus: float | None = None
    away_manager_win_rate: float | None = None
    away_manager_xg_diff_last5: float | None = None
    away_new_manager_flag: bool | None = None
    home_days_since_manager_change: int | None = None
    home_games_under_manager: int | None = None
    home_manager_attack_style: float | None = None
    home_manager_avg_possession: float | None = None
    home_manager_avg_ppda: float | None = None
    home_manager_clean_sheet_rate: float | None = None
    home_manager_defensive_style: float | None = None
    home_manager_goals_per_game: float | None = None
    home_manager_honeymoon: bool | None = None
    home_manager_ppg_last5: float | None = None
    home_manager_set_piece_focus: float | None = None
    home_manager_win_rate: float | None = None
    home_manager_xg_diff_last5: float | None = None
    home_new_manager_flag: bool | None = None
    manager_experience_diff: int | None = None
    manager_h2h_home_wins: int | None = None
    manager_h2h_matches: int | None = None
    manager_trophy_diff: int | None = None

    # -- Market Efficiency (MarketEfficiencyFeatureCalculator) --
    market_betfair_volume_estimate: float | None = None
    market_bookmaker_agreement: float | None = None
    market_bookmaker_count: int | None = None
    market_closing_line_predictability: float | None = None
    market_confidence: float | None = None
    market_data_completeness_score: float | None = None
    market_entropy: float | None = None
    market_gap_max_vs_pinnacle_away: float | None = None
    market_gap_max_vs_pinnacle_draw: float | None = None
    market_gap_max_vs_pinnacle_home: float | None = None
    market_league_liquidity_tier: int | None = None
    market_liquidity_score: float | None = None
    market_max_odds_away: float | None = None
    market_max_odds_draw: float | None = None
    market_max_odds_home: float | None = None
    market_max_stake_estimate: float | None = None
    market_odds_range_home: float | None = None
    market_odds_stability_score: float | None = None
    market_pinnacle_away: float | None = None
    market_pinnacle_draw: float | None = None
    market_pinnacle_home: float | None = None
    market_price_discovery_score: float | None = None
    market_sharp_book_available: bool | None = None
    market_soft_book_value_home: float | None = None

    # -- Market Structure (MarketStructureFeatureCalculator) --
    market_betfair_weight: float | None = None
    market_consensus_confidence: float | None = None
    market_league_avg_margin: float | None = None
    market_league_bookmaker_count_avg: float | None = None
    market_league_closing_line_accuracy: float | None = None
    market_league_efficiency_score: float | None = None
    market_league_exchange_available: bool | None = None
    market_league_odds_variance: float | None = None
    market_league_pinnacle_coverage: bool | None = None
    market_league_sharp_coverage: float | None = None
    market_league_steam_frequency: float | None = None
    market_league_tier: int | None = None
    market_league_total_liquidity: float | None = None
    market_maturity_score: float | None = None
    market_max_min_spread: float | None = None
    market_pinnacle_weight: float | None = None
    market_sharp_book_count: int | None = None
    market_sharp_consensus_away: float | None = None
    market_sharp_consensus_draw: float | None = None
    market_sharp_consensus_home: float | None = None
    market_sharp_soft_delta_away: float | None = None
    market_sharp_soft_delta_draw: float | None = None
    market_sharp_soft_delta_home: float | None = None
    market_sharp_vs_all_weight: float | None = None
    market_soft_consensus_away: float | None = None
    market_soft_consensus_draw: float | None = None
    market_soft_consensus_home: float | None = None
    market_weighted_consensus_home: float | None = None

    # -- Price Dynamics (PriceDynamicsFeatureCalculator) --
    price_acceleration_away_1h: float | None = None
    price_acceleration_away_6h: float | None = None
    price_acceleration_draw_1h: float | None = None
    price_acceleration_draw_6h: float | None = None
    price_acceleration_home_1h: float | None = None
    price_acceleration_home_6h: float | None = None
    price_asian_leads_european: bool | None = None
    price_bet365_lag: float | None = None
    price_book_fragmentation: float | None = None
    price_books_in_sync: float | None = None
    price_market_maker_spread: float | None = None
    price_max_single_move_away: float | None = None
    price_max_single_move_draw: float | None = None
    price_max_single_move_home: float | None = None
    price_path_smoothness: float | None = None
    price_pinnacle_lead_time: float | None = None
    price_sharp_soft_spread_current: float | None = None
    price_steam_bookmaker_sync: int | None = None
    price_steam_detected: bool | None = None
    price_steam_direction: int | None = None
    price_steam_magnitude: float | None = None
    price_steam_recovery: float | None = None
    price_steam_timing: float | None = None
    price_velocity_away_10m: float | None = None
    price_velocity_away_12h: float | None = None
    price_velocity_away_24h: float | None = None
    price_velocity_away_30m: float | None = None
    price_velocity_away_6h: float | None = None
    price_velocity_away_90m: float | None = None
    price_velocity_draw_10m: float | None = None
    price_velocity_draw_12h: float | None = None
    price_velocity_draw_24h: float | None = None
    price_velocity_draw_30m: float | None = None
    price_velocity_draw_6h: float | None = None
    price_velocity_draw_90m: float | None = None
    price_velocity_home_10m: float | None = None
    price_velocity_home_12h: float | None = None
    price_velocity_home_24h: float | None = None
    price_velocity_home_30m: float | None = None
    price_velocity_home_6h: float | None = None
    price_velocity_home_90m: float | None = None
    price_volatility_away_24h: float | None = None
    price_volatility_draw_24h: float | None = None
    price_volatility_home_24h: float | None = None
    price_volatility_ratio: float | None = None

    # -- Promoted Team (PromotedTeamFeatureCalculator) --
    away_decay_weighted_goals_against: float | None = None
    away_decay_weighted_goals_for: float | None = None
    away_decay_weighted_ppg: float | None = None
    away_decay_weighted_xg_against: float | None = None
    away_decay_weighted_xg_for: float | None = None
    away_history_depth_last1: int | None = None
    away_history_depth_last3: int | None = None
    away_history_depth_last5: int | None = None
    away_insufficient_data_flag: bool | None = None
    away_is_promoted_team: bool | None = None
    away_league_adjusted_attack: float | None = None
    away_league_adjusted_defense: float | None = None
    away_league_normalized_attack: float | None = None
    away_preseason_form: float | None = None
    away_preseason_goals_per_game: float | None = None
    away_preseason_xg_avg: float | None = None
    away_prior_goals_against_avg: float | None = None
    away_prior_goals_for_avg: float | None = None
    away_prior_league_position: int | None = None
    away_prior_ppg: float | None = None
    away_prior_xg_attack: float | None = None
    away_prior_xg_defense: float | None = None
    away_relative_league_difficulty: float | None = None
    away_squad_turnover_rate: float | None = None
    away_squad_xg_aggregate: float | None = None
    away_style_pc1: float | None = None
    away_style_pc2: float | None = None
    away_total_history_depth: int | None = None
    games_since_season_start: int | None = None
    home_decay_weighted_goals_against: float | None = None
    home_decay_weighted_goals_for: float | None = None
    home_decay_weighted_ppg: float | None = None
    home_decay_weighted_xg_against: float | None = None
    home_decay_weighted_xg_for: float | None = None
    home_history_depth_last1: int | None = None
    home_history_depth_last3: int | None = None
    home_history_depth_last5: int | None = None
    home_insufficient_data_flag: bool | None = None
    home_is_promoted_team: bool | None = None
    home_league_adjusted_attack: float | None = None
    home_league_adjusted_defense: float | None = None
    home_league_normalized_attack: float | None = None
    home_preseason_form: float | None = None
    home_preseason_goals_per_game: float | None = None
    home_preseason_xg_avg: float | None = None
    home_prior_goals_against_avg: float | None = None
    home_prior_goals_for_avg: float | None = None
    home_prior_league_position: int | None = None
    home_prior_ppg: float | None = None
    home_prior_xg_attack: float | None = None
    home_prior_xg_defense: float | None = None
    home_relative_league_difficulty: float | None = None
    home_squad_turnover_rate: float | None = None
    home_squad_xg_aggregate: float | None = None
    home_style_pc1: float | None = None
    home_style_pc2: float | None = None
    home_total_history_depth: int | None = None

    # -- Synthetic xG (SyntheticXGFeatureCalculator) --
    synthetic_big_chance_conversion_away: float | None = None
    synthetic_big_chance_conversion_home: float | None = None
    synthetic_xg_away: float | None = None
    synthetic_xg_confidence: float | None = None
    synthetic_xg_diff: float | None = None
    synthetic_xg_home: float | None = None
    synthetic_xg_last5_away: float | None = None
    synthetic_xg_last5_home: float | None = None
    synthetic_xg_model_residual_away: float | None = None
    synthetic_xg_model_residual_home: float | None = None
    synthetic_xg_per_shot_away: float | None = None
    synthetic_xg_per_shot_home: float | None = None
    synthetic_xg_season_away: float | None = None
    synthetic_xg_season_home: float | None = None
    synthetic_xg_source: int | None = None
    synthetic_xg_total: float | None = None
    synthetic_xg_vs_goals_away: float | None = None
    synthetic_xg_vs_goals_home: float | None = None

    # -- Schedule Fatigue (ScheduleFatigueFeatureCalculator) --
    away_away_travel_km: float | None = None
    away_congestion_score_14d: float | None = None
    away_continental_hangover: float | None = None
    away_fixture_pile_up: bool | None = None
    away_games_last_21d: int | None = None
    away_midweek_european: bool | None = None
    away_played_continental_last_week: bool | None = None
    away_schedule_days_rest: int | None = None
    away_schedule_games_14d: int | None = None
    away_short_rest: bool | None = None
    away_total_travel_14d: float | None = None
    away_travel_band: int | None = None
    away_travel_fatigue: float | None = None
    both_short_rest: bool | None = None
    home_away_travel_km: float | None = None
    home_congestion_score_14d: float | None = None
    home_continental_hangover: float | None = None
    home_fixture_pile_up: bool | None = None
    home_games_last_21d: int | None = None
    home_midweek_european: bool | None = None
    home_played_continental_last_week: bool | None = None
    home_schedule_days_rest: int | None = None
    home_schedule_games_14d: int | None = None
    home_short_rest: bool | None = None
    home_total_travel_14d: float | None = None
    home_travel_band: int | None = None
    home_travel_fatigue: float | None = None
    schedule_rest_diff: int | None = None

