"""API contracts: Pydantic schemas and VCR mocks for external APIs."""

import sys
from types import ModuleType
from typing import cast

from .canonical.canonical_mappings import (
    DATA_SOURCE_TO_SECRET,
    DATA_SOURCE_TO_VENUES,
    VENUE_TO_DATA_SOURCE,
    VENUE_TO_DATA_SOURCES,
    ContractSpec,
    DataSourceMapping,
    DataSourceRoute,
    get_data_sources_for_venue,
    get_required_secrets,
)

# ``canonical.crosscutting.alerting`` transitively triggers
# ``unified_api_contracts.internal`` via ``rules.py`` (KillSwitchScope) +
# downstream chain. ``internal/...`` imports back from this top-level
# facade (BetStatus, CanonicalFill, DefiAlertType, ...). Order matters:
# canonical_mappings → errors → domain → alerting (loads internal/).
from .canonical.crosscutting.alerting import (
    ALERT_CODES,
    ALERT_THRESHOLDS,
    LIVE_ALERT_RULES,
    AlertChannel,
    AlertCode,
    AlertRule,
    AlertSeverity,
    AlertThreshold,
    KillSwitchScope,
    ThresholdUnit,
    UnknownAlertCodeError,
    UnknownThresholdKeyError,
)
from .canonical.crosscutting.bar_boundary import (
    BAR_TIMEFRAME_SECONDS,
    BAR_TIMEFRAMES,
    BarBoundaryViolationError,
    BarTimeframe,
    assert_bar_boundary_contract,
    bar_window_for_close,
)
from .canonical.crosscutting.circuit_breaker import (
    BREAKER_RECOVERY_DEFAULTS,
    BreakerAction,
    BreakerConfig,
    BreakerFiredEvent,
    BreakerRecoveryMode,
    BreakerRecoveryRule,
    BreakerScope,
    BreakerTrigger,
    CircuitBreakerId,
    breaker_fired_event,
)
from .canonical.crosscutting.client_lifecycle_events import (
    ClientLifecycleEvent,
    ClientLifecycleKind,
    ClientQuarantinedEvent,
    ClientReadyEvent,
    QuarantineReason,
    ShardCapacityEvent,
    ShardRecommendedAction,
    VenueAuthStatus,
)
from .canonical.crosscutting.cme_polymarket_link import (
    CME_ROOT_TO_POLYMARKET_GROUP,
    LINKED_CME_ROOTS,
    linked_question_group,
)
from .canonical.crosscutting.defi import (
    CHAIN_WIRE_VALUE_OVERRIDES,
    ChainKind,
    to_canonical_chain_wire,
)
from .canonical.crosscutting.errors import (
    VENUE_ERROR_MAP,
    CanonicalAuthenticationError,
    CanonicalAuthorizationError,
    CanonicalContractExpiredError,
    CanonicalDuplicateOrderError,
    CanonicalError,
    CanonicalInstrumentHaltedError,
    CanonicalInsufficientBalanceError,
    CanonicalInsufficientMarginError,
    CanonicalInternalServerError,
    CanonicalInvalidRequestError,
    CanonicalMaintenanceModeError,
    CanonicalMarketClosedError,
    CanonicalNetworkError,
    CanonicalOrderRejectedError,
    CanonicalPositionLimitExceededError,
    CanonicalPriceBoundError,
    CanonicalRateLimitError,
    CanonicalSchemaError,
    CanonicalServiceUnavailableError,
    CanonicalSizeLimitError,
    CanonicalUnknownVenueError,
    DatabentoError,
    DefiAlertType,
    DefiErrorCode,
    ErrorAction,
    OracleDeviationError,
    OracleStaleError,
    RateLimitInfo,
    RateLimitResponse,
    UnsupportedCapabilityError,
    VenueErrorClassification,
    WebSocketCloseInfo,
    classify_venue_error,
)
from .canonical.crosscutting.execution import (
    BATCH_FILL_ALGO_TYPES,
    BENCHMARK_FILL_ALGO_TYPE,
    NORMAL_ALGO_TYPE,
    BatchExecutionMode,
)
from .canonical.crosscutting.experiment_registry import (
    ExperimentKind,
    ExperimentRunSpec,
    ExperimentStatus,
)
from .canonical.crosscutting.kill_switch import (
    KillSwitchArmedEvent,
    KillSwitchArmRequest,
    KillSwitchDisarmEvent,
    KillSwitchId,
    KillSwitchProvenance,
)

# Global Ledger SSOT — Phase 2 (shipped 2026-05-23). LedgerRow + 4 aliases + 5 StrEnums.
# NOTE: ledger AssetClass (fine-grained: spot_token/option/perp/lst/…) exposed as LedgerAssetClass
# to avoid name collision with the domain AssetClass (crypto/equity/fx/commodity/fixed_income).
# SSOT: codex/04-architecture/global-ledger-architecture.md
from .canonical.crosscutting.ledger import (
    CrossClientTransferForbiddenError,
    Direction,
    EventOrigin,
    EventType,
    InstructionLedger,
    LedgerRow,
    OptionRight,
    PassiveLedger,
    PricingLedger,
    TreasuryLedger,
    assert_no_cross_client_transfer,
)
from .canonical.crosscutting.ledger._enums import AssetClass as LedgerAssetClass
from .canonical.crosscutting.live_cluster_registry import (
    LIVE_CLUSTER_REGISTRY,
    LiveClusterDeploymentKind,
    LiveClusterSpec,
    get_clusters_for_env,
)
from .canonical.crosscutting.mvp_scope import (
    MVP_SCOPE,
    CeFiMvpRule,
    DeFiMvpRule,
    FeaturesModelsMvpStub,
    PredictionMvpRule,
    SportsMvpRule,
    TradFiMvpRule,
    is_mvp,
)
from .canonical.crosscutting.pipeline_mode import (
    _SPORTS_ENTITY_TO_PIPELINE_MODE,  # pyright: ignore[reportPrivateUsage]  # package-internal mapping, intentionally re-exported via __all__
    Cadence,
    Mode,
    PipelineMode,
    Transport,
    default_transport_for_source,
    is_batch,
    is_live,
    is_replay,
    mode_of,
    pipeline_mode_for_source,
    pipeline_mode_for_sports_entity,
    source_string_for,
    transport_of,
)
from .canonical.crosscutting.scenario_overlay import (
    SCENARIO_REGISTRY,
    BookSpoof,
    DropRows,
    EventDrop,
    EventDuplicate,
    GasSurge,
    LatencyInject,
    ManifestPhantom,
    OracleDeviate,
    OutcomeCategory,
    PriceShift,
    RejectFills,
    ScenarioApplicabilityFilter,
    ScenarioCategory,
    ScenarioMutationSpec,
    ScenarioOutcomeAssertion,
    ScenarioOutcomeResult,
    ScenarioOverlay,
    ScenarioOverlayLayer,
    ScenarioReport,
    StaleHold,
    register_scenario,
)
from .canonical.crosscutting.scheduler_registry import (
    SCHEDULER_REGISTRY,
    SchedulerSpec,
    SchedulerTargetKind,
    get_schedulers_for_env,
)
from .canonical.crosscutting.source_priority import (
    BATCH_CAPABLE_CEFI_VENUES,
    CEFI_LIVE_VENUES,
    MOCK_SOURCE,
    SOURCE_MODE_CAPABILITY,
    default_source,
    detect_dual_source_conflicts,
    emission_latency_ms_for_source,
    external_sources_for,
    get_all_sources_with_priority,
    get_primary_source,
    get_primary_source_with_latency,
    get_source_priority,
    has_source_priority,
    modes_for_source,
    read_with_source_priority,
    select_primary_available_source,
    source_required,
    source_supports,
    sources_supporting,
)
from .canonical.crosscutting.strategy_family import (
    STRATEGY_FAMILY_REGISTRY,
    StrategyFamily,
    StrategyFamilyId,
    family_for_archetype,
)
from .canonical.crosscutting.synthetic_generator import (
    SYNTHETIC_GENERATOR_REGISTRY,
    SyntheticDataDomain,
    SyntheticGeneratorId,
    SyntheticGeneratorSpec,
    SyntheticOutputManifest,
    SyntheticParams,
    SyntheticRealismAxis,
    SyntheticRunManifest,
    SyntheticShardLayout,
    SyntheticShardManifest,
    generators_for_archetype,
    get_generator_spec,
    register_generator,
)
from .canonical.crosscutting.transfer_events import (
    BusTransferType,
    TransferIntent,
    TransferResult,
    TransferResultStatus,
)
from .canonical.crosscutting.venue_thresholds import (
    VENUE_HEARTBEAT_THRESHOLDS,
    get_heartbeat_threshold,
)
from .canonical.domain import (
    BOOKMAKER_REGISTRY,
    ODDS_API_KEY_TO_VENUE,
    ODDS_API_KEY_TO_VENUE_CATEGORY,
    OHLCV_AGGREGATION,
    RISK_TYPE_CATEGORIES,
    SHARE_CLASS_BASE_ASSETS,
    VENUE_EXECUTION_REGISTRY,
    AccountVerificationLevel,
    AggregatedPosition,
    AlternativeDataSignal,
    AlternativeDataType,
    AntiDetectionLevel,
    ArbitrageMarket,
    ArbitrageOpportunity,
    ArbitrageStatus,
    AssetClass,
    BenchmarkType,
    BetExecution,
    BetOrder,
    BetRejectedError,
    BetSide,
    BetStatus,
    BettingSignal,
    BinanceWithdrawRequest,
    BinanceWithdrawResponse,
    BookLevel,
    BookmakerCategory,
    BookmakerInfo,
    BookmakerRegistry,
    BookmakerUnavailableError,
    BybitWithdrawRequest,
    BybitWithdrawResponse,
    CanonicalAccountSnapshot,
    CanonicalAccountState,
    CanonicalBalance,
    CanonicalBase,
    CanonicalBetMarket,
    CanonicalBetOrder,
    CanonicalBondData,
    CanonicalBookmakerMarket,
    CanonicalCdsSpread,
    CanonicalComboBet,
    CanonicalComboLeg,
    CanonicalComputeService,
    CanonicalDerivativeTicker,
    CanonicalFeatureRecord,
    CanonicalFee,
    CanonicalFill,
    CanonicalFixture,
    CanonicalFixtureEvent,
    CanonicalFixtureStatsDetail,
    CanonicalFundingRate,
    CanonicalFuturesContract,
    CanonicalInjury,
    CanonicalInstrument,
    CanonicalLeague,
    CanonicalLineup,
    CanonicalLiquidation,
    CanonicalLiquidationCluster,
    CanonicalMarginState,
    CanonicalMarketStateEvent,
    CanonicalOdds,
    CanonicalOhlcvBar,
    CanonicalOnChainMetric,
    CanonicalOptionsChainEntry,
    CanonicalOrder,
    CanonicalOrderAmendment,
    CanonicalOrderBook,
    CanonicalOrderRejection,
    CanonicalPlayer,
    CanonicalPlayerMatchStats,
    CanonicalPosition,
    CanonicalPredictionMarket,
    CanonicalProgressiveOdds,
    CanonicalProgressiveStats,
    CanonicalPullRequest,
    CanonicalReferee,
    CanonicalRepository,
    CanonicalSettlement,
    CanonicalSpread,
    CanonicalTeam,
    CanonicalTicker,
    CanonicalTrade,
    CanonicalVenue,
    CanonicalWebSocketLifecycle,
    CanonicalWorkflowRun,
    CanonicalYieldCurvePoint,
    CloudProvider,
    CloudTarget,
    CLVRecord,
    CoinbaseWithdrawRequest,
    CoinbaseWithdrawResponse,
    ComboLeg,
    ComboQuote,
    ComboStrategyType,
    CommissionModel,
    ComputeTarget,
    ComputeType,
    CredentialType,
    DarkPoolPrintRecord,
    DeFiAggregatedHealth,
    DeFiLPAggregatedMetrics,
    DeFiStakingAggregatedMetrics,
    DepositAddress,
    DepositRecord,
    EnvironmentTier,
    Erc20TransferCalldata,
    Erc20TransferFromCalldata,
    EthSendRawTransactionRequest,
    EthSendRawTransactionResponse,
    EthSendTransactionRequest,
    EthTransactionRequest,
    ExchangeFeeSchedule,
    ExecutionAlpha,
    ExecutionInstruction,
    ExecutionMethod,
    ExecutionRejectionCode,
    ExecutionRejectionEvent,
    ExecutionResult,
    ExecutionStatus,
    ExpectedValue,
    FeatureMetadata,
    FeeType,
    FixtureMapping,
    FixtureNotFoundError,
    FundingRateHistory,
    FuturesContractLifecyclePhase,
    HealthPingResponse,
    HttpRateLimitHeaders,
    InstructionType,
    InstrumentType,
    InsuranceFundState,
    InternalTransfer,
    LatencyComponent,
    LifecycleClass,
    LineupPlayer,
    LiveMatchState,
    LiveOddsUpdate,
    LongShortRatio,
    LPProtocolBreakdown,
    MappingRule,
    MarginType,
    MarketClosedError,
    MarketState,
    MarketStatus,
    MarketTrade,
    MatchPeriod,
    MultiLegInstrument,
    NetworkJitterMetric,
    NormalizedStrikeCoordinate,
    OddsChangedError,
    OddsFormat,
    OddsType,
    OhlcvAggregation,
    OKXWithdrawRequest,
    OKXWithdrawResponse,
    OpenInterestHistory,
    OperationType,
    OptionChainSnapshot,
    OptionsFlowRecord,
    OptionType,
    OrderBookSnapshot5,
    OrderLatencyRecord,
    OrderSide,
    OrderStatus,
    OrderType,
    OrphanDetector,
    OutcomeType,
    PlayerMapping,
    PortfolioGreeksSnapshot,
    PortfolioMarginAccount,
    PortfolioPnLAttribution,
    PortfolioView,
    PositionRisk,
    PredictionMarketCategory,
    PredictionMarketMapper,
    ProcessedOddsOutput,
    ProtocolHealthBreakdown,
    RiskCategory,
    RiskGroupSummary,
    RiskType,
    SatelliteObservation,
    ScalingMode,
    ScraperError,
    ScraperVersionMeta,
    SentimentScore,
    SettlementEvent,
    ShareClass,
    SignalSource,
    SourceControlProvider,
    Sport,
    SportsArbLeg,
    SportsArbPosition,
    SportsError,
    SpreadLeg,
    StakingProtocolBreakdown,
    SubAccount,
    TeamMapping,
    TimeInForce,
    UnderlyingGreeksBreakdown,
    UpbitWithdrawRequest,
    UpbitWithdrawResponse,
    VenueCategory,
    VenueExecutionProfile,
    VenuePositionBreakdown,
    VenueRateLimitSpec,
    VmPrefixSpec,
    VmQuotaShape,
    VolSmilePoint,
    VolSurface,
    VolSurfaceSlice,
    VolTermStructure,
    WebSocketConnectionClosed,
    WebSocketConnectionOpened,
    WebSocketEvent,
    WithdrawalRecord,
    classify_cloud_run_service,
    classify_experiment_run,
    classify_scheduled_job,
    classify_vm_name,
    get_expected_bookmakers,
    resolve_environment_from_env,
    resolve_environment_from_hostname,
)
from .canonical.domain.features import (
    get_required_inputs,
)
from .canonical.domain.strategy import (
    ClientRiskLimits,
    ClientsYaml,
    ClientsYamlEntry,
    MinBalancePerVenue,
)
from .canonical.partition_paths import (
    build_cefi_partition_path,
    build_defi_partition_path,
    build_prediction_partition_path,
    build_tradfi_partition_path,
    candidate_parquet_paths,
)
from .config.trading_validation import (
    CONFIG_REQUIRED_FIELDS,
    CONFIG_SCHEMA,
    INSTRUMENT_SCHEMA,
    OPTIONAL_CONFIG_FIELDS,
    REQUIRED_CONFIG_FIELDS,
    VALID_ALGORITHMS,
    VALID_ASSET_GROUPS,
    VALID_BOOK_TYPES,
    VALID_INSTRUCTION_TYPES,
    VALID_MODES,
    VALID_TIMEFRAMES,
)

# Importing the per-asset_group generator seeds populates SYNTHETIC_GENERATOR_REGISTRY at module load.
from .registry import generators as _generators_registry  # pyright: ignore[reportUnusedImport]

# Importing the per-asset_group registry seeds populates SCENARIO_REGISTRY at module load.
from .registry import scenarios as _scenarios_registry  # pyright: ignore[reportUnusedImport]

# Phase 5.A — per-archetype regression matrix derived from SCENARIO_REGISTRY at module load.
from .registry.scenario_archetype_matrix import (
    CUTOVER_ARCHETYPES,
    matrix_cell_count,
    scenarios_for_archetype,
)
from .registry.scenario_archetype_matrix import (
    MATRIX as SCENARIO_ARCHETYPE_MATRIX,
)

# isort: off
# These crosscutting / features imports must load AFTER ``.canonical.domain``
# so ``BetStatus`` is already in the top-level UAC namespace when the
# honest_coverage → registry → capability_declarations → _signal_broadcast
# → internal/__init__.py → execution_service/sports.py chain triggers
# ``from unified_api_contracts import BetStatus``. Pre-existing circular
# import — see ``canonical.crosscutting.alerting`` comment block above.
from .canonical.crosscutting.honest_coverage import (
    BUNDLED_DATA_TYPES,
    CaptureStatusCounts,
    DATA_TYPE_TO_CLUSTER_REGISTRY,
    EMPTY_CONFIRMED_REASONS,
    EVENT_CONTRACT_ROOT_CLUSTERS,
    EXPECTED_EMPTY_REASON_PREFIX,
    FUTURES_CHAIN_BUCKETS,
    EmptyConfirmedReason,
    EmptyFromLiveInstrumentError,
    LegacyBlankErrorReasonError,
    RecordFailedReason,
    compute_honest_coverage,
    futures_expiry_bucket,
    get_active_es_options_clusters_for_date,
    was_instrument_alive,
)
from .canonical.crosscutting.instruments_preflight_dag import (
    PreflightFailed,
    PreflightOK,
    PreflightResult,
    PreflightTrigger,
    validate_preflight_for_trigger,
)
from .canonical.crosscutting.manifest_schema import (
    EXPECTED_WINDOW_COMPLETENESS_FRACTION_COLUMN,
    LAST_EMISSION_DECISION_AT_COLUMN,
    MANIFEST_SCHEMA_VERSION_V8,
    PIPELINE_MODE_COLUMN,
    PIPELINE_MODE_NOT_NULL_SINCE,
    READER_FALLBACK_WINDOW_DAYS,
    SERVICE_EMISSION_STATE_COLUMN,
    V8_COLUMN_DEFAULTS,
    V8_NEW_COLUMNS,
)
from .canonical.crosscutting.service_emission_policy import (
    EmissionLifecycleEvent,
    ServiceEmissionPolicy,
    get_emission_policy,
    is_emission_policy_declared,
    next_state,
    policy_is_alert,
    policy_is_publish_row,
)
from .canonical.crosscutting.market_session import (
    MarketSession,
    SessionPhase,
    classify_session,
)
from .canonical.crosscutting.service_emission_state import (
    SERVICE_EMISSION_STATES,
    ManifestRowBlockedError,
    ServiceEmissionStateEnum,
)
from .canonical.gcs_paths import AssetGroup

# isort: on
from .canonical.asset_group_registry import (
    AssetGroupInventory as AssetGroupInventory,
)
from .canonical.crosscutting.analytics import (
    CorrelationRegimeChange as CorrelationRegimeChange,
)
from .canonical.crosscutting.analytics import (
    CrossAssetCorrelationMatrix as CrossAssetCorrelationMatrix,
)
from .canonical.crosscutting.analytics import (
    FactorAttributionModel as FactorAttributionModel,
)
from .canonical.crosscutting.analytics import (
    FactorAttributionRecord as FactorAttributionRecord,
)
from .canonical.crosscutting.data_locality import (
    DataLocalityResult as DataLocalityResult,
)
from .canonical.crosscutting.defi import (
    LendingProtocol as LendingProtocol,
)
from .canonical.crosscutting.dependency.health_policy import (
    DependencyClass as DependencyClass,
)
from .canonical.crosscutting.dependency.health_policy import (
    DependencyHealthPolicy as DependencyHealthPolicy,
)
from .canonical.crosscutting.deployment.errors import (
    ManifestShaDriftError as ManifestShaDriftError,
)
from .canonical.crosscutting.incident.action import (
    ActionProvenance as ActionProvenance,
)
from .canonical.crosscutting.incident.action import (
    ActionStatus as ActionStatus,
)
from .canonical.crosscutting.incident.action import (
    ActionType as ActionType,
)
from .canonical.crosscutting.incident.action import (
    AgentActionEvent as AgentActionEvent,
)
from .canonical.crosscutting.incident.action import (
    RecoveryVerificationResult as RecoveryVerificationResult,
)
from .canonical.crosscutting.incident.envelope import (
    IncidentEnvelope as IncidentEnvelope,
)
from .canonical.crosscutting.incident.evidence import (
    IncidentEvidence as IncidentEvidence,
)
from .canonical.crosscutting.incident.overrides import (
    ImmediateSev0Override as ImmediateSev0Override,
)
from .canonical.crosscutting.incident.recovery_audit import (
    RecoveryAuditSignoff as RecoveryAuditSignoff,
)
from .canonical.crosscutting.incident.recovery_audit import (
    SignoffVerdict as SignoffVerdict,
)
from .canonical.crosscutting.incident.sla import (
    AuditAckSLAPolicy as AuditAckSLAPolicy,
)
from .canonical.crosscutting.incident.state import (
    IllegalIncidentTransitionError as IllegalIncidentTransitionError,
)
from .canonical.crosscutting.incident.state import (
    IncidentState as IncidentState,
)
from .canonical.crosscutting.instruments_preflight_dag import (
    ManifestReader as ManifestReader,
)
from .canonical.crosscutting.instruments_preflight_dag import (
    PreflightRequirement as PreflightRequirement,
)
from .canonical.crosscutting.market_session import (
    SessionWindow as SessionWindow,
)
from .canonical.crosscutting.risk.drawdown import (
    DrawdownThresholdKind as DrawdownThresholdKind,
)
from .canonical.crosscutting.risk.drawdown import (
    ExpectedDrawdownModel as ExpectedDrawdownModel,
)
from .canonical.crosscutting.risk.drawdown import (
    ExpectedDrawdownModelBasis as ExpectedDrawdownModelBasis,
)
from .canonical.crosscutting.risk.drawdown import (
    ResponsePolicy as ResponsePolicy,
)
from .canonical.crosscutting.risk.drawdown import (
    RiskThresholds as RiskThresholds,
)
from .canonical.crosscutting.risk.investigation import (
    DrawdownInvestigationReport as DrawdownInvestigationReport,
)
from .canonical.crosscutting.risk.liquidation import (
    LiquidationInvestigationReport as LiquidationInvestigationReport,
)
from .canonical.crosscutting.risk_rule._base import (
    RiskRule as RiskRule,
)
from .canonical.crosscutting.risk_rule._enums import (
    RiskRuleConsequence as RiskRuleConsequence,
)
from .canonical.crosscutting.risk_rule._enums import (
    RiskRuleId as RiskRuleId,
)
from .canonical.crosscutting.risk_rule._enums import (
    RiskRuleScope as RiskRuleScope,
)
from .canonical.crosscutting.risk_rule._events import (
    RiskRuleFiredEvent as RiskRuleFiredEvent,
)
from .canonical.crosscutting.risk_rule._triggers import (
    BinaryEventTrigger as BinaryEventTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    CapitalAtRiskCeilingTrigger as CapitalAtRiskCeilingTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    CounterpartyRatioCapTrigger as CounterpartyRatioCapTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    FundingCostCeilingTrigger as FundingCostCeilingTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    GasBudgetTrigger as GasBudgetTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxConcentrationTrigger as MaxConcentrationTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxCorrelationTrigger as MaxCorrelationTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxDailyLossTrigger as MaxDailyLossTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxDrawdownTrigger as MaxDrawdownTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxGrossExposureTrigger as MaxGrossExposureTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxLeverageTrigger as MaxLeverageTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxNetExposureTrigger as MaxNetExposureTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxOITrigger as MaxOITrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    MaxPositionSizeTrigger as MaxPositionSizeTrigger,
)
from .canonical.crosscutting.risk_rule._triggers import (
    SlippageBudgetTrigger as SlippageBudgetTrigger,
)
from .canonical.crosscutting.source_priority import (
    DivergenceKind as DivergenceKind,
)
from .canonical.crosscutting.venue_thresholds import (
    VenueTestnetEndpoints as VenueTestnetEndpoints,
)
from .canonical.domain.derivatives.tradfi_etfs import (
    ETFMetadata as ETFMetadata,
)
from .canonical.domain.derivatives.tradfi_roots import (
    RootMetadata as RootMetadata,
)
from .canonical.domain.features.registry import (
    FeatureFamily as FeatureFamily,
)
from .canonical.domain.features.registry import (
    FeatureGroupFamilyCollisionError as FeatureGroupFamilyCollisionError,
)
from .canonical.domain.features.required_inputs import (
    InputReq as InputReq,
)
from .canonical.domain.instruments_catalog import (
    CatalogRow as CatalogRow,
)
from .canonical.domain.instruments_catalog import (
    InstrumentCatalogReader as InstrumentCatalogReader,
)
from .canonical.domain.instruments_catalog import (
    list_instruments as list_instruments,
)
from .canonical.domain.instruments_catalog import (
    list_not_yet_listed_cefi as list_not_yet_listed_cefi,
)
from .canonical.domain.instruments_catalog import (
    register_catalog_reader as register_catalog_reader,
)
from .canonical.domain.prediction.prediction_mapping import (
    PredictionMarketCrossVenueMapping as PredictionMarketCrossVenueMapping,
)
from .canonical.domain.predictions.canonical_groups import (
    CanonicalGroupMetadata as CanonicalGroupMetadata,
)
from .canonical.domain.predictions.canonical_groups import (
    CanonicalQuestionGroup as CanonicalQuestionGroup,
)
from .canonical.domain.predictions.lifecycle import (
    MarketLifecycle as MarketLifecycle,
)
from .canonical.domain.sports.feature_upstream import (
    CoverageResult as CoverageResult,
)
from .canonical.domain.sports.feature_upstream import (
    UpstreamReq as UpstreamReq,
)
from .canonical.domain.sports.fixture_lifecycle import (
    CanonicalFixtureOutcomes as CanonicalFixtureOutcomes,
)
from .canonical.domain.sports.fixture_lifecycle import (
    CanonicalFixtureSchedule as CanonicalFixtureSchedule,
)
from .canonical.domain.sports.fixture_lifecycle import (
    MatchLifecycle as MatchLifecycle,
)
from .canonical.domain.sports.fixture_lifecycle import (
    MatchResult as MatchResult,
)
from .canonical.domain.sports.fixture_status import (
    MatchStatus as MatchStatus,
)
from .canonical.domain.sports.gcs_paths import (
    SportsPathLayout as SportsPathLayout,
)
from .canonical.domain.sports.injury import (
    AbsenceType as AbsenceType,
)
from .canonical.domain.sports.league_data import (
    SPORTS_DATA_TYPE_TO_SOURCE as SPORTS_DATA_TYPE_TO_SOURCE,
)
from .canonical.domain.sports.league_data import (
    get_league as get_league,
)
from .canonical.domain.sports.league_data import (
    get_league_by_api_football_id as get_league_by_api_football_id,
)
from .canonical.domain.sports.league_data import (
    get_league_fixture_calendar as get_league_fixture_calendar,
)
from .canonical.domain.sports.league_data import (
    is_in_known_gap as is_in_known_gap,
)
from .canonical.domain.sports.league_registry import (
    LeagueClassification as LeagueClassification,
)
from .canonical.domain.sports.league_registry import (
    LeagueClassificationRegistry as LeagueClassificationRegistry,
)
from .canonical.domain.sports.league_registry import (
    LeagueClassificationType as LeagueClassificationType,
)
from .canonical.domain.sports.league_registry import (
    LeagueDefinition as LeagueDefinition,
)
from .canonical.domain.sports.round_names import (
    RoundMatch as RoundMatch,
)
from .canonical.domain.sports.season_dates import (
    SeasonBoundary as SeasonBoundary,
)
from .canonical.domain.sports.season_dates import (
    footystats_season_status_for_day as footystats_season_status_for_day,
)
from .canonical.domain.sports.transfer_windows import (
    TransferWindowPeriod as TransferWindowPeriod,
)
from .canonical.gcs_paths import (
    BucketKind as BucketKind,
)
from .external.aster.schemas import AsterExchangeInfo
from .external.betfair import (
    BetfairCurrentOrderSummary,
    BetfairListCurrentOrdersResponse,
    BetfairMarketCatalogue,
)
from .external.betfair.schemas import BetfairRunnerCatalog
from .external.binance import (
    BinanceLiquidationOrder,
    BinanceMarkPriceUpdate,
    BinanceOrderBook,
    BinanceTicker,
    BinanceTrade,
)
from .external.binance.market_schemas import (
    BinanceFuturesExchangeInfo,
    BinanceInstrumentInfo,
    BinanceOptionInstrumentInfo,
)
from .external.bybit.schemas import (
    BybitInstrumentInfo,
    BybitInstrumentsResponse,
    BybitLiquidationOrder,
    BybitOrderBook,
    BybitTicker,
)
from .external.ccxt.schemas import (
    CcxtAggTrade,
    CcxtFundingRate,
    CcxtMarket,
    CcxtOhlcv,
    CcxtOpenInterest,
    CcxtOrderBook,
    CcxtTicker,
    CcxtTrade,
)
from .external.coinbase.schemas import (
    CoinbaseOrderBook,
    CoinbaseProductInfo,
    CoinbaseProductsResponse,
    CoinbaseTicker,
    CoinbaseTrade,
)
from .external.deribit.schemas import (
    DeribitAccountSummaryResponse,
    DeribitCancelResponse,
    DeribitGetInstrumentResponse,
    DeribitGetInstrumentsResponse,
    DeribitInstrumentInfoFull,
    DeribitInstrumentsResponse,
    DeribitOpenOrdersResponse,
    DeribitOrderResponse,
    DeribitOrderStateResponse,
    DeribitPositionsResponse,
    DeribitTickerResponse,
)
from .external.hyperliquid.schemas import (
    HyperliquidAssetInfo,
    HyperliquidFill,
    HyperliquidMeta,
    HyperliquidOpenOrder,
    HyperliquidPosition,
    HyperliquidUserState,
)
from .external.ibkr import (
    IBKRAccountValue,
    IBKRContractDetails,
    IBKRCorporateAction,
    IBKRPosition,
)
from .external.kalshi.schemas import (
    KalshiMarket,
    KalshiOrderBook,
    KalshiTrade,
)
from .external.massive.normalize import (
    normalize_massive_equity,
    normalize_massive_futures,
    normalize_massive_fx,
    normalize_massive_index,
    normalize_massive_option,
)
from .external.massive.schemas import (
    MassiveFuturesContract,
    MassiveFuturesContractsResponse,
    MassiveFuturesProduct,
    MassiveFuturesProductsResponse,
    MassiveOptionContract,
    MassiveOptionContractsResponse,
    MassiveTicker,
    MassiveTickersResponse,
)
from .external.okx.schemas import (
    OKXFundingRate,
    OKXInstrumentInfo,
    OKXInstrumentsResponse,
    OKXLiquidationOrder,
    OKXMarkPrice,
    OKXOrderBook,
    OKXTicker,
)
from .external.polygon.schemas import (
    PolygonOptionContract,
    PolygonOptionContractsResponse,
    PolygonTicker,
    PolygonTickersResponse,
)
from .external.polymarket import (
    PolymarketGammaMarket,
    PolymarketPosition,
)
from .external.polymarket.arb_schemas import (
    BucketMarket,
    CrossVenueArbLeg,
    CrossVenueArbSignal,
    CrossVenueLink,
    NegRiskArbSignal,
    NegRiskBucket,
    PredictionMarketUniverse,
    ProbabilityBucket,
    SportsbookLink,
)
from .external.protocol_sdks.schemas import (
    AaveBorrowParams,
    AaveDepositParams,
    AaveFlashLoanParams,
    AaveRepayParams,
    AaveV3ReserveData,
    AaveV3UserAccountData,
    AaveV3UserReserveData,
    CompoundV3MarketInfo,
    CompoundV3UserPosition,
    CurveDepositParams,
    CurveSwapParams,
    CurveWithdrawParams,
    EtherFiStakeResponse,
    EtherFiUnstakeResponse,
    EulerBorrowParams,
    EulerDepositParams,
    EulerRepayParams,
    EulerUserPosition,
    EulerVaultData,
    FluidBorrowParams,
    FluidDepositParams,
    FluidRepayParams,
    LidoRequestWithdrawalsParams,
    LidoSubmitParams,
    LidoSubmitResponse,
    LidoWstEthWrapResponse,
    MorphoBorrowParams,
    MorphoFlashLoanParams,
    MorphoMarketParams,
    MorphoRepayParams,
    MorphoSupplyParams,
    MorphoUserPosition,
    UniswapV3PoolStateResponse,
    UniswapV3QuoteResponse,
    UniswapV3SwapTxReceipt,
)
from .external.tardis.schemas import (
    TardisExchangeDetail,
    TardisInstrumentDetail,
)
from .external.upbit.schemas import (
    UpbitBalanceQueryResponse,
    UpbitTicker,
)
from .internal.domain.client_reporting import FundNAVSnapshot
from .internal.domain.fund_administration import (
    AllocationExecutionStatus,
    AllocatorCashAccountView,
    AllocatorRedemption,
    AllocatorSubscription,
    ApproveSubscriptionRequest,
    CashAccountMovement,
    FundAllocation,
    FundTransferContext,
    ProcessRedemptionRequest,
    RebalanceRequest,
    RedeemRequest,
    RedemptionStatus,
    RejectRequest,
    SubscribeRequest,
    SubscriptionStatus,
)
from .internal.reference.canonical_id_builder import (
    build_combo_id,
    build_instrument_id,
)
from .internal.reference.ticker_registry import (
    EXCHANGE_BY_TICKER,
    UNDERLYING_NORMALIZATION,
    normalize_underlying,
    resolve_exchange,
)
from .internal.reporting import FeeStructure
from .internal.schemas.contracts import (
    CEFI_FUTURES_CHAIN_TRADES,
    CEFI_OPTIONS_CHAIN_TRADES,
    CEFI_PERPETUAL_BOOK_SNAPSHOT_5,
    CEFI_PERPETUAL_DERIVATIVE_TICKER,
    CEFI_PERPETUAL_LIQUIDATIONS,
    CEFI_PERPETUAL_QUOTES,
    CEFI_PERPETUAL_TRADES,
    CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5,
    CEFI_SPOT_PAIR_TRADES,
    CONTRACT_REGISTRY,
    DEFI_AAVE_V3_LENDING_INDICES,
    DEFI_DEX_POOL_DEX_POOL_STATE,
    DEFI_DEX_POOL_DEX_POOL_SWAPS,
    DEFI_LENDING_FLASH_LOAN_EVENTS,
    DEFI_LENDING_INDICES_MARKET_ID,
    DEFI_LENDING_LIQUIDATION_EVENTS,
    DEFI_LENDING_LIQUIDATIONS,
    DEFI_LENDING_POSITION_DATA,
    DEFI_LENDING_POSITION_LENDING_INDICES,
    DEFI_LST_LST_RATES,
    DEFI_PERPETUAL_PERP_FUNDING,
    DEFI_POOL_DEX_POOL_SWAPS,
    DEFI_SPOT_ASSET_BRIDGE_EVENTS,
    DEFI_SPOT_ASSET_GAS_FEES,
    DEFI_SPOT_ASSET_GOVERNANCE_EVENTS,
    DEFI_SPOT_ASSET_MEV_EVENTS,
    DEFI_SPOT_ASSET_ORACLE_PRICES,
    DEFI_SPOT_ASSET_TOKEN_TRANSFERS,
    DEFI_STAKING_EIGENLAYER_REWARDS,
    DEFI_STAKING_STAKING_YIELDS,
    DEFI_STAKING_YIELD_SNAPSHOTS,
    TRADFI_EQUITY_OHLCV_1M,
    TRADFI_EQUITY_TRADES,
    TRADFI_FUTURE_OHLCV_1M,
    TRADFI_FUTURE_TRADES,
    TRADFI_INDEX_TRADES,
    TRADFI_OPTIONS_CHAIN_TRADES,
    VENUE_CONTRACT_OVERRIDES,
    ColumnSpec,
    RowSchemaValidationError,
    SchemaContract,
    SchemaContractNotFoundError,
    Violation,
    lookup_contract,
    validate_dataframe,
    validate_row_df,
)
from .internal.strategy_directives import ArchetypeAllocationDirective
from .internal.strategy_pnl_stream import StrategyPnlStreamEvent
from .normalize_utils import american_to_decimal, decimal_to_american
from .registry import (
    ALL_VENUES,
    BUNDLE_INSTRUMENT_TYPE_BY_AG_AND_LEAF,
    CEFI_ACCEPTED_QUOTE_ASSETS,
    CEFI_BASE_ASSET_UNIVERSE,
    CEFI_BASE_ASSETS,
    CEFI_OPTIONS_UNDERLYINGS,
    CLOB_VENUES,
    CME_MONTH_CODES,
    DATA_TYPES_BY_ASSET_GROUP,
    DEFI_INSTRUMENTS,
    DEFI_INSTRUMENTS_NOT_YET_COLLECTED,
    DEFI_LENDING_ASSETS,
    DEFI_MAJOR_ASSET_ADDRESS_LIST,
    DEFI_MAJOR_ASSET_ADDRESSES,
    DEFI_MAJOR_ASSET_SYMBOLS,
    DEPRECATED_DEFI_GHOST_VENUE_NAMES,
    DEX_VENUE_KEYWORDS,
    DEX_VENUES,
    EMPTY_OR_DEPRECATED_DEFI_VENUES,
    ENDPOINT_REGISTRY,
    EXPECTED_COVERAGE_BY_ASSET_GROUP,
    FX_SPOT_PAIRS,
    GRAIN_BUNDLE_BY_UNDERLYING,
    GRAIN_LEAF,
    INSTRUMENT_GRAIN_BY_AG_AND_INSTRUMENT_TYPE,
    INSTRUMENT_TYPE_FOLDER_MAP,
    INSTRUMENT_TYPES_BY_VENUE,
    KNOWN_ETFS,
    OKX_FUTURES,
    OKX_SPOT,
    POSSIBLE_MANIFEST_ASSET_GROUPS,
    PROCESSED_REQUIRES_RAW,
    QUARTERLY_MONTHS,
    SPORTS_VENUES,
    TARDIS_FREE_ROLLING_WINDOW_DAYS,
    TIMEFRAMES,
    TRADFI_DATABENTO_INSTRUMENTS,
    TRADFI_EQUITIES,
    TRADFI_FUTURES,
    TRADFI_INSTRUMENTS,
    TRADFI_TICKER_UNIVERSE,
    VALID_DATA_TYPES_BY_AG_AND_INSTRUMENT_TYPE,
    VENUE_CATEGORY_MAP,
    VENUE_COORDINATES,
    VENUE_DATA_AVAILABILITY,
    VENUE_TO_ASSET_GROUP,
    VENUES_BY_ASSET_GROUP,
    ZERO_ALPHA_VENUES,
    CatalogueLeaf,
    DataTypeConfig,
    EndpointSpec,
    ExchangeInstrumentConfig,
    PossibleManifestSpec,
    ProviderDataAvailability,
    ShardKey,
    VenueCoordinates,
    VenueMapping,
    bundle_instrument_type_for_leaf,
    canonical_path_templates,
    enumerate_possible_shard_keys,
    external_batch_sources_for_asset_group,
    free_dates_in_range,
    get_databento_symbols_for_venue,
    get_expected_data_types_for_venue,
    get_expected_instruments_for_venue,
    get_possible_manifest_spec,
    get_provider_availability,
    get_valid_data_types_for_venue,
    get_venue_coordinates,
    get_venue_data_type_start_date,
    grain_for_instrument_type,
    is_per_instrument_shard_data_type,
    is_tardis_free_date,
    is_valid_shard_key,
    needs_candle_processing,
    non_trading_day_reason,
    resolve_data_type_for_feature_group,
    valid_data_types_for_instrument_type,
    validate_data_type_for_venue,
    venue_has_no_expected_defi_coverage,
)
from .registry import (
    is_expected as is_expected,
)
from .signal_broadcast import (
    COUNTERPARTY_ENTITLEMENTS as COUNTERPARTY_ENTITLEMENTS,
)
from .signal_broadcast import (
    COUNTERPARTY_REGISTRY as COUNTERPARTY_REGISTRY,
)
from .signal_broadcast import (
    AckSource as AckSource,
)
from .signal_broadcast import (
    Counterparty as Counterparty,
)
from .signal_broadcast import (
    CounterpartyEntitlement as CounterpartyEntitlement,
)
from .signal_broadcast import (
    CounterpartyEntitlementProfile as CounterpartyEntitlementProfile,
)
from .signal_broadcast import (
    CounterpartyStatus as CounterpartyStatus,
)
from .signal_broadcast import (
    DeliveryAttempt as DeliveryAttempt,
)
from .signal_broadcast import (
    DeliveryStatus as DeliveryStatus,
)
from .signal_broadcast import (
    DirectionalIntent as DirectionalIntent,
)
from .signal_broadcast import (
    PayloadDepth as PayloadDepth,
)
from .signal_broadcast import (
    RateLimitConfig as RateLimitConfig,
)
from .signal_broadcast import (
    RestPullDeliveryConfig as RestPullDeliveryConfig,
)
from .signal_broadcast import (
    SchemaDepth as SchemaDepth,
)
from .signal_broadcast import (
    SignalAcknowledgement as SignalAcknowledgement,
)
from .signal_broadcast import (
    SignalEmission as SignalEmission,
)
from .signal_broadcast import (
    SignalPayload as SignalPayload,
)
from .signal_broadcast import (
    SignalPayloadMinimal as SignalPayloadMinimal,
)
from .signal_broadcast import (
    SignalPayloadRich as SignalPayloadRich,
)
from .signal_broadcast import (
    SignalPayloadStandard as SignalPayloadStandard,
)
from .signal_broadcast import (
    StrategySignalAcknowledged as StrategySignalAcknowledged,
)
from .signal_broadcast import (
    StrategySignalEmittedExternal as StrategySignalEmittedExternal,
)
from .signal_broadcast import (
    WebhookDeliveryConfig as WebhookDeliveryConfig,
)
from .signal_broadcast import (
    active_counterparties as active_counterparties,
)
from .signal_broadcast import (
    counterparty_for as counterparty_for,
)
from .signal_broadcast import (
    entitled_slots_for as entitled_slots_for,
)
from .signal_broadcast import (
    entitlements_for as entitlements_for,
)
from .sports import (
    BUNDESLIGA_TEAM_ALIASES as BUNDESLIGA_TEAM_ALIASES,
)
from .sports import (
    CANONICAL_TO_ODDS_API_BUNDESLIGA as CANONICAL_TO_ODDS_API_BUNDESLIGA,
)
from .sports import (
    CANONICAL_TO_ODDS_API_EPL as CANONICAL_TO_ODDS_API_EPL,
)
from .sports import (
    CANONICAL_TO_UNDERSTAT_EPL as CANONICAL_TO_UNDERSTAT_EPL,
)
from .sports import (
    EPL_TEAM_ALIASES as EPL_TEAM_ALIASES,
)
from .sports import (
    get_expected_leagues_for_source as get_expected_leagues_for_source,
)
from .sports import (
    get_prediction_leagues as get_prediction_leagues,
)

__all__ = [
    "ALERT_CODES",
    "ALERT_THRESHOLDS",
    "ALL_VENUES",
    "BAR_TIMEFRAMES",
    "BAR_TIMEFRAME_SECONDS",
    "BOOKMAKER_REGISTRY",
    "BREAKER_RECOVERY_DEFAULTS",
    "BUNDESLIGA_TEAM_ALIASES",
    "BUNDLED_DATA_TYPES",
    "CaptureStatusCounts",
    "compute_honest_coverage",
    "was_instrument_alive",
    "futures_expiry_bucket",
    "get_active_es_options_clusters_for_date",
    "CANONICAL_TO_ODDS_API_BUNDESLIGA",
    "CANONICAL_TO_ODDS_API_EPL",
    "CANONICAL_TO_UNDERSTAT_EPL",
    "CEFI_ACCEPTED_QUOTE_ASSETS",
    "CEFI_BASE_ASSETS",
    "CEFI_BASE_ASSET_UNIVERSE",
    "CEFI_FUTURES_CHAIN_TRADES",
    "CEFI_OPTIONS_CHAIN_TRADES",
    "CEFI_OPTIONS_UNDERLYINGS",
    "CEFI_PERPETUAL_BOOK_SNAPSHOT_5",
    "CEFI_PERPETUAL_DERIVATIVE_TICKER",
    "CEFI_PERPETUAL_LIQUIDATIONS",
    "CEFI_PERPETUAL_QUOTES",
    "CEFI_PERPETUAL_TRADES",
    "CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5",
    "CEFI_SPOT_PAIR_TRADES",
    "CLOB_VENUES",
    "CME_MONTH_CODES",
    "CME_ROOT_TO_POLYMARKET_GROUP",
    "CONFIG_REQUIRED_FIELDS",
    "CONFIG_SCHEMA",
    "CONTRACT_REGISTRY",
    "COUNTERPARTY_ENTITLEMENTS",
    "COUNTERPARTY_REGISTRY",
    "CUTOVER_ARCHETYPES",
    "DATA_SOURCE_TO_SECRET",
    "DATA_SOURCE_TO_VENUES",
    "DATA_TYPES_BY_ASSET_GROUP",
    "DATA_TYPE_TO_CLUSTER_REGISTRY",
    "GRAIN_BUNDLE_BY_UNDERLYING",
    "GRAIN_LEAF",
    "BUNDLE_INSTRUMENT_TYPE_BY_AG_AND_LEAF",
    "INSTRUMENT_GRAIN_BY_AG_AND_INSTRUMENT_TYPE",
    "DEFI_AAVE_V3_LENDING_INDICES",
    "DEFI_DEX_POOL_DEX_POOL_STATE",
    "DEFI_DEX_POOL_DEX_POOL_SWAPS",
    "DEFI_INSTRUMENTS",
    "DEFI_INSTRUMENTS_NOT_YET_COLLECTED",
    "DEFI_LENDING_ASSETS",
    "DEFI_LENDING_FLASH_LOAN_EVENTS",
    "DEFI_LENDING_INDICES_MARKET_ID",
    "DEFI_LENDING_LIQUIDATIONS",
    "DEFI_LENDING_LIQUIDATION_EVENTS",
    "DEFI_LENDING_POSITION_DATA",
    "DEFI_LENDING_POSITION_LENDING_INDICES",
    "DEFI_LST_LST_RATES",
    "DEFI_MAJOR_ASSET_ADDRESSES",
    "DEFI_MAJOR_ASSET_ADDRESS_LIST",
    "DEFI_MAJOR_ASSET_SYMBOLS",
    "DEFI_PERPETUAL_PERP_FUNDING",
    "DEFI_POOL_DEX_POOL_SWAPS",
    "DEFI_SPOT_ASSET_BRIDGE_EVENTS",
    "DEFI_SPOT_ASSET_GAS_FEES",
    "DEFI_SPOT_ASSET_GOVERNANCE_EVENTS",
    "DEFI_SPOT_ASSET_MEV_EVENTS",
    "DEFI_SPOT_ASSET_ORACLE_PRICES",
    "DEFI_SPOT_ASSET_TOKEN_TRANSFERS",
    "DEFI_STAKING_EIGENLAYER_REWARDS",
    "DEFI_STAKING_STAKING_YIELDS",
    "DEFI_STAKING_YIELD_SNAPSHOTS",
    "DEPRECATED_DEFI_GHOST_VENUE_NAMES",
    "DEX_VENUES",
    "DEX_VENUE_KEYWORDS",
    "EMPTY_CONFIRMED_REASONS",
    "EMPTY_OR_DEPRECATED_DEFI_VENUES",
    "ENDPOINT_REGISTRY",
    "EPL_TEAM_ALIASES",
    "EVENT_CONTRACT_ROOT_CLUSTERS",
    "EXCHANGE_BY_TICKER",
    "EXPECTED_COVERAGE_BY_ASSET_GROUP",
    "EXPECTED_EMPTY_REASON_PREFIX",
    "EXPECTED_WINDOW_COMPLETENESS_FRACTION_COLUMN",
    "FUTURES_CHAIN_BUCKETS",
    "FX_SPOT_PAIRS",
    "INSTRUMENT_SCHEMA",
    "INSTRUMENT_TYPES_BY_VENUE",
    "INSTRUMENT_TYPE_FOLDER_MAP",
    "KNOWN_ETFS",
    "LAST_EMISSION_DECISION_AT_COLUMN",
    "LINKED_CME_ROOTS",
    "LIVE_ALERT_RULES",
    "LIVE_CLUSTER_REGISTRY",
    "MANIFEST_SCHEMA_VERSION_V8",
    "ODDS_API_KEY_TO_VENUE",
    "ODDS_API_KEY_TO_VENUE_CATEGORY",
    "OKX_FUTURES",
    "OKX_SPOT",
    "OPTIONAL_CONFIG_FIELDS",
    "PIPELINE_MODE_COLUMN",
    "PIPELINE_MODE_NOT_NULL_SINCE",
    "PROCESSED_REQUIRES_RAW",
    "QUARTERLY_MONTHS",
    "READER_FALLBACK_WINDOW_DAYS",
    "REQUIRED_CONFIG_FIELDS",
    "RISK_TYPE_CATEGORIES",
    "SCENARIO_ARCHETYPE_MATRIX",
    "SCENARIO_REGISTRY",
    "SCHEDULER_REGISTRY",
    "SERVICE_EMISSION_STATES",
    "SERVICE_EMISSION_STATE_COLUMN",
    "SHARE_CLASS_BASE_ASSETS",
    "SPORTS_DATA_TYPE_TO_SOURCE",
    "SPORTS_VENUES",
    "STRATEGY_FAMILY_REGISTRY",
    "SYNTHETIC_GENERATOR_REGISTRY",
    "TIMEFRAMES",
    "TRADFI_DATABENTO_INSTRUMENTS",
    "TRADFI_EQUITIES",
    "TRADFI_EQUITY_OHLCV_1M",
    "TRADFI_EQUITY_TRADES",
    "TRADFI_FUTURES",
    "TRADFI_FUTURE_OHLCV_1M",
    "TRADFI_FUTURE_TRADES",
    "TRADFI_INDEX_TRADES",
    "TRADFI_INSTRUMENTS",
    "TRADFI_OPTIONS_CHAIN_TRADES",
    "TRADFI_TICKER_UNIVERSE",
    "UNDERLYING_NORMALIZATION",
    "V8_COLUMN_DEFAULTS",
    "V8_NEW_COLUMNS",
    "VALID_ALGORITHMS",
    "POSSIBLE_MANIFEST_ASSET_GROUPS",
    "PossibleManifestSpec",
    "CatalogueLeaf",
    "ShardKey",
    "canonical_path_templates",
    "enumerate_possible_shard_keys",
    "external_batch_sources_for_asset_group",
    "get_possible_manifest_spec",
    "is_valid_shard_key",
    "VALID_ASSET_GROUPS",
    "VALID_BOOK_TYPES",
    "VALID_DATA_TYPES_BY_AG_AND_INSTRUMENT_TYPE",
    "VALID_INSTRUCTION_TYPES",
    "VALID_MODES",
    "VALID_TIMEFRAMES",
    "VENUES_BY_ASSET_GROUP",
    "VENUE_CATEGORY_MAP",
    "VENUE_CONTRACT_OVERRIDES",
    "VENUE_COORDINATES",
    "VENUE_DATA_AVAILABILITY",
    "VENUE_ERROR_MAP",
    "VENUE_EXECUTION_REGISTRY",
    "VENUE_HEARTBEAT_THRESHOLDS",
    "VENUE_TO_ASSET_GROUP",
    "VENUE_TO_DATA_SOURCE",
    "VENUE_TO_DATA_SOURCES",
    "ZERO_ALPHA_VENUES",
    "AaveBorrowParams",
    "AaveDepositParams",
    "AaveFlashLoanParams",
    "AaveRepayParams",
    "AaveV3ReserveData",
    "AaveV3UserAccountData",
    "AaveV3UserReserveData",
    "AccountVerificationLevel",
    "AckSource",
    "AggregatedPosition",
    "AlertChannel",
    "AlertCode",
    "AlertRule",
    "AlertSeverity",
    "AlertThreshold",
    "AllocationExecutionStatus",
    "AllocatorCashAccountView",
    "AllocatorRedemption",
    "AllocatorSubscription",
    "AlternativeDataSignal",
    "AlternativeDataType",
    "AntiDetectionLevel",
    "ApproveSubscriptionRequest",
    "ArbitrageMarket",
    "ArbitrageOpportunity",
    "ArbitrageStatus",
    "AssetClass",
    # Honest-coverage taxonomy — UTL ManifestWriter consumers
    "AssetGroup",
    "AsterExchangeInfo",
    "BarBoundaryViolationError",
    "BarTimeframe",
    "BenchmarkType",
    "BetExecution",
    "BetOrder",
    "BetRejectedError",
    "BetSide",
    "BetStatus",
    "BetfairCurrentOrderSummary",
    "BetfairListCurrentOrdersResponse",
    "BetfairMarketCatalogue",
    "BetfairRunnerCatalog",
    "BettingSignal",
    "BinanceFuturesExchangeInfo",
    "BinanceInstrumentInfo",
    "BinanceLiquidationOrder",
    "BinanceMarkPriceUpdate",
    "BinanceOptionInstrumentInfo",
    "BATCH_FILL_ALGO_TYPES",
    "BENCHMARK_FILL_ALGO_TYPE",
    "NORMAL_ALGO_TYPE",
    "BatchExecutionMode",
    "BinanceOrderBook",
    "BinanceTicker",
    "BinanceTrade",
    "BinanceWithdrawRequest",
    "BinanceWithdrawResponse",
    "BookLevel",
    "BookSpoof",
    "BookmakerCategory",
    "BookmakerInfo",
    "BookmakerRegistry",
    "BookmakerUnavailableError",
    "BreakerAction",
    "BreakerConfig",
    "BreakerFiredEvent",
    "BreakerRecoveryMode",
    "BreakerRecoveryRule",
    "BreakerScope",
    "BreakerTrigger",
    "BucketMarket",
    "BusTransferType",
    "BybitInstrumentInfo",
    "BybitInstrumentsResponse",
    "BybitLiquidationOrder",
    "BybitOrderBook",
    "BybitTicker",
    "BybitWithdrawRequest",
    "BybitWithdrawResponse",
    "CLVRecord",
    "CanonicalAccountSnapshot",
    "CanonicalAccountState",
    "CanonicalAuthenticationError",
    "CanonicalAuthorizationError",
    "CanonicalBalance",
    "CanonicalBase",
    "CanonicalBetMarket",
    "CanonicalBetOrder",
    "CanonicalBondData",
    "CanonicalBookmakerMarket",
    "CanonicalCdsSpread",
    "CanonicalComboBet",
    "CanonicalComboLeg",
    "CanonicalComputeService",
    "CanonicalContractExpiredError",
    "CanonicalDerivativeTicker",
    "CanonicalDuplicateOrderError",
    "CanonicalError",
    "CanonicalFeatureRecord",
    "CanonicalFee",
    "CanonicalFill",
    "CanonicalFixture",
    "CanonicalFixtureEvent",
    "CanonicalFixtureStatsDetail",
    "CanonicalFundingRate",
    "CanonicalFuturesContract",
    "CanonicalInjury",
    "CanonicalInstrument",
    "CanonicalInstrumentHaltedError",
    "CanonicalInsufficientBalanceError",
    "CanonicalInsufficientMarginError",
    "CanonicalInternalServerError",
    "CanonicalInvalidRequestError",
    "CanonicalLeague",
    "CanonicalLineup",
    "CanonicalLiquidation",
    "CanonicalLiquidationCluster",
    "CanonicalMaintenanceModeError",
    "CanonicalMarginState",
    "CanonicalMarketClosedError",
    "CanonicalMarketStateEvent",
    "CanonicalNetworkError",
    "CanonicalOdds",
    "CanonicalOhlcvBar",
    "CanonicalOnChainMetric",
    "CanonicalOptionsChainEntry",
    "OHLCV_AGGREGATION",
    "OhlcvAggregation",
    "CanonicalOrder",
    "CanonicalOrderAmendment",
    "CanonicalOrderBook",
    "CanonicalOrderRejectedError",
    "CanonicalOrderRejection",
    "CanonicalPlayer",
    "CanonicalPlayerMatchStats",
    "CanonicalPosition",
    "CanonicalPositionLimitExceededError",
    "CanonicalPredictionMarket",
    "CanonicalPriceBoundError",
    "CanonicalProgressiveOdds",
    "CanonicalProgressiveStats",
    "CanonicalPullRequest",
    "CanonicalRateLimitError",
    "CanonicalReferee",
    "CanonicalRepository",
    "CanonicalSchemaError",
    "CanonicalServiceUnavailableError",
    "CanonicalSettlement",
    "CanonicalSizeLimitError",
    "CanonicalSpread",
    "CanonicalTeam",
    "CanonicalTicker",
    "CanonicalTrade",
    "CanonicalUnknownVenueError",
    "CanonicalVenue",
    "CanonicalWebSocketLifecycle",
    "CanonicalWorkflowRun",
    "CanonicalYieldCurvePoint",
    "CashAccountMovement",
    "CcxtAggTrade",
    "CcxtFundingRate",
    "CcxtMarket",
    "CcxtOhlcv",
    "CcxtOpenInterest",
    "CcxtOrderBook",
    "CcxtTicker",
    "CcxtTrade",
    "CHAIN_WIRE_VALUE_OVERRIDES",
    "ChainKind",
    "CircuitBreakerId",
    "ClientLifecycleEvent",
    "ClientLifecycleKind",
    "ClientQuarantinedEvent",
    "ClientReadyEvent",
    "ClientRiskLimits",
    "ClientsYaml",
    "ClientsYamlEntry",
    "CloudProvider",
    "CloudTarget",
    "CrossClientTransferForbiddenError",
    "CoinbaseOrderBook",
    "CoinbaseProductInfo",
    "CoinbaseProductsResponse",
    "CoinbaseTicker",
    "CoinbaseTrade",
    "CoinbaseWithdrawRequest",
    "CoinbaseWithdrawResponse",
    "ColumnSpec",
    "ComboLeg",
    "ComboQuote",
    "ComboStrategyType",
    "CommissionModel",
    "CompoundV3MarketInfo",
    "CompoundV3UserPosition",
    "ComputeTarget",
    "ComputeType",
    "ContractSpec",
    "Counterparty",
    "CounterpartyEntitlement",
    "CounterpartyEntitlementProfile",
    "CounterpartyStatus",
    "CredentialType",
    "CrossVenueArbLeg",
    "CrossVenueArbSignal",
    "CrossVenueLink",
    "CurveDepositParams",
    "CurveSwapParams",
    "CurveWithdrawParams",
    "DarkPoolPrintRecord",
    "DataSourceMapping",
    "DataSourceRoute",
    "DataTypeConfig",
    "DatabentoError",
    "DeFiAggregatedHealth",
    "DeFiLPAggregatedMetrics",
    "DeFiStakingAggregatedMetrics",
    "DefiAlertType",
    "DefiErrorCode",
    "DeliveryAttempt",
    "DeliveryStatus",
    "DepositAddress",
    "DepositRecord",
    "DeribitAccountSummaryResponse",
    "DeribitCancelResponse",
    "DeribitGetInstrumentResponse",
    "DeribitGetInstrumentsResponse",
    "DeribitInstrumentInfoFull",
    "DeribitInstrumentsResponse",
    "DeribitOpenOrdersResponse",
    "DeribitOrderResponse",
    "DeribitOrderStateResponse",
    "DeribitPositionsResponse",
    "DeribitTickerResponse",
    "Direction",
    "DirectionalIntent",
    "DropRows",
    # Service emission policy — UTL emission_publisher consumers
    "EmissionLifecycleEvent",
    "EmptyConfirmedReason",
    "EmptyFromLiveInstrumentError",
    "EndpointSpec",
    "EnvironmentTier",
    "Erc20TransferCalldata",
    "Erc20TransferFromCalldata",
    "ErrorAction",
    "EthSendRawTransactionRequest",
    "EthSendRawTransactionResponse",
    "EthSendTransactionRequest",
    "EthTransactionRequest",
    "EtherFiStakeResponse",
    "EtherFiUnstakeResponse",
    "EulerBorrowParams",
    "EulerDepositParams",
    "EulerRepayParams",
    "EulerUserPosition",
    "EulerVaultData",
    "EventDrop",
    "EventDuplicate",
    "EventOrigin",
    "EventType",
    "ExchangeFeeSchedule",
    "ExchangeInstrumentConfig",
    "ExecutionAlpha",
    "ExecutionInstruction",
    "ExecutionMethod",
    "ExecutionRejectionCode",
    "ExecutionRejectionEvent",
    "ExecutionResult",
    "ExecutionStatus",
    "ExpectedValue",
    "ExperimentKind",
    "ExperimentRunSpec",
    "ExperimentStatus",
    "FeatureMetadata",
    "FeeStructure",
    "FeeType",
    "FixtureMapping",
    "FixtureNotFoundError",
    "FluidBorrowParams",
    "FluidDepositParams",
    "FluidRepayParams",
    "FundAllocation",
    "ArchetypeAllocationDirective",
    "FundNAVSnapshot",
    "StrategyPnlStreamEvent",
    "FundTransferContext",
    "FundingRateHistory",
    "FuturesContractLifecyclePhase",
    "GasSurge",
    "HealthPingResponse",
    "HttpRateLimitHeaders",
    "HyperliquidAssetInfo",
    "HyperliquidFill",
    "HyperliquidMeta",
    "HyperliquidOpenOrder",
    "HyperliquidPosition",
    "HyperliquidUserState",
    "IBKRAccountValue",
    "IBKRContractDetails",
    "IBKRCorporateAction",
    "IBKRPosition",
    "InstructionLedger",
    "InstructionType",
    "InstrumentType",
    "InsuranceFundState",
    "InternalTransfer",
    "KalshiMarket",
    "KalshiOrderBook",
    "KalshiTrade",
    "KillSwitchArmRequest",
    "KillSwitchArmedEvent",
    "KillSwitchDisarmEvent",
    "KillSwitchId",
    "KillSwitchProvenance",
    "KillSwitchScope",
    "LPProtocolBreakdown",
    "LatencyComponent",
    "LatencyInject",
    "LedgerAssetClass",
    "LedgerRow",
    "LegacyBlankErrorReasonError",
    "RecordFailedReason",
    "LidoRequestWithdrawalsParams",
    "LidoSubmitParams",
    "LidoSubmitResponse",
    "LidoWstEthWrapResponse",
    "LifecycleClass",
    "LineupPlayer",
    "LiveClusterDeploymentKind",
    "LiveClusterSpec",
    "LiveMatchState",
    "LiveOddsUpdate",
    "LongShortRatio",
    "ManifestPhantom",
    "ManifestRowBlockedError",
    "MappingRule",
    "MarginType",
    "MarketClosedError",
    "MarketSession",
    "MarketState",
    "MarketStatus",
    "MarketTrade",
    "MatchPeriod",
    "MinBalancePerVenue",
    "MorphoBorrowParams",
    "MorphoFlashLoanParams",
    "MorphoMarketParams",
    "MorphoRepayParams",
    "MorphoSupplyParams",
    "MorphoUserPosition",
    "MultiLegInstrument",
    "NegRiskArbSignal",
    "NegRiskBucket",
    "NetworkJitterMetric",
    "NormalizedStrikeCoordinate",
    "OKXFundingRate",
    "OKXInstrumentInfo",
    "OKXInstrumentsResponse",
    "OKXLiquidationOrder",
    "OKXMarkPrice",
    "OKXOrderBook",
    "OKXTicker",
    "OKXWithdrawRequest",
    "OKXWithdrawResponse",
    "OddsChangedError",
    "OddsFormat",
    "OddsType",
    "OpenInterestHistory",
    "OperationType",
    "OptionChainSnapshot",
    "OptionRight",
    "OptionType",
    "OptionsFlowRecord",
    "OracleDeviate",
    "OracleDeviationError",
    "OracleStaleError",
    "OrderBookSnapshot5",
    "OrderLatencyRecord",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "OrphanDetector",
    "OutcomeCategory",
    "OutcomeType",
    "PassiveLedger",
    "PayloadDepth",
    "PipelineMode",
    "PricingLedger",
    "PlayerMapping",
    "PolymarketGammaMarket",
    "PolymarketPosition",
    "MassiveFuturesContract",
    "MassiveFuturesContractsResponse",
    "MassiveFuturesProduct",
    "MassiveFuturesProductsResponse",
    "MassiveOptionContract",
    "MassiveOptionContractsResponse",
    "MassiveTicker",
    "MassiveTickersResponse",
    "normalize_massive_equity",
    "normalize_massive_futures",
    "normalize_massive_fx",
    "normalize_massive_index",
    "normalize_massive_option",
    "PolygonOptionContract",
    "PolygonOptionContractsResponse",
    "PolygonTicker",
    "PolygonTickersResponse",
    "PortfolioGreeksSnapshot",
    "PortfolioMarginAccount",
    "PortfolioPnLAttribution",
    "PortfolioView",
    "PositionRisk",
    "PredictionMarketCategory",
    "PredictionMarketMapper",
    "PredictionMarketUniverse",
    "PreflightFailed",
    "PreflightOK",
    "PreflightResult",
    "PreflightTrigger",
    "PriceShift",
    "ProbabilityBucket",
    "ProcessRedemptionRequest",
    "ProcessedOddsOutput",
    "ProtocolHealthBreakdown",
    "ProviderDataAvailability",
    "QuarantineReason",
    "RateLimitConfig",
    "RateLimitInfo",
    "RateLimitResponse",
    "RebalanceRequest",
    "RedeemRequest",
    "RedemptionStatus",
    "RejectFills",
    "RejectRequest",
    "RestPullDeliveryConfig",
    "RiskCategory",
    "RiskGroupSummary",
    "RiskType",
    "RowSchemaValidationError",
    "SatelliteObservation",
    "ScalingMode",
    "ScenarioApplicabilityFilter",
    "ScenarioCategory",
    "ScenarioMutationSpec",
    "ScenarioOutcomeAssertion",
    "ScenarioOutcomeResult",
    "ScenarioOverlay",
    "ScenarioOverlayLayer",
    "ScenarioReport",
    "SchedulerSpec",
    "SchedulerTargetKind",
    "SchemaContract",
    "SchemaContractNotFoundError",
    "SchemaDepth",
    "ScraperError",
    "ScraperVersionMeta",
    "SentimentScore",
    "ServiceEmissionPolicy",
    "ServiceEmissionStateEnum",
    "SessionPhase",
    "SettlementEvent",
    "ShareClass",
    "ShardCapacityEvent",
    "ShardRecommendedAction",
    "SignalAcknowledgement",
    "SignalEmission",
    "SignalPayload",
    "SignalPayloadMinimal",
    "SignalPayloadRich",
    "SignalPayloadStandard",
    "SignalSource",
    "SourceControlProvider",
    "Sport",
    "SportsArbLeg",
    "SportsArbPosition",
    "SportsError",
    "SportsbookLink",
    "SpreadLeg",
    "StakingProtocolBreakdown",
    "StaleHold",
    "StrategyFamily",
    "StrategyFamilyId",
    "StrategySignalAcknowledged",
    "StrategySignalEmittedExternal",
    "SubAccount",
    "SubscribeRequest",
    "SubscriptionStatus",
    "SyntheticDataDomain",
    "SyntheticGeneratorId",
    "SyntheticGeneratorSpec",
    "SyntheticOutputManifest",
    "SyntheticParams",
    "SyntheticRealismAxis",
    "SyntheticRunManifest",
    "SyntheticShardLayout",
    "SyntheticShardManifest",
    "TardisExchangeDetail",
    "TardisInstrumentDetail",
    "TeamMapping",
    "ThresholdUnit",
    "TransferIntent",
    "TransferResult",
    "TransferResultStatus",
    "TreasuryLedger",
    "TimeInForce",
    "UnderlyingGreeksBreakdown",
    "UniswapV3PoolStateResponse",
    "UniswapV3QuoteResponse",
    "UniswapV3SwapTxReceipt",
    "UnknownAlertCodeError",
    "UnknownThresholdKeyError",
    "UnsupportedCapabilityError",
    "UpbitBalanceQueryResponse",
    "UpbitTicker",
    "UpbitWithdrawRequest",
    "UpbitWithdrawResponse",
    "VenueAuthStatus",
    "VenueCategory",
    "VenueCoordinates",
    "VenueErrorClassification",
    "VenueExecutionProfile",
    "VenueMapping",
    "VenuePositionBreakdown",
    "VenueRateLimitSpec",
    "Violation",
    "VmPrefixSpec",
    "VmQuotaShape",
    "VolSmilePoint",
    "VolSurface",
    "VolSurfaceSlice",
    "VolTermStructure",
    "WebSocketCloseInfo",
    "WebSocketConnectionClosed",
    "WebSocketConnectionOpened",
    "WebSocketEvent",
    "WebhookDeliveryConfig",
    "WithdrawalRecord",
    "active_counterparties",
    "american_to_decimal",
    "assert_bar_boundary_contract",
    "assert_no_cross_client_transfer",
    "bar_window_for_close",
    "breaker_fired_event",
    "build_cefi_partition_path",
    "build_combo_id",
    "build_defi_partition_path",
    "build_instrument_id",
    "build_prediction_partition_path",
    "build_tradfi_partition_path",
    "candidate_parquet_paths",
    "classify_cloud_run_service",
    "classify_experiment_run",
    "classify_scheduled_job",
    "classify_session",
    "classify_venue_error",
    "classify_vm_name",
    "counterparty_for",
    "decimal_to_american",
    "emission_latency_ms_for_source",
    "entitled_slots_for",
    "entitlements_for",
    "family_for_archetype",
    "generators_for_archetype",
    "get_clusters_for_env",
    "get_data_sources_for_venue",
    "get_databento_symbols_for_venue",
    "get_emission_policy",
    "get_expected_bookmakers",
    "get_expected_data_types_for_venue",
    "get_valid_data_types_for_venue",
    "get_expected_instruments_for_venue",
    "needs_candle_processing",
    "get_expected_leagues_for_source",
    "get_generator_spec",
    "get_heartbeat_threshold",
    "get_prediction_leagues",
    "get_primary_source",
    "get_primary_source_with_latency",
    "get_provider_availability",
    # Features DAG — UTL point_in_time + features-* consumers
    "get_all_sources_with_priority",
    "detect_dual_source_conflicts",
    "select_primary_available_source",
    "Mode",
    "Cadence",
    "Transport",
    "transport_of",
    "default_transport_for_source",
    "mode_of",
    "BATCH_CAPABLE_CEFI_VENUES",
    "CEFI_LIVE_VENUES",
    "MOCK_SOURCE",
    "SOURCE_MODE_CAPABILITY",
    "modes_for_source",
    "source_supports",
    "sources_supporting",
    "get_required_inputs",
    "get_required_secrets",
    "get_schedulers_for_env",
    "get_source_priority",
    "get_venue_coordinates",
    "get_venue_data_type_start_date",
    "bundle_instrument_type_for_leaf",
    "grain_for_instrument_type",
    "has_source_priority",
    "is_batch",
    "is_emission_policy_declared",
    "is_live",
    "is_per_instrument_shard_data_type",
    "is_replay",
    "linked_question_group",
    "lookup_contract",
    "matrix_cell_count",
    "next_state",
    "non_trading_day_reason",
    "normalize_underlying",
    "_SPORTS_ENTITY_TO_PIPELINE_MODE",
    "pipeline_mode_for_source",
    "pipeline_mode_for_sports_entity",
    "policy_is_alert",
    "policy_is_publish_row",
    "read_with_source_priority",
    "register_catalog_reader",
    "register_generator",
    "register_scenario",
    "resolve_environment_from_env",
    "resolve_data_type_for_feature_group",
    "default_source",
    "external_sources_for",
    "resolve_environment_from_hostname",
    "resolve_exchange",
    "scenarios_for_archetype",
    "source_required",
    "source_string_for",
    "valid_data_types_for_instrument_type",
    "validate_data_type_for_venue",
    "validate_dataframe",
    "validate_preflight_for_trigger",
    "to_canonical_chain_wire",
    "validate_row_df",
    "venue_has_no_expected_defi_coverage",
    "TARDIS_FREE_ROLLING_WINDOW_DAYS",
    "free_dates_in_range",
    "is_tardis_free_date",
    "AbsenceType",
    "ActionProvenance",
    "ActionStatus",
    "ActionType",
    "AgentActionEvent",
    "AssetGroupInventory",
    "AuditAckSLAPolicy",
    "BinaryEventTrigger",
    "BucketKind",
    "CanonicalFixtureOutcomes",
    "CanonicalFixtureSchedule",
    "CanonicalGroupMetadata",
    "CanonicalQuestionGroup",
    "CapitalAtRiskCeilingTrigger",
    "CatalogRow",
    "CorrelationRegimeChange",
    "CounterpartyRatioCapTrigger",
    "CoverageResult",
    "CrossAssetCorrelationMatrix",
    "DataLocalityResult",
    "DependencyClass",
    "DependencyHealthPolicy",
    "DivergenceKind",
    "DrawdownInvestigationReport",
    "DrawdownThresholdKind",
    "ETFMetadata",
    "ExpectedDrawdownModel",
    "ExpectedDrawdownModelBasis",
    "FactorAttributionModel",
    "FactorAttributionRecord",
    "FeatureFamily",
    "FeatureGroupFamilyCollisionError",
    "FundingCostCeilingTrigger",
    "GasBudgetTrigger",
    "IllegalIncidentTransitionError",
    "ImmediateSev0Override",
    "IncidentEnvelope",
    "IncidentEvidence",
    "IncidentState",
    "InputReq",
    "InstrumentCatalogReader",
    "list_instruments",
    "list_not_yet_listed_cefi",
    "LeagueClassification",
    "LeagueClassificationRegistry",
    "LeagueClassificationType",
    "LeagueDefinition",
    "LendingProtocol",
    "LiquidationInvestigationReport",
    "ManifestReader",
    "ManifestShaDriftError",
    "MarketLifecycle",
    "MatchLifecycle",
    "MatchResult",
    "MatchStatus",
    "MaxConcentrationTrigger",
    "MaxCorrelationTrigger",
    "MaxDailyLossTrigger",
    "MaxDrawdownTrigger",
    "MaxGrossExposureTrigger",
    "MaxLeverageTrigger",
    "MaxNetExposureTrigger",
    "MaxOITrigger",
    "MaxPositionSizeTrigger",
    "PredictionMarketCrossVenueMapping",
    "PreflightRequirement",
    "RecoveryAuditSignoff",
    "RecoveryVerificationResult",
    "ResponsePolicy",
    "RiskRule",
    "RiskRuleConsequence",
    "RiskRuleFiredEvent",
    "RiskRuleId",
    "RiskRuleScope",
    "RiskThresholds",
    "RootMetadata",
    "RoundMatch",
    "SeasonBoundary",
    "footystats_season_status_for_day",
    "get_league",
    "get_league_by_api_football_id",
    "get_league_fixture_calendar",
    "is_in_known_gap",
    "SessionWindow",
    "SignoffVerdict",
    "SlippageBudgetTrigger",
    "SportsPathLayout",
    "TransferWindowPeriod",
    "UpstreamReq",
    "VenueTestnetEndpoints",
    # MVP scope config + predicate (Phase 1)
    "MVP_SCOPE",
    "is_mvp",
    "CeFiMvpRule",
    "DeFiMvpRule",
    "TradFiMvpRule",
    "SportsMvpRule",
    "PredictionMvpRule",
    "FeaturesModelsMvpStub",
]

# fmt: off
_VENUES = [
    "alchemy", "api_football", "aster", "barchart", "betfair", "binance",
    "bybit", "ccxt", "aws", "gcp", "coinbase", "databento", "defi", "defillama",
    "deribit", "eigenlayer", "footystats", "github", "hyperliquid", "ibkr", "kalshi",
    "mev", "metabet", "morpho_blue_api", "nautilus", "odds_api", "odds_engine", "okx",
    "open_meteo", "opticodds", "pinnacle", "polymarket", "soccer_football_info",
    "sky", "tardis", "thegraph", "transfermarkt", "understat", "upbit", "yahoo_finance",
]
# fmt: on
for _v in _VENUES:
    _mod = cast(ModuleType, __import__(f"{__name__}.external.{_v}", fromlist=[_v]))
    sys.modules[f"{__name__}.{_v}"] = _mod
