"""API contracts: Pydantic schemas and VCR mocks for external APIs."""

import sys
from types import ModuleType
from typing import cast

from .canonical.canonical_mappings import (
    DATA_SOURCE_TO_SECRET,
    DATA_SOURCE_TO_VENUES,
    VENUE_TO_DATA_SOURCE,
    VENUE_TO_DATA_SOURCES,
    ContractSpec,
    DataSourceMapping,
    DataSourceRoute,
    get_data_sources_for_venue,
    get_required_secrets,
)

# ``canonical.crosscutting.alerting`` transitively triggers
# ``unified_api_contracts.internal`` via ``rules.py`` (KillSwitchScope) +
# downstream chain. ``internal/...`` imports back from this top-level
# facade (BetStatus, CanonicalFill, DefiAlertType, ...). Order matters:
# canonical_mappings → errors → domain → alerting (loads internal/).
from .canonical.crosscutting.alerting import (
    ALERT_CODES,
    ALERT_THRESHOLDS,
    LIVE_ALERT_RULES,
    AlertChannel,
    AlertCode,
    AlertRule,
    AlertSeverity,
    AlertThreshold,
    KillSwitchScope,
    ThresholdUnit,
    UnknownAlertCodeError,
    UnknownThresholdKeyError,
)
from .canonical.crosscutting.bar_boundary import (
    BAR_TIMEFRAME_SECONDS,
    BAR_TIMEFRAMES,
    BarBoundaryViolationError,
    BarTimeframe,
    assert_bar_boundary_contract,
    bar_window_for_close,
)
from .canonical.crosscutting.circuit_breaker import (
    BREAKER_RECOVERY_DEFAULTS,
    BreakerAction,
    BreakerConfig,
    BreakerFiredEvent,
    BreakerRecoveryMode,
    BreakerRecoveryRule,
    BreakerScope,
    BreakerTrigger,
    CircuitBreakerId,
    breaker_fired_event,
)
from .canonical.crosscutting.client_lifecycle_events import (
    ClientLifecycleEvent,
    ClientLifecycleKind,
    ClientQuarantinedEvent,
    ClientReadyEvent,
    QuarantineReason,
    ShardCapacityEvent,
    ShardRecommendedAction,
    VenueAuthStatus,
)
from .canonical.crosscutting.defi import ChainKind
from .canonical.crosscutting.errors import (
    VENUE_ERROR_MAP,
    CanonicalAuthenticationError,
    CanonicalAuthorizationError,
    CanonicalContractExpiredError,
    CanonicalDuplicateOrderError,
    CanonicalError,
    CanonicalInstrumentHaltedError,
    CanonicalInsufficientBalanceError,
    CanonicalInsufficientMarginError,
    CanonicalInternalServerError,
    CanonicalInvalidRequestError,
    CanonicalMaintenanceModeError,
    CanonicalMarketClosedError,
    CanonicalNetworkError,
    CanonicalOrderRejectedError,
    CanonicalPositionLimitExceededError,
    CanonicalPriceBoundError,
    CanonicalRateLimitError,
    CanonicalSchemaError,
    CanonicalServiceUnavailableError,
    CanonicalSizeLimitError,
    CanonicalUnknownVenueError,
    DatabentoError,
    DefiAlertType,
    DefiErrorCode,
    ErrorAction,
    OracleDeviationError,
    OracleStaleError,
    RateLimitInfo,
    RateLimitResponse,
    UnsupportedCapabilityError,
    VenueErrorClassification,
    WebSocketCloseInfo,
    classify_venue_error,
)
from .canonical.crosscutting.execution import (
    BATCH_FILL_ALGO_TYPES,
    BENCHMARK_FILL_ALGO_TYPE,
    NORMAL_ALGO_TYPE,
    BatchExecutionMode,
)
from .canonical.crosscutting.experiment_registry import (
    ExperimentKind,
    ExperimentRunSpec,
    ExperimentStatus,
)
from .canonical.crosscutting.kill_switch import (
    KillSwitchArmedEvent,
    KillSwitchArmRequest,
    KillSwitchDisarmEvent,
    KillSwitchId,
    KillSwitchProvenance,
)
from .canonical.crosscutting.live_cluster_registry import (
    LIVE_CLUSTER_REGISTRY,
    LiveClusterDeploymentKind,
    LiveClusterSpec,
    get_clusters_for_env,
)
from .canonical.crosscutting.pipeline_mode import (
    PipelineMode,
    is_batch,
    is_live,
    pipeline_mode_for_source,
    source_string_for,
)
from .canonical.crosscutting.scenario_overlay import (
    SCENARIO_REGISTRY,
    BookSpoof,
    DropRows,
    EventDrop,
    EventDuplicate,
    GasSurge,
    LatencyInject,
    ManifestPhantom,
    OracleDeviate,
    OutcomeCategory,
    PriceShift,
    RejectFills,
    ScenarioApplicabilityFilter,
    ScenarioCategory,
    ScenarioMutationSpec,
    ScenarioOutcomeAssertion,
    ScenarioOutcomeResult,
    ScenarioOverlay,
    ScenarioOverlayLayer,
    ScenarioReport,
    StaleHold,
    register_scenario,
)
from .canonical.crosscutting.scheduler_registry import (
    SCHEDULER_REGISTRY,
    SchedulerSpec,
    SchedulerTargetKind,
    get_schedulers_for_env,
)
from .canonical.crosscutting.source_priority import (
    emission_latency_ms_for_source,
    get_primary_source,
    get_primary_source_with_latency,
    get_source_priority,
    has_source_priority,
    read_with_source_priority,
)
from .canonical.crosscutting.strategy_family import (
    STRATEGY_FAMILY_REGISTRY,
    StrategyFamily,
    StrategyFamilyId,
    family_for_archetype,
)
from .canonical.crosscutting.synthetic_generator import (
    SYNTHETIC_GENERATOR_REGISTRY,
    SyntheticDataDomain,
    SyntheticGeneratorId,
    SyntheticGeneratorSpec,
    SyntheticOutputManifest,
    SyntheticParams,
    SyntheticRealismAxis,
    SyntheticRunManifest,
    SyntheticShardLayout,
    SyntheticShardManifest,
    generators_for_archetype,
    get_generator_spec,
    register_generator,
)
from .canonical.crosscutting.transfer_events import (
    BusTransferType,
    TransferIntent,
    TransferResult,
    TransferResultStatus,
)
from .canonical.crosscutting.venue_thresholds import (
    VENUE_HEARTBEAT_THRESHOLDS,
    get_heartbeat_threshold,
)
from .canonical.domain import (
    BOOKMAKER_REGISTRY,
    ODDS_API_KEY_TO_VENUE,
    ODDS_API_KEY_TO_VENUE_CATEGORY,
    RISK_TYPE_CATEGORIES,
    SHARE_CLASS_BASE_ASSETS,
    VENUE_EXECUTION_REGISTRY,
    AccountVerificationLevel,
    AggregatedPosition,
    AlternativeDataSignal,
    AlternativeDataType,
    AntiDetectionLevel,
    ArbitrageMarket,
    ArbitrageOpportunity,
    ArbitrageStatus,
    AssetClass,
    BenchmarkType,
    BetExecution,
    BetOrder,
    BetRejectedError,
    BetSide,
    BetStatus,
    BettingSignal,
    BinanceWithdrawRequest,
    BinanceWithdrawResponse,
    BookLevel,
    BookmakerCategory,
    BookmakerInfo,
    BookmakerRegistry,
    BookmakerUnavailableError,
    BybitWithdrawRequest,
    BybitWithdrawResponse,
    CanonicalAccountSnapshot,
    CanonicalAccountState,
    CanonicalBalance,
    CanonicalBase,
    CanonicalBetMarket,
    CanonicalBetOrder,
    CanonicalBondData,
    CanonicalBookmakerMarket,
    CanonicalCdsSpread,
    CanonicalComboBet,
    CanonicalComboLeg,
    CanonicalComputeService,
    CanonicalDerivativeTicker,
    CanonicalFeatureRecord,
    CanonicalFee,
    CanonicalFill,
    CanonicalFixture,
    CanonicalFixtureEvent,
    CanonicalFixtureStatsDetail,
    CanonicalFundingRate,
    CanonicalFuturesContract,
    CanonicalInjury,
    CanonicalInstrument,
    CanonicalLeague,
    CanonicalLineup,
    CanonicalLiquidation,
    CanonicalLiquidationCluster,
    CanonicalMarginState,
    CanonicalMarketStateEvent,
    CanonicalOdds,
    CanonicalOhlcvBar,
    CanonicalOnChainMetric,
    CanonicalOptionsChainEntry,
    CanonicalOrder,
    CanonicalOrderAmendment,
    CanonicalOrderBook,
    CanonicalOrderRejection,
    CanonicalPlayer,
    CanonicalPlayerMatchStats,
    CanonicalPosition,
    CanonicalPredictionMarket,
    CanonicalProgressiveOdds,
    CanonicalProgressiveStats,
    CanonicalPullRequest,
    CanonicalReferee,
    CanonicalRepository,
    CanonicalSettlement,
    CanonicalSpread,
    CanonicalTeam,
    CanonicalTicker,
    CanonicalTrade,
    CanonicalVenue,
    CanonicalWebSocketLifecycle,
    CanonicalWorkflowRun,
    CanonicalYieldCurvePoint,
    CloudProvider,
    CloudTarget,
    CLVRecord,
    CoinbaseWithdrawRequest,
    CoinbaseWithdrawResponse,
    ComboLeg,
    ComboQuote,
    ComboStrategyType,
    CommissionModel,
    ComputeTarget,
    ComputeType,
    CredentialType,
    DarkPoolPrintRecord,
    DeFiAggregatedHealth,
    DeFiLPAggregatedMetrics,
    DeFiStakingAggregatedMetrics,
    DepositAddress,
    DepositRecord,
    EnvironmentTier,
    Erc20TransferCalldata,
    Erc20TransferFromCalldata,
    EthSendRawTransactionRequest,
    EthSendRawTransactionResponse,
    EthSendTransactionRequest,
    EthTransactionRequest,
    ExchangeFeeSchedule,
    ExecutionAlpha,
    ExecutionInstruction,
    ExecutionMethod,
    ExecutionRejectionCode,
    ExecutionRejectionEvent,
    ExecutionResult,
    ExecutionStatus,
    ExpectedValue,
    FeatureMetadata,
    FeeType,
    FixtureMapping,
    FixtureNotFoundError,
    FundingRateHistory,
    FuturesContractLifecyclePhase,
    HealthPingResponse,
    HttpRateLimitHeaders,
    InstructionType,
    InstrumentType,
    InsuranceFundState,
    InternalTransfer,
    LatencyComponent,
    LifecycleClass,
    LineupPlayer,
    LiveMatchState,
    LiveOddsUpdate,
    LongShortRatio,
    LPProtocolBreakdown,
    MappingRule,
    MarginType,
    MarketClosedError,
    MarketState,
    MarketStatus,
    MarketTrade,
    MatchPeriod,
    MultiLegInstrument,
    NetworkJitterMetric,
    NormalizedStrikeCoordinate,
    OddsChangedError,
    OddsFormat,
    OddsType,
    OKXWithdrawRequest,
    OKXWithdrawResponse,
    OpenInterestHistory,
    OperationType,
    OptionChainSnapshot,
    OptionsFlowRecord,
    OptionType,
    OrderBookSnapshot5,
    OrderLatencyRecord,
    OrderSide,
    OrderStatus,
    OrderType,
    OrphanDetector,
    OutcomeType,
    PlayerMapping,
    PortfolioGreeksSnapshot,
    PortfolioMarginAccount,
    PortfolioPnLAttribution,
    PortfolioView,
    PositionRisk,
    PredictionMarketCategory,
    PredictionMarketMapper,
    ProcessedOddsOutput,
    ProtocolHealthBreakdown,
    RiskCategory,
    RiskGroupSummary,
    RiskType,
    SatelliteObservation,
    ScalingMode,
    ScraperError,
    ScraperVersionMeta,
    SentimentScore,
    SettlementEvent,
    ShareClass,
    SignalSource,
    SourceControlProvider,
    Sport,
    SportsArbLeg,
    SportsArbPosition,
    SportsError,
    SpreadLeg,
    StakingProtocolBreakdown,
    SubAccount,
    TeamMapping,
    TimeInForce,
    UnderlyingGreeksBreakdown,
    UpbitWithdrawRequest,
    UpbitWithdrawResponse,
    VenueCategory,
    VenueExecutionProfile,
    VenuePositionBreakdown,
    VenueRateLimitSpec,
    VmPrefixSpec,
    VmQuotaShape,
    VolSmilePoint,
    VolSurface,
    VolSurfaceSlice,
    VolTermStructure,
    WebSocketConnectionClosed,
    WebSocketConnectionOpened,
    WebSocketEvent,
    WithdrawalRecord,
    classify_cloud_run_service,
    classify_experiment_run,
    classify_scheduled_job,
    classify_vm_name,
    get_expected_bookmakers,
    resolve_environment_from_env,
    resolve_environment_from_hostname,
)
from .canonical.domain.features import (
    get_required_inputs,
)
from .canonical.domain.strategy import (
    ClientRiskLimits,
    ClientsYaml,
    ClientsYamlEntry,
    MinBalancePerVenue,
)
from .canonical.partition_paths import (
    build_cefi_partition_path,
    build_defi_partition_path,
    build_prediction_partition_path,
    build_tradfi_partition_path,
)
from .config.trading_validation import (
    CONFIG_REQUIRED_FIELDS,
    CONFIG_SCHEMA,
    INSTRUMENT_SCHEMA,
    OPTIONAL_CONFIG_FIELDS,
    REQUIRED_CONFIG_FIELDS,
    VALID_ALGORITHMS,
    VALID_ASSET_GROUPS,
    VALID_BOOK_TYPES,
    VALID_INSTRUCTION_TYPES,
    VALID_MODES,
    VALID_TIMEFRAMES,
)

# Importing the per-asset_group generator seeds populates SYNTHETIC_GENERATOR_REGISTRY at module load.
from .registry import generators as _generators_registry  # type: ignore[reportUnusedImport]

# Importing the per-asset_group registry seeds populates SCENARIO_REGISTRY at module load.
from .registry import scenarios as _scenarios_registry  # type: ignore[reportUnusedImport]

# Phase 5.A — per-archetype regression matrix derived from SCENARIO_REGISTRY at module load.
from .registry.scenario_archetype_matrix import (
    CUTOVER_ARCHETYPES,
    matrix_cell_count,
    scenarios_for_archetype,
)
from .registry.scenario_archetype_matrix import (
    MATRIX as SCENARIO_ARCHETYPE_MATRIX,
)

# isort: off
# These crosscutting / features imports must load AFTER ``.canonical.domain``
# so ``BetStatus`` is already in the top-level UAC namespace when the
# honest_coverage → registry → capability_declarations → _signal_broadcast
# → internal/__init__.py → execution_service/sports.py chain triggers
# ``from unified_api_contracts import BetStatus``. Pre-existing circular
# import — see ``canonical.crosscutting.alerting`` comment block above.
from .canonical.crosscutting.honest_coverage import (
    BUNDLED_DATA_TYPES,
    CaptureStatusCounts,
    DATA_TYPE_TO_CLUSTER_REGISTRY,
    EMPTY_CONFIRMED_REASONS,
    EVENT_CONTRACT_ROOT_CLUSTERS,
    EXPECTED_EMPTY_REASON_PREFIX,
    FUTURES_CHAIN_BUCKETS,
    EmptyConfirmedReason,
    LegacyBlankErrorReasonError,
    RecordFailedReason,
    compute_honest_coverage,
    futures_expiry_bucket,
    get_active_es_options_clusters_for_date,
)
from .canonical.crosscutting.instruments_preflight_dag import (
    PreflightFailed,
    PreflightOK,
    PreflightResult,
    validate_preflight_for_trigger,
)
from .canonical.crosscutting.manifest_schema import (
    EXPECTED_WINDOW_COMPLETENESS_FRACTION_COLUMN,
    LAST_EMISSION_DECISION_AT_COLUMN,
    MANIFEST_SCHEMA_VERSION_V8,
    READER_FALLBACK_WINDOW_DAYS,
    SERVICE_EMISSION_STATE_COLUMN,
    V8_COLUMN_DEFAULTS,
    V8_NEW_COLUMNS,
)
from .canonical.crosscutting.service_emission_policy import (
    EmissionLifecycleEvent,
    ServiceEmissionPolicy,
    get_emission_policy,
    is_emission_policy_declared,
    next_state,
    policy_is_alert,
    policy_is_publish_row,
)
from .canonical.crosscutting.market_session import (
    MarketSession,
    SessionPhase,
    classify_session,
)
from .canonical.crosscutting.service_emission_state import (
    SERVICE_EMISSION_STATES,
    ManifestRowBlockedError,
    ServiceEmissionStateEnum,
)
from .canonical.gcs_paths import AssetGroup

# isort: on
from .external.aster.schemas import AsterExchangeInfo
from .external.betfair import (
    BetfairCurrentOrderSummary,
    BetfairListCurrentOrdersResponse,
    BetfairMarketCatalogue,
)
from .external.betfair.schemas import BetfairRunnerCatalog
from .external.binance import (
    BinanceLiquidationOrder,
    BinanceMarkPriceUpdate,
    BinanceOrderBook,
    BinanceTicker,
    BinanceTrade,
)
from .external.binance.market_schemas import (
    BinanceFuturesExchangeInfo,
    BinanceInstrumentInfo,
    BinanceOptionInstrumentInfo,
)
from .external.bybit.schemas import (
    BybitInstrumentInfo,
    BybitInstrumentsResponse,
    BybitLiquidationOrder,
    BybitOrderBook,
    BybitTicker,
)
from .external.ccxt.schemas import (
    CcxtAggTrade,
    CcxtFundingRate,
    CcxtMarket,
    CcxtOhlcv,
    CcxtOpenInterest,
    CcxtOrderBook,
    CcxtTicker,
    CcxtTrade,
)
from .external.coinbase.schemas import (
    CoinbaseOrderBook,
    CoinbaseProductInfo,
    CoinbaseProductsResponse,
    CoinbaseTicker,
    CoinbaseTrade,
)
from .external.deribit.schemas import (
    DeribitAccountSummaryResponse,
    DeribitCancelResponse,
    DeribitGetInstrumentResponse,
    DeribitGetInstrumentsResponse,
    DeribitInstrumentInfoFull,
    DeribitInstrumentsResponse,
    DeribitOpenOrdersResponse,
    DeribitOrderResponse,
    DeribitOrderStateResponse,
    DeribitPositionsResponse,
    DeribitTickerResponse,
)
from .external.hyperliquid.schemas import (
    HyperliquidAssetInfo,
    HyperliquidFill,
    HyperliquidMeta,
    HyperliquidOpenOrder,
    HyperliquidPosition,
    HyperliquidUserState,
)
from .external.ibkr import (
    IBKRAccountValue,
    IBKRContractDetails,
    IBKRCorporateAction,
    IBKRPosition,
)
from .external.kalshi.schemas import (
    KalshiMarket,
    KalshiOrderBook,
    KalshiTrade,
)
from .external.okx.schemas import (
    OKXFundingRate,
    OKXInstrumentInfo,
    OKXInstrumentsResponse,
    OKXLiquidationOrder,
    OKXMarkPrice,
    OKXOrderBook,
    OKXTicker,
)
from .external.polygon.schemas import (
    PolygonOptionContract,
    PolygonOptionContractsResponse,
    PolygonTicker,
    PolygonTickersResponse,
)
from .external.polymarket import (
    PolymarketGammaMarket,
    PolymarketPosition,
)
from .external.polymarket.arb_schemas import (
    BucketMarket,
    CrossVenueArbLeg,
    CrossVenueArbSignal,
    CrossVenueLink,
    NegRiskArbSignal,
    NegRiskBucket,
    PredictionMarketUniverse,
    ProbabilityBucket,
    SportsbookLink,
)
from .external.protocol_sdks.schemas import (
    AaveBorrowParams,
    AaveDepositParams,
    AaveFlashLoanParams,
    AaveRepayParams,
    AaveV3ReserveData,
    AaveV3UserAccountData,
    AaveV3UserReserveData,
    CompoundV3MarketInfo,
    CompoundV3UserPosition,
    CurveDepositParams,
    CurveSwapParams,
    CurveWithdrawParams,
    EtherFiStakeResponse,
    EtherFiUnstakeResponse,
    EulerBorrowParams,
    EulerDepositParams,
    EulerRepayParams,
    EulerUserPosition,
    EulerVaultData,
    FluidBorrowParams,
    FluidDepositParams,
    FluidRepayParams,
    LidoRequestWithdrawalsParams,
    LidoSubmitParams,
    LidoSubmitResponse,
    LidoWstEthWrapResponse,
    MorphoBorrowParams,
    MorphoFlashLoanParams,
    MorphoMarketParams,
    MorphoRepayParams,
    MorphoSupplyParams,
    MorphoUserPosition,
    UniswapV3PoolStateResponse,
    UniswapV3QuoteResponse,
    UniswapV3SwapTxReceipt,
)
from .external.tardis.schemas import (
    TardisExchangeDetail,
    TardisInstrumentDetail,
)
from .external.upbit.schemas import (
    UpbitBalanceQueryResponse,
    UpbitTicker,
)
from .internal.domain.client_reporting import FundNAVSnapshot
from .internal.domain.fund_administration import (
    AllocationExecutionStatus,
    AllocatorCashAccountView,
    AllocatorRedemption,
    AllocatorSubscription,
    ApproveSubscriptionRequest,
    CashAccountMovement,
    FundAllocation,
    FundTransferContext,
    ProcessRedemptionRequest,
    RebalanceRequest,
    RedeemRequest,
    RedemptionStatus,
    RejectRequest,
    SubscribeRequest,
    SubscriptionStatus,
)
from .internal.reference.canonical_id_builder import (
    build_combo_id,
    build_instrument_id,
)
from .internal.reference.ticker_registry import (
    EXCHANGE_BY_TICKER,
    UNDERLYING_NORMALIZATION,
    normalize_underlying,
    resolve_exchange,
)
from .internal.reporting import FeeStructure
from .internal.schemas.contracts import (
    CEFI_FUTURES_CHAIN_TRADES,
    CEFI_OPTIONS_CHAIN_TRADES,
    CEFI_PERPETUAL_BOOK_SNAPSHOT_5,
    CEFI_PERPETUAL_DERIVATIVE_TICKER,
    CEFI_PERPETUAL_LIQUIDATIONS,
    CEFI_PERPETUAL_QUOTES,
    CEFI_PERPETUAL_TRADES,
    CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5,
    CEFI_SPOT_PAIR_TRADES,
    CONTRACT_REGISTRY,
    DEFI_AAVE_V3_LENDING_INDICES,
    DEFI_DEX_POOL_DEX_POOL_STATE,
    DEFI_DEX_POOL_DEX_POOL_SWAPS,
    DEFI_LENDING_FLASH_LOAN_EVENTS,
    DEFI_LENDING_INDICES_MARKET_ID,
    DEFI_LENDING_LIQUIDATION_EVENTS,
    DEFI_LENDING_LIQUIDATIONS,
    DEFI_LENDING_POSITION_DATA,
    DEFI_LENDING_POSITION_LENDING_INDICES,
    DEFI_LST_LST_RATES,
    DEFI_PERPETUAL_PERP_FUNDING,
    DEFI_POOL_DEX_POOL_SWAPS,
    DEFI_SPOT_ASSET_BRIDGE_EVENTS,
    DEFI_SPOT_ASSET_GAS_FEES,
    DEFI_SPOT_ASSET_GOVERNANCE_EVENTS,
    DEFI_SPOT_ASSET_MEV_EVENTS,
    DEFI_SPOT_ASSET_ORACLE_PRICES,
    DEFI_SPOT_ASSET_TOKEN_TRANSFERS,
    DEFI_STAKING_EIGENLAYER_REWARDS,
    DEFI_STAKING_STAKING_YIELDS,
    DEFI_STAKING_YIELD_SNAPSHOTS,
    TRADFI_EQUITY_OHLCV_1M,
    TRADFI_EQUITY_TRADES,
    TRADFI_FUTURE_OHLCV_1M,
    TRADFI_FUTURE_TRADES,
    TRADFI_INDEX_TRADES,
    TRADFI_OPTIONS_CHAIN_TRADES,
    VENUE_CONTRACT_OVERRIDES,
    ColumnSpec,
    RowSchemaValidationError,
    SchemaContract,
    SchemaContractNotFoundError,
    Violation,
    lookup_contract,
    validate_dataframe,
    validate_row_df,
)
from .internal.strategy_directives import ArchetypeAllocationDirective
from .internal.strategy_pnl_stream import StrategyPnlStreamEvent
from .normalize_utils import american_to_decimal, decimal_to_american
from .registry import (
    ALL_VENUES,
    CEFI_ACCEPTED_QUOTE_ASSETS,
    CEFI_BASE_ASSET_UNIVERSE,
    CEFI_BASE_ASSETS,
    CEFI_OPTIONS_UNDERLYINGS,
    CLOB_VENUES,
    CME_MONTH_CODES,
    DATA_TYPES_BY_ASSET_GROUP,
    DEFI_INSTRUMENTS,
    DEFI_LENDING_ASSETS,
    DEFI_MAJOR_ASSET_ADDRESS_LIST,
    DEFI_MAJOR_ASSET_ADDRESSES,
    DEFI_MAJOR_ASSET_SYMBOLS,
    DEX_VENUE_KEYWORDS,
    DEX_VENUES,
    ENDPOINT_REGISTRY,
    EXPECTED_COVERAGE_BY_ASSET_GROUP,
    FX_SPOT_PAIRS,
    INSTRUMENT_TYPE_FOLDER_MAP,
    INSTRUMENT_TYPES_BY_VENUE,
    KNOWN_ETFS,
    OKX_FUTURES,
    OKX_SPOT,
    PROCESSED_REQUIRES_RAW,
    QUARTERLY_MONTHS,
    SPORTS_VENUES,
    TIMEFRAMES,
    TRADFI_DATABENTO_INSTRUMENTS,
    TRADFI_EQUITIES,
    TRADFI_FUTURES,
    TRADFI_INSTRUMENTS,
    TRADFI_TICKER_UNIVERSE,
    VENUE_CATEGORY_MAP,
    VENUE_COORDINATES,
    VENUE_DATA_AVAILABILITY,
    VENUE_TO_ASSET_GROUP,
    VENUES_BY_ASSET_GROUP,
    ZERO_ALPHA_VENUES,
    DataTypeConfig,
    EndpointSpec,
    ExchangeInstrumentConfig,
    ProviderDataAvailability,
    VenueCoordinates,
    VenueMapping,
    get_databento_symbols_for_venue,
    get_expected_data_types_for_venue,
    get_expected_instruments_for_venue,
    get_provider_availability,
    get_valid_data_types_for_venue,
    get_venue_coordinates,
    get_venue_data_type_start_date,
    is_per_instrument_shard_data_type,
)
from .signal_broadcast import (
    COUNTERPARTY_ENTITLEMENTS as COUNTERPARTY_ENTITLEMENTS,
)
from .signal_broadcast import (
    COUNTERPARTY_REGISTRY as COUNTERPARTY_REGISTRY,
)
from .signal_broadcast import (
    AckSource as AckSource,
)
from .signal_broadcast import (
    Counterparty as Counterparty,
)
from .signal_broadcast import (
    CounterpartyEntitlement as CounterpartyEntitlement,
)
from .signal_broadcast import (
    CounterpartyEntitlementProfile as CounterpartyEntitlementProfile,
)
from .signal_broadcast import (
    CounterpartyStatus as CounterpartyStatus,
)
from .signal_broadcast import (
    DeliveryAttempt as DeliveryAttempt,
)
from .signal_broadcast import (
    DeliveryStatus as DeliveryStatus,
)
from .signal_broadcast import (
    DirectionalIntent as DirectionalIntent,
)
from .signal_broadcast import (
    PayloadDepth as PayloadDepth,
)
from .signal_broadcast import (
    RateLimitConfig as RateLimitConfig,
)
from .signal_broadcast import (
    RestPullDeliveryConfig as RestPullDeliveryConfig,
)
from .signal_broadcast import (
    SchemaDepth as SchemaDepth,
)
from .signal_broadcast import (
    SignalAcknowledgement as SignalAcknowledgement,
)
from .signal_broadcast import (
    SignalEmission as SignalEmission,
)
from .signal_broadcast import (
    SignalPayload as SignalPayload,
)
from .signal_broadcast import (
    SignalPayloadMinimal as SignalPayloadMinimal,
)
from .signal_broadcast import (
    SignalPayloadRich as SignalPayloadRich,
)
from .signal_broadcast import (
    SignalPayloadStandard as SignalPayloadStandard,
)
from .signal_broadcast import (
    StrategySignalAcknowledged as StrategySignalAcknowledged,
)
from .signal_broadcast import (
    StrategySignalEmittedExternal as StrategySignalEmittedExternal,
)
from .signal_broadcast import (
    WebhookDeliveryConfig as WebhookDeliveryConfig,
)
from .signal_broadcast import (
    active_counterparties as active_counterparties,
)
from .signal_broadcast import (
    counterparty_for as counterparty_for,
)
from .signal_broadcast import (
    entitled_slots_for as entitled_slots_for,
)
from .signal_broadcast import (
    entitlements_for as entitlements_for,
)
from .sports import (
    BUNDESLIGA_TEAM_ALIASES as BUNDESLIGA_TEAM_ALIASES,
)
from .sports import (
    CANONICAL_TO_ODDS_API_BUNDESLIGA as CANONICAL_TO_ODDS_API_BUNDESLIGA,
)
from .sports import (
    CANONICAL_TO_ODDS_API_EPL as CANONICAL_TO_ODDS_API_EPL,
)
from .sports import (
    CANONICAL_TO_UNDERSTAT_EPL as CANONICAL_TO_UNDERSTAT_EPL,
)
from .sports import (
    EPL_TEAM_ALIASES as EPL_TEAM_ALIASES,
)
from .sports import (
    get_expected_leagues_for_source as get_expected_leagues_for_source,
)
from .sports import (
    get_prediction_leagues as get_prediction_leagues,
)

__all__ = [
    "ALERT_CODES",
    "ALERT_THRESHOLDS",
    "ALL_VENUES",
    "BAR_TIMEFRAMES",
    "BAR_TIMEFRAME_SECONDS",
    "BOOKMAKER_REGISTRY",
    "BREAKER_RECOVERY_DEFAULTS",
    "BUNDESLIGA_TEAM_ALIASES",
    "BUNDLED_DATA_TYPES",
    "CaptureStatusCounts",
    "compute_honest_coverage",
    "futures_expiry_bucket",
    "get_active_es_options_clusters_for_date",
    "CANONICAL_TO_ODDS_API_BUNDESLIGA",
    "CANONICAL_TO_ODDS_API_EPL",
    "CANONICAL_TO_UNDERSTAT_EPL",
    "CEFI_ACCEPTED_QUOTE_ASSETS",
    "CEFI_BASE_ASSETS",
    "CEFI_BASE_ASSET_UNIVERSE",
    "CEFI_FUTURES_CHAIN_TRADES",
    "CEFI_OPTIONS_CHAIN_TRADES",
    "CEFI_OPTIONS_UNDERLYINGS",
    "CEFI_PERPETUAL_BOOK_SNAPSHOT_5",
    "CEFI_PERPETUAL_DERIVATIVE_TICKER",
    "CEFI_PERPETUAL_LIQUIDATIONS",
    "CEFI_PERPETUAL_QUOTES",
    "CEFI_PERPETUAL_TRADES",
    "CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5",
    "CEFI_SPOT_PAIR_TRADES",
    "CLOB_VENUES",
    "CME_MONTH_CODES",
    "CONFIG_REQUIRED_FIELDS",
    "CONFIG_SCHEMA",
    "CONTRACT_REGISTRY",
    "COUNTERPARTY_ENTITLEMENTS",
    "COUNTERPARTY_REGISTRY",
    "CUTOVER_ARCHETYPES",
    "DATA_SOURCE_TO_SECRET",
    "DATA_SOURCE_TO_VENUES",
    "DATA_TYPES_BY_ASSET_GROUP",
    "DATA_TYPE_TO_CLUSTER_REGISTRY",
    "DEFI_AAVE_V3_LENDING_INDICES",
    "DEFI_DEX_POOL_DEX_POOL_STATE",
    "DEFI_DEX_POOL_DEX_POOL_SWAPS",
    "DEFI_INSTRUMENTS",
    "DEFI_LENDING_ASSETS",
    "DEFI_LENDING_FLASH_LOAN_EVENTS",
    "DEFI_LENDING_INDICES_MARKET_ID",
    "DEFI_LENDING_LIQUIDATIONS",
    "DEFI_LENDING_LIQUIDATION_EVENTS",
    "DEFI_LENDING_POSITION_DATA",
    "DEFI_LENDING_POSITION_LENDING_INDICES",
    "DEFI_LST_LST_RATES",
    "DEFI_MAJOR_ASSET_ADDRESSES",
    "DEFI_MAJOR_ASSET_ADDRESS_LIST",
    "DEFI_MAJOR_ASSET_SYMBOLS",
    "DEFI_PERPETUAL_PERP_FUNDING",
    "DEFI_POOL_DEX_POOL_SWAPS",
    "DEFI_SPOT_ASSET_BRIDGE_EVENTS",
    "DEFI_SPOT_ASSET_GAS_FEES",
    "DEFI_SPOT_ASSET_GOVERNANCE_EVENTS",
    "DEFI_SPOT_ASSET_MEV_EVENTS",
    "DEFI_SPOT_ASSET_ORACLE_PRICES",
    "DEFI_SPOT_ASSET_TOKEN_TRANSFERS",
    "DEFI_STAKING_EIGENLAYER_REWARDS",
    "DEFI_STAKING_STAKING_YIELDS",
    "DEFI_STAKING_YIELD_SNAPSHOTS",
    "DEX_VENUES",
    "DEX_VENUE_KEYWORDS",
    "EMPTY_CONFIRMED_REASONS",
    "ENDPOINT_REGISTRY",
    "EPL_TEAM_ALIASES",
    "EVENT_CONTRACT_ROOT_CLUSTERS",
    "EXCHANGE_BY_TICKER",
    "EXPECTED_COVERAGE_BY_ASSET_GROUP",
    "EXPECTED_EMPTY_REASON_PREFIX",
    "EXPECTED_WINDOW_COMPLETENESS_FRACTION_COLUMN",
    "FUTURES_CHAIN_BUCKETS",
    "FX_SPOT_PAIRS",
    "INSTRUMENT_SCHEMA",
    "INSTRUMENT_TYPES_BY_VENUE",
    "INSTRUMENT_TYPE_FOLDER_MAP",
    "KNOWN_ETFS",
    "LAST_EMISSION_DECISION_AT_COLUMN",
    "LIVE_ALERT_RULES",
    "LIVE_CLUSTER_REGISTRY",
    "MANIFEST_SCHEMA_VERSION_V8",
    "ODDS_API_KEY_TO_VENUE",
    "ODDS_API_KEY_TO_VENUE_CATEGORY",
    "OKX_FUTURES",
    "OKX_SPOT",
    "OPTIONAL_CONFIG_FIELDS",
    "PROCESSED_REQUIRES_RAW",
    "QUARTERLY_MONTHS",
    "READER_FALLBACK_WINDOW_DAYS",
    "REQUIRED_CONFIG_FIELDS",
    "RISK_TYPE_CATEGORIES",
    "SCENARIO_ARCHETYPE_MATRIX",
    "SCENARIO_REGISTRY",
    "SCHEDULER_REGISTRY",
    "SERVICE_EMISSION_STATES",
    "SERVICE_EMISSION_STATE_COLUMN",
    "SHARE_CLASS_BASE_ASSETS",
    "SPORTS_VENUES",
    "STRATEGY_FAMILY_REGISTRY",
    "SYNTHETIC_GENERATOR_REGISTRY",
    "TIMEFRAMES",
    "TRADFI_DATABENTO_INSTRUMENTS",
    "TRADFI_EQUITIES",
    "TRADFI_EQUITY_OHLCV_1M",
    "TRADFI_EQUITY_TRADES",
    "TRADFI_FUTURES",
    "TRADFI_FUTURE_OHLCV_1M",
    "TRADFI_FUTURE_TRADES",
    "TRADFI_INDEX_TRADES",
    "TRADFI_INSTRUMENTS",
    "TRADFI_OPTIONS_CHAIN_TRADES",
    "TRADFI_TICKER_UNIVERSE",
    "UNDERLYING_NORMALIZATION",
    "V8_COLUMN_DEFAULTS",
    "V8_NEW_COLUMNS",
    "VALID_ALGORITHMS",
    "VALID_ASSET_GROUPS",
    "VALID_BOOK_TYPES",
    "VALID_INSTRUCTION_TYPES",
    "VALID_MODES",
    "VALID_TIMEFRAMES",
    "VENUES_BY_ASSET_GROUP",
    "VENUE_CATEGORY_MAP",
    "VENUE_CONTRACT_OVERRIDES",
    "VENUE_COORDINATES",
    "VENUE_DATA_AVAILABILITY",
    "VENUE_ERROR_MAP",
    "VENUE_EXECUTION_REGISTRY",
    "VENUE_HEARTBEAT_THRESHOLDS",
    "VENUE_TO_ASSET_GROUP",
    "VENUE_TO_DATA_SOURCE",
    "VENUE_TO_DATA_SOURCES",
    "ZERO_ALPHA_VENUES",
    "AaveBorrowParams",
    "AaveDepositParams",
    "AaveFlashLoanParams",
    "AaveRepayParams",
    "AaveV3ReserveData",
    "AaveV3UserAccountData",
    "AaveV3UserReserveData",
    "AccountVerificationLevel",
    "AckSource",
    "AggregatedPosition",
    "AlertChannel",
    "AlertCode",
    "AlertRule",
    "AlertSeverity",
    "AlertThreshold",
    "AllocationExecutionStatus",
    "AllocatorCashAccountView",
    "AllocatorRedemption",
    "AllocatorSubscription",
    "AlternativeDataSignal",
    "AlternativeDataType",
    "AntiDetectionLevel",
    "ApproveSubscriptionRequest",
    "ArbitrageMarket",
    "ArbitrageOpportunity",
    "ArbitrageStatus",
    "AssetClass",
    # Honest-coverage taxonomy — UTL ManifestWriter consumers
    "AssetGroup",
    "AsterExchangeInfo",
    "BarBoundaryViolationError",
    "BarTimeframe",
    "BenchmarkType",
    "BetExecution",
    "BetOrder",
    "BetRejectedError",
    "BetSide",
    "BetStatus",
    "BetfairCurrentOrderSummary",
    "BetfairListCurrentOrdersResponse",
    "BetfairMarketCatalogue",
    "BetfairRunnerCatalog",
    "BettingSignal",
    "BinanceFuturesExchangeInfo",
    "BinanceInstrumentInfo",
    "BinanceLiquidationOrder",
    "BinanceMarkPriceUpdate",
    "BinanceOptionInstrumentInfo",
    "BATCH_FILL_ALGO_TYPES",
    "BENCHMARK_FILL_ALGO_TYPE",
    "NORMAL_ALGO_TYPE",
    "BatchExecutionMode",
    "BinanceOrderBook",
    "BinanceTicker",
    "BinanceTrade",
    "BinanceWithdrawRequest",
    "BinanceWithdrawResponse",
    "BookLevel",
    "BookSpoof",
    "BookmakerCategory",
    "BookmakerInfo",
    "BookmakerRegistry",
    "BookmakerUnavailableError",
    "BreakerAction",
    "BreakerConfig",
    "BreakerFiredEvent",
    "BreakerRecoveryMode",
    "BreakerRecoveryRule",
    "BreakerScope",
    "BreakerTrigger",
    "BucketMarket",
    "BusTransferType",
    "BybitInstrumentInfo",
    "BybitInstrumentsResponse",
    "BybitLiquidationOrder",
    "BybitOrderBook",
    "BybitTicker",
    "BybitWithdrawRequest",
    "BybitWithdrawResponse",
    "CLVRecord",
    "CanonicalAccountSnapshot",
    "CanonicalAccountState",
    "CanonicalAuthenticationError",
    "CanonicalAuthorizationError",
    "CanonicalBalance",
    "CanonicalBase",
    "CanonicalBetMarket",
    "CanonicalBetOrder",
    "CanonicalBondData",
    "CanonicalBookmakerMarket",
    "CanonicalCdsSpread",
    "CanonicalComboBet",
    "CanonicalComboLeg",
    "CanonicalComputeService",
    "CanonicalContractExpiredError",
    "CanonicalDerivativeTicker",
    "CanonicalDuplicateOrderError",
    "CanonicalError",
    "CanonicalFeatureRecord",
    "CanonicalFee",
    "CanonicalFill",
    "CanonicalFixture",
    "CanonicalFixtureEvent",
    "CanonicalFixtureStatsDetail",
    "CanonicalFundingRate",
    "CanonicalFuturesContract",
    "CanonicalInjury",
    "CanonicalInstrument",
    "CanonicalInstrumentHaltedError",
    "CanonicalInsufficientBalanceError",
    "CanonicalInsufficientMarginError",
    "CanonicalInternalServerError",
    "CanonicalInvalidRequestError",
    "CanonicalLeague",
    "CanonicalLineup",
    "CanonicalLiquidation",
    "CanonicalLiquidationCluster",
    "CanonicalMaintenanceModeError",
    "CanonicalMarginState",
    "CanonicalMarketClosedError",
    "CanonicalMarketStateEvent",
    "CanonicalNetworkError",
    "CanonicalOdds",
    "CanonicalOhlcvBar",
    "CanonicalOnChainMetric",
    "CanonicalOptionsChainEntry",
    "CanonicalOrder",
    "CanonicalOrderAmendment",
    "CanonicalOrderBook",
    "CanonicalOrderRejectedError",
    "CanonicalOrderRejection",
    "CanonicalPlayer",
    "CanonicalPlayerMatchStats",
    "CanonicalPosition",
    "CanonicalPositionLimitExceededError",
    "CanonicalPredictionMarket",
    "CanonicalPriceBoundError",
    "CanonicalProgressiveOdds",
    "CanonicalProgressiveStats",
    "CanonicalPullRequest",
    "CanonicalRateLimitError",
    "CanonicalReferee",
    "CanonicalRepository",
    "CanonicalSchemaError",
    "CanonicalServiceUnavailableError",
    "CanonicalSettlement",
    "CanonicalSizeLimitError",
    "CanonicalSpread",
    "CanonicalTeam",
    "CanonicalTicker",
    "CanonicalTrade",
    "CanonicalUnknownVenueError",
    "CanonicalVenue",
    "CanonicalWebSocketLifecycle",
    "CanonicalWorkflowRun",
    "CanonicalYieldCurvePoint",
    "CashAccountMovement",
    "CcxtAggTrade",
    "CcxtFundingRate",
    "CcxtMarket",
    "CcxtOhlcv",
    "CcxtOpenInterest",
    "CcxtOrderBook",
    "CcxtTicker",
    "CcxtTrade",
    "ChainKind",
    "CircuitBreakerId",
    "ClientLifecycleEvent",
    "ClientLifecycleKind",
    "ClientQuarantinedEvent",
    "ClientReadyEvent",
    "ClientRiskLimits",
    "ClientsYaml",
    "ClientsYamlEntry",
    "CloudProvider",
    "CloudTarget",
    "CoinbaseOrderBook",
    "CoinbaseProductInfo",
    "CoinbaseProductsResponse",
    "CoinbaseTicker",
    "CoinbaseTrade",
    "CoinbaseWithdrawRequest",
    "CoinbaseWithdrawResponse",
    "ColumnSpec",
    "ComboLeg",
    "ComboQuote",
    "ComboStrategyType",
    "CommissionModel",
    "CompoundV3MarketInfo",
    "CompoundV3UserPosition",
    "ComputeTarget",
    "ComputeType",
    "ContractSpec",
    "Counterparty",
    "CounterpartyEntitlement",
    "CounterpartyEntitlementProfile",
    "CounterpartyStatus",
    "CredentialType",
    "CrossVenueArbLeg",
    "CrossVenueArbSignal",
    "CrossVenueLink",
    "CurveDepositParams",
    "CurveSwapParams",
    "CurveWithdrawParams",
    "DarkPoolPrintRecord",
    "DataSourceMapping",
    "DataSourceRoute",
    "DataTypeConfig",
    "DatabentoError",
    "DeFiAggregatedHealth",
    "DeFiLPAggregatedMetrics",
    "DeFiStakingAggregatedMetrics",
    "DefiAlertType",
    "DefiErrorCode",
    "DeliveryAttempt",
    "DeliveryStatus",
    "DepositAddress",
    "DepositRecord",
    "DeribitAccountSummaryResponse",
    "DeribitCancelResponse",
    "DeribitGetInstrumentResponse",
    "DeribitGetInstrumentsResponse",
    "DeribitInstrumentInfoFull",
    "DeribitInstrumentsResponse",
    "DeribitOpenOrdersResponse",
    "DeribitOrderResponse",
    "DeribitOrderStateResponse",
    "DeribitPositionsResponse",
    "DeribitTickerResponse",
    "DirectionalIntent",
    "DropRows",
    # Service emission policy — UTL emission_publisher consumers
    "EmissionLifecycleEvent",
    "EmptyConfirmedReason",
    "EndpointSpec",
    "EnvironmentTier",
    "Erc20TransferCalldata",
    "Erc20TransferFromCalldata",
    "ErrorAction",
    "EthSendRawTransactionRequest",
    "EthSendRawTransactionResponse",
    "EthSendTransactionRequest",
    "EthTransactionRequest",
    "EtherFiStakeResponse",
    "EtherFiUnstakeResponse",
    "EulerBorrowParams",
    "EulerDepositParams",
    "EulerRepayParams",
    "EulerUserPosition",
    "EulerVaultData",
    "EventDrop",
    "EventDuplicate",
    "ExchangeFeeSchedule",
    "ExchangeInstrumentConfig",
    "ExecutionAlpha",
    "ExecutionInstruction",
    "ExecutionMethod",
    "ExecutionRejectionCode",
    "ExecutionRejectionEvent",
    "ExecutionResult",
    "ExecutionStatus",
    "ExpectedValue",
    "ExperimentKind",
    "ExperimentRunSpec",
    "ExperimentStatus",
    "FeatureMetadata",
    "FeeStructure",
    "FeeType",
    "FixtureMapping",
    "FixtureNotFoundError",
    "FluidBorrowParams",
    "FluidDepositParams",
    "FluidRepayParams",
    "FundAllocation",
    "ArchetypeAllocationDirective",
    "FundNAVSnapshot",
    "StrategyPnlStreamEvent",
    "FundTransferContext",
    "FundingRateHistory",
    "FuturesContractLifecyclePhase",
    "GasSurge",
    "HealthPingResponse",
    "HttpRateLimitHeaders",
    "HyperliquidAssetInfo",
    "HyperliquidFill",
    "HyperliquidMeta",
    "HyperliquidOpenOrder",
    "HyperliquidPosition",
    "HyperliquidUserState",
    "IBKRAccountValue",
    "IBKRContractDetails",
    "IBKRCorporateAction",
    "IBKRPosition",
    "InstructionType",
    "InstrumentType",
    "InsuranceFundState",
    "InternalTransfer",
    "KalshiMarket",
    "KalshiOrderBook",
    "KalshiTrade",
    "KillSwitchArmRequest",
    "KillSwitchArmedEvent",
    "KillSwitchDisarmEvent",
    "KillSwitchId",
    "KillSwitchProvenance",
    "KillSwitchScope",
    "LPProtocolBreakdown",
    "LatencyComponent",
    "LatencyInject",
    "LegacyBlankErrorReasonError",
    "RecordFailedReason",
    "LidoRequestWithdrawalsParams",
    "LidoSubmitParams",
    "LidoSubmitResponse",
    "LidoWstEthWrapResponse",
    "LifecycleClass",
    "LineupPlayer",
    "LiveClusterDeploymentKind",
    "LiveClusterSpec",
    "LiveMatchState",
    "LiveOddsUpdate",
    "LongShortRatio",
    "ManifestPhantom",
    "ManifestRowBlockedError",
    "MappingRule",
    "MarginType",
    "MarketClosedError",
    "MarketSession",
    "MarketState",
    "MarketStatus",
    "MarketTrade",
    "MatchPeriod",
    "MinBalancePerVenue",
    "MorphoBorrowParams",
    "MorphoFlashLoanParams",
    "MorphoMarketParams",
    "MorphoRepayParams",
    "MorphoSupplyParams",
    "MorphoUserPosition",
    "MultiLegInstrument",
    "NegRiskArbSignal",
    "NegRiskBucket",
    "NetworkJitterMetric",
    "NormalizedStrikeCoordinate",
    "OKXFundingRate",
    "OKXInstrumentInfo",
    "OKXInstrumentsResponse",
    "OKXLiquidationOrder",
    "OKXMarkPrice",
    "OKXOrderBook",
    "OKXTicker",
    "OKXWithdrawRequest",
    "OKXWithdrawResponse",
    "OddsChangedError",
    "OddsFormat",
    "OddsType",
    "OpenInterestHistory",
    "OperationType",
    "OptionChainSnapshot",
    "OptionType",
    "OptionsFlowRecord",
    "OracleDeviate",
    "OracleDeviationError",
    "OracleStaleError",
    "OrderBookSnapshot5",
    "OrderLatencyRecord",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "OrphanDetector",
    "OutcomeCategory",
    "OutcomeType",
    "PayloadDepth",
    "PipelineMode",
    "PlayerMapping",
    "PolymarketGammaMarket",
    "PolymarketPosition",
    "PolygonOptionContract",
    "PolygonOptionContractsResponse",
    "PolygonTicker",
    "PolygonTickersResponse",
    "PortfolioGreeksSnapshot",
    "PortfolioMarginAccount",
    "PortfolioPnLAttribution",
    "PortfolioView",
    "PositionRisk",
    "PredictionMarketCategory",
    "PredictionMarketMapper",
    "PredictionMarketUniverse",
    "PreflightFailed",
    "PreflightOK",
    "PreflightResult",
    "PriceShift",
    "ProbabilityBucket",
    "ProcessRedemptionRequest",
    "ProcessedOddsOutput",
    "ProtocolHealthBreakdown",
    "ProviderDataAvailability",
    "QuarantineReason",
    "RateLimitConfig",
    "RateLimitInfo",
    "RateLimitResponse",
    "RebalanceRequest",
    "RedeemRequest",
    "RedemptionStatus",
    "RejectFills",
    "RejectRequest",
    "RestPullDeliveryConfig",
    "RiskCategory",
    "RiskGroupSummary",
    "RiskType",
    "RowSchemaValidationError",
    "SatelliteObservation",
    "ScalingMode",
    "ScenarioApplicabilityFilter",
    "ScenarioCategory",
    "ScenarioMutationSpec",
    "ScenarioOutcomeAssertion",
    "ScenarioOutcomeResult",
    "ScenarioOverlay",
    "ScenarioOverlayLayer",
    "ScenarioReport",
    "SchedulerSpec",
    "SchedulerTargetKind",
    "SchemaContract",
    "SchemaContractNotFoundError",
    "SchemaDepth",
    "ScraperError",
    "ScraperVersionMeta",
    "SentimentScore",
    "ServiceEmissionPolicy",
    "ServiceEmissionStateEnum",
    "SessionPhase",
    "SettlementEvent",
    "ShareClass",
    "ShardCapacityEvent",
    "ShardRecommendedAction",
    "SignalAcknowledgement",
    "SignalEmission",
    "SignalPayload",
    "SignalPayloadMinimal",
    "SignalPayloadRich",
    "SignalPayloadStandard",
    "SignalSource",
    "SourceControlProvider",
    "Sport",
    "SportsArbLeg",
    "SportsArbPosition",
    "SportsError",
    "SportsbookLink",
    "SpreadLeg",
    "StakingProtocolBreakdown",
    "StaleHold",
    "StrategyFamily",
    "StrategyFamilyId",
    "StrategySignalAcknowledged",
    "StrategySignalEmittedExternal",
    "SubAccount",
    "SubscribeRequest",
    "SubscriptionStatus",
    "SyntheticDataDomain",
    "SyntheticGeneratorId",
    "SyntheticGeneratorSpec",
    "SyntheticOutputManifest",
    "SyntheticParams",
    "SyntheticRealismAxis",
    "SyntheticRunManifest",
    "SyntheticShardLayout",
    "SyntheticShardManifest",
    "TardisExchangeDetail",
    "TardisInstrumentDetail",
    "TeamMapping",
    "ThresholdUnit",
    "TransferIntent",
    "TransferResult",
    "TransferResultStatus",
    "TimeInForce",
    "UnderlyingGreeksBreakdown",
    "UniswapV3PoolStateResponse",
    "UniswapV3QuoteResponse",
    "UniswapV3SwapTxReceipt",
    "UnknownAlertCodeError",
    "UnknownThresholdKeyError",
    "UnsupportedCapabilityError",
    "UpbitBalanceQueryResponse",
    "UpbitTicker",
    "UpbitWithdrawRequest",
    "UpbitWithdrawResponse",
    "VenueAuthStatus",
    "VenueCategory",
    "VenueCoordinates",
    "VenueErrorClassification",
    "VenueExecutionProfile",
    "VenueMapping",
    "VenuePositionBreakdown",
    "VenueRateLimitSpec",
    "Violation",
    "VmPrefixSpec",
    "VmQuotaShape",
    "VolSmilePoint",
    "VolSurface",
    "VolSurfaceSlice",
    "VolTermStructure",
    "WebSocketCloseInfo",
    "WebSocketConnectionClosed",
    "WebSocketConnectionOpened",
    "WebSocketEvent",
    "WebhookDeliveryConfig",
    "WithdrawalRecord",
    "active_counterparties",
    "american_to_decimal",
    "assert_bar_boundary_contract",
    "bar_window_for_close",
    "breaker_fired_event",
    "build_cefi_partition_path",
    "build_combo_id",
    "build_defi_partition_path",
    "build_instrument_id",
    "build_prediction_partition_path",
    "build_tradfi_partition_path",
    "classify_cloud_run_service",
    "classify_experiment_run",
    "classify_scheduled_job",
    "classify_session",
    "classify_venue_error",
    "classify_vm_name",
    "counterparty_for",
    "decimal_to_american",
    "emission_latency_ms_for_source",
    "entitled_slots_for",
    "entitlements_for",
    "family_for_archetype",
    "generators_for_archetype",
    "get_clusters_for_env",
    "get_data_sources_for_venue",
    "get_databento_symbols_for_venue",
    "get_emission_policy",
    "get_expected_bookmakers",
    "get_expected_data_types_for_venue",
    "get_valid_data_types_for_venue",
    "get_expected_instruments_for_venue",
    "get_expected_leagues_for_source",
    "get_generator_spec",
    "get_heartbeat_threshold",
    "get_prediction_leagues",
    "get_primary_source",
    "get_primary_source_with_latency",
    "get_provider_availability",
    # Features DAG — UTL point_in_time + features-* consumers
    "get_required_inputs",
    "get_required_secrets",
    "get_schedulers_for_env",
    "get_source_priority",
    "get_venue_coordinates",
    "get_venue_data_type_start_date",
    "has_source_priority",
    "is_batch",
    "is_emission_policy_declared",
    "is_live",
    "is_per_instrument_shard_data_type",
    "lookup_contract",
    "matrix_cell_count",
    "next_state",
    "normalize_underlying",
    "pipeline_mode_for_source",
    "policy_is_alert",
    "policy_is_publish_row",
    "read_with_source_priority",
    "register_generator",
    "register_scenario",
    "resolve_environment_from_env",
    "resolve_environment_from_hostname",
    "resolve_exchange",
    "scenarios_for_archetype",
    "source_string_for",
    "validate_dataframe",
    "validate_preflight_for_trigger",
    "validate_row_df",
]

# fmt: off
_VENUES = [
    "alchemy", "api_football", "aster", "barchart", "betfair", "binance",
    "bybit", "cambrian", "ccxt", "aws", "gcp", "coinbase", "databento", "defi", "defillama",
    "deribit", "eigenlayer", "footystats", "github", "hyperliquid", "ibkr", "kalshi",
    "mev", "metabet", "morpho_blue_api", "nautilus", "odds_api", "odds_engine", "okx",
    "open_meteo", "opticodds", "picasso", "pinnacle", "polymarket", "soccer_football_info",
    "sky", "solayer", "tardis", "thegraph", "transfermarkt", "understat", "upbit", "yahoo_finance",
]
# fmt: on
for _v in _VENUES:
    _mod = cast(ModuleType, __import__(f"{__name__}.external.{_v}", fromlist=[_v]))
    sys.modules[f"{__name__}.{_v}"] = _mod
