"""API contracts: Pydantic schemas and VCR mocks for external APIs."""

import sys
from types import ModuleType
from typing import cast

from .canonical.canonical_mappings import (
    DATA_SOURCE_TO_SECRET,
    DATA_SOURCE_TO_VENUES,
    DATASET_TO_CANONICAL_VENUE,
    SYMBOL_MAPPINGS,
    VENUE_TO_DATA_SOURCE,
    VENUE_TO_DATA_SOURCES,
    ContractSpec,
    DataSourceMapping,
    DataSourceRoute,
    get_data_sources_for_venue,
    get_required_secrets,
)
from .canonical.crosscutting.errors import (
    DATABENTO_ERROR_MAP,
    VENUE_ERROR_MAP,
    CanonicalAuthenticationError,
    CanonicalAuthorizationError,
    CanonicalContractExpiredError,
    CanonicalDuplicateOrderError,
    CanonicalError,
    CanonicalInstrumentHaltedError,
    CanonicalInsufficientBalanceError,
    CanonicalInsufficientMarginError,
    CanonicalInternalServerError,
    CanonicalInvalidRequestError,
    CanonicalMaintenanceModeError,
    CanonicalMarketClosedError,
    CanonicalNetworkError,
    CanonicalOrderRejectedError,
    CanonicalPositionLimitExceededError,
    CanonicalPriceBoundError,
    CanonicalRateLimitError,
    CanonicalSchemaError,
    CanonicalServiceUnavailableError,
    CanonicalSizeLimitError,
    CanonicalUnknownVenueError,
    DatabentoError,
    DefiAlertType,
    DefiErrorCode,
    ErrorAction,
    RateLimitInfo,
    RateLimitResponse,
    VenueErrorClassification,
    WebSocketCloseInfo,
    classify_venue_error,
)
from .canonical.domain import (
    BOOKMAKER_REGISTRY,
    ODDS_API_KEY_TO_VENUE,
    ODDS_API_KEY_TO_VENUE_CATEGORY,
    RISK_TYPE_CATEGORIES,
    SHARE_CLASS_BASE_ASSETS,
    VENUE_EXECUTION_REGISTRY,
    AccountVerificationLevel,
    AggregatedPosition,
    AlternativeDataSignal,
    AlternativeDataType,
    AntiDetectionLevel,
    ArbitrageMarket,
    ArbitrageOpportunity,
    ArbitrageStatus,
    AssetClass,
    BenchmarkType,
    BetExecution,
    BetOrder,
    BetRejectedError,
    BetSide,
    BetStatus,
    BettingSignal,
    BinanceWithdrawRequest,
    BinanceWithdrawResponse,
    BookLevel,
    BookmakerCategory,
    BookmakerInfo,
    BookmakerRegistry,
    BookmakerUnavailableError,
    BybitWithdrawRequest,
    BybitWithdrawResponse,
    CanonicalAccountSnapshot,
    CanonicalAccountState,
    CanonicalBalance,
    CanonicalBase,
    CanonicalBetMarket,
    CanonicalBetOrder,
    CanonicalBondData,
    CanonicalBookmakerMarket,
    CanonicalCdsSpread,
    CanonicalComboBet,
    CanonicalComboLeg,
    CanonicalComputeService,
    CanonicalDerivativeTicker,
    CanonicalFeatureRecord,
    CanonicalFee,
    CanonicalFill,
    CanonicalFixture,
    CanonicalFixtureEvent,
    CanonicalFixtureStatsDetail,
    CanonicalFundingRate,
    CanonicalInjury,
    CanonicalInstrument,
    CanonicalLeague,
    CanonicalLineup,
    CanonicalLiquidation,
    CanonicalLiquidationCluster,
    CanonicalMarginState,
    CanonicalMarketStateEvent,
    CanonicalOdds,
    CanonicalOhlcvBar,
    CanonicalOnChainMetric,
    CanonicalOptionsChainEntry,
    CanonicalOrder,
    CanonicalOrderAmendment,
    CanonicalOrderBook,
    CanonicalOrderRejection,
    CanonicalPlayer,
    CanonicalPlayerMatchStats,
    CanonicalPosition,
    CanonicalPredictionMarket,
    CanonicalProgressiveOdds,
    CanonicalProgressiveStats,
    CanonicalPullRequest,
    CanonicalReferee,
    CanonicalRepository,
    CanonicalSettlement,
    CanonicalSpread,
    CanonicalTeam,
    CanonicalTicker,
    CanonicalTrade,
    CanonicalVenue,
    CanonicalWebSocketLifecycle,
    CanonicalWorkflowRun,
    CanonicalYieldCurvePoint,
    CloudProvider,
    CLVRecord,
    CoinbaseWithdrawRequest,
    CoinbaseWithdrawResponse,
    CollateralAsset,
    ComboLeg,
    ComboQuote,
    ComboStrategyType,
    CommissionModel,
    ComputeTarget,
    ComputeType,
    CredentialType,
    CrossMarginNettingResult,
    DarkPoolPrintRecord,
    DeFiAggregatedHealth,
    DeFiLPAggregatedMetrics,
    DeFiStakingAggregatedMetrics,
    DepositAddress,
    DepositRecord,
    Erc20TransferCalldata,
    Erc20TransferFromCalldata,
    EthSendRawTransactionRequest,
    EthSendRawTransactionResponse,
    EthSendTransactionRequest,
    EthTransactionRequest,
    ExchangeFeeSchedule,
    ExecutionAlpha,
    ExecutionInstruction,
    ExecutionMethod,
    ExecutionResult,
    ExecutionStatus,
    ExpectedValue,
    FeatureMetadata,
    FeeType,
    FixtureMapping,
    FixtureNotFoundError,
    FundingRateHistory,
    HealthPingResponse,
    HttpRateLimitHeaders,
    InstructionType,
    InstrumentType,
    InsuranceFundState,
    InternalTransfer,
    LatencyComponent,
    LineupPlayer,
    LiveMatchState,
    LiveOddsUpdate,
    LongShortRatio,
    LPProtocolBreakdown,
    MappingRule,
    MarginType,
    MarketClosedError,
    MarketState,
    MarketStatus,
    MarketTrade,
    MatchPeriod,
    MultiLegInstrument,
    NetClearingInstruction,
    NetworkJitterMetric,
    NormalizedStrikeCoordinate,
    OddsChangedError,
    OddsFormat,
    OddsType,
    OKXWithdrawRequest,
    OKXWithdrawResponse,
    OpenInterestHistory,
    OperationType,
    OptionChainSnapshot,
    OptionsFlowRecord,
    OptionType,
    OrderBookSnapshot5,
    OrderLatencyRecord,
    OrderSide,
    OrderStatus,
    OrderType,
    OrphanDetector,
    OutcomeType,
    PlayerMapping,
    PortfolioGreeksSnapshot,
    PortfolioMarginAccount,
    PortfolioPnLAttribution,
    PortfolioView,
    PositionRisk,
    PredictionMarketCategory,
    PredictionMarketMapper,
    PrimeBrokerAccount,
    PrimeBrokerError,
    PrimeBrokerFill,
    PrimeBrokerMarginCall,
    PrimeBrokerPosition,
    PrimeBrokerProvider,
    ProcessedOddsOutput,
    ProtocolHealthBreakdown,
    RiskCategory,
    RiskGroupSummary,
    RiskType,
    SatelliteObservation,
    ScalingMode,
    ScraperError,
    ScraperVersionMeta,
    SentimentScore,
    SettlementEvent,
    ShareClass,
    SignalSource,
    SourceControlProvider,
    Sport,
    SportsArbLeg,
    SportsArbPosition,
    SportsError,
    SpreadLeg,
    StakingProtocolBreakdown,
    SubAccount,
    TeamMapping,
    TimeInForce,
    UnderlyingGreeksBreakdown,
    UpbitWithdrawRequest,
    UpbitWithdrawResponse,
    VenueCategory,
    VenueExecutionProfile,
    VenuePositionBreakdown,
    VenueRateLimitSpec,
    VmQuotaShape,
    VolSmilePoint,
    VolSurface,
    VolSurfaceSlice,
    VolTermStructure,
    WebSocketConnectionClosed,
    WebSocketConnectionOpened,
    WebSocketEvent,
    WithdrawalRecord,
)
from .config.trading_validation import (
    CONFIG_REQUIRED_FIELDS,
    CONFIG_SCHEMA,
    INSTRUMENT_SCHEMA,
    OPTIONAL_CONFIG_FIELDS,
    REQUIRED_CONFIG_FIELDS,
    VALID_ALGORITHMS,
    VALID_BOOK_TYPES,
    VALID_CATEGORIES,
    VALID_INSTRUCTION_TYPES,
    VALID_MODES,
    VALID_TIMEFRAMES,
)
from .external.aster.schemas import AsterExchangeInfo
from .external.betfair import (
    BetfairCurrentOrderSummary,
    BetfairListCurrentOrdersResponse,
    BetfairMarketCatalogue,
)
from .external.betfair.schemas import BetfairRunnerCatalog
from .external.binance import (
    BinanceLiquidationOrder,
    BinanceMarkPriceUpdate,
    BinanceOrderBook,
    BinanceTicker,
    BinanceTrade,
)
from .external.binance.market_schemas import (
    BinanceFuturesExchangeInfo,
    BinanceInstrumentInfo,
    BinanceOptionInstrumentInfo,
)
from .external.bybit.schemas import (
    BybitInstrumentInfo,
    BybitInstrumentsResponse,
    BybitLiquidationOrder,
    BybitOrderBook,
    BybitTicker,
)
from .external.ccxt.schemas import (
    CcxtAggTrade,
    CcxtFundingRate,
    CcxtMarket,
    CcxtOhlcv,
    CcxtOpenInterest,
    CcxtOrderBook,
    CcxtTicker,
    CcxtTrade,
)
from .external.coinbase.schemas import (
    CoinbaseOrderBook,
    CoinbaseProductInfo,
    CoinbaseProductsResponse,
    CoinbaseTicker,
    CoinbaseTrade,
)
from .external.coinglass.schemas import (
    LiquidationHeatmapResponse,
    LiquidationLevel,
)
from .external.deribit.schemas import (
    DeribitAccountSummaryResponse,
    DeribitCancelResponse,
    DeribitGetInstrumentResponse,
    DeribitGetInstrumentsResponse,
    DeribitInstrumentInfoFull,
    DeribitInstrumentsResponse,
    DeribitOpenOrdersResponse,
    DeribitOrderResponse,
    DeribitOrderStateResponse,
    DeribitPositionsResponse,
    DeribitTickerResponse,
)
from .external.hyblock.schemas import (
    HyblockLiquidationLevelEntry,
    HyblockLiquidationLevelResponse,
    HyblockOIClusterEntry,
)
from .external.hyperliquid.schemas import (
    HyperliquidAssetInfo,
    HyperliquidFill,
    HyperliquidFundingHistoryEntry,
    HyperliquidMeta,
    HyperliquidOpenOrder,
    HyperliquidPosition,
    HyperliquidUserState,
)
from .external.ibkr import (
    IBKRAccountValue,
    IBKRContractDetails,
    IBKRCorporateAction,
    IBKRPosition,
)
from .external.kalshi.schemas import (
    KalshiMarket,
    KalshiOrderBook,
    KalshiTrade,
)
from .external.manifold.schemas import (
    ManifoldMarket,
    ManifoldPrice,
    ManifoldTrade,
)
from .external.okx.schemas import (
    OKXFundingRate,
    OKXInstrumentInfo,
    OKXInstrumentsResponse,
    OKXLiquidationOrder,
    OKXMarkPrice,
    OKXOrderBook,
    OKXTicker,
)
from .external.polygon.schemas import (
    PolygonDividend,
    PolygonDividendsResponse,
    PolygonOptionContract,
    PolygonOptionContractsResponse,
    PolygonSplit,
    PolygonSplitsResponse,
    PolygonTicker,
    PolygonTickersResponse,
)
from .external.polymarket import (
    PolymarketGammaMarket,
    PolymarketPosition,
)
from .external.polymarket.arb_schemas import (
    BucketMarket,
    CrossVenueArbLeg,
    CrossVenueArbSignal,
    CrossVenueLink,
    NegRiskArbSignal,
    NegRiskBucket,
    PredictionMarketUniverse,
    ProbabilityBucket,
    SportsbookLink,
)
from .external.protocol_sdks.schemas import (
    AaveBorrowParams,
    AaveDepositParams,
    AaveFlashLoanParams,
    AaveRepayParams,
    AaveV3ReserveData,
    AaveV3UserAccountData,
    AaveV3UserReserveData,
    CompoundV3MarketInfo,
    CompoundV3UserPosition,
    CurveDepositParams,
    CurveSwapParams,
    CurveWithdrawParams,
    EtherFiStakeResponse,
    EtherFiUnstakeResponse,
    EulerBorrowParams,
    EulerDepositParams,
    EulerRepayParams,
    EulerUserPosition,
    EulerVaultData,
    FluidBorrowParams,
    FluidDepositParams,
    FluidRepayParams,
    LidoRequestWithdrawalsParams,
    LidoSubmitParams,
    LidoSubmitResponse,
    LidoWstEthWrapResponse,
    MorphoBorrowParams,
    MorphoFlashLoanParams,
    MorphoMarketParams,
    MorphoRepayParams,
    MorphoSupplyParams,
    MorphoUserPosition,
    UniswapV3PoolStateResponse,
    UniswapV3QuoteResponse,
    UniswapV3SwapTxReceipt,
)
from .external.tardis.schemas import (
    TardisExchangeDetail,
    TardisInstrumentDetail,
)
from .external.upbit.schemas import (
    UpbitBalanceQueryResponse,
    UpbitTicker,
)
from .internal.domain.client_reporting import FundNAVSnapshot
from .internal.domain.fund_administration import (
    AllocationExecutionStatus,
    AllocatorRedemption,
    AllocatorSubscription,
    ApproveSubscriptionRequest,
    FundAllocation,
    ProcessRedemptionRequest,
    RebalanceRequest,
    RedeemRequest,
    RedemptionStatus,
    RejectRequest,
    SubscribeRequest,
    SubscriptionStatus,
)
from .internal.reference.canonical_id_builder import (
    build_combo_id,
    build_instrument_id,
)
from .internal.reference.ticker_registry import (
    EXCHANGE_BY_TICKER,
    UNDERLYING_NORMALIZATION,
    normalize_underlying,
    resolve_exchange,
)
from .internal.reporting import FeeStructure
from .internal.schemas.contracts import (
    CEFI_FUTURES_CHAIN_TRADES,
    CEFI_OPTIONS_CHAIN_TRADES,
    CEFI_PERPETUAL_BOOK_SNAPSHOT_5,
    CEFI_PERPETUAL_DERIVATIVE_TICKER,
    CEFI_PERPETUAL_LIQUIDATIONS,
    CEFI_PERPETUAL_QUOTES,
    CEFI_PERPETUAL_TRADES,
    CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5,
    CEFI_SPOT_PAIR_TRADES,
    CONTRACT_REGISTRY,
    DEFI_AAVE_V3_LENDING_INDICES,
    DEFI_DEX_POOL_DEX_POOL_STATE,
    DEFI_DEX_POOL_DEX_POOL_SWAPS,
    DEFI_LENDING_INDICES_MARKET_ID,
    DEFI_LENDING_LIQUIDATIONS,
    DEFI_LENDING_POSITION_LENDING_INDICES,
    DEFI_LST_LST_RATES,
    DEFI_PERPETUAL_PERP_FUNDING,
    DEFI_POOL_DEX_POOL_SWAPS,
    DEFI_SPOT_ASSET_GAS_FEES,
    DEFI_SPOT_ASSET_ORACLE_PRICES,
    DEFI_STAKING_EIGENLAYER_REWARDS,
    DEFI_STAKING_YIELD_SNAPSHOTS,
    TRADFI_EQUITY_OHLCV_1M,
    TRADFI_EQUITY_TRADES,
    TRADFI_FUTURE_OHLCV_1M,
    TRADFI_FUTURE_TRADES,
    TRADFI_INDEX_TRADES,
    TRADFI_OPTIONS_CHAIN_TRADES,
    VENUE_CONTRACT_OVERRIDES,
    ColumnSpec,
    SchemaContract,
    SchemaContractNotFoundError,
    Violation,
    lookup_contract,
    validate_dataframe,
)
from .normalize_utils import american_to_decimal, decimal_to_american
from .registry import (
    ALL_VENUES,
    CEFI_ACCEPTED_QUOTE_ASSETS,
    CEFI_BASE_ASSET_UNIVERSE,
    CEFI_BASE_ASSETS,
    CEFI_OPTIONS_UNDERLYINGS,
    CLOB_VENUES,
    CME_MONTH_CODES,
    COINBASE_SPOT,
    DATA_TYPES_BY_CATEGORY,
    DATABENTO_VALID_OPTIONS_SYMBOLS,
    DATABENTO_VALID_PARENT_SYMBOLS,
    DEFI_INSTRUMENTS,
    DEFI_LENDING_ASSETS,
    DEFI_MAJOR_ASSET_ADDRESS_LIST,
    DEFI_MAJOR_ASSET_ADDRESSES,
    DEFI_MAJOR_ASSET_SYMBOLS,
    DEFI_POOL_PAIRS,
    DEFI_PROTOCOLS,
    DEFI_VENUE_TO_PROTOCOL,
    DEX_VENUE_KEYWORDS,
    DEX_VENUES,
    ENDPOINT_REGISTRY,
    EXCHANGE_CODE_TO_NAME,
    FX_SPOT_PAIRS,
    INSTRUMENT_TYPE_FOLDER_MAP,
    INSTRUMENT_TYPES_BY_VENUE,
    KNOWN_ETFS,
    OKX_FUTURES,
    OKX_SPOT,
    OPTIONS_CHAIN_CONFIG,
    QUARTERLY_MONTHS,
    SPACE_TO_DOT_SYMBOLS,
    SPORTS_LEAGUES,
    SPORTS_VENUES,
    TIMEFRAMES,
    TRADFI_DATA_BINDINGS,
    TRADFI_DATABENTO_INSTRUMENTS,
    TRADFI_EQUITIES,
    TRADFI_FUTURES,
    TRADFI_INSTRUMENTS,
    TRADFI_INSTRUMENTS_CONFIG,
    TRADFI_TICKER_UNIVERSE,
    TRADFI_VENUE_MAPPINGS,
    VENUE_CATEGORY_MAP,
    VENUE_COORDINATES,
    VENUE_DATA_AVAILABILITY,
    VENUE_TO_CATEGORY,
    VENUES_BY_CATEGORY,
    ZERO_ALPHA_VENUES,
    AccessMode,
    CassetteStatus,
    DataAvailability,
    DatabentoInstrumentDef,
    DataTypeConfig,
    EndpointSpec,
    ExchangeInstrumentConfig,
    FxSpotPairDef,
    ProviderBinding,
    ProviderDataAvailability,
    ResponseFormat,
    SessionTimes,
    TradFiInstrumentDef,
    VenueCoordinates,
    VenueMapping,
    get_databento_symbols_for_dataset,
    get_databento_symbols_for_venue,
    get_expected_data_types_for_venue,
    get_provider_availability,
    get_required_datasets,
    get_session_times,
    get_valid_data_types_for_venue,
    get_venue_coordinates,
    get_venue_data_type_start_date,
    is_trading_hours,
    needs_candle_processing,
    resolve_data_type_for_feature_group,
    validate_data_type_for_venue,
)
from .signal_broadcast import (
    COUNTERPARTY_ENTITLEMENTS as COUNTERPARTY_ENTITLEMENTS,
)
from .signal_broadcast import (
    COUNTERPARTY_REGISTRY as COUNTERPARTY_REGISTRY,
)
from .signal_broadcast import (
    AckSource as AckSource,
)
from .signal_broadcast import (
    Counterparty as Counterparty,
)
from .signal_broadcast import (
    CounterpartyEntitlement as CounterpartyEntitlement,
)
from .signal_broadcast import (
    CounterpartyEntitlementProfile as CounterpartyEntitlementProfile,
)
from .signal_broadcast import (
    CounterpartyStatus as CounterpartyStatus,
)
from .signal_broadcast import (
    DeliveryAttempt as DeliveryAttempt,
)
from .signal_broadcast import (
    DeliveryStatus as DeliveryStatus,
)
from .signal_broadcast import (
    DirectionalIntent as DirectionalIntent,
)
from .signal_broadcast import (
    PayloadDepth as PayloadDepth,
)
from .signal_broadcast import (
    RateLimitConfig as RateLimitConfig,
)
from .signal_broadcast import (
    RestPullDeliveryConfig as RestPullDeliveryConfig,
)
from .signal_broadcast import (
    SchemaDepth as SchemaDepth,
)
from .signal_broadcast import (
    SignalAcknowledgement as SignalAcknowledgement,
)
from .signal_broadcast import (
    SignalEmission as SignalEmission,
)
from .signal_broadcast import (
    SignalPayload as SignalPayload,
)
from .signal_broadcast import (
    SignalPayloadMinimal as SignalPayloadMinimal,
)
from .signal_broadcast import (
    SignalPayloadRich as SignalPayloadRich,
)
from .signal_broadcast import (
    SignalPayloadStandard as SignalPayloadStandard,
)
from .signal_broadcast import (
    StrategySignalAcknowledged as StrategySignalAcknowledged,
)
from .signal_broadcast import (
    StrategySignalEmittedExternal as StrategySignalEmittedExternal,
)
from .signal_broadcast import (
    WebhookDeliveryConfig as WebhookDeliveryConfig,
)
from .signal_broadcast import (
    active_counterparties as active_counterparties,
)
from .signal_broadcast import (
    counterparty_for as counterparty_for,
)
from .signal_broadcast import (
    entitled_slots_for as entitled_slots_for,
)
from .signal_broadcast import (
    entitlements_for as entitlements_for,
)
from .sports import (
    BUNDESLIGA_TEAM_ALIASES as BUNDESLIGA_TEAM_ALIASES,
)
from .sports import (
    CANONICAL_TO_ODDS_API_BUNDESLIGA as CANONICAL_TO_ODDS_API_BUNDESLIGA,
)
from .sports import (
    CANONICAL_TO_ODDS_API_EPL as CANONICAL_TO_ODDS_API_EPL,
)
from .sports import (
    CANONICAL_TO_UNDERSTAT_EPL as CANONICAL_TO_UNDERSTAT_EPL,
)
from .sports import (
    EPL_TEAM_ALIASES as EPL_TEAM_ALIASES,
)
from .sports import (
    get_expected_leagues_for_source as get_expected_leagues_for_source,
)
from .sports import (
    get_prediction_leagues as get_prediction_leagues,
)

__all__ = [
    "ALL_VENUES",
    "BOOKMAKER_REGISTRY",
    "CEFI_ACCEPTED_QUOTE_ASSETS",
    "CEFI_BASE_ASSETS",
    "CEFI_BASE_ASSET_UNIVERSE",
    "CEFI_FUTURES_CHAIN_TRADES",
    "CEFI_OPTIONS_CHAIN_TRADES",
    "CEFI_OPTIONS_UNDERLYINGS",
    "CEFI_PERPETUAL_BOOK_SNAPSHOT_5",
    "CEFI_PERPETUAL_DERIVATIVE_TICKER",
    "CEFI_PERPETUAL_LIQUIDATIONS",
    "CEFI_PERPETUAL_QUOTES",
    "CEFI_PERPETUAL_TRADES",
    "CEFI_SPOT_PAIR_BOOK_SNAPSHOT_5",
    "CEFI_SPOT_PAIR_TRADES",
    "CLOB_VENUES",
    "CME_MONTH_CODES",
    "CONFIG_REQUIRED_FIELDS",
    "CONFIG_SCHEMA",
    "CONTRACT_REGISTRY",
    "COUNTERPARTY_ENTITLEMENTS",
    "COUNTERPARTY_REGISTRY",
    "DATA_SOURCE_TO_SECRET",
    "DATA_SOURCE_TO_VENUES",
    "DATA_TYPES_BY_CATEGORY",
    "DEFI_AAVE_V3_LENDING_INDICES",
    "DEFI_DEX_POOL_DEX_POOL_STATE",
    "DEFI_DEX_POOL_DEX_POOL_SWAPS",
    "DEFI_INSTRUMENTS",
    "DEFI_LENDING_ASSETS",
    "DEFI_LENDING_INDICES_MARKET_ID",
    "DEFI_LENDING_LIQUIDATIONS",
    "DEFI_LENDING_POSITION_LENDING_INDICES",
    "DEFI_LST_LST_RATES",
    "DEFI_MAJOR_ASSET_ADDRESSES",
    "DEFI_MAJOR_ASSET_ADDRESS_LIST",
    "DEFI_MAJOR_ASSET_SYMBOLS",
    "DEFI_PERPETUAL_PERP_FUNDING",
    "DEFI_POOL_DEX_POOL_SWAPS",
    "DEFI_SPOT_ASSET_GAS_FEES",
    "DEFI_SPOT_ASSET_ORACLE_PRICES",
    "DEFI_STAKING_EIGENLAYER_REWARDS",
    "DEFI_STAKING_YIELD_SNAPSHOTS",
    "DEX_VENUES",
    "DEX_VENUE_KEYWORDS",
    "ENDPOINT_REGISTRY",
    "EXCHANGE_BY_TICKER",
    "FX_SPOT_PAIRS",
    "INSTRUMENT_SCHEMA",
    "INSTRUMENT_TYPES_BY_VENUE",
    "INSTRUMENT_TYPE_FOLDER_MAP",
    "KNOWN_ETFS",
    "ODDS_API_KEY_TO_VENUE",
    "ODDS_API_KEY_TO_VENUE_CATEGORY",
    "OKX_FUTURES",
    "OKX_SPOT",
    "OPTIONAL_CONFIG_FIELDS",
    "QUARTERLY_MONTHS",
    "REQUIRED_CONFIG_FIELDS",
    "RISK_TYPE_CATEGORIES",
    "SHARE_CLASS_BASE_ASSETS",
    "SPORTS_VENUES",
    "TIMEFRAMES",
    "TRADFI_DATABENTO_INSTRUMENTS",
    "TRADFI_EQUITIES",
    "TRADFI_EQUITY_OHLCV_1M",
    "TRADFI_EQUITY_TRADES",
    "TRADFI_FUTURES",
    "TRADFI_FUTURE_OHLCV_1M",
    "TRADFI_FUTURE_TRADES",
    "TRADFI_INDEX_TRADES",
    "TRADFI_INSTRUMENTS",
    "TRADFI_OPTIONS_CHAIN_TRADES",
    "TRADFI_TICKER_UNIVERSE",
    "UNDERLYING_NORMALIZATION",
    "VALID_ALGORITHMS",
    "VALID_BOOK_TYPES",
    "VALID_CATEGORIES",
    "VALID_INSTRUCTION_TYPES",
    "VALID_MODES",
    "VALID_TIMEFRAMES",
    "VENUES_BY_CATEGORY",
    "VENUE_CATEGORY_MAP",
    "VENUE_CONTRACT_OVERRIDES",
    "VENUE_COORDINATES",
    "VENUE_DATA_AVAILABILITY",
    "VENUE_ERROR_MAP",
    "VENUE_EXECUTION_REGISTRY",
    "VENUE_TO_CATEGORY",
    "VENUE_TO_DATA_SOURCE",
    "VENUE_TO_DATA_SOURCES",
    "ZERO_ALPHA_VENUES",
    "AaveBorrowParams",
    "AaveDepositParams",
    "AaveFlashLoanParams",
    "AaveRepayParams",
    "AaveV3ReserveData",
    "AaveV3UserAccountData",
    "AaveV3UserReserveData",
    "AccountVerificationLevel",
    "AckSource",
    "AggregatedPosition",
    "AllocationExecutionStatus",
    "AllocatorRedemption",
    "AllocatorSubscription",
    "AlternativeDataSignal",
    "AlternativeDataType",
    "AntiDetectionLevel",
    "ApproveSubscriptionRequest",
    "ArbitrageMarket",
    "ArbitrageOpportunity",
    "ArbitrageStatus",
    "AssetClass",
    "AsterExchangeInfo",
    "BenchmarkType",
    "BetExecution",
    "BetOrder",
    "BetRejectedError",
    "BetSide",
    "BetStatus",
    "BetfairCurrentOrderSummary",
    "BetfairListCurrentOrdersResponse",
    "BetfairMarketCatalogue",
    "BetfairRunnerCatalog",
    "BettingSignal",
    "BinanceFuturesExchangeInfo",
    "BinanceInstrumentInfo",
    "BinanceLiquidationOrder",
    "BinanceMarkPriceUpdate",
    "BinanceOptionInstrumentInfo",
    "BinanceOrderBook",
    "BinanceTicker",
    "BinanceTrade",
    "BinanceWithdrawRequest",
    "BinanceWithdrawResponse",
    "BookLevel",
    "BookmakerCategory",
    "BookmakerInfo",
    "BookmakerRegistry",
    "BookmakerUnavailableError",
    "BucketMarket",
    "BybitInstrumentInfo",
    "BybitInstrumentsResponse",
    "BybitLiquidationOrder",
    "BybitOrderBook",
    "BybitTicker",
    "BybitWithdrawRequest",
    "BybitWithdrawResponse",
    "CLVRecord",
    "CanonicalAccountSnapshot",
    "CanonicalAccountState",
    "CanonicalAuthenticationError",
    "CanonicalAuthorizationError",
    "CanonicalBalance",
    "CanonicalBase",
    "CanonicalBetMarket",
    "CanonicalBetOrder",
    "CanonicalBondData",
    "CanonicalBookmakerMarket",
    "CanonicalCdsSpread",
    "CanonicalComboBet",
    "CanonicalComboLeg",
    "CanonicalComputeService",
    "CanonicalContractExpiredError",
    "CanonicalDerivativeTicker",
    "CanonicalDuplicateOrderError",
    "CanonicalError",
    "CanonicalFeatureRecord",
    "CanonicalFee",
    "CanonicalFill",
    "CanonicalFixture",
    "CanonicalFixtureEvent",
    "CanonicalFixtureStatsDetail",
    "CanonicalFundingRate",
    "CanonicalInjury",
    "CanonicalInstrument",
    "CanonicalInstrumentHaltedError",
    "CanonicalInsufficientBalanceError",
    "CanonicalInsufficientMarginError",
    "CanonicalInternalServerError",
    "CanonicalInvalidRequestError",
    "CanonicalLeague",
    "CanonicalLineup",
    "CanonicalLiquidation",
    "CanonicalLiquidationCluster",
    "CanonicalMaintenanceModeError",
    "CanonicalMarginState",
    "CanonicalMarketClosedError",
    "CanonicalMarketStateEvent",
    "CanonicalNetworkError",
    "CanonicalOdds",
    "CanonicalOhlcvBar",
    "CanonicalOnChainMetric",
    "CanonicalOptionsChainEntry",
    "CanonicalOrder",
    "CanonicalOrderAmendment",
    "CanonicalOrderBook",
    "CanonicalOrderRejectedError",
    "CanonicalOrderRejection",
    "CanonicalPlayer",
    "CanonicalPlayerMatchStats",
    "CanonicalPosition",
    "CanonicalPositionLimitExceededError",
    "CanonicalPredictionMarket",
    "CanonicalPriceBoundError",
    "CanonicalProgressiveOdds",
    "CanonicalProgressiveStats",
    "CanonicalPullRequest",
    "CanonicalRateLimitError",
    "CanonicalReferee",
    "CanonicalRepository",
    "CanonicalSchemaError",
    "CanonicalServiceUnavailableError",
    "CanonicalSettlement",
    "CanonicalSizeLimitError",
    "CanonicalSpread",
    "CanonicalTeam",
    "CanonicalTicker",
    "CanonicalTrade",
    "CanonicalUnknownVenueError",
    "CanonicalVenue",
    "CanonicalWebSocketLifecycle",
    "CanonicalWorkflowRun",
    "CanonicalYieldCurvePoint",
    "CcxtAggTrade",
    "CcxtFundingRate",
    "CcxtMarket",
    "CcxtOhlcv",
    "CcxtOpenInterest",
    "CcxtOrderBook",
    "CcxtTicker",
    "CcxtTrade",
    "CloudProvider",
    "CoinbaseOrderBook",
    "CoinbaseProductInfo",
    "CoinbaseProductsResponse",
    "CoinbaseTicker",
    "CoinbaseTrade",
    "CoinbaseWithdrawRequest",
    "CoinbaseWithdrawResponse",
    "CollateralAsset",
    "ColumnSpec",
    "ComboLeg",
    "ComboQuote",
    "ComboStrategyType",
    "CommissionModel",
    "CompoundV3MarketInfo",
    "CompoundV3UserPosition",
    "ComputeTarget",
    "ComputeType",
    "ContractSpec",
    "Counterparty",
    "CounterpartyEntitlement",
    "CounterpartyEntitlementProfile",
    "CounterpartyStatus",
    "CredentialType",
    "CrossMarginNettingResult",
    "CrossVenueArbLeg",
    "CrossVenueArbSignal",
    "CrossVenueLink",
    "CurveDepositParams",
    "CurveSwapParams",
    "CurveWithdrawParams",
    "DarkPoolPrintRecord",
    "DataSourceMapping",
    "DataSourceRoute",
    "DataTypeConfig",
    "DatabentoError",
    "DeFiAggregatedHealth",
    "DeFiLPAggregatedMetrics",
    "DeFiStakingAggregatedMetrics",
    "DefiAlertType",
    "DefiErrorCode",
    "DeliveryAttempt",
    "DeliveryStatus",
    "DepositAddress",
    "DepositRecord",
    "DeribitAccountSummaryResponse",
    "DeribitCancelResponse",
    "DeribitGetInstrumentResponse",
    "DeribitGetInstrumentsResponse",
    "DeribitInstrumentInfoFull",
    "DeribitInstrumentsResponse",
    "DeribitOpenOrdersResponse",
    "DeribitOrderResponse",
    "DeribitOrderStateResponse",
    "DeribitPositionsResponse",
    "DeribitTickerResponse",
    "DirectionalIntent",
    "EndpointSpec",
    "Erc20TransferCalldata",
    "Erc20TransferFromCalldata",
    "ErrorAction",
    "EthSendRawTransactionRequest",
    "EthSendRawTransactionResponse",
    "EthSendTransactionRequest",
    "EthTransactionRequest",
    "EtherFiStakeResponse",
    "EtherFiUnstakeResponse",
    "EulerBorrowParams",
    "EulerDepositParams",
    "EulerRepayParams",
    "EulerUserPosition",
    "EulerVaultData",
    "ExchangeFeeSchedule",
    "ExchangeInstrumentConfig",
    "ExecutionAlpha",
    "ExecutionInstruction",
    "ExecutionMethod",
    "ExecutionResult",
    "ExecutionStatus",
    "ExpectedValue",
    "FeatureMetadata",
    "FeeStructure",
    "FeeType",
    "FixtureMapping",
    "FixtureNotFoundError",
    "FluidBorrowParams",
    "FluidDepositParams",
    "FluidRepayParams",
    "FundAllocation",
    "FundNAVSnapshot",
    "FundingRateHistory",
    "HealthPingResponse",
    "HttpRateLimitHeaders",
    "HyperliquidAssetInfo",
    "HyperliquidFill",
    "HyperliquidMeta",
    "HyperliquidOpenOrder",
    "HyperliquidPosition",
    "HyperliquidUserState",
    "IBKRAccountValue",
    "IBKRContractDetails",
    "IBKRCorporateAction",
    "IBKRPosition",
    "InstructionType",
    "InstrumentType",
    "InsuranceFundState",
    "InternalTransfer",
    "KalshiMarket",
    "KalshiOrderBook",
    "KalshiTrade",
    "LPProtocolBreakdown",
    "LatencyComponent",
    "LidoRequestWithdrawalsParams",
    "LidoSubmitParams",
    "LidoSubmitResponse",
    "LidoWstEthWrapResponse",
    "LineupPlayer",
    "LiquidationHeatmapResponse",
    "LiquidationLevel",
    "LiveMatchState",
    "LiveOddsUpdate",
    "LongShortRatio",
    "ManifoldMarket",
    "ManifoldPrice",
    "ManifoldTrade",
    "MappingRule",
    "MarginType",
    "MarketClosedError",
    "MarketState",
    "MarketStatus",
    "MarketTrade",
    "MatchPeriod",
    "MorphoBorrowParams",
    "MorphoFlashLoanParams",
    "MorphoMarketParams",
    "MorphoRepayParams",
    "MorphoSupplyParams",
    "MorphoUserPosition",
    "MultiLegInstrument",
    "NegRiskArbSignal",
    "NegRiskBucket",
    "NetClearingInstruction",
    "NetworkJitterMetric",
    "NormalizedStrikeCoordinate",
    "OKXFundingRate",
    "OKXInstrumentInfo",
    "OKXInstrumentsResponse",
    "OKXLiquidationOrder",
    "OKXMarkPrice",
    "OKXOrderBook",
    "OKXTicker",
    "OKXWithdrawRequest",
    "OKXWithdrawResponse",
    "OddsChangedError",
    "OddsFormat",
    "OddsType",
    "OpenInterestHistory",
    "OperationType",
    "OptionChainSnapshot",
    "OptionType",
    "OptionsFlowRecord",
    "OrderBookSnapshot5",
    "OrderLatencyRecord",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "OrphanDetector",
    "OutcomeType",
    "PayloadDepth",
    "PlayerMapping",
    "PolygonDividend",
    "PolygonDividendsResponse",
    "PolygonOptionContract",
    "PolygonOptionContractsResponse",
    "PolygonSplit",
    "PolygonSplitsResponse",
    "PolygonTicker",
    "PolygonTickersResponse",
    "PolymarketGammaMarket",
    "PolymarketPosition",
    "PortfolioGreeksSnapshot",
    "PortfolioMarginAccount",
    "PortfolioPnLAttribution",
    "PortfolioView",
    "PositionRisk",
    "PredictionMarketCategory",
    "PredictionMarketMapper",
    "PredictionMarketUniverse",
    "PrimeBrokerAccount",
    "PrimeBrokerError",
    "PrimeBrokerFill",
    "PrimeBrokerMarginCall",
    "PrimeBrokerPosition",
    "PrimeBrokerProvider",
    "ProbabilityBucket",
    "ProcessRedemptionRequest",
    "ProcessedOddsOutput",
    "ProtocolHealthBreakdown",
    "ProviderDataAvailability",
    "RateLimitConfig",
    "RateLimitInfo",
    "RateLimitResponse",
    "RebalanceRequest",
    "RedeemRequest",
    "RedemptionStatus",
    "RejectRequest",
    "RestPullDeliveryConfig",
    "RiskCategory",
    "RiskGroupSummary",
    "RiskType",
    "SatelliteObservation",
    "ScalingMode",
    "SchemaContract",
    "SchemaContractNotFoundError",
    "SchemaDepth",
    "ScraperError",
    "ScraperVersionMeta",
    "SentimentScore",
    "SettlementEvent",
    "ShareClass",
    "SignalAcknowledgement",
    "SignalEmission",
    "SignalPayload",
    "SignalPayloadMinimal",
    "SignalPayloadRich",
    "SignalPayloadStandard",
    "SignalSource",
    "SourceControlProvider",
    "Sport",
    "SportsArbLeg",
    "SportsArbPosition",
    "SportsError",
    "SportsbookLink",
    "SpreadLeg",
    "StakingProtocolBreakdown",
    "StrategySignalAcknowledged",
    "StrategySignalEmittedExternal",
    "SubAccount",
    "SubscribeRequest",
    "SubscriptionStatus",
    "TardisExchangeDetail",
    "TardisInstrumentDetail",
    "TeamMapping",
    "TimeInForce",
    "UnderlyingGreeksBreakdown",
    "UniswapV3PoolStateResponse",
    "UniswapV3QuoteResponse",
    "UniswapV3SwapTxReceipt",
    "UpbitBalanceQueryResponse",
    "UpbitTicker",
    "UpbitWithdrawRequest",
    "UpbitWithdrawResponse",
    "VenueCategory",
    "VenueCoordinates",
    "VenueErrorClassification",
    "VenueExecutionProfile",
    "VenueMapping",
    "VenuePositionBreakdown",
    "VenueRateLimitSpec",
    "Violation",
    "VmQuotaShape",
    "VolSmilePoint",
    "VolSurface",
    "VolSurfaceSlice",
    "VolTermStructure",
    "WebSocketCloseInfo",
    "WebSocketConnectionClosed",
    "WebSocketConnectionOpened",
    "WebSocketEvent",
    "WebhookDeliveryConfig",
    "WithdrawalRecord",
    "active_counterparties",
    "american_to_decimal",
    "build_combo_id",
    "build_instrument_id",
    "classify_venue_error",
    "counterparty_for",
    "decimal_to_american",
    "entitled_slots_for",
    "entitlements_for",
    "get_data_sources_for_venue",
    "get_databento_symbols_for_venue",
    "get_provider_availability",
    "get_required_secrets",
    "get_venue_coordinates",
    "lookup_contract",
    "normalize_underlying",
    "resolve_exchange",
    "validate_dataframe",
]

# fmt: off
_VENUES = [
    "alchemy", "api_football", "aster", "barchart", "betfair", "binance",
    "bybit", "ccxt", "aws", "gcp", "coinbase", "cryptoquant", "databento", "defi", "defillama",
    "deribit", "fear_greed", "footystats", "github", "glassnode", "hyperliquid", "ibkr", "kalshi",
    "mev", "metabet", "nautilus", "odds_api", "odds_engine", "oddsjam", "okx", "open_meteo",
    "opticodds", "pinnacle", "polymarket", "soccer_football_info", "sharpapi", "tardis",
    "thegraph", "transfermarkt", "understat", "upbit", "yahoo_finance",
]
# fmt: on
for _v in _VENUES:
    _mod = cast(ModuleType, __import__(f"{__name__}.external.{_v}", fromlist=[_v]))
    sys.modules[f"{__name__}.{_v}"] = _mod
