"""Domain facade — strategy registry, families, and client identity.

Consumer repos import from here:
    from unified_api_contracts.strategy import STRATEGY_REGISTRY, StrategyFamily, ...

G1.8 added the v2 archetype-capability surface (``ArchetypeCapability`` +
``ARCHETYPE_CAPABILITY_REGISTRY`` + ``archetypes_for_pair`` + friends) so
pricing / derivation / instruction-validation consumers can query per-
archetype (category, instrument_type) support without reaching into the
strategy-service v2 code or the UI coverage.ts.
"""

from unified_api_contracts.internal.architecture_v2.allocator_access import (
    allocator_access_control,
    user_context_for_allocator,
)
from unified_api_contracts.internal.architecture_v2.archetype_capability import (
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    ArchetypeCapabilityCell,
    ArchetypeInstrumentType,
    CoverageStatus,
    RollMode,
    all_capabilities,
    archetypes_for_pair,
    archetypes_for_venue,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.archetype_config import (
    ARCHETYPE_CONFIG_SEED,
    ArchetypeConfig,
    archetype_kill_switch_thresholds,
    get_archetype_config,
    is_archetype_config_declared,
)
from unified_api_contracts.internal.architecture_v2.capital_allocation import (
    CAPITAL_ALLOCATION_SEED,
    AllocationViolationError,
    CapitalAllocation,
    get_capital_allocation,
    is_allocation_declared,
    is_within_allocation,
    validate_allocation_respect,
)
from unified_api_contracts.internal.architecture_v2.derivation import (
    AccessDecision,
    ClientAudience,
    ClientContext,
    ClientPackage,
    Combo,
    CommercialPath,
    DemoFlavour,
    DemoUniverse,
    DenialReason,
    DimensionQuery,
    IntegrationDepth,
    InternalCostLeakageError,
    ItemRef,
    Persona,
    Phase,
    PriceQuote,
    PricingTier,
    ProductionRestrictions,
    QuoteLine,
    RestrictionProfile,
    RouteDescriptor,
    Rule08Violation,
    SlotFilter,
    TileLockState,
    UserContext,
    combo,
    prod_restrictions,
)
from unified_api_contracts.internal.architecture_v2.derivation_access import (
    access_control,
)
from unified_api_contracts.internal.architecture_v2.derivation_cost import (
    cost,
)
from unified_api_contracts.internal.architecture_v2.derivation_demo import (
    demo_universe,
)
from unified_api_contracts.internal.architecture_v2.restriction_profiles import (
    RESTRICTION_PROFILE_REGISTRY,
    Env,
    ProfileYaml,
    QuestionnaireCategory,
    QuestionnaireFundStructure,
    QuestionnaireInstrumentType,
    QuestionnaireResponse,
    QuestionnaireServiceFamily,
    QuestionnaireStrategyStyle,
    known_persona_ids,
    resolve_profile,
)
from unified_api_contracts.internal.architecture_v2.service_family_scope import (
    SERVICE_FAMILY_SCOPE_RULES,
    ScopeAllow,
    ScopeDecision,
    ScopeDeny,
    ServiceFamily,
    ServiceFamilyScopeRule,
    check_service_family_scope,
    service_family_from_audience,
)
from unified_api_contracts.internal.architecture_v2.strategy_naming import (
    ParsedStrategyId,
    format_strategy_id,
    parse_strategy_id,
)
from unified_api_contracts.internal.domain.strategy_service.client_registry import (
    CLIENT_REGISTRY,
    ClientDefinition,
    ClientRegistry,
)
from unified_api_contracts.internal.domain.strategy_service.registry import (
    STRATEGY_REGISTRY,
    Category,
    ExecutionMode,
    StrategyArchetype,
    StrategyDefinition,
    StrategyFamily,
    StrategyRegistry,
    validate_mode_for_category,
)
from unified_api_contracts.internal.domain.strategy_service.subscription import (
    ExclusiveLockViolation,
    StrategyInstanceSubscription,
    SubscriptionType,
)
from unified_api_contracts.internal.domain.strategy_service.versions import (
    ApprovalRecord,
    ConfigDiff,
    StrategyVersion,
    VersionStatus,
    minimum_approval_maturity,
)

__all__ = [
    "ARCHETYPE_CAPABILITY_REGISTRY",
    "ARCHETYPE_CONFIG_SEED",
    "CAPITAL_ALLOCATION_SEED",
    "CLIENT_REGISTRY",
    "RESTRICTION_PROFILE_REGISTRY",
    "SERVICE_FAMILY_SCOPE_RULES",
    "STRATEGY_REGISTRY",
    "AccessDecision",
    "AllocationViolationError",
    "ApprovalRecord",
    "ArchetypeCapability",
    "ArchetypeCapabilityCell",
    "ArchetypeConfig",
    "ArchetypeInstrumentType",
    "CapitalAllocation",
    "Category",
    "ClientAudience",
    "ClientContext",
    "ClientDefinition",
    "ClientPackage",
    "ClientRegistry",
    "Combo",
    "CommercialPath",
    "ConfigDiff",
    "CoverageStatus",
    "DemoFlavour",
    "DemoUniverse",
    "DenialReason",
    "DimensionQuery",
    "Env",
    "ExclusiveLockViolation",
    "ExecutionMode",
    "IntegrationDepth",
    "InternalCostLeakageError",
    "ItemRef",
    "ParsedStrategyId",
    "Persona",
    "Phase",
    "PriceQuote",
    "PricingTier",
    "ProductionRestrictions",
    "ProfileYaml",
    "QuestionnaireCategory",
    "QuestionnaireFundStructure",
    "QuestionnaireInstrumentType",
    "QuestionnaireResponse",
    "QuestionnaireServiceFamily",
    "QuestionnaireStrategyStyle",
    "QuoteLine",
    "RestrictionProfile",
    "RollMode",
    "RouteDescriptor",
    "Rule08Violation",
    "ScopeAllow",
    "ScopeDecision",
    "ScopeDeny",
    "ServiceFamily",
    "ServiceFamilyScopeRule",
    "SlotFilter",
    "StrategyArchetype",
    "StrategyDefinition",
    "StrategyFamily",
    "StrategyInstanceSubscription",
    "StrategyRegistry",
    "StrategyVersion",
    "SubscriptionType",
    "TileLockState",
    "UserContext",
    "VersionStatus",
    "access_control",
    "all_capabilities",
    "allocator_access_control",
    "archetype_kill_switch_thresholds",
    "archetypes_for_pair",
    "archetypes_for_venue",
    "capability_for",
    "check_service_family_scope",
    "combo",
    "cost",
    "demo_universe",
    "format_strategy_id",
    "get_archetype_config",
    "get_capital_allocation",
    "is_allocation_declared",
    "is_archetype_config_declared",
    "is_within_allocation",
    "known_persona_ids",
    "minimum_approval_maturity",
    "parse_strategy_id",
    "prod_restrictions",
    "resolve_profile",
    "service_family_from_audience",
    "user_context_for_allocator",
    "validate_allocation_respect",
    "validate_mode_for_category",
]
