"""Domain facade — strategy registry, families, and client identity.

Consumer repos import from here:
    from unified_api_contracts.strategy import STRATEGY_REGISTRY, StrategyFamily, ...

G1.8 added the v2 archetype-capability surface (``ArchetypeCapability`` +
``ARCHETYPE_CAPABILITY_REGISTRY`` + ``archetypes_for_pair`` + friends) so
pricing / derivation / instruction-validation consumers can query per-
archetype (category, instrument_type) support without reaching into the
strategy-service v2 code or the UI coverage.ts.
"""

from unified_api_contracts.internal.architecture_v2.archetype_capability import (
    ARCHETYPE_CAPABILITY_REGISTRY,
    ArchetypeCapability,
    ArchetypeCapabilityCell,
    ArchetypeInstrumentType,
    CoverageStatus,
    RollMode,
    all_capabilities,
    archetypes_for_pair,
    archetypes_for_venue,
    capability_for,
)
from unified_api_contracts.internal.architecture_v2.derivation import (
    AccessDecision,
    ClientAudience,
    ClientContext,
    ClientPackage,
    Combo,
    CommercialPath,
    DemoFlavour,
    DemoUniverse,
    DenialReason,
    DimensionQuery,
    IntegrationDepth,
    InternalCostLeakageError,
    ItemRef,
    Persona,
    Phase,
    PriceQuote,
    PricingTier,
    ProductionRestrictions,
    QuoteLine,
    RestrictionProfile,
    RouteDescriptor,
    Rule08Violation,
    SlotFilter,
    TileLockState,
    UserContext,
    access_control,
    combo,
    cost,
    demo_universe,
    prod_restrictions,
)
from unified_api_contracts.internal.architecture_v2.restriction_profiles import (
    RESTRICTION_PROFILE_REGISTRY,
    Env,
    ProfileYaml,
    QuestionnaireResponse,
    known_persona_ids,
    resolve_profile,
)
from unified_api_contracts.internal.architecture_v2.service_family_scope import (
    SERVICE_FAMILY_SCOPE_RULES,
    ScopeAllow,
    ScopeDecision,
    ScopeDeny,
    ServiceFamily,
    ServiceFamilyScopeRule,
    check_service_family_scope,
    service_family_from_audience,
)
from unified_api_contracts.internal.domain.strategy_service.client_registry import (
    CLIENT_REGISTRY,
    ClientDefinition,
    ClientRegistry,
)
from unified_api_contracts.internal.domain.strategy_service.registry import (
    STRATEGY_REGISTRY,
    Category,
    ExecutionMode,
    StrategyArchetype,
    StrategyDefinition,
    StrategyFamily,
    StrategyRegistry,
    validate_mode_for_category,
)

__all__ = [
    "ARCHETYPE_CAPABILITY_REGISTRY",
    "CLIENT_REGISTRY",
    "RESTRICTION_PROFILE_REGISTRY",
    "SERVICE_FAMILY_SCOPE_RULES",
    "STRATEGY_REGISTRY",
    "AccessDecision",
    "ArchetypeCapability",
    "ArchetypeCapabilityCell",
    "ArchetypeInstrumentType",
    "Category",
    "ClientAudience",
    "ClientContext",
    "ClientDefinition",
    "ClientPackage",
    "ClientRegistry",
    "Combo",
    "CommercialPath",
    "CoverageStatus",
    "DemoFlavour",
    "DemoUniverse",
    "DenialReason",
    "DimensionQuery",
    "Env",
    "ExecutionMode",
    "IntegrationDepth",
    "InternalCostLeakageError",
    "ItemRef",
    "Persona",
    "Phase",
    "PriceQuote",
    "PricingTier",
    "ProductionRestrictions",
    "ProfileYaml",
    "QuestionnaireResponse",
    "QuoteLine",
    "RestrictionProfile",
    "RollMode",
    "RouteDescriptor",
    "Rule08Violation",
    "ScopeAllow",
    "ScopeDecision",
    "ScopeDeny",
    "ServiceFamily",
    "ServiceFamilyScopeRule",
    "SlotFilter",
    "StrategyArchetype",
    "StrategyDefinition",
    "StrategyFamily",
    "StrategyRegistry",
    "TileLockState",
    "UserContext",
    "access_control",
    "all_capabilities",
    "archetypes_for_pair",
    "archetypes_for_venue",
    "capability_for",
    "check_service_family_scope",
    "combo",
    "cost",
    "demo_universe",
    "known_persona_ids",
    "prod_restrictions",
    "resolve_profile",
    "service_family_from_audience",
    "validate_mode_for_category",
]
