"""Single source of truth for per-venue contract coverage: REST, WebSocket, FIX, schemas, errors.

Used by tests to assert we have the right schemas and by optional live verification for secret names.
Align with docs/INDEX.md; update both if adding a venue or capability.
"""

from __future__ import annotations

from typing import TypedDict


class VenueContract(TypedDict):
    """Per-venue contract claims."""

    has_rest: bool
    has_websocket: bool
    has_fix: bool
    """Config field name for Secret Manager (UnifiedCloudConfig), or empty if no API key."""
    config_secret_field: str
    """Expected schema class names in this venue's schemas.py (REST response types)."""
    response_schema_classes: list[str]
    """Expected error/status schema class names."""
    error_schema_classes: list[str]
    """Example file name pattern -> schema class name for validation."""
    example_schema_map: dict[str, str]


# Internal/fix/regulatory entries have extra keys (module, description, etc.); use object for mixed dict
VENUE_MANIFEST: dict[str, VenueContract | dict[str, object]] = {
    "databento": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "databento_secret_name",
        "response_schema_classes": [
            "DatabentoOhlcvBar",
            "DatabentoTrade",
            "DatabentoMbp1",
            "DatabentoMbp10",
            "DatabentoMbo",
            "DatabentoBbo1s",
            "DatabentoBbo1m",
            "DatabentoCmbp1",
            "DatabentoStatus",
            "DatabentoImbalance",
            "DatabentoStatistics",
            "DatabentoTbbo",
            "DatabentoDefinition",
            "DatabentoSymbol",
        ],
        "error_schema_classes": ["DatabentoError"],
        "example_schema_map": {"ohlcv_bar_example.json": "DatabentoOhlcvBar", "error_example.json": "DatabentoError"},
    },
    "tardis": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "tardis_secret_name",
        "response_schema_classes": [
            "TardisExchange",
            "TardisInstrument",
            "TardisTrade",
            "TardisOrderBookLevel",
            "TardisOrderBook",
            "TardisBookSnapshot5",
            "TardisBookSnapshot25",
            "TardisIncrementalBookL2",
            "TardisQuotes",
            "TardisLiquidations",
            "TardisDerivativeTicker",
            "TardisOptionsChain",
        ],
        "error_schema_classes": ["TardisError"],
        "example_schema_map": {
            "trade_example.json": "TardisTrade",
            "error_example.json": "TardisError",
            "book_snapshot_25_example.json": "TardisBookSnapshot25",
            "incremental_book_L2_example.json": "TardisIncrementalBookL2",
            "quotes_example.json": "TardisQuotes",
        },
    },
    "ccxt": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "",  # CCXT uses exchange-specific keys
        "response_schema_classes": [
            "CcxtOrder",
            "CcxtTrade",
            "CcxtBalance",
            "CcxtBalanceResponse",
            "CcxtPosition",
            "CcxtMarket",
            "CcxtTicker",
            "CcxtOrderBook",
            "CcxtFundingRate",
            "CcxtFundingRateHistory",
            "CcxtOpenInterest",
            "CcxtOpenInterestHistory",
            "CcxtOhlcv",
            "CcxtAggTrade",
            "CcxtLeverageTiers",
            "CcxtLongShortRatio",
            "CcxtGreeks",
            "CcxtWithdrawal",
            "CcxtDeposit",
            "CcxtDepositAddress",
            "CcxtLedger",
            "CcxtTransfer",
            "CcxtTradingFee",
            "CcxtBorrowRate",
            "CcxtBorrowInterest",
            "CcxtMarginAdjustment",
            "CcxtInsuranceFund",
            "CcxtLiquidation",
            "CcxtSettlementHistory",
            "CcxtSubaccount",
            "CcxtCurrency",
            "CcxtCurrencyNetwork",
            "CcxtOption",
            "CcxtFees",
            "CcxtVolatilityHistory",
            "CcxtLeverage",
        ],
        "error_schema_classes": ["CcxtErrorPayload"],
        "example_schema_map": {
            "fetch_order_example.json": "CcxtOrder",
            "error_example.json": "CcxtErrorPayload",
            "borrow_rate_example.json": "CcxtBorrowRate",
            "insurance_fund_example.json": "CcxtInsuranceFund",
            "liquidation_example.json": "CcxtLiquidation",
            "subaccount_example.json": "CcxtSubaccount",
            "currency_example.json": "CcxtCurrency",
        },
    },
    "binance": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "BinanceTicker",
            "BinanceOrderBook",
            "BinanceTrade",
            "BinanceOrder",
            "BinancePosition",
            "BinanceKline",
            "BinanceSymbol",
            "BinanceExchangeInfo",
            "BinanceMarkPriceKline",
            "BinanceIndexPriceKline",
            "BinanceMyTrades",
            "BinanceIncome",
            "BinanceDeliveryPrice",
            "BinanceDeliveryHistory",
        ],
        "error_schema_classes": ["BinanceError"],
        "example_schema_map": {
            "ticker_example.json": "BinanceTicker",
            "order_example.json": "BinanceOrder",
            "error_example.json": "BinanceError",
            "klines_example.json": "BinanceKline",
            "exchange_info_example.json": "BinanceExchangeInfo",
            "mark_price_kline_example.json": "BinanceMarkPriceKline",
            "index_price_kline_example.json": "BinanceIndexPriceKline",
        },
    },
    "thegraph": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "thegraph_secret_name",
        "response_schema_classes": [
            "TheGraphResponse",
            "SubgraphPool",
            "SubgraphSwap",
            "SubgraphToken",
            "SubgraphReserve",
            "SubgraphAaveUserPosition",
            "SubgraphUniV3Position",
            "SubgraphUniV3PoolTick",
            "SubgraphCurveGauge",
            "SubgraphCurveVotingEscrow",
            "SubgraphMorphoPosition",
            "SubgraphLidoRebase",
            "SubgraphEthenaYield",
            "SubgraphERC20Transfer",
            "SubgraphERC20Approval",
        ],
        "error_schema_classes": ["GraphQLError"],
        "example_schema_map": {
            "response_example.json": "TheGraphResponse",
            "graphql_error_example.json": "GraphQLError",
        },
    },
    "okx": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "OKXMarket",
            "OKXTicker",
            "OKXOrder",
            "OKXOrderBook",
            "OKXPosition",
            "OKXFeeRate",
            "OKXFundingRateHistory",
            "OKXDepositAddress",
            "OKXDepositHistory",
            "OKXWithdrawalHistory",
            "OKXFundTransfer",
            "OKXLongShortRatio",
            "OKXOpenInterest",
            "OKXOpenInterestHistory",
            "OKXRiskLimit",
            "OKXPortfolioMarginAccount",
            "OKXDeliveryExerciseHistory",
        ],
        "error_schema_classes": ["OKXError"],
        "example_schema_map": {
            "ticker_example.json": "OKXTicker",
            "error_example.json": "OKXError",
        },
    },
    "bybit": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "BybitMarket",
            "BybitTicker",
            "BybitOrderBook",
            "BybitOrder",
            "BybitPosition",
            "BybitFeeRate",
            "BybitFundingRateHistory",
            "BybitDepositAddress",
            "BybitDepositRecords",
            "BybitWithdrawals",
            "BybitAccountTransfer",
            "BybitLongShortRatio",
            "BybitRiskLimit",
            "BybitInsuranceFund",
            "BybitDeliveryRecord",
        ],
        "error_schema_classes": ["BybitError"],
        "example_schema_map": {
            "ticker_example.json": "BybitTicker",
            "error_example.json": "BybitError",
        },
    },
    "deribit": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "DeribitInstrument",
            "DeribitTicker",
            "DeribitOrderBook",
            "DeribitOrder",
            "DeribitPosition",
            "DeribitAccountSummary",
            "DeribitPortfolioMarginSummary",
            "DeribitVolatilityIndex",
            "DeribitFundingRateHistory",
            "DeribitSettlementCashFlows",
            "DeribitRiskLimit",
            "DeribitSessionBankruptcyDetails",
            "DeribitInstrumentInfoFull",
            "DeribitUserPortfolio",
            "DeribitSettlementHistory",
        ],
        "error_schema_classes": ["DeribitError"],
        "example_schema_map": {
            "order_example.json": "DeribitOrder",
            "error_example.json": "DeribitError",
        },
    },
    "yahoo_finance": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "YahooQuote",
            "YahooChartResult",
            "YahooOhlcv24h",
            "YahooSplits",
            "YahooDividends",
        ],
        "error_schema_classes": ["YahooError"],
        "example_schema_map": {
            "quote_example.json": "YahooQuote",
            "ohlcv_24h_example.json": "YahooOhlcv24h",
            "splits_example.json": "YahooSplits",
            "dividends_example.json": "YahooDividends",
            "error_example.json": "YahooError",
        },
    },
    "barchart": {
        "has_rest": False,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": ["BarchartOhlcv15m"],
        "error_schema_classes": [],
        "example_schema_map": {"ohlcv_15m_example.json": "BarchartOhlcv15m"},
    },
    "alchemy": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "alchemy_secret_name",
        "response_schema_classes": [
            "AlchemyRpcResponse",
            "AlchemyAssetTransfer",
            "AlchemyTokenBalance",
            "AlchemyBlock",
            "AlchemyTransaction",
            "AlchemyTransactionReceipt",
            "AlchemyLog",
            "AlchemyDecodedLog",
            "AlchemyGasOracle",
            "AlchemyEnsResolution",
            "AlchemyNFTMetadata",
            "AlchemyNFTOwnership",
            "AlchemyTokenMetadata",
            "AlchemySimulationResult",
            "AlchemyWebhookSubscription",
        ],
        "error_schema_classes": ["AlchemyError"],
        "example_schema_map": {
            "rpc_response_example.json": "AlchemyRpcResponse",
            "error_example.json": "AlchemyError",
        },
    },
    "hyperliquid": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "HyperliquidMeta",
            "HyperliquidTicker",
            "HyperliquidUserState",
            "HyperliquidL2Book",
            "HyperliquidFundingHistoryEntry",
            "HyperliquidFill",
            "HyperliquidOpenOrder",
            "HyperliquidCandle",
            "HyperliquidVaultDetails",
            "HyperliquidLiquidation",
            "HyperliquidSpotMeta",
            "HyperliquidSpotAssetInfo",
            "HyperliquidUserFees",
            "HyperliquidSubAccount",
            "HyperliquidOrder",
            "HyperliquidPosition",
            "HyperliquidStatsRow",
        ],
        "error_schema_classes": ["HyperliquidError"],
        "example_schema_map": {
            "ticker_example.json": "HyperliquidTicker",
            "error_example.json": "HyperliquidError",
        },
    },
    "aster": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "AsterAggTrade",
            "AsterTrade",
            "AsterKline",
            "AsterMarkPrice",
            "AsterFundingRate",
            "AsterOpenInterest",
            "AsterOpenInterestHistory",
            "AsterTicker24hr",
            "AsterExchangeInfo",
            "AsterAccount",
            "AsterBalance",
            "AsterIncome",
            "AsterLeverageBracket",
            "AsterOrderTradeUpdate",
            "AsterAccountUpdate",
            "AsterLiquidationOrder",
            "AsterMarket",
            "AsterOrderBook",
            "AsterOrder",
            "AsterPosition",
        ],
        "error_schema_classes": ["AsterError"],
        "example_schema_map": {
            "order_example.json": "AsterOrder",
            "error_example.json": "AsterError",
        },
    },
    "upbit": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "UpbitMarket",
            "UpbitTicker",
            "UpbitOrder",
            "UpbitBalance",
            "UpbitFeeRate",
            "UpbitDeposit",
            "UpbitWithdrawal",
        ],
        "error_schema_classes": ["UpbitError"],
        "example_schema_map": {
            "ticker_example.json": "UpbitTicker",
            "error_example.json": "UpbitError",
        },
    },
    "ibkr": {
        "has_rest": False,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "IBKRBar",
            "IBKRTicker",
            "IBKROrder",
            "IBKRPosition",
            "IBKRAccountValue",
            "IBKRAccountUpdateMulti",
            "IBKRPortfolioItem",
            "IBKRPnL",
            "IBKRContractDetails",
            "IBKRScannerSubscription",
            "IBKRScannerData",
            "IBKRExecution",
            "IBKRCommissionReport",
            "IBKRPnLSingle",
            "IBKRPnLHistory",
            "IBKRMarketDepth",
            "IBKRHistoricalTick",
            "IBKRHistoricalTickBidAsk",
            "IBKRHistoricalTickLast",
            "IBKRSecDefOptParams",
            "IBKROptionGreeks",
            "IBKRHistoricalVolatility",
            "IBKRRealTimeBar",
        ],
        "error_schema_classes": ["IBKRError"],
        "example_schema_map": {
            "bar_example.json": "IBKRBar",
            "error_example.json": "IBKRError",
        },
    },
    "coinbase": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "coinbase_secret_name",
        "response_schema_classes": [
            "CoinbaseTicker",
            "CoinbaseOrderBook",
            "CoinbaseTrade",
            "CoinbaseCandle",
            "CoinbaseProduct",
            "CoinbaseFeeSchedule",
            "CoinbaseOrder",
            "CoinbaseFill",
        ],
        "error_schema_classes": ["CoinbaseError"],
        "example_schema_map": {
            "ticker_example.json": "CoinbaseTicker",
            "orderbook_example.json": "CoinbaseOrderBook",
            "trade_example.json": "CoinbaseTrade",
            "candle_example.json": "CoinbaseCandle",
            "error_example.json": "CoinbaseError",
        },
    },
    "betfair": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "betfair_secret_name",
        "response_schema_classes": [
            "BetfairAuthResponse",
            "BetfairMarketBook",
            "BetfairMarketCatalogue",
            "BetfairMarketChangeMessage",
            "BetfairOrderUpdate",
            "BetfairPlaceOrdersResponse",
            "BetfairListCurrentOrdersResponse",
            "BetfairRunner",
            "BetfairRunnerChange",
        ],
        "error_schema_classes": ["BetfairError"],
        "example_schema_map": {
            "market_book_example.json": "BetfairMarketBook",
            "market_catalogue_example.json": "BetfairMarketCatalogue",
            "place_orders_example.json": "BetfairPlaceOrdersResponse",
            "list_current_orders_example.json": "BetfairListCurrentOrdersResponse",
            "error_example.json": "BetfairError",
        },
    },
    "pinnacle": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "pinnacle_secret_name",
        "response_schema_classes": [
            "PinnacleLeague",
            "PinnacleEvent",
            "PinnaclePeriod",
            "PinnacleMoneyline",
            "PinnacleTotals",
            "PinnacleSpread",
            "PinnacleOddsResponse",
            "PinnacleSettlementResponse",
        ],
        "error_schema_classes": ["PinnacleError"],
        "example_schema_map": {
            "odds_response_example.json": "PinnacleOddsResponse",
            "error_example.json": "PinnacleError",
        },
    },
    "polymarket": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "polymarket_secret_name",
        "response_schema_classes": [
            "PolymarketIdentifiers",
            "PolymarketMarket",
            "PolymarketToken",
            "PolymarketOrderBook",
            "PolymarketTrade",
            "PolymarketOrder",
            "PolymarketCLOBOrder",
            "PolymarketFill",
            "PolymarketMarketResult",
            "PolymarketGammaMarket",
            "PolymarketGammaEvent",
            "PolymarketGammaTag",
            "PolymarketGammaSeries",
            "PolymarketEvent",
            "PolymarketTag",
            "PolymarketNegRiskEvent",
            "PolymarketNegRiskMarket",
            "PolymarketResolution",
            "PolymarketSplit",
            "PolymarketMerge",
            "PolymarketL1AuthParams",
            "PolymarketPriceHistory",
        ],
        "error_schema_classes": ["PolymarketError"],
        "example_schema_map": {
            "market_example.json": "PolymarketMarket",
            "error_example.json": "PolymarketError",
        },
    },
    "odds_api": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "odds_api_secret_name",
        "response_schema_classes": [
            "OddsApiFixture",
            "OddsApiBookmaker",
            "OddsApiMarket",
            "OddsApiOutcome",
            "OddsApiHistoricalOdds",
        ],
        "error_schema_classes": ["OddsApiError"],
        "example_schema_map": {
            "fixture_example.json": "OddsApiFixture",
            "error_example.json": "OddsApiError",
        },
    },
    "api_football": {
        "has_rest": True,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "api_football_secret_name",
        "response_schema_classes": [
            "ApiFootballFixture",
            "ApiFootballTeam",
            "ApiFootballLeague",
            "ApiFootballLineup",
            "ApiFootballStat",
            "ApiFootballScore",
            "ApiFootballPlayerStat",
            "ApiFootballStanding",
            "ApiFootballOdds",
            "ApiFootballOddsBookmaker",
            "ApiFootballOddsBet",
            "ApiFootballOddsValue",
        ],
        "error_schema_classes": ["ApiFootballError"],
        "example_schema_map": {
            "fixture_example.json": "ApiFootballFixture",
            "odds_example.json": "ApiFootballOdds",
            "error_example.json": "ApiFootballError",
        },
    },
    "bloxroute": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "bloxroute_secret_name",
        "response_schema_classes": [
            "BloxrouteTxSubmitParams",
            "BloxrouteTxSubmitResult",
            "BloxrouteJsonRpcResponse",
            "BloxrouteBdnBlocksParams",
            "BloxrouteSubscribeParams",
            "BloxrouteProtectEndpoints",
        ],
        "error_schema_classes": ["BloxrouteError"],
        "example_schema_map": {"error_example.json": "BloxrouteError"},
    },
    "cloud_sdks": {
        "has_rest": False,
        "has_websocket": False,
        "has_fix": False,
        "config_secret_field": "",
        "response_schema_classes": [
            "AlertPolicy",
            "ArtifactPackage",
            "ArtifactRegistryQuotaUsage",
            "ArtifactRepository",
            "ArtifactTag",
            "ArtifactVersion",
            "BlobDownloadRequest",
            "BlobListRequest",
            "BlobListResponse",
            "BlobUploadRequest",
            "BqQuotaUsage",
            "BucketCreateRequest",
            "CloudBuildBuild",
            "CloudBuildConfig",
            "CloudBuildGitHubConfig",
            "CloudBuildListBuildsResponse",
            "CloudBuildQuotaUsage",
            "CloudBuildRunTriggerRequest",
            "CloudBuildStep",
            "CloudBuildTrigger",
            "CloudBuildTriggerListResponse",
            "CloudLoggingQuotaUsage",
            "CloudSchedulerAttempt",
            "CloudSchedulerCreateJobRequest",
            "CloudSchedulerJob",
            "CloudSchedulerListJobsResponse",
            "CloudSchedulerPauseJobRequest",
            "CloudSchedulerResumeJobRequest",
            "CloudSchedulerRunJobRequest",
            "CloudRunRevision",
            "CloudRunService",
            "ComputeInstance",
            "ComputeOperation",
            "CreateServiceRequest",
            "DeleteInstanceRequest",
            "ExternalTableConfig",
            "ExternalTableCreateRequest",
            "GcpCloudRunQuotaUsage",
            "GcpComputeQuotaUsage",
            "GcsBlobInfo",
            "GcsQuotaUsage",
            "GetInstanceRequest",
            "HivePartitioningOptions",
            "IamBinding",
            "IamPolicy",
            "InsertInstanceRequest",
            "InstanceListResponse",
            "ListInstancesRequest",
            "ListTimeSeriesRequest",
            "ListTimeSeriesResponse",
            "ListLogEntriesRequest",
            "ListLogEntriesResponse",
            "ListPackagesResponse",
            "ListRepositoriesResponse",
            "ListRevisionsRequest",
            "ListSecretsResponse",
            "LogEntry",
            "LogMetric",
            "LogSink",
            "MonitoringCreateTimeSeriesRequest",
            "MonitoringPoint",
            "MonitoringTimeSeries",
            "PubSubAcknowledgeRequest",
            "PubSubMessage",
            "PubSubPublishRequest",
            "PubSubPublishResponse",
            "PubSubPullRequest",
            "PubSubPullResponse",
            "PubSubQuotaUsage",
            "PubSubReceivedMessage",
            "PubSubSeekRequest",
            "PubSubSubscription",
            "PubSubTopic",
            "PythonPackage",
            "QueryJobResult",
            "QueryRequest",
            "RevisionListResponse",
            "SecretAccessRequest",
            "SecretAccessResponse",
            "SecretAddVersionRequest",
            "SecretAddVersionResponse",
            "SecretCreateRequest",
            "SecretManagerQuotaUsage",
            "SecretVersion",
            "ServiceAccount",
            "ServiceAccountKey",
            "SetIamPolicyRequest",
            "StartInstanceRequest",
            "StopInstanceRequest",
            "TableCreateRequest",
            "TableInfo",
            "TestIamPermissionsRequest",
            "TestIamPermissionsResponse",
            "TrafficTarget",
            "UpdateServiceRequest",
            "UpdateTrafficSplitRequest",
            "UptimeCheckConfig",
            "WriteLogEntriesRequest",
        ],
        "error_schema_classes": [],
        "example_schema_map": {"bq_quota_usage_example.json": "BqQuotaUsage"},
    },
    "kalshi": {
        "has_rest": True,
        "has_websocket": True,
        "has_fix": False,
        "config_secret_field": "kalshi_secret_name",
        "response_schema_classes": [
            "KalshiSeries",
            "KalshiEvent",
            "KalshiMarket",
            "KalshiOrderBook",
            "KalshiTrade",
            "KalshiOrder",
            "KalshiFill",
            "KalshiPosition",
            "KalshiBalance",
            "KalshiCandlestick",
            "KalshiHistoricalCutoff",
            "KalshiWebSocketTickerMsg",
            "KalshiWebSocketOrderbookDeltaMsg",
            "KalshiWebSocketTradeMsg",
            "KalshiWebSocketMarketLifecycleMsg",
        ],
        "error_schema_classes": ["KalshiError"],
        "example_schema_map": {
            "series_example.json": "KalshiSeries",
            "event_example.json": "KalshiEvent",
            "market_example.json": "KalshiMarket",
            "orderbook_example.json": "KalshiOrderBook",
            "trade_example.json": "KalshiTrade",
            "fill_example.json": "KalshiFill",
            "order_example.json": "KalshiOrder",
            "position_example.json": "KalshiPosition",
            "balance_example.json": "KalshiBalance",
            "error_example.json": "KalshiError",
        },
    },
    # ------------------------------------------------------------------
    # Internal contracts — inter-service messages (NOT external APIs)
    # ------------------------------------------------------------------
    "internal": {
        "module": "api_contracts.internal",
        "description": (
            "Typed schemas for all data flowing between internal services: "
            "lifecycle events, Pub/Sub messages, domain data, orders/fills, "
            "risk alerts, feature vectors, ML predictions, health checks, "
            "circuit breakers, and config change notifications."
        ),
        "is_internal": True,
        "sub_modules": {
            "events": "Lifecycle event envelopes and per-event metadata (GCS JSONL + Pub/Sub)",
            "domain": "Instrument records, market ticks, order books, OHLCV, candles",
            "execution": "Orders, fills, execution instructions, execution results",
            "signals": "Strategy instructions, DeFi signals, GCS output records",
            "risk": "Risk metrics, alerts, exposure summaries, pre-trade checks, positions",
            "features": "Delta-one feature vectors, vol surface, futures term structure",
            "ml": "Model metadata, inference requests/results, training jobs",
            "health": "Health status, dependency checks, circuit breakers, error envelopes",
            "config": "Config store records, change notifications, active pointers",
            "pubsub": "Typed Pub/Sub message bodies for every internal topic",
        },
        "response_schema_classes": [
            # Events
            "LifecycleEventEnvelope",
            "PubSubLifecycleEventMessage",
            "LifecycleEventType",
            "EventMetadata",
            "AuthFailureEvent",
            "ConfigChangedEvent",
            "SecretAccessedEvent",
            "StartedEvent",
            "FailedEvent",
            # Domain
            "InstrumentRecord",
            "MarketTrade",
            "OrderBookSnapshot5",
            "DerivativeTicker",
            "LiquidationRecord",
            "OhlcvBar",
            "QuoteRecord",
            "CanonicalOrderBook",
            "CanonicalTrade",
            "ProcessedCandle",
            # Execution
            "CanonicalOrder",
            "CanonicalFill",
            "FillEventPubSubPayload",
            "ExecutionInstruction",
            "ExecutionResult",
            "ManualInstructionRequest",
            "ManualInstructionResponse",
            # Signals
            "StrategyInstruction",
            "DeFiSignal",
            "InstructionRecord",
            "DeFiSignalRecord",
            # Risk
            "RiskMetrics",
            "AlertMessage",
            "PreTradeCheckRequest",
            "PreTradeCheckResponse",
            "ExposureSummary",
            "AccountState",
            "MarginState",
            "InternalPosition",
            "Balance",
            # Features
            "DeltaOneFeatureRecord",
            "OptionsIvRecord",
            "FuturesTermStructureRecord",
            # ML
            "ModelMetadata",
            "InferenceRequest",
            "InferenceResult",
            "TrainingJobRequest",
            "TrainingJobResult",
            # Health
            "ServiceHealthStatus",
            "DependencyReport",
            "EnhancedError",
            "CircuitBreakerState",
            # Config
            "ConfigStoreRecord",
            "ConfigChangeNotification",
            "ConfigStoreActivePointer",
            # Pub/Sub topics
            "InternalPubSubTopic",
            "PubSubMessageEnvelope",
            "FillEventMessage",
            "PositionUpdateMessage",
            "RiskAlertMessage",
            "MarketTickMessage",
            "StrategySignalMessage",
            "MLPredictionMessage",
            "ServiceLifecycleEventMessage",
            "HealthAlertMessage",
            "CircuitBreakerEventMessage",
        ],
        "pubsub_topics": {
            "fill-events-{venue}": "FillEventMessage",
            "order-requests": "OrderRequestMessage",
            "execution-results": "ExecutionResultMessage",
            "position-updates": "PositionUpdateMessage",
            "positions": "PositionUpdateMessage",
            "risk-alerts": "RiskAlertMessage",
            "margin-warnings": "RiskAlertMessage",
            "market-ticks": "MarketTickMessage",
            "order-book-updates": "PubSubMessageEnvelope",
            "derivative-tickers": "DerivativeTickerMessage",
            "liquidations": "LiquidationMessage",
            "feature-updates": "FeatureUpdateMessage",
            "strategy-signals": "StrategySignalMessage",
            "ml-predictions": "MLPredictionMessage",
            "service-lifecycle-events": "ServiceLifecycleEventMessage",
            "health-alerts": "HealthAlertMessage",
            "circuit-breaker-events": "CircuitBreakerEventMessage",
        },
        "sor_schemas": [
            "SorVenueScore",
            "SorRouteDecision",
            "SorChildOrder",
            "SorTwapSlice",
            "SorExecutionSummary",
            "SorVenueCapacity",
        ],
    },
    # ------------------------------------------------------------------
    # FIX protocol schemas (institutional order routing)
    # ------------------------------------------------------------------
    "fix": {
        "module": "api_contracts.fix.schemas",
        "description": (
            "FIX 4.2 / 4.4 / 5.0 message schemas for institutional order routing. "
            "Covers order management (NewOrderSingle, ExecutionReport, Cancel), "
            "market data (Snapshot, IncrementalRefresh), and admin messages. "
            "Venues: IBKR (FIX 4.2), Databento (FIX 4.4), institutional CeFi."
        ),
        "is_internal": False,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "fix_versions": ["FIX.4.2", "FIX.4.4", "FIX.5.0"],
        "response_schema_classes": [
            "FixNewOrderSingle",
            "FixExecutionReport",
            "FixOrderCancelRequest",
            "FixOrderCancelReject",
            "FixMarketDataRequest",
            "FixMarketDataSnapshot",
            "FixMarketDataIncrementalRefresh",
            "FixLogon",
            "FixLogout",
            "FixHeartbeat",
            "FixReject",
            "FixSessionConfig",
        ],
        "msg_type_map": {
            "D": "FixNewOrderSingle",
            "8": "FixExecutionReport",
            "F": "FixOrderCancelRequest",
            "9": "FixOrderCancelReject",
            "V": "FixMarketDataRequest",
            "W": "FixMarketDataSnapshot",
            "X": "FixMarketDataIncrementalRefresh",
            "A": "FixLogon",
            "5": "FixLogout",
            "0": "FixHeartbeat",
            "3": "FixReject",
        },
    },
    # ------------------------------------------------------------------
    # Prime broker integration
    # ------------------------------------------------------------------
    "prime_broker": {
        "module": "api_contracts.prime_broker.schemas",
        "description": (
            "Prime broker integration schemas — HiddenRoad / Talos / FalconX style. "
            "Covers credit accounts, cross-venue position netting, margin calls, "
            "net clearing instructions, and cleared fills."
        ),
        "is_internal": False,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "supported_providers": ["hidden_road", "talos", "falconx", "genesis", "cumberland"],
        "response_schema_classes": [
            "PrimeBrokerAccount",
            "PrimeBrokerPosition",
            "PrimeBrokerMarginCall",
            "NetClearingInstruction",
            "CrossMarginNettingResult",
            "PrimeBrokerFill",
            "CollateralAsset",
        ],
        "error_schema_classes": ["PrimeBrokerError"],
    },
    # ------------------------------------------------------------------
    # Regulatory and compliance reporting
    # ------------------------------------------------------------------
    "regulatory": {
        "module": "api_contracts.regulatory.schemas",
        "description": (
            "Regulatory reporting schemas: MiFID II (RTS 22/27/28), EMIR, Dodd-Frank, "
            "trade surveillance, and best execution monitoring."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "regimes": ["mifid_ii", "emir", "dodd_frank", "mas", "asic", "cftc", "sec"],
        "response_schema_classes": [
            "MifidIITradeReport",
            "BestExecutionRecord",
            "BestExecutionMonitoringRecord",
            "EmirTradeReport",
            "DoddFrankSwapReport",
            "TradeSurveillanceAlert",
        ],
        "error_schema_classes": ["TradeReportingError"],
    },
    # ------------------------------------------------------------------
    # Advanced risk analytics
    # ------------------------------------------------------------------
    "risk_analytics": {
        "module": "api_contracts.schemas.risk",
        "description": (
            "Advanced quantitative risk schemas: VaR (historical, parametric, Monte Carlo), "
            "CVaR, stress testing, SPAN multi-asset margin, P&L attribution."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "VaRRequest",
            "VaRResult",
            "StressScenario",
            "StressTestResult",
            "MultiAssetMarginCalculation",
            "PnLAttributionRecord",
            "RealTimePnLRecord",
            "RiskLimitBreach",
        ],
    },
    # ------------------------------------------------------------------
    # HFT latency metrics
    # ------------------------------------------------------------------
    "latency": {
        "module": "api_contracts.schemas.latency",
        "description": (
            "HFT and latency measurement schemas: tick-to-trade, co-location performance, "
            "sub-millisecond operation timing, order latency percentiles."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "TickToTradeMetric",
            "OrderLatencyRecord",
            "CoLocationPerformanceMetric",
            "NetworkJitterMetric",
            "SubMillisecondLatencyRecord",
            "LatencyPercentile",
            "LatencyBenchmarkReport",
        ],
    },
    # ------------------------------------------------------------------
    # Advanced analytics
    # ------------------------------------------------------------------
    "analytics": {
        "module": "api_contracts.schemas.analytics",
        "description": (
            "Advanced analytics schemas: factor attribution (momentum, value, carry, etc.), "
            "cross-asset correlation matrices, regime detection, alternative data signals "
            "(sentiment, satellite, options flow, dark pool)."
        ),
        "is_internal": True,
        "has_vcr_cassettes": False,
        "cassette_schema_version": "1.0",
        "response_schema_classes": [
            "FactorAttributionRecord",
            "FactorAttributionModel",
            "CrossAssetCorrelationMatrix",
            "CorrelationRegimeChange",
            "SentimentScore",
            "AlternativeDataSignal",
            "SatelliteObservation",
            "OptionsFlowRecord",
            "DarkPoolPrintRecord",
        ],
    },
}
