"""Features, Reference, and Non-football league definitions for the canonical registry.

Loaded by ``league_data.py`` to build the full LEAGUE_REGISTRY.
"""

from __future__ import annotations

from .league_registry import (
    FEAT_NO_FOOTYSTATS,
    FEAT_STANDARD,
    NO_FOOTBALL_SOURCES,
    REF_API_ONLY,
    LeagueDefinition,
)

# ---------------------------------------------------------------------------
# FEATURES LEAGUES - second divisions and lower tiers
# ---------------------------------------------------------------------------

FEATURES_LEAGUES: dict[str, LeagueDefinition] = {
    "ENG_NATIONAL_LEAGUE": LeagueDefinition(
        league_id="ENG_NATIONAL_LEAGUE",
        display_name="English National League",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=43,
        tier=5,
        classification="Features",
    ),
    "FRANCE_NATIONAL": LeagueDefinition(
        league_id="FRANCE_NATIONAL",
        display_name="National",
        sport="FOOTBALL",
        country="FR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=63,
        tier=3,
        classification="Features",
    ),
    "EERSTE_DIVISIE": LeagueDefinition(
        league_id="EERSTE_DIVISIE",
        display_name="Eerste Divisie",
        sport="FOOTBALL",
        country="NL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=89,
        tier=2,
        classification="Features",
    ),
    "LIGA_PORTUGAL_2": LeagueDefinition(
        league_id="LIGA_PORTUGAL_2",
        display_name="Liga Portugal 2",
        sport="FOOTBALL",
        country="PT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=95,
        tier=2,
        classification="Features",
    ),
    "BELGIAN_FIRST_B": LeagueDefinition(
        league_id="BELGIAN_FIRST_B",
        display_name="Belgian First Division B",
        sport="FOOTBALL",
        country="BE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=145,
        tier=2,
        classification="Features",
    ),
    "TFF_FIRST_LEAGUE": LeagueDefinition(
        league_id="TFF_FIRST_LEAGUE",
        display_name="TFF First League",
        sport="FOOTBALL",
        country="TR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=204,
        tier=2,
        classification="Features",
    ),
    "GREEK_SUPER_LEAGUE_2": LeagueDefinition(
        league_id="GREEK_SUPER_LEAGUE_2",
        display_name="Greek Super League 2",
        sport="FOOTBALL",
        country="GR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=198,
        tier=2,
        classification="Features",
    ),
    "SCOTTISH_CHAMPIONSHIP": LeagueDefinition(
        league_id="SCOTTISH_CHAMPIONSHIP",
        display_name="Scottish Championship",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=180,
        tier=2,
        classification="Features",
    ),
    "AUSTRIAN_2_LIGA": LeagueDefinition(
        league_id="AUSTRIAN_2_LIGA",
        display_name="Austrian 2. Liga",
        sport="FOOTBALL",
        country="AT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=219,
        tier=2,
        classification="Features",
    ),
    "SWISS_CHALLENGE_LEAGUE": LeagueDefinition(
        league_id="SWISS_CHALLENGE_LEAGUE",
        display_name="Swiss Challenge League",
        sport="FOOTBALL",
        country="CH",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=208,
        tier=2,
        classification="Features",
    ),
    "DANISH_1ST_DIVISION": LeagueDefinition(
        league_id="DANISH_1ST_DIVISION",
        display_name="Danish 1st Division",
        sport="FOOTBALL",
        country="DK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=120,
        tier=2,
        classification="Features",
    ),
    "NORWAY_1_DIVISJON": LeagueDefinition(
        league_id="NORWAY_1_DIVISJON",
        display_name="Norwegian 1. divisjon",
        sport="FOOTBALL",
        country="NO",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=104,
        tier=2,
        classification="Features",
    ),
    "SUPERETTAN": LeagueDefinition(
        league_id="SUPERETTAN",
        display_name="Superettan",
        sport="FOOTBALL",
        country="SE",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=114,
        tier=2,
        classification="Features",
    ),
    "POLAND_I_LIGA": LeagueDefinition(
        league_id="POLAND_I_LIGA",
        display_name="Polish I Liga",
        sport="FOOTBALL",
        country="PL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=107,
        tier=2,
        classification="Features",
    ),
    "ARGENTINA_PRIMERA_NACIONAL": LeagueDefinition(
        league_id="ARGENTINA_PRIMERA_NACIONAL",
        display_name="Argentine Primera Nacional",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=129,
        tier=2,
        classification="Features",
    ),
    "BRASILEIRAO_SERIE_B": LeagueDefinition(
        league_id="BRASILEIRAO_SERIE_B",
        display_name="Brasileirao Serie B",
        sport="FOOTBALL",
        country="BR",
        season_months=(4, 12),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=72,
        tier=2,
        classification="Features",
    ),
    "CHILE_PRIMERA_B": LeagueDefinition(
        league_id="CHILE_PRIMERA_B",
        display_name="Chilean Primera B",
        sport="FOOTBALL",
        country="CL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=266,
        tier=2,
        classification="Features",
    ),
    "LIGA_EXPANSION_MX": LeagueDefinition(
        league_id="LIGA_EXPANSION_MX",
        display_name="Liga de Expansion MX",
        sport="FOOTBALL",
        country="MX",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=263,
        tier=2,
        classification="Features",
    ),
    "J2_LEAGUE": LeagueDefinition(
        league_id="J2_LEAGUE",
        display_name="J2 League",
        sport="FOOTBALL",
        country="JP",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=99,
        tier=2,
        classification="Features",
    ),
    "K_LEAGUE_2": LeagueDefinition(
        league_id="K_LEAGUE_2",
        display_name="K League 2",
        sport="FOOTBALL",
        country="KR",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=293,
        tier=2,
        classification="Features",
    ),
    "USL_CHAMPIONSHIP": LeagueDefinition(
        league_id="USL_CHAMPIONSHIP",
        display_name="USL Championship",
        sport="FOOTBALL",
        country="US",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=255,
        tier=2,
        classification="Features",
    ),
    "PRIMERA_RFEF": LeagueDefinition(
        league_id="PRIMERA_RFEF",
        display_name="Primera Division RFEF",
        sport="FOOTBALL",
        country="ES",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=435,
        tier=3,
        classification="Features",
    ),
    # Added 2026-07-21 (operator ruling: in-universe) so the historical odds captured
    # under sport_key soccer_china_superleague / soccer_russia_premier_league resolve to
    # a canonical slug instead of reading as non-canonical. Resolution is by NUMERIC
    # api_football_id, so the bare display names ("Super League"/"Premier League") that
    # collide with other leagues are harmless here.
    "CHINA_SUPER_LEAGUE": LeagueDefinition(
        league_id="CHINA_SUPER_LEAGUE",
        display_name="Chinese Super League",
        sport="FOOTBALL",
        country="CN",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=FEAT_STANDARD,
        api_football_id=169,
        tier=1,
        classification="Features",
    ),
    "RUSSIA_PREMIER_LEAGUE": LeagueDefinition(
        league_id="RUSSIA_PREMIER_LEAGUE",
        display_name="Russian Premier League",
        sport="FOOTBALL",
        country="RU",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=FEAT_STANDARD,
        api_football_id=235,
        tier=1,
        classification="Features",
    ),
}

# ---------------------------------------------------------------------------
# REFERENCE LEAGUES - domestic cups + continental competitions
# ---------------------------------------------------------------------------

REFERENCE_LEAGUES: dict[str, LeagueDefinition] = {
    "FA_CUP": LeagueDefinition(
        league_id="FA_CUP",
        display_name="FA Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=45,
        tier=0,
        classification="Reference",
    ),
    "CARABAO_CUP": LeagueDefinition(
        league_id="CARABAO_CUP",
        display_name="Carabao Cup (EFL Cup)",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 3),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=48,
        tier=0,
        classification="Reference",
    ),
    "COPA_DEL_REY": LeagueDefinition(
        league_id="COPA_DEL_REY",
        display_name="Copa del Rey",
        sport="FOOTBALL",
        country="ES",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=143,
        tier=0,
        classification="Reference",
    ),
    "SUPERCOPA_ESPANA": LeagueDefinition(
        league_id="SUPERCOPA_ESPANA",
        display_name="Supercopa de Espana",
        sport="FOOTBALL",
        country="ES",
        season_months=(1, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=556,
        tier=0,
        classification="Reference",
    ),
    "DFB_POKAL": LeagueDefinition(
        league_id="DFB_POKAL",
        display_name="DFB Pokal",
        sport="FOOTBALL",
        country="DE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=81,
        tier=0,
        classification="Reference",
    ),
    "DFL_SUPERCUP": LeagueDefinition(
        league_id="DFL_SUPERCUP",
        display_name="DFL Supercup",
        sport="FOOTBALL",
        country="DE",
        season_months=(8, 8),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=529,
        tier=0,
        classification="Reference",
    ),
    "COPPA_ITALIA": LeagueDefinition(
        league_id="COPPA_ITALIA",
        display_name="Coppa Italia",
        sport="FOOTBALL",
        country="IT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=137,
        tier=0,
        classification="Reference",
    ),
    "SUPERCOPPA_ITALIANA": LeagueDefinition(
        league_id="SUPERCOPPA_ITALIANA",
        display_name="Supercoppa Italiana",
        sport="FOOTBALL",
        country="IT",
        season_months=(1, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=547,
        tier=0,
        classification="Reference",
    ),
    "COUPE_DE_FRANCE": LeagueDefinition(
        league_id="COUPE_DE_FRANCE",
        display_name="Coupe de France",
        sport="FOOTBALL",
        country="FR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=66,
        tier=0,
        classification="Reference",
    ),
    "TROPHEE_CHAMPIONS": LeagueDefinition(
        league_id="TROPHEE_CHAMPIONS",
        display_name="Trophee des Champions",
        sport="FOOTBALL",
        country="FR",
        season_months=(8, 8),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=526,
        tier=0,
        classification="Reference",
    ),
    "KNVB_CUP": LeagueDefinition(
        league_id="KNVB_CUP",
        display_name="KNVB Cup",
        sport="FOOTBALL",
        country="NL",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=90,
        tier=0,
        classification="Reference",
    ),
    "TACA_DE_PORTUGAL": LeagueDefinition(
        league_id="TACA_DE_PORTUGAL",
        display_name="Taca de Portugal",
        sport="FOOTBALL",
        country="PT",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=96,
        tier=0,
        classification="Reference",
    ),
    "TACA_DA_LIGA": LeagueDefinition(
        league_id="TACA_DA_LIGA",
        display_name="Taca da Liga",
        sport="FOOTBALL",
        country="PT",
        season_months=(8, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=97,
        tier=0,
        classification="Reference",
    ),
    "GREEK_CUP": LeagueDefinition(
        league_id="GREEK_CUP",
        display_name="Greek Cup",
        sport="FOOTBALL",
        country="GR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=199,
        tier=0,
        classification="Reference",
    ),
    "SCOTTISH_CUP": LeagueDefinition(
        league_id="SCOTTISH_CUP",
        display_name="Scottish Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=181,
        tier=0,
        classification="Reference",
    ),
    "SCOTTISH_LEAGUE_CUP": LeagueDefinition(
        league_id="SCOTTISH_LEAGUE_CUP",
        display_name="Scottish League Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(7, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=182,
        tier=0,
        classification="Reference",
    ),
    # SCOTTISH_LEAGUE_CUP_185 retired 2026-05-06 — duplicate registry entry
    # for Scottish League Cup. The ``_185`` suffix is api_football's season
    # ID leaking into the canonical name. ``SCOTTISH_LEAGUE_CUP`` (af_id=182)
    # is the canonical entry; 185 was a leftover from an api_football catalogue
    # rotation. Both shared classification=Reference so dropping has no
    # downstream impact (no Prediction-tier consumers).
    "AUSTRIAN_CUP": LeagueDefinition(
        league_id="AUSTRIAN_CUP",
        display_name="Austrian Cup",
        sport="FOOTBALL",
        country="AT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=220,
        tier=0,
        classification="Reference",
    ),
    "SWISS_CUP": LeagueDefinition(
        league_id="SWISS_CUP",
        display_name="Swiss Cup",
        sport="FOOTBALL",
        country="CH",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=209,
        tier=0,
        classification="Reference",
    ),
    "DANISH_CUP": LeagueDefinition(
        league_id="DANISH_CUP",
        display_name="Danish Cup",
        sport="FOOTBALL",
        country="DK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=121,
        tier=0,
        classification="Reference",
    ),
    "NORWEGIAN_CUP": LeagueDefinition(
        league_id="NORWEGIAN_CUP",
        display_name="Norwegian Cup",
        sport="FOOTBALL",
        country="NO",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=105,
        tier=0,
        classification="Reference",
    ),
    "SVENSKA_CUPEN": LeagueDefinition(
        league_id="SVENSKA_CUPEN",
        display_name="Svenska Cupen",
        sport="FOOTBALL",
        country="SE",
        season_months=(1, 3),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=115,
        tier=0,
        classification="Reference",
    ),
    "POLISH_CUP": LeagueDefinition(
        league_id="POLISH_CUP",
        display_name="Polish Cup",
        sport="FOOTBALL",
        country="PL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=108,
        tier=0,
        classification="Reference",
    ),
    "COPA_ARGENTINA": LeagueDefinition(
        league_id="COPA_ARGENTINA",
        display_name="Copa Argentina",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=130,
        tier=0,
        classification="Reference",
    ),
    "COPA_LIGA_PROFESIONAL": LeagueDefinition(
        league_id="COPA_LIGA_PROFESIONAL",
        display_name="Copa de la Liga Profesional",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1032,
        tier=0,
        classification="Reference",
    ),
    "COPA_DO_BRASIL": LeagueDefinition(
        league_id="COPA_DO_BRASIL",
        display_name="Copa do Brasil",
        sport="FOOTBALL",
        country="BR",
        season_months=(2, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=73,
        tier=0,
        classification="Reference",
    ),
    "COPA_CHILE": LeagueDefinition(
        league_id="COPA_CHILE",
        display_name="Copa Chile",
        sport="FOOTBALL",
        country="CL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=267,
        tier=0,
        classification="Reference",
    ),
    "COPA_MX": LeagueDefinition(
        league_id="COPA_MX",
        display_name="Copa MX",
        sport="FOOTBALL",
        country="MX",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=264,
        tier=0,
        classification="Reference",
    ),
    "BELGIAN_CUP": LeagueDefinition(
        league_id="BELGIAN_CUP",
        display_name="Belgian Cup",
        sport="FOOTBALL",
        country="BE",
        season_months=(9, 4),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=147,
        tier=0,
        classification="Reference",
    ),
    "TURKIYE_KUPASI": LeagueDefinition(
        league_id="TURKIYE_KUPASI",
        display_name="Turkiye Kupasi",
        sport="FOOTBALL",
        country="TR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=206,
        tier=0,
        classification="Reference",
    ),
    "US_OPEN_CUP": LeagueDefinition(
        league_id="US_OPEN_CUP",
        display_name="US Open Cup",
        sport="FOOTBALL",
        country="US",
        season_months=(4, 9),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=257,
        tier=0,
        classification="Reference",
    ),
    "JLEAGUE_CUP": LeagueDefinition(
        league_id="JLEAGUE_CUP",
        display_name="J.League Cup",
        sport="FOOTBALL",
        country="JP",
        season_months=(2, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=101,
        tier=0,
        classification="Reference",
    ),
    "EMPEROR_CUP": LeagueDefinition(
        league_id="EMPEROR_CUP",
        display_name="Emperor Cup",
        sport="FOOTBALL",
        country="JP",
        season_months=(5, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=102,
        tier=0,
        classification="Reference",
    ),
    "KOREAN_FA_CUP": LeagueDefinition(
        league_id="KOREAN_FA_CUP",
        display_name="Korean FA Cup",
        sport="FOOTBALL",
        country="KR",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=294,
        tier=0,
        classification="Reference",
    ),
    "AUSTRALIA_CUP": LeagueDefinition(
        league_id="AUSTRALIA_CUP",
        display_name="Australia Cup",
        sport="FOOTBALL",
        country="AU",
        season_months=(5, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=874,
        tier=0,
        classification="Reference",
    ),
    # Continental
    "UCL": LeagueDefinition(
        league_id="UCL",
        display_name="UEFA Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=2,
        tier=0,
        classification="Reference",
    ),
    "UEL": LeagueDefinition(
        league_id="UEL",
        display_name="UEFA Europa League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=3,
        tier=0,
        classification="Reference",
    ),
    "UECL": LeagueDefinition(
        league_id="UECL",
        display_name="UEFA Conference League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=848,
        tier=0,
        classification="Reference",
    ),
    "COPA_LIBERTADORES": LeagueDefinition(
        league_id="COPA_LIBERTADORES",
        display_name="CONMEBOL Libertadores",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=13,
        tier=0,
        classification="Reference",
    ),
    "COPA_SUDAMERICANA": LeagueDefinition(
        league_id="COPA_SUDAMERICANA",
        display_name="CONMEBOL Sudamericana",
        sport="FOOTBALL",
        country="INTL",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=11,
        tier=0,
        classification="Reference",
    ),
    # =======================================================================
    # CONTINENTAL / INTERNATIONAL MAJORS — Directive A/B curated-universe
    # (plans/active/sports_satellite_ao_dispatch_batch2_2026_07_24.md).
    # in_mvp_scope=False (operator-approved 2026-07-25): a wider REFERENCE
    # universe, not a prediction-scope widening. season_months is a
    # HEMISPHERE-BASED PLACEHOLDER (operator-approved 2026-07-25 default:
    # UEFA/CONCACAF/AFC-anchored -> Northern (8,5); CONMEBOL/CAF/OFC-anchored
    # -> Southern (2,11)) — NOT researched per-competition real windows.
    # TODO(sports): replace with the real per-competition calendar (several
    # of these are quadrennial, not annual, e.g. World Cup/Euros/Copa
    # America run June-July only once every 4 years) before relying on
    # season_months for anything beyond a coarse write-gate filter.
    # =======================================================================
    "WORLD_CUP": LeagueDefinition(
        league_id="WORLD_CUP",
        display_name="World Cup",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EURO_CHAMPIONSHIP": LeagueDefinition(
        league_id="EURO_CHAMPIONSHIP",
        display_name="Euro Championship",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=4,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "FIFA_CLUB_WORLD_CUP": LeagueDefinition(
        league_id="FIFA_CLUB_WORLD_CUP",
        display_name="FIFA Club World Cup",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=15,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "COPA_AMERICA": LeagueDefinition(
        league_id="COPA_AMERICA",
        display_name="Copa America",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=9,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "OFC_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="OFC_CHAMPIONS_LEAGUE",
        display_name="OFC Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=27,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CONCACAF_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="CONCACAF_CHAMPIONS_LEAGUE",
        display_name="CONCACAF Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=16,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AFC_CHAMPIONS_LEAGUE_ELITE": LeagueDefinition(
        league_id="AFC_CHAMPIONS_LEAGUE_ELITE",
        display_name="AFC Champions League Elite",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=17,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AFC_CHAMPIONS_LEAGUE_TWO": LeagueDefinition(
        league_id="AFC_CHAMPIONS_LEAGUE_TWO",
        display_name="AFC Champions League Two",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=18,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UEFA_NATIONS_LEAGUE": LeagueDefinition(
        league_id="UEFA_NATIONS_LEAGUE",
        display_name="UEFA Nations League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=5,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CAF_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="CAF_CHAMPIONS_LEAGUE",
        display_name="CAF Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=12,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CONCACAF_NATIONS_LEAGUE": LeagueDefinition(
        league_id="CONCACAF_NATIONS_LEAGUE",
        display_name="CONCACAF Nations League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=536,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # =======================================================================
    # Domestic curated-universe expansion (Directive A/B, first verified batch,
    # 2026-07-25) -- top league + division below + primary domestic cup for
    # countries not yet in LEAGUE_REGISTRY. Each entry's tier structure was
    # verified against a real external source (not derived from the raw
    # api-football name field alone) before being added -- see
    # plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md
    # for the full remaining-country list and the fabrication-risk rationale
    # for why this is a small verified batch, not the whole 143/145.
    # =======================================================================
    "UKRAINE_PREMIER_LEAGUE": LeagueDefinition(
        league_id="UKRAINE_PREMIER_LEAGUE",
        display_name="Ukrainian Premier League",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=333,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UKRAINE_PERSHA_LIGA": LeagueDefinition(
        league_id="UKRAINE_PERSHA_LIGA",
        display_name="Ukrainian First League (Persha Liha)",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=334,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UKRAINE_CUP": LeagueDefinition(
        league_id="UKRAINE_CUP",
        display_name="Ukrainian Cup",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=335,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_HNL": LeagueDefinition(
        league_id="CROATIA_HNL",
        display_name="Croatian Football League (HNL)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=210,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_FIRST_NL": LeagueDefinition(
        league_id="CROATIA_FIRST_NL",
        display_name="Croatian First NL (Prva NL)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=211,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_CUP": LeagueDefinition(
        league_id="CROATIA_CUP",
        display_name="Croatian Cup (Hrvatski nogometni kup)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=212,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_BOTOLA_PRO": LeagueDefinition(
        league_id="MOROCCO_BOTOLA_PRO",
        display_name="Botola Pro",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=200,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_BOTOLA_2": LeagueDefinition(
        league_id="MOROCCO_BOTOLA_2",
        display_name="Botola 2",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=201,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_CUP": LeagueDefinition(
        league_id="MOROCCO_CUP",
        display_name="Throne Cup (Coupe du Trone)",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=822,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_SUPER_LIGA": LeagueDefinition(
        league_id="SERBIA_SUPER_LIGA",
        display_name="Serbian SuperLiga",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=286,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_PRVA_LIGA": LeagueDefinition(
        league_id="SERBIA_PRVA_LIGA",
        display_name="Serbian First League",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=287,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_CUP": LeagueDefinition(
        league_id="SERBIA_CUP",
        display_name="Serbian Cup",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=732,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_PREMIER_LEAGUE": LeagueDefinition(
        league_id="EGYPT_PREMIER_LEAGUE",
        display_name="Egyptian Premier League",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=233,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_SECOND_DIVISION": LeagueDefinition(
        league_id="EGYPT_SECOND_DIVISION",
        display_name="Egyptian Second Division A",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=887,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_CUP": LeagueDefinition(
        league_id="EGYPT_CUP",
        display_name="Egypt Cup",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=714,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # =======================================================================
    # Domestic curated-universe expansion (Directive A/B, Central Asia (AFC)
    # batch, 2026-07-25) -- see
    # plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md
    # for the shared batch contract. Kyrgyzstan/Tajikistan/Turkmenistan each
    # verified via WebSearch as having a real division-below and/or domestic
    # cup in reality, but the api-football leagues catalog (leagues.parquet)
    # carries ONLY the top league for each -- no api_football_id exists to
    # cite for the missing tiers, so per the near-miss "never fabricate an
    # id" rule those tiers are omitted rather than guessed. Turkmenistan's
    # catalog also has a "Youth League" (id 829) which is explicitly NOT used
    # as a division-below stand-in -- wrong axis (youth vs senior pyramid).
    # =======================================================================
    "KAZAKHSTAN_PREMIER_LEAGUE": LeagueDefinition(
        league_id="KAZAKHSTAN_PREMIER_LEAGUE",
        display_name="Kazakhstan Premier League",
        sport="FOOTBALL",
        country="KZ",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=389,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KAZAKHSTAN_FIRST_DIVISION": LeagueDefinition(
        league_id="KAZAKHSTAN_FIRST_DIVISION",
        display_name="Kazakhstan First Division",
        sport="FOOTBALL",
        country="KZ",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=388,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KAZAKHSTAN_CUP": LeagueDefinition(
        league_id="KAZAKHSTAN_CUP",
        display_name="Kazakhstan Cup",
        sport="FOOTBALL",
        country="KZ",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=498,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KYRGYZSTAN_PREMIER_LEAGUE": LeagueDefinition(
        league_id="KYRGYZSTAN_PREMIER_LEAGUE",
        display_name="Kyrgyz Premier League",
        sport="FOOTBALL",
        country="KG",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=569,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "TAJIKISTAN_VYSSHAYA_LIGA": LeagueDefinition(
        league_id="TAJIKISTAN_VYSSHAYA_LIGA",
        display_name="Tajikistan Higher League (Vysshaya Liga)",
        sport="FOOTBALL",
        country="TJ",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=571,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "TURKMENISTAN_YOKARY_LIGA": LeagueDefinition(
        league_id="TURKMENISTAN_YOKARY_LIGA",
        display_name="Turkmenistan Higher League (Ýokary Liga)",
        sport="FOOTBALL",
        country="TM",
        season_months=(4, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=636,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UZBEKISTAN_SUPER_LEAGUE": LeagueDefinition(
        league_id="UZBEKISTAN_SUPER_LEAGUE",
        display_name="Uzbekistan Super League",
        sport="FOOTBALL",
        country="UZ",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=369,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UZBEKISTAN_PRO_LEAGUE": LeagueDefinition(
        league_id="UZBEKISTAN_PRO_LEAGUE",
        display_name="Uzbekistan Pro League",
        sport="FOOTBALL",
        country="UZ",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1075,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UZBEKISTAN_CUP": LeagueDefinition(
        league_id="UZBEKISTAN_CUP",
        display_name="Uzbekistan Cup",
        sport="FOOTBALL",
        country="UZ",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=802,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # =======================================================================
    # Domestic curated-universe expansion, South America / CONMEBOL batch
    # (2026-07-25) -- top league + division below + primary domestic cup for
    # Bolivia, Colombia, Ecuador, Paraguay, Peru, Uruguay, Venezuela. Each
    # entry verified via WebSearch against a real external source (Wikipedia)
    # before being added, per the same fabrication-risk discipline as the
    # first batch. Two deliberate gaps, NOT guessed:
    #  - Bolivia's "division below": the catalog's only 2nd-tier-shaped entry
    #    ("Nacional B") was Bolivia's real 2nd tier ONLY 2011-2016 -- replaced
    #    by Copa Simon Bolivar in 2016, which is NOT in the catalog. No
    #    catalog entry correctly represents the CURRENT 2nd tier -- skipped.
    #  - Peru's cup: "Copa Peru" is an amateur/promotion tournament for
    #    lower-tier clubs (not a knockout cup); "Copa Bicentenario" was
    #    dissolved after 2021 and is defunct. Neither is a genuine current
    #    primary domestic cup -- skipped.
    # Paraguay/Uruguay split their top flight into Apertura/Clausura HALVES
    # of the SAME season (not two tiers) -- the Apertura entry is used as the
    # representative top-league row; the Clausura catalog entry is a sibling
    # half-season, not a separate competition, and is intentionally not added.
    # See plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md
    # for the full remaining-country list and near-miss error classes.
    # =======================================================================
    "BOLIVIA_PRIMERA": LeagueDefinition(
        league_id="BOLIVIA_PRIMERA",
        display_name="Bolivian Primera Division",
        sport="FOOTBALL",
        country="BO",
        season_months=(2, 11),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=344,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BOLIVIA_CUP": LeagueDefinition(
        league_id="BOLIVIA_CUP",
        display_name="Copa de la Division Profesional",
        sport="FOOTBALL",
        country="BO",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=964,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "COLOMBIA_PRIMERA_A": LeagueDefinition(
        league_id="COLOMBIA_PRIMERA_A",
        display_name="Colombian Primera A",
        sport="FOOTBALL",
        country="CO",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=239,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "COLOMBIA_PRIMERA_B": LeagueDefinition(
        league_id="COLOMBIA_PRIMERA_B",
        display_name="Colombian Primera B",
        sport="FOOTBALL",
        country="CO",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=240,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "COLOMBIA_CUP": LeagueDefinition(
        league_id="COLOMBIA_CUP",
        display_name="Copa Colombia",
        sport="FOOTBALL",
        country="CO",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=241,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ECUADOR_LIGA_PRO": LeagueDefinition(
        league_id="ECUADOR_LIGA_PRO",
        display_name="Ecuadorian LigaPro Serie A",
        sport="FOOTBALL",
        country="EC",
        season_months=(2, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=242,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ECUADOR_SERIE_B": LeagueDefinition(
        league_id="ECUADOR_SERIE_B",
        display_name="Ecuadorian LigaPro Serie B",
        sport="FOOTBALL",
        country="EC",
        season_months=(3, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=243,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ECUADOR_CUP": LeagueDefinition(
        league_id="ECUADOR_CUP",
        display_name="Copa Ecuador",
        sport="FOOTBALL",
        country="EC",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=917,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PARAGUAY_DIVISION_PROFESIONAL": LeagueDefinition(
        league_id="PARAGUAY_DIVISION_PROFESIONAL",
        display_name="Paraguayan Division Profesional (Apertura)",
        sport="FOOTBALL",
        country="PY",
        season_months=(1, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=250,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PARAGUAY_DIVISION_INTERMEDIA": LeagueDefinition(
        league_id="PARAGUAY_DIVISION_INTERMEDIA",
        display_name="Paraguayan Division Intermedia",
        sport="FOOTBALL",
        country="PY",
        season_months=(1, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=251,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PARAGUAY_CUP": LeagueDefinition(
        league_id="PARAGUAY_CUP",
        display_name="Copa Paraguay",
        sport="FOOTBALL",
        country="PY",
        season_months=(4, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=501,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PERU_PRIMERA": LeagueDefinition(
        league_id="PERU_PRIMERA",
        display_name="Peruvian Primera Division",
        sport="FOOTBALL",
        country="PE",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=281,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PERU_SEGUNDA": LeagueDefinition(
        league_id="PERU_SEGUNDA",
        display_name="Peruvian Segunda Division",
        sport="FOOTBALL",
        country="PE",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=282,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "URUGUAY_PRIMERA": LeagueDefinition(
        league_id="URUGUAY_PRIMERA",
        display_name="Uruguayan Primera Division (Apertura)",
        sport="FOOTBALL",
        country="UY",
        season_months=(2, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=268,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "URUGUAY_SEGUNDA": LeagueDefinition(
        league_id="URUGUAY_SEGUNDA",
        display_name="Uruguayan Segunda Division",
        sport="FOOTBALL",
        country="UY",
        season_months=(2, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=269,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "URUGUAY_CUP": LeagueDefinition(
        league_id="URUGUAY_CUP",
        display_name="Copa Uruguay",
        sport="FOOTBALL",
        country="UY",
        season_months=(8, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=930,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "VENEZUELA_PRIMERA": LeagueDefinition(
        league_id="VENEZUELA_PRIMERA",
        display_name="Venezuelan Primera Division",
        sport="FOOTBALL",
        country="VE",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=299,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "VENEZUELA_SEGUNDA": LeagueDefinition(
        league_id="VENEZUELA_SEGUNDA",
        display_name="Venezuelan Segunda Division",
        sport="FOOTBALL",
        country="VE",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=300,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "VENEZUELA_CUP": LeagueDefinition(
        league_id="VENEZUELA_CUP",
        display_name="Copa Venezuela",
        sport="FOOTBALL",
        country="VE",
        season_months=(6, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1113,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # Domestic curated-universe expansion (Directive A/B, Eastern Europe (UEFA)
    # batch, 2026-07-25) -- top league + division below + primary domestic cup
    # for 16 of 17 candidate countries (Crimea SKIPPED -- see note below). Each
    # entry's tier structure was verified against a real external source
    # (WebSearch/Wikipedia) before being added -- see
    # plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md.
    # None of these countries have real captured odds data (verified against
    # the pre-pruning backup parquet -- zero ODDS rows for any candidate
    # api_football_id), so all entries are in_mvp_scope=False.
    # CRIMEA SKIPPED: no solid, current, citable evidence establishes the
    # catalog's "Premier League" (api_football_id=870) as a stable, sanctioned
    # competition under any body FIFA/UEFA/Ukraine treats as legitimate --
    # UEFA-granted "special status" (non-member, non-cross-border), Ukrainian
    # federation does not recognize it, and reporting suggests the scene may
    # be fragmented across multiple competitions. Per the near-miss rule, an
    # unresolved political/federation identity is SKIPPED, never guessed.
    # =======================================================================
    "ALBANIA_SUPERLIGA": LeagueDefinition(
        league_id="ALBANIA_SUPERLIGA",
        display_name="Kategoria Superiore (Albanian Superliga)",
        sport="FOOTBALL",
        country="AL",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=310,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ALBANIA_FIRST_DIVISION": LeagueDefinition(
        league_id="ALBANIA_FIRST_DIVISION",
        display_name="Kategoria e Parë (Albanian First Division)",
        sport="FOOTBALL",
        country="AL",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=311,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ALBANIA_CUP": LeagueDefinition(
        league_id="ALBANIA_CUP",
        display_name="Albanian Cup (Kupa e Shqipërisë)",
        sport="FOOTBALL",
        country="AL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=707,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ARMENIA_PREMIER_LEAGUE": LeagueDefinition(
        league_id="ARMENIA_PREMIER_LEAGUE",
        display_name="Armenian Premier League",
        sport="FOOTBALL",
        country="AM",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=342,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ARMENIA_FIRST_LEAGUE": LeagueDefinition(
        league_id="ARMENIA_FIRST_LEAGUE",
        display_name="Armenian First League",
        sport="FOOTBALL",
        country="AM",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=343,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ARMENIA_CUP": LeagueDefinition(
        league_id="ARMENIA_CUP",
        display_name="Armenian Cup",
        sport="FOOTBALL",
        country="AM",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=709,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AZERBAIJAN_PREMYER_LIQA": LeagueDefinition(
        league_id="AZERBAIJAN_PREMYER_LIQA",
        display_name="Azerbaijan Premier League",
        sport="FOOTBALL",
        country="AZ",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=419,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AZERBAIJAN_BIRINCI_DASTA": LeagueDefinition(
        league_id="AZERBAIJAN_BIRINCI_DASTA",
        display_name="Azerbaijan First League (Birinci Dəstə)",
        sport="FOOTBALL",
        country="AZ",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=418,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AZERBAIJAN_CUP": LeagueDefinition(
        league_id="AZERBAIJAN_CUP",
        display_name="Azerbaijan Cup",
        sport="FOOTBALL",
        country="AZ",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=420,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BELARUS_PREMIER_LEAGUE": LeagueDefinition(
        league_id="BELARUS_PREMIER_LEAGUE",
        display_name="Belarusian Premier League",
        sport="FOOTBALL",
        country="BY",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=116,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BELARUS_FIRST_LEAGUE": LeagueDefinition(
        league_id="BELARUS_FIRST_LEAGUE",
        display_name="Belarusian First League",
        sport="FOOTBALL",
        country="BY",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=117,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BELARUS_CUP": LeagueDefinition(
        league_id="BELARUS_CUP",
        display_name="Belarusian Cup",
        sport="FOOTBALL",
        country="BY",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=486,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BOSNIA_PREMIJER_LIGA": LeagueDefinition(
        league_id="BOSNIA_PREMIJER_LIGA",
        display_name="Premier League of Bosnia and Herzegovina",
        sport="FOOTBALL",
        country="BA",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=315,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BOSNIA_FIRST_LEAGUE_FBIH": LeagueDefinition(
        league_id="BOSNIA_FIRST_LEAGUE_FBIH",
        display_name="First League of the Federation of Bosnia and Herzegovina",
        sport="FOOTBALL",
        country="BA",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=316,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BOSNIA_FIRST_LEAGUE_RS": LeagueDefinition(
        league_id="BOSNIA_FIRST_LEAGUE_RS",
        display_name="First League of the Republika Srpska",
        sport="FOOTBALL",
        country="BA",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=317,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BOSNIA_CUP": LeagueDefinition(
        league_id="BOSNIA_CUP",
        display_name="Bosnia and Herzegovina Football Cup",
        sport="FOOTBALL",
        country="BA",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=314,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BULGARIA_FIRST_LEAGUE": LeagueDefinition(
        league_id="BULGARIA_FIRST_LEAGUE",
        display_name="Bulgarian First Professional Football League",
        sport="FOOTBALL",
        country="BG",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=172,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BULGARIA_SECOND_LEAGUE": LeagueDefinition(
        league_id="BULGARIA_SECOND_LEAGUE",
        display_name="Bulgarian Second Professional Football League",
        sport="FOOTBALL",
        country="BG",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=173,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BULGARIA_CUP": LeagueDefinition(
        league_id="BULGARIA_CUP",
        display_name="Bulgarian Cup",
        sport="FOOTBALL",
        country="BG",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=174,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CZECH_REPUBLIC_LIGA": LeagueDefinition(
        league_id="CZECH_REPUBLIC_LIGA",
        display_name="Czech First League (Chance Liga)",
        sport="FOOTBALL",
        country="CZ",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=345,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CZECH_REPUBLIC_FNL": LeagueDefinition(
        league_id="CZECH_REPUBLIC_FNL",
        display_name="Czech National Football League (Fortuna národní liga)",
        sport="FOOTBALL",
        country="CZ",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=346,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CZECH_REPUBLIC_CUP": LeagueDefinition(
        league_id="CZECH_REPUBLIC_CUP",
        display_name="Czech Cup (MOL Cup)",
        sport="FOOTBALL",
        country="CZ",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=347,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "GEORGIA_EROVNULI_LIGA": LeagueDefinition(
        league_id="GEORGIA_EROVNULI_LIGA",
        display_name="Erovnuli Liga",
        sport="FOOTBALL",
        country="GE",
        season_months=(2, 12),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=327,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "GEORGIA_EROVNULI_LIGA_2": LeagueDefinition(
        league_id="GEORGIA_EROVNULI_LIGA_2",
        display_name="Erovnuli Liga 2",
        sport="FOOTBALL",
        country="GE",
        season_months=(2, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=326,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "GEORGIA_CUP": LeagueDefinition(
        league_id="GEORGIA_CUP",
        display_name="Georgian Cup (David Kipiani Cup)",
        sport="FOOTBALL",
        country="GE",
        season_months=(2, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=672,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "HUNGARY_NB_I": LeagueDefinition(
        league_id="HUNGARY_NB_I",
        display_name="Nemzeti Bajnokság I",
        sport="FOOTBALL",
        country="HU",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=271,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "HUNGARY_NB_II": LeagueDefinition(
        league_id="HUNGARY_NB_II",
        display_name="Nemzeti Bajnokság II",
        sport="FOOTBALL",
        country="HU",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=272,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "HUNGARY_CUP": LeagueDefinition(
        league_id="HUNGARY_CUP",
        display_name="Magyar Kupa (Hungarian Cup)",
        sport="FOOTBALL",
        country="HU",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=273,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KOSOVO_SUPERLIGA": LeagueDefinition(
        league_id="KOSOVO_SUPERLIGA",
        display_name="Football Superleague of Kosovo",
        sport="FOOTBALL",
        country="XK",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=664,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KOSOVO_FIRST_LEAGUE": LeagueDefinition(
        league_id="KOSOVO_FIRST_LEAGUE",
        display_name="First Football League of Kosovo (Liga e Parë)",
        sport="FOOTBALL",
        country="XK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1195,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KOSOVO_CUP": LeagueDefinition(
        league_id="KOSOVO_CUP",
        display_name="Kosovar Cup",
        sport="FOOTBALL",
        country="XK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=665,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MACEDONIA_FIRST_LEAGUE": LeagueDefinition(
        league_id="MACEDONIA_FIRST_LEAGUE",
        display_name="Macedonian First Football League",
        sport="FOOTBALL",
        country="MK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=371,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MACEDONIA_SECOND_LEAGUE": LeagueDefinition(
        league_id="MACEDONIA_SECOND_LEAGUE",
        display_name="Macedonian Second Football League",
        sport="FOOTBALL",
        country="MK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=372,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MACEDONIA_CUP": LeagueDefinition(
        league_id="MACEDONIA_CUP",
        display_name="Macedonian Football Cup",
        sport="FOOTBALL",
        country="MK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=756,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOLDOVA_SUPER_LIGA": LeagueDefinition(
        league_id="MOLDOVA_SUPER_LIGA",
        display_name="Moldovan Liga (Super Liga)",
        sport="FOOTBALL",
        country="MD",
        season_months=(6, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=394,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOLDOVA_LIGA_1": LeagueDefinition(
        league_id="MOLDOVA_LIGA_1",
        display_name="Moldovan Liga 1",
        sport="FOOTBALL",
        country="MD",
        season_months=(6, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=395,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOLDOVA_CUP": LeagueDefinition(
        league_id="MOLDOVA_CUP",
        display_name="Cupa Moldovei (Moldovan Cup)",
        sport="FOOTBALL",
        country="MD",
        season_months=(6, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=674,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MONTENEGRO_FIRST_LEAGUE": LeagueDefinition(
        league_id="MONTENEGRO_FIRST_LEAGUE",
        display_name="Montenegrin First League",
        sport="FOOTBALL",
        country="ME",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=355,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MONTENEGRO_SECOND_LEAGUE": LeagueDefinition(
        league_id="MONTENEGRO_SECOND_LEAGUE",
        display_name="Montenegrin Second League",
        sport="FOOTBALL",
        country="ME",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=356,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MONTENEGRO_CUP": LeagueDefinition(
        league_id="MONTENEGRO_CUP",
        display_name="Montenegrin Cup",
        sport="FOOTBALL",
        country="ME",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=723,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ROMANIA_LIGA_I": LeagueDefinition(
        league_id="ROMANIA_LIGA_I",
        display_name="Liga I (SuperLiga)",
        sport="FOOTBALL",
        country="RO",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=283,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ROMANIA_LIGA_II": LeagueDefinition(
        league_id="ROMANIA_LIGA_II",
        display_name="Liga II",
        sport="FOOTBALL",
        country="RO",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=284,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ROMANIA_CUP": LeagueDefinition(
        league_id="ROMANIA_CUP",
        display_name="Cupa României (Romanian Cup)",
        sport="FOOTBALL",
        country="RO",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=285,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVAKIA_SUPER_LIGA": LeagueDefinition(
        league_id="SLOVAKIA_SUPER_LIGA",
        display_name="Slovak First Football League (Niké Liga)",
        sport="FOOTBALL",
        country="SK",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=332,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVAKIA_SECOND_LIGA": LeagueDefinition(
        league_id="SLOVAKIA_SECOND_LIGA",
        display_name="Slovak Second Football League",
        sport="FOOTBALL",
        country="SK",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=506,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVAKIA_CUP": LeagueDefinition(
        league_id="SLOVAKIA_CUP",
        display_name="Slovak Cup",
        sport="FOOTBALL",
        country="SK",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=680,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVENIA_PRVALIGA": LeagueDefinition(
        league_id="SLOVENIA_PRVALIGA",
        display_name="Slovenian PrvaLiga (1. SNL)",
        sport="FOOTBALL",
        country="SI",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=373,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVENIA_SECOND_LEAGUE": LeagueDefinition(
        league_id="SLOVENIA_SECOND_LEAGUE",
        display_name="Slovenian Second League (2. SNL)",
        sport="FOOTBALL",
        country="SI",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=374,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SLOVENIA_CUP": LeagueDefinition(
        league_id="SLOVENIA_CUP",
        display_name="Slovenian Football Cup",
        sport="FOOTBALL",
        country="SI",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=375,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # =======================================================================
    # Domestic curated-universe expansion, Middle East / AFC-WAFF batch
    # (2026-07-25) -- top league + division below (where the catalog has a
    # valid 2nd-tier candidate) + primary domestic cup (where the catalog has
    # one) for Bahrain, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Oman,
    # Palestine, Qatar, Saudi Arabia, Syria, UAE, Yemen. Each entry verified
    # via WebSearch against a real external source before being added.
    # Deliberate gaps, NOT guessed:
    #  - Bahrain/Jordan/Lebanon/Oman/Syria/Yemen: catalog carries only the top
    #    league (no 2nd-tier-shaped entry at all) -- division-below skipped,
    #    no id to cite.
    #  - Iraq/Palestine/Syria/Yemen: catalog carries ONLY the top league (no
    #    cup candidate either) -- both division-below and cup skipped.
    #  - Saudi Arabia: "King's Cup" (api_football_id=504, official title "The
    #    Custodian of the Two Holy Mosques' Cup") is the CURRENT primary cup;
    #    "Crown Prince Cup" was abolished in 2017 -- excluded as defunct, not
    #    a live competition, resolving this doc's own flagged ambiguity.
    #    "Division 2" (tier 3) and "Premier League Women" (women's) excluded.
    #  - Qatar/UAE/Kuwait each have 3-4 catalog cup candidates (Super Cup /
    #    League Cup / Federation-style secondary cups) -- picked the one
    #    verified as the genuine primary multi-team knockout (Emir Cup for
    #    Qatar+Kuwait, President's Cup for UAE), excluded the rest as super
    #    cups or secondary competitions.
    # See plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md
    # for the full remaining-country list and near-miss error classes.
    # =======================================================================
    "BAHRAIN_PREMIER_LEAGUE": LeagueDefinition(
        league_id="BAHRAIN_PREMIER_LEAGUE",
        display_name="Bahraini Premier League",
        sport="FOOTBALL",
        country="BH",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=417,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "BAHRAIN_KINGS_CUP": LeagueDefinition(
        league_id="BAHRAIN_KINGS_CUP",
        display_name="Bahraini King's Cup",
        sport="FOOTBALL",
        country="BH",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1049,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "IRAN_PERSIAN_GULF_PRO_LEAGUE": LeagueDefinition(
        league_id="IRAN_PERSIAN_GULF_PRO_LEAGUE",
        display_name="Persian Gulf Pro League",
        sport="FOOTBALL",
        country="IR",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=290,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "IRAN_AZADEGAN_LEAGUE": LeagueDefinition(
        league_id="IRAN_AZADEGAN_LEAGUE",
        display_name="Azadegan League",
        sport="FOOTBALL",
        country="IR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=291,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "IRAN_HAZFI_CUP": LeagueDefinition(
        league_id="IRAN_HAZFI_CUP",
        display_name="Hazfi Cup",
        sport="FOOTBALL",
        country="IR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=495,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "IRAQ_LEAGUE": LeagueDefinition(
        league_id="IRAQ_LEAGUE",
        display_name="Iraqi League",
        sport="FOOTBALL",
        country="IQ",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=542,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ISRAEL_LIGAT_HAAL": LeagueDefinition(
        league_id="ISRAEL_LIGAT_HAAL",
        display_name="Ligat ha'Al",
        sport="FOOTBALL",
        country="IL",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=383,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ISRAEL_LIGA_LEUMIT": LeagueDefinition(
        league_id="ISRAEL_LIGA_LEUMIT",
        display_name="Liga Leumit",
        sport="FOOTBALL",
        country="IL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=382,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "ISRAEL_STATE_CUP": LeagueDefinition(
        league_id="ISRAEL_STATE_CUP",
        display_name="Israel State Cup",
        sport="FOOTBALL",
        country="IL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=384,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "JORDAN_LEAGUE": LeagueDefinition(
        league_id="JORDAN_LEAGUE",
        display_name="Jordanian League",
        sport="FOOTBALL",
        country="JO",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=387,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "JORDAN_CUP": LeagueDefinition(
        league_id="JORDAN_CUP",
        display_name="Jordan FA Cup",
        sport="FOOTBALL",
        country="JO",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=863,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KUWAIT_PREMIER_LEAGUE": LeagueDefinition(
        league_id="KUWAIT_PREMIER_LEAGUE",
        display_name="Kuwaiti Premier League",
        sport="FOOTBALL",
        country="KW",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=330,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KUWAIT_DIVISION_1": LeagueDefinition(
        league_id="KUWAIT_DIVISION_1",
        display_name="Kuwaiti Division 1",
        sport="FOOTBALL",
        country="KW",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=331,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "KUWAIT_EMIR_CUP": LeagueDefinition(
        league_id="KUWAIT_EMIR_CUP",
        display_name="Kuwait Emir Cup",
        sport="FOOTBALL",
        country="KW",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=720,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "LEBANON_PREMIER_LEAGUE": LeagueDefinition(
        league_id="LEBANON_PREMIER_LEAGUE",
        display_name="Lebanese Premier League",
        sport="FOOTBALL",
        country="LB",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=390,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "LEBANON_FA_CUP": LeagueDefinition(
        league_id="LEBANON_FA_CUP",
        display_name="Lebanese FA Cup",
        sport="FOOTBALL",
        country="LB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=967,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "OMAN_PROFESSIONAL_LEAGUE": LeagueDefinition(
        league_id="OMAN_PROFESSIONAL_LEAGUE",
        display_name="Omani Professional League",
        sport="FOOTBALL",
        country="OM",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=406,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "OMAN_SULTAN_CUP": LeagueDefinition(
        league_id="OMAN_SULTAN_CUP",
        display_name="Sultan Qaboos Cup",
        sport="FOOTBALL",
        country="OM",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=726,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "PALESTINE_WEST_BANK_PREMIER_LEAGUE": LeagueDefinition(
        league_id="PALESTINE_WEST_BANK_PREMIER_LEAGUE",
        display_name="West Bank Premier League",
        sport="FOOTBALL",
        country="PS",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=586,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "QATAR_STARS_LEAGUE": LeagueDefinition(
        league_id="QATAR_STARS_LEAGUE",
        display_name="Qatar Stars League",
        sport="FOOTBALL",
        country="QA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=305,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "QATAR_SECOND_DIVISION": LeagueDefinition(
        league_id="QATAR_SECOND_DIVISION",
        display_name="Qatari Second Division",
        sport="FOOTBALL",
        country="QA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=306,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "QATAR_EMIR_CUP": LeagueDefinition(
        league_id="QATAR_EMIR_CUP",
        display_name="Emir of Qatar Cup",
        sport="FOOTBALL",
        country="QA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=824,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SAUDI_ARABIA_PRO_LEAGUE": LeagueDefinition(
        league_id="SAUDI_ARABIA_PRO_LEAGUE",
        display_name="Saudi Pro League",
        sport="FOOTBALL",
        country="SA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=307,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SAUDI_ARABIA_DIVISION_1": LeagueDefinition(
        league_id="SAUDI_ARABIA_DIVISION_1",
        display_name="Saudi First Division League",
        sport="FOOTBALL",
        country="SA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=308,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SAUDI_ARABIA_KINGS_CUP": LeagueDefinition(
        league_id="SAUDI_ARABIA_KINGS_CUP",
        display_name="King's Cup (Saudi Arabia)",
        sport="FOOTBALL",
        country="SA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=504,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SYRIA_PREMIER_LEAGUE": LeagueDefinition(
        league_id="SYRIA_PREMIER_LEAGUE",
        display_name="Syrian Premier League",
        sport="FOOTBALL",
        country="SY",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=425,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UAE_PRO_LEAGUE": LeagueDefinition(
        league_id="UAE_PRO_LEAGUE",
        display_name="UAE Pro League",
        sport="FOOTBALL",
        country="AE",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=301,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UAE_DIVISION_1": LeagueDefinition(
        league_id="UAE_DIVISION_1",
        display_name="UAE Division 1",
        sport="FOOTBALL",
        country="AE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=303,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UAE_PRESIDENTS_CUP": LeagueDefinition(
        league_id="UAE_PRESIDENTS_CUP",
        display_name="UAE President's Cup",
        sport="FOOTBALL",
        country="AE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=560,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "YEMEN_LEAGUE": LeagueDefinition(
        league_id="YEMEN_LEAGUE",
        display_name="Yemeni League",
        sport="FOOTBALL",
        country="YE",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=1079,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
}

# ---------------------------------------------------------------------------
# NON-FOOTBALL LEAGUES
# ---------------------------------------------------------------------------

NON_FOOTBALL_LEAGUES: dict[str, LeagueDefinition] = {
    "NBA": LeagueDefinition(
        league_id="NBA",
        display_name="National Basketball Association",
        sport="BASKETBALL",
        country="US",
        season_months=(10, 6),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "EUROLEAGUE": LeagueDefinition(
        league_id="EUROLEAGUE",
        display_name="EuroLeague",
        sport="BASKETBALL",
        country="INTL",
        season_months=(10, 5),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "NFL": LeagueDefinition(
        league_id="NFL",
        display_name="National Football League",
        sport="AMERICAN_FOOTBALL",
        country="US",
        season_months=(9, 2),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "MLB": LeagueDefinition(
        league_id="MLB",
        display_name="Major League Baseball",
        sport="BASEBALL",
        country="US",
        season_months=(3, 10),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "NHL": LeagueDefinition(
        league_id="NHL",
        display_name="National Hockey League",
        sport="ICE_HOCKEY",
        country="US",
        season_months=(10, 6),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "ATP": LeagueDefinition(
        league_id="ATP",
        display_name="ATP Tour",
        sport="TENNIS",
        country="INTL",
        season_months=(1, 11),
        has_playoffs=False,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "WTA": LeagueDefinition(
        league_id="WTA",
        display_name="WTA Tour",
        sport="TENNIS",
        country="INTL",
        season_months=(1, 11),
        has_playoffs=False,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
}

__all__ = [
    "FEATURES_LEAGUES",
    "NON_FOOTBALL_LEAGUES",
    "REFERENCE_LEAGUES",
]
