"""Features, Reference, and Non-football league definitions for the canonical registry.

Loaded by ``league_data.py`` to build the full LEAGUE_REGISTRY.
"""

from __future__ import annotations

from .league_registry import (
    FEAT_NO_FOOTYSTATS,
    FEAT_STANDARD,
    NO_FOOTBALL_SOURCES,
    REF_API_ONLY,
    LeagueDefinition,
)

# ---------------------------------------------------------------------------
# FEATURES LEAGUES - second divisions and lower tiers
# ---------------------------------------------------------------------------

FEATURES_LEAGUES: dict[str, LeagueDefinition] = {
    "ENG_NATIONAL_LEAGUE": LeagueDefinition(
        league_id="ENG_NATIONAL_LEAGUE",
        display_name="English National League",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=43,
        tier=5,
        classification="Features",
    ),
    "FRANCE_NATIONAL": LeagueDefinition(
        league_id="FRANCE_NATIONAL",
        display_name="National",
        sport="FOOTBALL",
        country="FR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=63,
        tier=3,
        classification="Features",
    ),
    "EERSTE_DIVISIE": LeagueDefinition(
        league_id="EERSTE_DIVISIE",
        display_name="Eerste Divisie",
        sport="FOOTBALL",
        country="NL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=89,
        tier=2,
        classification="Features",
    ),
    "LIGA_PORTUGAL_2": LeagueDefinition(
        league_id="LIGA_PORTUGAL_2",
        display_name="Liga Portugal 2",
        sport="FOOTBALL",
        country="PT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=95,
        tier=2,
        classification="Features",
    ),
    "BELGIAN_FIRST_B": LeagueDefinition(
        league_id="BELGIAN_FIRST_B",
        display_name="Belgian First Division B",
        sport="FOOTBALL",
        country="BE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=145,
        tier=2,
        classification="Features",
    ),
    "TFF_FIRST_LEAGUE": LeagueDefinition(
        league_id="TFF_FIRST_LEAGUE",
        display_name="TFF First League",
        sport="FOOTBALL",
        country="TR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=204,
        tier=2,
        classification="Features",
    ),
    "GREEK_SUPER_LEAGUE_2": LeagueDefinition(
        league_id="GREEK_SUPER_LEAGUE_2",
        display_name="Greek Super League 2",
        sport="FOOTBALL",
        country="GR",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=198,
        tier=2,
        classification="Features",
    ),
    "SCOTTISH_CHAMPIONSHIP": LeagueDefinition(
        league_id="SCOTTISH_CHAMPIONSHIP",
        display_name="Scottish Championship",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=180,
        tier=2,
        classification="Features",
    ),
    "AUSTRIAN_2_LIGA": LeagueDefinition(
        league_id="AUSTRIAN_2_LIGA",
        display_name="Austrian 2. Liga",
        sport="FOOTBALL",
        country="AT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=219,
        tier=2,
        classification="Features",
    ),
    "SWISS_CHALLENGE_LEAGUE": LeagueDefinition(
        league_id="SWISS_CHALLENGE_LEAGUE",
        display_name="Swiss Challenge League",
        sport="FOOTBALL",
        country="CH",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=208,
        tier=2,
        classification="Features",
    ),
    "DANISH_1ST_DIVISION": LeagueDefinition(
        league_id="DANISH_1ST_DIVISION",
        display_name="Danish 1st Division",
        sport="FOOTBALL",
        country="DK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=120,
        tier=2,
        classification="Features",
    ),
    "NORWAY_1_DIVISJON": LeagueDefinition(
        league_id="NORWAY_1_DIVISJON",
        display_name="Norwegian 1. divisjon",
        sport="FOOTBALL",
        country="NO",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=104,
        tier=2,
        classification="Features",
    ),
    "SUPERETTAN": LeagueDefinition(
        league_id="SUPERETTAN",
        display_name="Superettan",
        sport="FOOTBALL",
        country="SE",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=114,
        tier=2,
        classification="Features",
    ),
    "POLAND_I_LIGA": LeagueDefinition(
        league_id="POLAND_I_LIGA",
        display_name="Polish I Liga",
        sport="FOOTBALL",
        country="PL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=107,
        tier=2,
        classification="Features",
    ),
    "ARGENTINA_PRIMERA_NACIONAL": LeagueDefinition(
        league_id="ARGENTINA_PRIMERA_NACIONAL",
        display_name="Argentine Primera Nacional",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=129,
        tier=2,
        classification="Features",
    ),
    "BRASILEIRAO_SERIE_B": LeagueDefinition(
        league_id="BRASILEIRAO_SERIE_B",
        display_name="Brasileirao Serie B",
        sport="FOOTBALL",
        country="BR",
        season_months=(4, 12),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=72,
        tier=2,
        classification="Features",
    ),
    "CHILE_PRIMERA_B": LeagueDefinition(
        league_id="CHILE_PRIMERA_B",
        display_name="Chilean Primera B",
        sport="FOOTBALL",
        country="CL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=266,
        tier=2,
        classification="Features",
    ),
    "LIGA_EXPANSION_MX": LeagueDefinition(
        league_id="LIGA_EXPANSION_MX",
        display_name="Liga de Expansion MX",
        sport="FOOTBALL",
        country="MX",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=263,
        tier=2,
        classification="Features",
    ),
    "J2_LEAGUE": LeagueDefinition(
        league_id="J2_LEAGUE",
        display_name="J2 League",
        sport="FOOTBALL",
        country="JP",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=99,
        tier=2,
        classification="Features",
    ),
    "K_LEAGUE_2": LeagueDefinition(
        league_id="K_LEAGUE_2",
        display_name="K League 2",
        sport="FOOTBALL",
        country="KR",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=FEAT_NO_FOOTYSTATS,
        api_football_id=293,
        tier=2,
        classification="Features",
    ),
    "USL_CHAMPIONSHIP": LeagueDefinition(
        league_id="USL_CHAMPIONSHIP",
        display_name="USL Championship",
        sport="FOOTBALL",
        country="US",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=255,
        tier=2,
        classification="Features",
    ),
    "PRIMERA_RFEF": LeagueDefinition(
        league_id="PRIMERA_RFEF",
        display_name="Primera Division RFEF",
        sport="FOOTBALL",
        country="ES",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=FEAT_STANDARD,
        api_football_id=435,
        tier=3,
        classification="Features",
    ),
    # Added 2026-07-21 (operator ruling: in-universe) so the historical odds captured
    # under sport_key soccer_china_superleague / soccer_russia_premier_league resolve to
    # a canonical slug instead of reading as non-canonical. Resolution is by NUMERIC
    # api_football_id, so the bare display names ("Super League"/"Premier League") that
    # collide with other leagues are harmless here.
    "CHINA_SUPER_LEAGUE": LeagueDefinition(
        league_id="CHINA_SUPER_LEAGUE",
        display_name="Chinese Super League",
        sport="FOOTBALL",
        country="CN",
        season_months=(3, 11),
        has_playoffs=False,
        data_sources=FEAT_STANDARD,
        api_football_id=169,
        tier=1,
        classification="Features",
    ),
    "RUSSIA_PREMIER_LEAGUE": LeagueDefinition(
        league_id="RUSSIA_PREMIER_LEAGUE",
        display_name="Russian Premier League",
        sport="FOOTBALL",
        country="RU",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=FEAT_STANDARD,
        api_football_id=235,
        tier=1,
        classification="Features",
    ),
}

# ---------------------------------------------------------------------------
# REFERENCE LEAGUES - domestic cups + continental competitions
# ---------------------------------------------------------------------------

REFERENCE_LEAGUES: dict[str, LeagueDefinition] = {
    "FA_CUP": LeagueDefinition(
        league_id="FA_CUP",
        display_name="FA Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=45,
        tier=0,
        classification="Reference",
    ),
    "CARABAO_CUP": LeagueDefinition(
        league_id="CARABAO_CUP",
        display_name="Carabao Cup (EFL Cup)",
        sport="FOOTBALL",
        country="GB",
        season_months=(8, 3),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=48,
        tier=0,
        classification="Reference",
    ),
    "COPA_DEL_REY": LeagueDefinition(
        league_id="COPA_DEL_REY",
        display_name="Copa del Rey",
        sport="FOOTBALL",
        country="ES",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=143,
        tier=0,
        classification="Reference",
    ),
    "SUPERCOPA_ESPANA": LeagueDefinition(
        league_id="SUPERCOPA_ESPANA",
        display_name="Supercopa de Espana",
        sport="FOOTBALL",
        country="ES",
        season_months=(1, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=556,
        tier=0,
        classification="Reference",
    ),
    "DFB_POKAL": LeagueDefinition(
        league_id="DFB_POKAL",
        display_name="DFB Pokal",
        sport="FOOTBALL",
        country="DE",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=81,
        tier=0,
        classification="Reference",
    ),
    "DFL_SUPERCUP": LeagueDefinition(
        league_id="DFL_SUPERCUP",
        display_name="DFL Supercup",
        sport="FOOTBALL",
        country="DE",
        season_months=(8, 8),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=529,
        tier=0,
        classification="Reference",
    ),
    "COPPA_ITALIA": LeagueDefinition(
        league_id="COPPA_ITALIA",
        display_name="Coppa Italia",
        sport="FOOTBALL",
        country="IT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=137,
        tier=0,
        classification="Reference",
    ),
    "SUPERCOPPA_ITALIANA": LeagueDefinition(
        league_id="SUPERCOPPA_ITALIANA",
        display_name="Supercoppa Italiana",
        sport="FOOTBALL",
        country="IT",
        season_months=(1, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=547,
        tier=0,
        classification="Reference",
    ),
    "COUPE_DE_FRANCE": LeagueDefinition(
        league_id="COUPE_DE_FRANCE",
        display_name="Coupe de France",
        sport="FOOTBALL",
        country="FR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=66,
        tier=0,
        classification="Reference",
    ),
    "TROPHEE_CHAMPIONS": LeagueDefinition(
        league_id="TROPHEE_CHAMPIONS",
        display_name="Trophee des Champions",
        sport="FOOTBALL",
        country="FR",
        season_months=(8, 8),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=526,
        tier=0,
        classification="Reference",
    ),
    "KNVB_CUP": LeagueDefinition(
        league_id="KNVB_CUP",
        display_name="KNVB Cup",
        sport="FOOTBALL",
        country="NL",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=90,
        tier=0,
        classification="Reference",
    ),
    "TACA_DE_PORTUGAL": LeagueDefinition(
        league_id="TACA_DE_PORTUGAL",
        display_name="Taca de Portugal",
        sport="FOOTBALL",
        country="PT",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=96,
        tier=0,
        classification="Reference",
    ),
    "TACA_DA_LIGA": LeagueDefinition(
        league_id="TACA_DA_LIGA",
        display_name="Taca da Liga",
        sport="FOOTBALL",
        country="PT",
        season_months=(8, 1),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=97,
        tier=0,
        classification="Reference",
    ),
    "GREEK_CUP": LeagueDefinition(
        league_id="GREEK_CUP",
        display_name="Greek Cup",
        sport="FOOTBALL",
        country="GR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=199,
        tier=0,
        classification="Reference",
    ),
    "SCOTTISH_CUP": LeagueDefinition(
        league_id="SCOTTISH_CUP",
        display_name="Scottish Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=181,
        tier=0,
        classification="Reference",
    ),
    "SCOTTISH_LEAGUE_CUP": LeagueDefinition(
        league_id="SCOTTISH_LEAGUE_CUP",
        display_name="Scottish League Cup",
        sport="FOOTBALL",
        country="GB",
        season_months=(7, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=182,
        tier=0,
        classification="Reference",
    ),
    # SCOTTISH_LEAGUE_CUP_185 retired 2026-05-06 — duplicate registry entry
    # for Scottish League Cup. The ``_185`` suffix is api_football's season
    # ID leaking into the canonical name. ``SCOTTISH_LEAGUE_CUP`` (af_id=182)
    # is the canonical entry; 185 was a leftover from an api_football catalogue
    # rotation. Both shared classification=Reference so dropping has no
    # downstream impact (no Prediction-tier consumers).
    "AUSTRIAN_CUP": LeagueDefinition(
        league_id="AUSTRIAN_CUP",
        display_name="Austrian Cup",
        sport="FOOTBALL",
        country="AT",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=220,
        tier=0,
        classification="Reference",
    ),
    "SWISS_CUP": LeagueDefinition(
        league_id="SWISS_CUP",
        display_name="Swiss Cup",
        sport="FOOTBALL",
        country="CH",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=209,
        tier=0,
        classification="Reference",
    ),
    "DANISH_CUP": LeagueDefinition(
        league_id="DANISH_CUP",
        display_name="Danish Cup",
        sport="FOOTBALL",
        country="DK",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=121,
        tier=0,
        classification="Reference",
    ),
    "NORWEGIAN_CUP": LeagueDefinition(
        league_id="NORWEGIAN_CUP",
        display_name="Norwegian Cup",
        sport="FOOTBALL",
        country="NO",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=105,
        tier=0,
        classification="Reference",
    ),
    "SVENSKA_CUPEN": LeagueDefinition(
        league_id="SVENSKA_CUPEN",
        display_name="Svenska Cupen",
        sport="FOOTBALL",
        country="SE",
        season_months=(1, 3),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=115,
        tier=0,
        classification="Reference",
    ),
    "POLISH_CUP": LeagueDefinition(
        league_id="POLISH_CUP",
        display_name="Polish Cup",
        sport="FOOTBALL",
        country="PL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=108,
        tier=0,
        classification="Reference",
    ),
    "COPA_ARGENTINA": LeagueDefinition(
        league_id="COPA_ARGENTINA",
        display_name="Copa Argentina",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=130,
        tier=0,
        classification="Reference",
    ),
    "COPA_LIGA_PROFESIONAL": LeagueDefinition(
        league_id="COPA_LIGA_PROFESIONAL",
        display_name="Copa de la Liga Profesional",
        sport="FOOTBALL",
        country="AR",
        season_months=(2, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1032,
        tier=0,
        classification="Reference",
    ),
    "COPA_DO_BRASIL": LeagueDefinition(
        league_id="COPA_DO_BRASIL",
        display_name="Copa do Brasil",
        sport="FOOTBALL",
        country="BR",
        season_months=(2, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=73,
        tier=0,
        classification="Reference",
    ),
    "COPA_CHILE": LeagueDefinition(
        league_id="COPA_CHILE",
        display_name="Copa Chile",
        sport="FOOTBALL",
        country="CL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=267,
        tier=0,
        classification="Reference",
    ),
    "COPA_MX": LeagueDefinition(
        league_id="COPA_MX",
        display_name="Copa MX",
        sport="FOOTBALL",
        country="MX",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=264,
        tier=0,
        classification="Reference",
    ),
    "BELGIAN_CUP": LeagueDefinition(
        league_id="BELGIAN_CUP",
        display_name="Belgian Cup",
        sport="FOOTBALL",
        country="BE",
        season_months=(9, 4),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=147,
        tier=0,
        classification="Reference",
    ),
    "TURKIYE_KUPASI": LeagueDefinition(
        league_id="TURKIYE_KUPASI",
        display_name="Turkiye Kupasi",
        sport="FOOTBALL",
        country="TR",
        season_months=(9, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=206,
        tier=0,
        classification="Reference",
    ),
    "US_OPEN_CUP": LeagueDefinition(
        league_id="US_OPEN_CUP",
        display_name="US Open Cup",
        sport="FOOTBALL",
        country="US",
        season_months=(4, 9),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=257,
        tier=0,
        classification="Reference",
    ),
    "JLEAGUE_CUP": LeagueDefinition(
        league_id="JLEAGUE_CUP",
        display_name="J.League Cup",
        sport="FOOTBALL",
        country="JP",
        season_months=(2, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=101,
        tier=0,
        classification="Reference",
    ),
    "EMPEROR_CUP": LeagueDefinition(
        league_id="EMPEROR_CUP",
        display_name="Emperor Cup",
        sport="FOOTBALL",
        country="JP",
        season_months=(5, 12),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=102,
        tier=0,
        classification="Reference",
    ),
    "KOREAN_FA_CUP": LeagueDefinition(
        league_id="KOREAN_FA_CUP",
        display_name="Korean FA Cup",
        sport="FOOTBALL",
        country="KR",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=294,
        tier=0,
        classification="Reference",
    ),
    "AUSTRALIA_CUP": LeagueDefinition(
        league_id="AUSTRALIA_CUP",
        display_name="Australia Cup",
        sport="FOOTBALL",
        country="AU",
        season_months=(5, 10),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=874,
        tier=0,
        classification="Reference",
    ),
    # Continental
    "UCL": LeagueDefinition(
        league_id="UCL",
        display_name="UEFA Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=2,
        tier=0,
        classification="Reference",
    ),
    "UEL": LeagueDefinition(
        league_id="UEL",
        display_name="UEFA Europa League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=3,
        tier=0,
        classification="Reference",
    ),
    "UECL": LeagueDefinition(
        league_id="UECL",
        display_name="UEFA Conference League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(9, 6),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=848,
        tier=0,
        classification="Reference",
    ),
    "COPA_LIBERTADORES": LeagueDefinition(
        league_id="COPA_LIBERTADORES",
        display_name="CONMEBOL Libertadores",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=13,
        tier=0,
        classification="Reference",
    ),
    "COPA_SUDAMERICANA": LeagueDefinition(
        league_id="COPA_SUDAMERICANA",
        display_name="CONMEBOL Sudamericana",
        sport="FOOTBALL",
        country="INTL",
        season_months=(3, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=11,
        tier=0,
        classification="Reference",
    ),
    # =======================================================================
    # CONTINENTAL / INTERNATIONAL MAJORS — Directive A/B curated-universe
    # (plans/active/sports_satellite_ao_dispatch_batch2_2026_07_24.md).
    # in_mvp_scope=False (operator-approved 2026-07-25): a wider REFERENCE
    # universe, not a prediction-scope widening. season_months is a
    # HEMISPHERE-BASED PLACEHOLDER (operator-approved 2026-07-25 default:
    # UEFA/CONCACAF/AFC-anchored -> Northern (8,5); CONMEBOL/CAF/OFC-anchored
    # -> Southern (2,11)) — NOT researched per-competition real windows.
    # TODO(sports): replace with the real per-competition calendar (several
    # of these are quadrennial, not annual, e.g. World Cup/Euros/Copa
    # America run June-July only once every 4 years) before relying on
    # season_months for anything beyond a coarse write-gate filter.
    # =======================================================================
    "WORLD_CUP": LeagueDefinition(
        league_id="WORLD_CUP",
        display_name="World Cup",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=1,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EURO_CHAMPIONSHIP": LeagueDefinition(
        league_id="EURO_CHAMPIONSHIP",
        display_name="Euro Championship",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=4,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "FIFA_CLUB_WORLD_CUP": LeagueDefinition(
        league_id="FIFA_CLUB_WORLD_CUP",
        display_name="FIFA Club World Cup",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=15,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "COPA_AMERICA": LeagueDefinition(
        league_id="COPA_AMERICA",
        display_name="Copa America",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=9,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "OFC_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="OFC_CHAMPIONS_LEAGUE",
        display_name="OFC Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=27,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CONCACAF_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="CONCACAF_CHAMPIONS_LEAGUE",
        display_name="CONCACAF Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=16,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AFC_CHAMPIONS_LEAGUE_ELITE": LeagueDefinition(
        league_id="AFC_CHAMPIONS_LEAGUE_ELITE",
        display_name="AFC Champions League Elite",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=17,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "AFC_CHAMPIONS_LEAGUE_TWO": LeagueDefinition(
        league_id="AFC_CHAMPIONS_LEAGUE_TWO",
        display_name="AFC Champions League Two",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=18,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UEFA_NATIONS_LEAGUE": LeagueDefinition(
        league_id="UEFA_NATIONS_LEAGUE",
        display_name="UEFA Nations League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=5,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CAF_CHAMPIONS_LEAGUE": LeagueDefinition(
        league_id="CAF_CHAMPIONS_LEAGUE",
        display_name="CAF Champions League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(2, 11),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=12,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CONCACAF_NATIONS_LEAGUE": LeagueDefinition(
        league_id="CONCACAF_NATIONS_LEAGUE",
        display_name="CONCACAF Nations League",
        sport="FOOTBALL",
        country="INTL",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=536,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    # =======================================================================
    # Domestic curated-universe expansion (Directive A/B, first verified batch,
    # 2026-07-25) -- top league + division below + primary domestic cup for
    # countries not yet in LEAGUE_REGISTRY. Each entry's tier structure was
    # verified against a real external source (not derived from the raw
    # api-football name field alone) before being added -- see
    # plans/active/issues/sports_curated_universe_domestic_selection_remaining_2026_07_25.md
    # for the full remaining-country list and the fabrication-risk rationale
    # for why this is a small verified batch, not the whole 143/145.
    # =======================================================================
    "UKRAINE_PREMIER_LEAGUE": LeagueDefinition(
        league_id="UKRAINE_PREMIER_LEAGUE",
        display_name="Ukrainian Premier League",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=333,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UKRAINE_PERSHA_LIGA": LeagueDefinition(
        league_id="UKRAINE_PERSHA_LIGA",
        display_name="Ukrainian First League (Persha Liha)",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=334,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "UKRAINE_CUP": LeagueDefinition(
        league_id="UKRAINE_CUP",
        display_name="Ukrainian Cup",
        sport="FOOTBALL",
        country="UA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=335,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_HNL": LeagueDefinition(
        league_id="CROATIA_HNL",
        display_name="Croatian Football League (HNL)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=210,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_FIRST_NL": LeagueDefinition(
        league_id="CROATIA_FIRST_NL",
        display_name="Croatian First NL (Prva NL)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=211,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "CROATIA_CUP": LeagueDefinition(
        league_id="CROATIA_CUP",
        display_name="Croatian Cup (Hrvatski nogometni kup)",
        sport="FOOTBALL",
        country="HR",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=212,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_BOTOLA_PRO": LeagueDefinition(
        league_id="MOROCCO_BOTOLA_PRO",
        display_name="Botola Pro",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=200,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_BOTOLA_2": LeagueDefinition(
        league_id="MOROCCO_BOTOLA_2",
        display_name="Botola 2",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=201,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "MOROCCO_CUP": LeagueDefinition(
        league_id="MOROCCO_CUP",
        display_name="Throne Cup (Coupe du Trone)",
        sport="FOOTBALL",
        country="MA",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=822,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_SUPER_LIGA": LeagueDefinition(
        league_id="SERBIA_SUPER_LIGA",
        display_name="Serbian SuperLiga",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=286,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_PRVA_LIGA": LeagueDefinition(
        league_id="SERBIA_PRVA_LIGA",
        display_name="Serbian First League",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=287,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "SERBIA_CUP": LeagueDefinition(
        league_id="SERBIA_CUP",
        display_name="Serbian Cup",
        sport="FOOTBALL",
        country="RS",
        season_months=(7, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=732,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_PREMIER_LEAGUE": LeagueDefinition(
        league_id="EGYPT_PREMIER_LEAGUE",
        display_name="Egyptian Premier League",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=False,
        data_sources=REF_API_ONLY,
        api_football_id=233,
        tier=1,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_SECOND_DIVISION": LeagueDefinition(
        league_id="EGYPT_SECOND_DIVISION",
        display_name="Egyptian Second Division A",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=887,
        tier=2,
        classification="Reference",
        in_mvp_scope=False,
    ),
    "EGYPT_CUP": LeagueDefinition(
        league_id="EGYPT_CUP",
        display_name="Egypt Cup",
        sport="FOOTBALL",
        country="EG",
        season_months=(8, 5),
        has_playoffs=True,
        data_sources=REF_API_ONLY,
        api_football_id=714,
        tier=0,
        classification="Reference",
        in_mvp_scope=False,
    ),
}

# ---------------------------------------------------------------------------
# NON-FOOTBALL LEAGUES
# ---------------------------------------------------------------------------

NON_FOOTBALL_LEAGUES: dict[str, LeagueDefinition] = {
    "NBA": LeagueDefinition(
        league_id="NBA",
        display_name="National Basketball Association",
        sport="BASKETBALL",
        country="US",
        season_months=(10, 6),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "EUROLEAGUE": LeagueDefinition(
        league_id="EUROLEAGUE",
        display_name="EuroLeague",
        sport="BASKETBALL",
        country="INTL",
        season_months=(10, 5),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "NFL": LeagueDefinition(
        league_id="NFL",
        display_name="National Football League",
        sport="AMERICAN_FOOTBALL",
        country="US",
        season_months=(9, 2),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "MLB": LeagueDefinition(
        league_id="MLB",
        display_name="Major League Baseball",
        sport="BASEBALL",
        country="US",
        season_months=(3, 10),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "NHL": LeagueDefinition(
        league_id="NHL",
        display_name="National Hockey League",
        sport="ICE_HOCKEY",
        country="US",
        season_months=(10, 6),
        has_playoffs=True,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "ATP": LeagueDefinition(
        league_id="ATP",
        display_name="ATP Tour",
        sport="TENNIS",
        country="INTL",
        season_months=(1, 11),
        has_playoffs=False,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
    "WTA": LeagueDefinition(
        league_id="WTA",
        display_name="WTA Tour",
        sport="TENNIS",
        country="INTL",
        season_months=(1, 11),
        has_playoffs=False,
        data_sources=NO_FOOTBALL_SOURCES,
        api_football_id=None,
        tier=1,
        classification="Other",
    ),
}

__all__ = [
    "FEATURES_LEAGUES",
    "NON_FOOTBALL_LEAGUES",
    "REFERENCE_LEAGUES",
]
