"""Tier 1 (API) venue execution registry — sports betting execution profiles."""

from __future__ import annotations

from decimal import Decimal

from .venue_execution import (
    AntiDetectionLevel,
    CredentialType,
    ExecutionMethod,
    VenueCategory,
    VenueExecutionProfile,
)

VENUE_EXECUTION_REGISTRY: dict[str, VenueExecutionProfile] = {
    "betfair_ex_uk": VenueExecutionProfile(
        venue_key="betfair_ex_uk",
        odds_api_key="betfair_ex_uk",
        display_name="Betfair Exchange UK",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betfair_ex_eu": VenueExecutionProfile(
        venue_key="betfair_ex_eu",
        odds_api_key="betfair_ex_eu",
        display_name="Betfair Exchange EU",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["ES", "IT", "PT", "RO"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betfair_ex_au": VenueExecutionProfile(
        venue_key="betfair_ex_au",
        odds_api_key="betfair_ex_au",
        display_name="Betfair Exchange AU",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betfair.com",
        api_docs_url="https://docs.developer.betfair.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betfair_secret_name",
        min_bet="2.00",
        commission_model="net_winnings_pct",
        available_countries=["AU"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="5.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "pinnacle": VenueExecutionProfile(
        venue_key="pinnacle",
        odds_api_key="pinnacle",
        display_name="Pinnacle",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.pinnacle.com",
        api_docs_url="https://pinnacleapi.github.io/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.BOOKMAKER_API,
        config_secret_field="pinnacle_secret_name",
        min_bet="1.00",
        commission_model="built_into_odds",
        available_countries=["US", "UK", "AU", "CA"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=48,
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "smarkets": VenueExecutionProfile(
        venue_key="smarkets",
        odds_api_key="smarkets",
        display_name="Smarkets",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.smarkets.com/v3",
        api_docs_url="https://docs.smarkets.com/",
        credential_type=CredentialType.API_KEY,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="smarkets_secret_name",
        min_bet="1.00",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="2.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "matchbook": VenueExecutionProfile(
        venue_key="matchbook",
        odds_api_key="matchbook",
        display_name="Matchbook",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.matchbook.com/edge/rest",
        api_docs_url="https://www.matchbook.com/edge/rest",
        credential_type=CredentialType.USERNAME_PASSWORD,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="matchbook_secret_name",
        min_bet="5",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="1.5",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betdaq": VenueExecutionProfile(
        venue_key="betdaq",
        odds_api_key=None,
        display_name="Betdaq",
        primary_execution_method=ExecutionMethod.REST_API,
        api_base_url="https://api.betdaq.com",
        api_docs_url="https://www.betdaq.com/",
        credential_type=CredentialType.USERNAME_PASSWORD,
        venue_category=VenueCategory.EXCHANGE,
        config_secret_field="betdaq_secret_name",
        min_bet="0.50",
        commission_model="net_winnings_pct",
        available_countries=["GB", "IE"],
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        commission_rate="2.0",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "onexbet": VenueExecutionProfile(
        venue_key="onexbet",
        odds_api_key="onexbet",
        display_name="1xBet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://1xbet.com",
        config_secret_field="onexbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.20",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_uk": VenueExecutionProfile(
        venue_key="unibet_uk",
        odds_api_key="unibet_uk",
        display_name="Unibet UK",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "unibet_fr": VenueExecutionProfile(
        venue_key="unibet_fr",
        odds_api_key="unibet_fr",
        display_name="Unibet FR",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_it": VenueExecutionProfile(
        venue_key="unibet_it",
        odds_api_key="unibet_it",
        display_name="Unibet IT",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_it_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_nl": VenueExecutionProfile(
        venue_key="unibet_nl",
        odds_api_key="unibet_nl",
        display_name="Unibet NL",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_nl_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "unibet_se": VenueExecutionProfile(
        venue_key="unibet_se",
        odds_api_key="unibet_se",
        display_name="Unibet SE",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.unibet.com",
        config_secret_field="unibet_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "betsson": VenueExecutionProfile(
        venue_key="betsson",
        odds_api_key="betsson",
        display_name="Betsson",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betsson.com",
        config_secret_field="betsson_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "marathonbet": VenueExecutionProfile(
        venue_key="marathonbet",
        odds_api_key="marathonbet",
        display_name="Marathonbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.marathonbet.com",
        config_secret_field="marathonbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "coolbet": VenueExecutionProfile(
        venue_key="coolbet",
        odds_api_key="coolbet",
        display_name="Coolbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.coolbet.com",
        config_secret_field="coolbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "nordicbet": VenueExecutionProfile(
        venue_key="nordicbet",
        odds_api_key="nordicbet",
        display_name="NordicBet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.nordicbet.com",
        config_secret_field="nordicbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="EUR",
        withdrawal_fee="0",
    ),
    "bovada": VenueExecutionProfile(
        venue_key="bovada",
        odds_api_key="bovada",
        display_name="Bovada",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.bovada.lv",
        config_secret_field="bovada_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betonlineag": VenueExecutionProfile(
        venue_key="betonlineag",
        odds_api_key="betonlineag",
        display_name="BetOnline",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betonline.ag",
        config_secret_field="betonlineag_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "mybookieag": VenueExecutionProfile(
        venue_key="mybookieag",
        odds_api_key="mybookieag",
        display_name="MyBookie",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.mybookie.ag",
        config_secret_field="mybookieag_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="5",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betus": VenueExecutionProfile(
        venue_key="betus",
        odds_api_key="betus",
        display_name="BetUS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betus.com.pa",
        config_secret_field="betus_credentials",
        username_secret_key="username",
        password_secret_key="password",
        supports_crypto_withdrawal=True,
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "sportsbet": VenueExecutionProfile(
        venue_key="sportsbet",
        odds_api_key="sportsbet",
        display_name="Sportsbet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.sportsbet.com.au",
        config_secret_field="sportsbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "tab": VenueExecutionProfile(
        venue_key="tab",
        odds_api_key="tab",
        display_name="TAB",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tab.com.au",
        config_secret_field="tab_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "neds": VenueExecutionProfile(
        venue_key="neds",
        odds_api_key="neds",
        display_name="Neds",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.neds.com.au",
        config_secret_field="neds_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "pointsbetau": VenueExecutionProfile(
        venue_key="pointsbetau",
        odds_api_key="pointsbetau",
        display_name="PointsBet AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.pointsbet.com.au",
        config_secret_field="pointsbetau_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "ladbrokes_au": VenueExecutionProfile(
        venue_key="ladbrokes_au",
        odds_api_key="ladbrokes_au",
        display_name="Ladbrokes AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ladbrokes.com.au",
        config_secret_field="ladbrokes_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "betr_au": VenueExecutionProfile(
        venue_key="betr_au",
        odds_api_key="betr_au",
        display_name="Betr AU",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betr.com.au",
        config_secret_field="betr_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "betright": VenueExecutionProfile(
        venue_key="betright",
        odds_api_key="betright",
        display_name="BetRight",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betright.com.au",
        config_secret_field="betright_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "playup": VenueExecutionProfile(
        venue_key="playup",
        odds_api_key="playup",
        display_name="PlayUp",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.playup.com.au",
        config_secret_field="playup_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "tabtouch": VenueExecutionProfile(
        venue_key="tabtouch",
        odds_api_key="tabtouch",
        display_name="TAB Touch",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tabtouch.com.au",
        config_secret_field="tabtouch_credentials",
        username_secret_key="username",
        password_secret_key="password",
        available_countries=["AU"],
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="AUD",
        withdrawal_fee="0",
    ),
    "williamhill": VenueExecutionProfile(
        venue_key="williamhill",
        odds_api_key="williamhill",
        display_name="William Hill",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.williamhill.com/",
        config_secret_field="williamhill_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "ladbrokes_uk": VenueExecutionProfile(
        venue_key="ladbrokes_uk",
        odds_api_key="ladbrokes_uk",
        display_name="Ladbrokes UK",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ladbrokes.com/",
        config_secret_field="ladbrokes_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "coral": VenueExecutionProfile(
        venue_key="coral",
        odds_api_key="coral",
        display_name="Coral",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.coral.co.uk/",
        config_secret_field="coral_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "paddypower": VenueExecutionProfile(
        venue_key="paddypower",
        odds_api_key="paddypower",
        display_name="Paddy Power",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.paddypower.com/",
        config_secret_field="paddypower_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "skybet": VenueExecutionProfile(
        venue_key="skybet",
        odds_api_key="skybet",
        display_name="Sky Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.skybet.com/",
        config_secret_field="skybet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betway": VenueExecutionProfile(
        venue_key="betway",
        odds_api_key="betway",
        display_name="Betway",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betway.com/",
        config_secret_field="betway_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "sport888": VenueExecutionProfile(
        venue_key="sport888",
        odds_api_key="sport888",
        display_name="888sport",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.888sport.com/",
        config_secret_field="sport888_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "betvictor": VenueExecutionProfile(
        venue_key="betvictor",
        odds_api_key="betvictor",
        display_name="BetVictor",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betvictor.com/",
        config_secret_field="betvictor_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "boylesports": VenueExecutionProfile(
        venue_key="boylesports",
        odds_api_key="boylesports",
        display_name="BoyleSports",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.boylesports.com/",
        config_secret_field="boylesports_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "virginbet": VenueExecutionProfile(
        venue_key="virginbet",
        odds_api_key="virginbet",
        display_name="Virgin Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.virginbet.com/",
        config_secret_field="virginbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "livescorebet": VenueExecutionProfile(
        venue_key="livescorebet",
        odds_api_key="livescorebet",
        display_name="LiveScore Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.livescorebet.com/",
        config_secret_field="livescorebet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        available_countries=["GB"],
        commission_model="built_into_odds",
        min_bet="0.10",
        min_bet_currency="GBP",
        withdrawal_fee="0",
    ),
    "draftkings": VenueExecutionProfile(
        venue_key="draftkings",
        odds_api_key="draftkings",
        display_name="DraftKings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.draftkings.com/",
        config_secret_field="draftkings_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="0.50",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "fanduel": VenueExecutionProfile(
        venue_key="fanduel",
        odds_api_key="fanduel",
        display_name="FanDuel",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.fanduel.com/",
        config_secret_field="fanduel_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betmgm": VenueExecutionProfile(
        venue_key="betmgm",
        odds_api_key="betmgm",
        display_name="BetMGM",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sports.betmgm.com/",
        config_secret_field="betmgm_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "williamhill_us": VenueExecutionProfile(
        venue_key="williamhill_us",
        odds_api_key="williamhill_us",
        display_name="William Hill US",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.williamhill.com/us/",
        config_secret_field="williamhill_us_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "betrivers": VenueExecutionProfile(
        venue_key="betrivers",
        odds_api_key="betrivers",
        display_name="BetRivers",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betrivers.com/",
        config_secret_field="betrivers_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="0.50",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "espnbet": VenueExecutionProfile(
        venue_key="espnbet",
        odds_api_key="espnbet",
        display_name="ESPN Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.espnbet.com/",
        config_secret_field="espnbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "hardrockbet": VenueExecutionProfile(
        venue_key="hardrockbet",
        odds_api_key="hardrockbet",
        display_name="Hard Rock Bet",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.hardrockbet.com/",
        config_secret_field="hardrockbet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    "fanatics": VenueExecutionProfile(
        venue_key="fanatics",
        odds_api_key="fanatics",
        display_name="Fanatics",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://sportsbook.fanatics.com/",
        config_secret_field="fanatics_credentials",
        username_secret_key="username",
        password_secret_key="password",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        commission_model="built_into_odds",
        min_bet="1",
        min_bet_currency="USD",
        withdrawal_fee="0",
    ),
    # ── US Exchanges (REST API) ────────────────────────────────────────────
    "polymarket": VenueExecutionProfile(
        venue_key="polymarket",
        odds_api_key="polymarket",
        display_name="Polymarket",
        parent_company="Polymarket Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.REST_API,
        credential_type=CredentialType.API_KEY_SECRET,
        api_base_url="https://clob.polymarket.com",
        api_docs_url="https://docs.polymarket.com",
        has_rest_api=True,
        api_rate_limit_requests_per_second=10,
        config_secret_field="polymarket_credentials",
        api_key_secret_key="api_key",
        headquarters_country="US",
        available_countries=["US", "GB", "EU"],
        blocked_us_states=["NY"],
        supported_currencies=["USDC"],
        min_deposit=Decimal("1"),
        min_bet=Decimal("1"),
        min_bet_currency="USDC",
        supports_crypto_deposit=True,
        supports_crypto_withdrawal=True,
        crypto_currencies_accepted=["USDC"],
        withdrawal_delay_hours_min=0,
        withdrawal_delay_hours_max=1,
        commission_model="maker_taker",
        commission_rate=Decimal("0"),
        commission_notes="0% maker, 0% taker on prediction markets",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="Prediction market exchange on Polygon. CLOB API with HMAC auth.",
    ),
    "kalshi": VenueExecutionProfile(
        venue_key="kalshi",
        odds_api_key="kalshi",
        display_name="Kalshi",
        parent_company="Kalshi Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.REST_API,
        credential_type=CredentialType.API_KEY_SECRET,
        api_base_url="https://trading-api.kalshi.com/trade-api/v2",
        api_docs_url="https://trading-api.kalshi.com/docs",
        has_rest_api=True,
        has_websocket_api=True,
        api_rate_limit_requests_per_second=10,
        config_secret_field="kalshi_credentials",
        api_key_secret_key="api_key",
        headquarters_country="US",
        license_jurisdictions=["US-CFTC"],
        available_countries=["US"],
        blocked_us_states=[],
        requires_residency=True,
        residency_countries=["US"],
        supported_currencies=["USD"],
        min_deposit=Decimal("1"),
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        withdrawal_delay_hours_min=1,
        withdrawal_delay_hours_max=48,
        commission_model="maker_taker",
        commission_rate=Decimal("0"),
        commission_notes="No trading fees; exchange spread is the cost",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="CFTC-regulated event contracts exchange. REST + WebSocket API.",
    ),
    "novig": VenueExecutionProfile(
        venue_key="novig",
        odds_api_key="novig",
        display_name="Novig",
        parent_company="Novig Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.novig.com/",
        config_secret_field="novig_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["NJ", "CO", "IN", "IA", "KS", "KY", "LA", "MD", "OH", "PA", "VA"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="low_vig_exchange",
        commission_rate=Decimal("1.0"),
        commission_notes="Peer-to-peer exchange with ~1% vig; no traditional commission",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="US peer-to-peer sports exchange. Low vig model.",
    ),
    "betopenly": VenueExecutionProfile(
        venue_key="betopenly",
        odds_api_key="betopenly",
        display_name="BetOpenly",
        parent_company="BetOpenly Inc",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betopenly.com/",
        config_secret_field="betopenly_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="exchange_commission",
        commission_rate=Decimal("2.0"),
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="US sports exchange.",
    ),
    "prophetx": VenueExecutionProfile(
        venue_key="prophetx",
        odds_api_key="prophetx",
        display_name="ProphetX",
        parent_company="Prophet Exchange",
        venue_category=VenueCategory.EXCHANGE,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.prophetexchange.com/",
        config_secret_field="prophetx_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["NJ"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="exchange_commission",
        commission_rate=Decimal("2.0"),
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=False,
        notes="NJ-only peer-to-peer sports exchange.",
    ),
    # ── US DFS / Social Betting ────────────────────────────────────────────
    "betr_us_dfs": VenueExecutionProfile(
        venue_key="betr_us_dfs",
        odds_api_key="betr_us_dfs",
        display_name="Betr (US DFS)",
        parent_company="Betr Holdings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betr.app/",
        config_secret_field="betr_us_dfs_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS/micro-betting platform. Props and picks format.",
    ),
    "pick6": VenueExecutionProfile(
        venue_key="pick6",
        odds_api_key="pick6",
        display_name="Pick6 by DraftKings",
        parent_company="DraftKings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://pick6.draftkings.com/",
        config_secret_field="pick6_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="DraftKings DFS pick'em product.",
    ),
    "prizepicks": VenueExecutionProfile(
        venue_key="prizepicks",
        odds_api_key="prizepicks",
        display_name="PrizePicks",
        parent_company="PrizePicks LLC",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://app.prizepicks.com/",
        config_secret_field="prizepicks_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("5"),
        min_bet_currency="USD",
        max_payout=Decimal("100000"),
        max_payout_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS props platform. Over/under player props. $5 min entry.",
    ),
    "underdog": VenueExecutionProfile(
        venue_key="underdog",
        odds_api_key="underdog",
        display_name="Underdog Fantasy",
        parent_company="Underdog Sports",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://underdogfantasy.com/",
        config_secret_field="underdog_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        max_payout=Decimal("50000"),
        max_payout_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US DFS pick'em platform. Higher/lower player props.",
    ),
    "fliff": VenueExecutionProfile(
        venue_key="fliff",
        odds_api_key="fliff",
        display_name="Fliff",
        parent_company="Fliff Inc",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.getfliff.com/",
        config_secret_field="fliff_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        requires_geolocation_check=True,
        supported_currencies=["USD"],
        min_bet=Decimal("0.50"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="US social sportsbook using sweepstakes model.",
    ),
    # ── US Additional ──────────────────────────────────────────────────────
    "ballybet": VenueExecutionProfile(
        venue_key="ballybet",
        odds_api_key="ballybet",
        display_name="Bally Bet",
        parent_company="Bally's Corporation",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.ballybet.com/",
        config_secret_field="ballybet_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["AZ", "CO", "IA", "IN", "NY", "OH", "VA"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("0.50"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Bally's Corp US sportsbook. Multi-state licensed.",
    ),
    "betparx": VenueExecutionProfile(
        venue_key="betparx",
        odds_api_key="betparx",
        display_name="BetParx",
        parent_company="Parx Casino",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betparx.com/",
        config_secret_field="betparx_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="US",
        available_us_states=["PA", "NJ", "OH", "MD"],
        requires_geolocation_check=True,
        geolocation_provider="geocomply",
        supported_currencies=["USD"],
        min_bet=Decimal("1"),
        min_bet_currency="USD",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Parx Casino US sportsbook. PA-based.",
    ),
    # ── UK Additional ──────────────────────────────────────────────────────
    "betfair_sb_uk": VenueExecutionProfile(
        venue_key="betfair_sb_uk",
        odds_api_key="betfair_sb_uk",
        display_name="Betfair Sportsbook (UK)",
        parent_company="Flutter Entertainment",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.betfair.com/sport/",
        config_secret_field="betfair_sb_uk_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["GB-UKGC", "MT-MGA"],
        available_countries=["GB", "IE"],
        supported_currencies=["GBP", "EUR"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        account_limiting_severity="moderate",
        notes="Betfair's fixed-odds sportsbook (NOT the exchange). Limits sharps.",
    ),
    "grosvenor": VenueExecutionProfile(
        venue_key="grosvenor",
        odds_api_key="grosvenor",
        display_name="Grosvenor Sport",
        parent_company="Rank Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.grosvenorsport.com/",
        config_secret_field="grosvenor_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["GB-UKGC"],
        supported_currencies=["GBP"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Rank Group UK sportsbook. Casino-first brand.",
    ),
    "casumo": VenueExecutionProfile(
        venue_key="casumo",
        odds_api_key="casumo",
        display_name="Casumo",
        parent_company="Casumo Services Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.casumo.com/en-gb/sports/",
        config_secret_field="casumo_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["GB-UKGC", "MT-MGA", "SE-SGA"],
        available_countries=["GB", "SE", "NO", "FI", "DE"],
        supported_currencies=["GBP", "EUR", "SEK"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Malta-based casino/sportsbook. Multi-market EU.",
    ),
    "leovegas": VenueExecutionProfile(
        venue_key="leovegas",
        odds_api_key="leovegas",
        display_name="LeoVegas",
        parent_company="MGM Resorts (acquired 2022)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.leovegas.com/en-gb/betting/",
        config_secret_field="leovegas_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["GB-UKGC", "MT-MGA", "SE-SGA"],
        available_countries=["GB", "SE", "DE", "DK", "IT"],
        supported_currencies=["GBP", "EUR", "SEK"],
        min_bet=Decimal("0.10"),
        min_bet_currency="GBP",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="MGM-owned EU sportsbook. Originally Swedish mobile casino.",
    ),
    # ── France ─────────────────────────────────────────────────────────────
    "winamax_fr": VenueExecutionProfile(
        venue_key="winamax_fr",
        odds_api_key="winamax_fr",
        display_name="Winamax (France)",
        parent_company="Winamax SAS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.winamax.fr/paris-sportifs",
        config_secret_field="winamax_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="French-licensed. Competitive odds. FR residents only.",
    ),
    "winamax_de": VenueExecutionProfile(
        venue_key="winamax_de",
        odds_api_key="winamax_de",
        display_name="Winamax (Germany)",
        parent_company="Winamax SAS",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.winamax.de/sportwetten",
        config_secret_field="winamax_de_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["DE-GGL"],
        available_countries=["DE"],
        requires_residency=True,
        residency_countries=["DE"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Winamax German market. GGL-licensed. 5.3% turnover tax on bets.",
    ),
    "parionssport_fr": VenueExecutionProfile(
        venue_key="parionssport_fr",
        odds_api_key="parionssport_fr",
        display_name="ParionsSport (FDJ)",
        parent_company="Francaise des Jeux (FDJ)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.enligne.parionssport.fdj.fr/",
        config_secret_field="parionssport_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="French state lottery sportsbook. Wide retail network.",
    ),
    "pmu_fr": VenueExecutionProfile(
        venue_key="pmu_fr",
        odds_api_key="pmu_fr",
        display_name="PMU (France)",
        parent_company="Pari Mutuel Urbain",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://paris-sportifs.pmu.fr/",
        config_secret_field="pmu_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="FR",
        license_jurisdictions=["FR-ANJ"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="French horse racing monopoly. Also offers sports betting.",
    ),
    "netbet_fr": VenueExecutionProfile(
        venue_key="netbet_fr",
        odds_api_key="netbet_fr",
        display_name="NetBet (France)",
        parent_company="NetBet Enterprises Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.netbet.fr/sport",
        config_secret_field="netbet_fr_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["FR-ANJ", "MT-MGA"],
        available_countries=["FR"],
        requires_residency=True,
        residency_countries=["FR"],
        supported_currencies=["EUR"],
        min_bet=Decimal("0.50"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Malta-based, French-licensed sportsbook.",
    ),
    # ── Germany ────────────────────────────────────────────────────────────
    "tipico_de": VenueExecutionProfile(
        venue_key="tipico_de",
        odds_api_key="tipico_de",
        display_name="Tipico (Germany)",
        parent_company="Tipico Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.tipico.de/sportwetten",
        config_secret_field="tipico_de_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["DE-GGL", "MT-MGA"],
        available_countries=["DE", "AT"],
        requires_residency=True,
        residency_countries=["DE"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.MODERATE,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="Germany's largest sportsbook. 5.3% turnover tax. Limits sharps.",
    ),
    "codere_it": VenueExecutionProfile(
        venue_key="codere_it",
        odds_api_key="codere_it",
        display_name="Codere (Italy)",
        parent_company="Codere Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.codere.it/scommesse",
        config_secret_field="codere_it_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="ES",
        license_jurisdictions=["IT-ADM"],
        available_countries=["IT"],
        requires_residency=True,
        residency_countries=["IT"],
        supported_currencies=["EUR"],
        min_bet=Decimal("1"),
        min_bet_currency="EUR",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Spanish-owned, Italian-licensed. Retail + online.",
    ),
    # ── Sweden ─────────────────────────────────────────────────────────────
    "svenskaspel_se": VenueExecutionProfile(
        venue_key="svenskaspel_se",
        odds_api_key="svenskaspel_se",
        display_name="Svenska Spel",
        parent_company="Svenska Spel AB (Swedish state)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.svenskaspel.se/odds",
        config_secret_field="svenskaspel_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        requires_residency=True,
        residency_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("1"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Swedish state gambling monopoly. BankID login required.",
    ),
    "atg_se": VenueExecutionProfile(
        venue_key="atg_se",
        odds_api_key="atg_se",
        display_name="ATG (Sweden)",
        parent_company="AB Trav och Galopp",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.atg.se/sport",
        config_secret_field="atg_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="SE",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        requires_residency=True,
        residency_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("1"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Swedish horse racing monopoly. Also offers sports betting.",
    ),
    "sport888_se": VenueExecutionProfile(
        venue_key="sport888_se",
        odds_api_key="sport888_se",
        display_name="888sport (Sweden)",
        parent_company="888 Holdings",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.888sport.se/",
        config_secret_field="sport888_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GI",
        license_jurisdictions=["SE-SGA"],
        available_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("10"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        notes="888 Holdings Swedish market. SGA-licensed.",
    ),
    "mrgreen_se": VenueExecutionProfile(
        venue_key="mrgreen_se",
        odds_api_key="mrgreen_se",
        display_name="Mr Green (Sweden)",
        parent_company="William Hill (888 Holdings)",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.mrgreen.se/sport",
        config_secret_field="mrgreen_se_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="MT",
        license_jurisdictions=["SE-SGA", "MT-MGA"],
        available_countries=["SE"],
        supported_currencies=["SEK"],
        min_bet=Decimal("10"),
        min_bet_currency="SEK",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="888/WH subsidiary. Swedish sportsbook.",
    ),
    # ── Australia Additional ───────────────────────────────────────────────
    "bet365_au": VenueExecutionProfile(
        venue_key="bet365_au",
        odds_api_key="bet365_au",
        display_name="bet365 (Australia)",
        parent_company="bet365 Group",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.bet365.com.au/",
        config_secret_field="bet365_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="GB",
        license_jurisdictions=["AU-NT"],
        available_countries=["AU"],
        requires_residency=True,
        residency_countries=["AU"],
        supported_currencies=["AUD"],
        min_bet=Decimal("1"),
        min_bet_currency="AUD",
        withdrawal_delay_hours_min=24,
        withdrawal_delay_hours_max=72,
        anti_detection_level=AntiDetectionLevel.AGGRESSIVE,
        known_waf="cloudflare",
        requires_captcha=True,
        captcha_type="hcaptcha",
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        limits_winning_accounts=True,
        account_limiting_severity="aggressive",
        notes="bet365 AU. Aggressive anti-bot + account limiting. Hardest to automate.",
    ),
    "dabble_au": VenueExecutionProfile(
        venue_key="dabble_au",
        odds_api_key="dabble_au",
        display_name="Dabble (Australia)",
        parent_company="Dabble Pty Ltd",
        venue_category=VenueCategory.SCRAPER,
        primary_execution_method=ExecutionMethod.BROWSER_AUTOMATION,
        credential_type=CredentialType.USERNAME_PASSWORD,
        login_url="https://www.dabble.com.au/",
        config_secret_field="dabble_au_credentials",
        username_secret_key="username",
        password_secret_key="password",
        headquarters_country="AU",
        license_jurisdictions=["AU-NT"],
        available_countries=["AU"],
        requires_residency=True,
        residency_countries=["AU"],
        supported_currencies=["AUD"],
        min_bet=Decimal("1"),
        min_bet_currency="AUD",
        anti_detection_level=AntiDetectionLevel.BASIC,
        commission_model="built_into_odds",
        withdrawal_fee=Decimal("0"),
        notes="Australian social betting app. Newer entrant.",
    ),
}
