"""
DeFi Signal Model

Defines the DeFiSignal dataclass - a complete signal containing one or more
execution instructions that can be atomic (all-or-nothing) or sequential.

Signals are generated by the strategy layer and consumed by the execution engine.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import cast

from unified_api_contracts.internal.domain.execution_service.types import (
    ExecutionInstruction,
    OperationType,
    ensure_dict,
)


@dataclass
class AtomicLeg:
    """
    Legacy compatibility - maps to ExecutionInstruction within atomic bundle.

    Used for simple representation of flash loan sequence steps.
    """

    leg_index: int
    operation: OperationType
    token_in: str
    token_out: str | None
    amount: Decimal
    protocol: str  # AAVE, ETHERFI, MORPHO, UNISWAP
    expected_output: Decimal | None = None

    def to_instruction(
        self,
        instruction_id: str,
        timestamp: datetime,
        benchmark_price: Decimal = Decimal("0"),
    ) -> ExecutionInstruction:
        """Convert to ExecutionInstruction."""
        # Map protocol to venue
        protocol_to_venue = {
            "AAVE": "AAVE_V3-ETHEREUM",
            "MORPHO": "MORPHO",
            "ETHERFI-ETHEREUM": "ETHERFI-ETHEREUM",
            "LIDO": "LIDO-ETHEREUM",
            "UNISWAP": "UNISWAP_V3-ETHEREUM",
            "CURVE": "CURVE-ETHEREUM",
            "BALANCER": "BALANCER-ETH",
        }

        venue = protocol_to_venue.get(self.protocol.upper(), self.protocol)

        # Determine from/to venue based on operation
        if self.operation in [OperationType.LEND, OperationType.STAKE, OperationType.FLASH_REPAY]:
            from_venue = "WALLET_ETH"
            to_venue = venue
        elif self.operation in [
            OperationType.BORROW,
            OperationType.WITHDRAW,
            OperationType.UNSTAKE,
            OperationType.FLASH_BORROW,
        ]:
            from_venue = venue
            to_venue = "WALLET_ETH"
        else:
            from_venue = venue
            to_venue = "WALLET_ETH"

        return ExecutionInstruction(
            instruction_id=instruction_id,
            operation=self.operation,
            timestamp=timestamp,
            from_venue=from_venue,
            to_venue=to_venue,
            token_in=self.token_in,
            token_out=self.token_out,
            amount=self.amount,
            benchmark_price=benchmark_price,
            benchmark_type=OperationType.benchmark_type_for_operation(self.operation),
        )


@dataclass
class DeFiSignal:
    """
    Complete signal containing one or more execution instructions.

    Can be:
    - Single instruction (simple operation)
    - Multiple sequential instructions (non-atomic)
    - Multiple atomic instructions (flash loan bundle - all-or-nothing)

    Attributes:
        signal_id: Unique identifier for this signal
        strategy_id: Strategy that generated this signal (e.g., "ETH_LEVERAGED_STAKING")
        timestamp: When this signal was generated
        instructions: Ordered list of instructions to execute
        is_atomic: If True, all instructions must succeed or all fail
        expected_apy: Expected annual yield from this strategy
        ethena_benchmark_apy: Ethena sUSDe APR at signal time (for comparison)
        total_gas_budget: Maximum total gas to spend (for on-chain)
        max_total_slippage_bps: Maximum total slippage across all instructions

    Example (Simple Lend):
        DeFiSignal(
            signal_id="sig_001",
            strategy_id="SIMPLE_LEND",
            instructions=[
                ExecutionInstruction(operation=OperationType.LEND, ...)
            ],
            is_atomic=False,
        )

    Example (Flash Loan Leveraged Staking):
        DeFiSignal(
            signal_id="sig_002",
            strategy_id="RECURSIVE_STAKED_BASIS",
            is_atomic=True,  # All-or-nothing
            instructions=[
                ExecutionInstruction(operation=OperationType.FLASH_BORROW, ...),
                ExecutionInstruction(operation=OperationType.STAKE, ...),
                ExecutionInstruction(operation=OperationType.LEND, ...),
                ExecutionInstruction(operation=OperationType.BORROW, ...),
                ExecutionInstruction(operation=OperationType.FLASH_REPAY, ...),
            ],
        )
    """

    # Core identification
    signal_id: str
    strategy_id: str
    timestamp: datetime

    # Instructions to execute (ordered)
    instructions: list[ExecutionInstruction]

    # Atomic execution flag
    is_atomic: bool = False

    # Strategy context for comparison
    expected_apy: Decimal = Decimal("0")
    ethena_benchmark_apy: Decimal = Decimal("0")

    # Risk parameters
    total_gas_budget: int | None = None
    max_total_slippage_bps: int = 100  # Default 1% total slippage

    # Metadata
    metadata: dict[str, object] = field(default_factory=dict)

    def __post_init__(self):
        """Validate signal after initialization."""
        # Convert APY values to Decimal
        if not isinstance(self.expected_apy, Decimal):  # pyright: ignore[reportUnnecessaryIsInstance]
            self.expected_apy = Decimal(str(self.expected_apy))
        if not isinstance(self.ethena_benchmark_apy, Decimal):  # pyright: ignore[reportUnnecessaryIsInstance]
            self.ethena_benchmark_apy = Decimal(str(self.ethena_benchmark_apy))

        # Validate atomic signals have flash loan operations paired
        if self.is_atomic:
            self._validate_atomic_signal()

    def _validate_atomic_signal(self):
        """Validate that atomic signals have properly paired flash loans."""
        flash_borrows = sum(1 for i in self.instructions if i.operation == OperationType.FLASH_BORROW)
        flash_repays = sum(1 for i in self.instructions if i.operation == OperationType.FLASH_REPAY)

        if flash_borrows != flash_repays:
            raise ValueError(
                f"Atomic signal has mismatched flashloans: {flash_borrows} FLASH_BORROW vs{flash_repays} FLASH_REPAY"
            )

        # Flash borrow should come before flash repay
        if flash_borrows > 0:
            first_borrow_idx = next(
                i for i, inst in enumerate(self.instructions) if inst.operation == OperationType.FLASH_BORROW
            )
            last_repay_idx = (
                len(self.instructions)
                - 1
                - next(
                    i
                    for i, inst in enumerate(reversed(self.instructions))
                    if inst.operation == OperationType.FLASH_REPAY
                )
            )

            if first_borrow_idx >= last_repay_idx:
                raise ValueError("FLASH_BORROW must come before FLASH_REPAY")

    @property
    def num_instructions(self) -> int:
        """Get number of instructions."""
        return len(self.instructions)

    @property
    def operation_types(self) -> list[OperationType]:
        """Get list of operation types in this signal."""
        return [i.operation for i in self.instructions]

    @property
    def involves_flash_loan(self) -> bool:
        """Check if this signal involves flash loans."""
        return any(i.is_flash_loan_operation for i in self.instructions)

    @property
    def total_tokens_involved(self) -> set[str]:
        """Get set of all tokens involved in this signal."""
        tokens: set[str] = set()
        for inst in self.instructions:
            tokens.add(inst.token_in)
            if inst.token_out:
                tokens.add(inst.token_out)
        return tokens

    @property
    def venues_involved(self) -> set[str]:
        """Get set of all venues involved in this signal."""
        venues: set[str] = set()
        for inst in self.instructions:
            venues.add(inst.from_venue)
            venues.add(inst.to_venue)
        return venues

    @property
    def strategy_outperformance(self) -> Decimal:
        """Calculate expected outperformance vs Ethena benchmark."""
        return self.expected_apy - self.ethena_benchmark_apy

    def get_instruction_by_id(self, instruction_id: str) -> ExecutionInstruction | None:
        """Get instruction by ID."""
        for inst in self.instructions:
            if inst.instruction_id == instruction_id:
                return inst
        return None

    @classmethod
    def from_atomic_legs(
        cls,
        signal_id: str,
        strategy_id: str,
        timestamp: datetime,
        legs: list[AtomicLeg],
        expected_apy: Decimal = Decimal("0"),
        ethena_benchmark_apy: Decimal = Decimal("0"),
    ) -> "DeFiSignal":
        """
        Create atomic signal from legacy AtomicLeg list.

        Convenience method for callers.
        """
        instructions: list[ExecutionInstruction] = []
        for i, leg in enumerate(legs):
            inst = leg.to_instruction(
                instruction_id=f"{signal_id}_leg_{i:03d}",
                timestamp=timestamp,
            )
            instructions.append(inst)

        return cls(
            signal_id=signal_id,
            strategy_id=strategy_id,
            timestamp=timestamp,
            instructions=instructions,
            is_atomic=True,
            expected_apy=expected_apy,
            ethena_benchmark_apy=ethena_benchmark_apy,
        )

    def to_dict(self) -> dict[str, object]:
        """Convert to dictionary for serialization."""
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "timestamp": self.timestamp.isoformat(),
            "instructions": [i.to_dict() for i in self.instructions],
            "is_atomic": self.is_atomic,
            "expected_apy": str(self.expected_apy),
            "ethena_benchmark_apy": str(self.ethena_benchmark_apy),
            "total_gas_budget": self.total_gas_budget,
            "max_total_slippage_bps": self.max_total_slippage_bps,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, object]) -> "DeFiSignal":
        """Create from dictionary."""
        raw_instructions = data["instructions"]
        instructions_list = (
            cast(list[dict[str, object]], raw_instructions) if isinstance(raw_instructions, list) else []
        )
        return cls(
            signal_id=cast(str, data["signal_id"]),
            strategy_id=cast(str, data["strategy_id"]),
            timestamp=datetime.fromisoformat(cast(str, data["timestamp"])),
            instructions=[ExecutionInstruction.from_dict(i) for i in instructions_list],
            is_atomic=cast(bool, data.get("is_atomic", False)),
            expected_apy=Decimal(cast(str, data.get("expected_apy", "0"))),
            ethena_benchmark_apy=Decimal(cast(str, data.get("ethena_benchmark_apy", "0"))),
            total_gas_budget=cast(int | None, data.get("total_gas_budget")),
            max_total_slippage_bps=cast(int, data.get("max_total_slippage_bps", 100)),
            metadata=ensure_dict(cast(dict[str, object] | None, data.get("metadata"))),
        )
