"""Venue error classifications for CeFi exchanges."""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_CEFI: dict[str, list[VenueErrorClassification]] = {
    "binance": [
        ve(
            "binance",
            "-1003",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        ve(
            "binance",
            "-1021",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Timestamp recv window",
        ),
        ve(
            "binance",
            "-1000",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unknown error",
        ),
        ve(
            "binance",
            "-1006",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Connection closed",
        ),
        ve(
            "binance",
            "-2011",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unknown order",
        ),
        ve(
            "binance",
            "-1013",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid lot size",
        ),
        ve(
            "binance",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "binance",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "binance",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "binance",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "bybit": [
        ve(
            "bybit",
            "10006",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "bybit",
            "10000",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal error",
        ),
        ve(
            "bybit",
            "10001",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Parameter error",
        ),
        ve(
            "bybit",
            "10019",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="WS restarting",
        ),
        ve(
            "bybit",
            "33004",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid",
        ),
        ve(
            "bybit",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "bybit",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "bybit",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "bybit",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "okx": [
        ve(
            "okx",
            "50004",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="WebSocket closed",
        ),
        ve(
            "okx",
            "50011",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "okx",
            "50026",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="System busy",
        ),
        ve(
            "okx",
            "51008",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Insufficient funds",
        ),
        ve(
            "okx",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "okx",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "okx",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "okx",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "deribit": [
        ve(
            "deribit",
            "10028",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        ve(
            "deribit",
            "10040",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
        ve(
            "deribit",
            "11044",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Not enough funds",
        ),
        ve(
            "deribit",
            "13009",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Invalid token",
        ),
        ve(
            "deribit",
            "13010",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Token revoked",
        ),
        ve(
            "deribit",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "deribit",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "deribit",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "deribit",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "coinbase": [
        ve(
            "coinbase",
            "RATE_LIMIT_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        ve(
            "coinbase",
            "INTERNAL_SERVICE_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server",
        ),
        ve(
            "coinbase",
            "TEMPORARILY_UNAVAILABLE",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Temp",
        ),
        ve(
            "coinbase",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "coinbase",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "coinbase",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "coinbase",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "upbit": [
        ve(
            "upbit",
            "invalid_access_key",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid key",
        ),
        ve(
            "upbit",
            "invalid_query_payload",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid",
        ),
        ve(
            "upbit",
            "too_many_requests",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        ve(
            "upbit",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "upbit",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "upbit",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "upbit",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "ccxt": [
        ve(
            "ccxt",
            "RateLimitExceeded",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        ve(
            "ccxt",
            "ExchangeNotAvailable",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Unavail",
        ),
        ve(
            "ccxt",
            "ExchangeError",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Transient",
        ),
        ve(
            "ccxt",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "ccxt",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "ccxt",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "ccxt",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    # ---------------------------------------------------------------------------
    # Kraken REST + WebSocket error codes
    # BLOCKED-CREDENTIALS scaffold 2026-05-14 — see ikenna_orchestrator/pings/slot_11.md
    # Kraken returns errors in the "error" array of the JSON response body.
    # Private endpoint auth uses HMAC-SHA512 (API-Key + API-Sign headers).
    # Rate limits: tier-based; Tier-0 = 15/45 req; Tier-1+ scales up.
    # Ref: https://docs.kraken.com/rest/#section/General-Usage/Error-Conditions
    # ---------------------------------------------------------------------------
    "kraken": [
        ve(
            "kraken",
            "EGeneral:Permission denied",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key lacks required permission",
        ),
        ve(
            "kraken",
            "EGeneral:Invalid arguments",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Request contains invalid arguments",
        ),
        ve(
            "kraken",
            "EGeneral:Temporary lockout",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Temporary lockout — too many requests; back off",
        ),
        ve(
            "kraken",
            "EOrder:Rate limit exceeded",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Order rate limit exceeded",
        ),
        ve(
            "kraken",
            "EGeneral:Insufficient funds",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Insufficient funds to place order",
        ),
        ve(
            "kraken",
            "EOrder:Unknown order",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order ID not found",
        ),
        ve(
            "kraken",
            "EOrder:Cannot open opposing position",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Cannot open position opposing an existing one",
        ),
        ve(
            "kraken",
            "EService:Unavailable",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Service temporarily unavailable",
        ),
        ve(
            "kraken",
            "EService:Market in cancel only",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Market is in cancel-only mode",
        ),
        ve(
            "kraken",
            "ETIMEDOUT",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Connection timed out",
        ),
        ve(
            "kraken",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP 429 rate limit exceeded",
        ),
        ve(
            "kraken",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="HTTP 401 unauthorized — invalid or missing API key",
        ),
        ve(
            "kraken",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="HTTP 403 forbidden — key lacks required scope",
        ),
        ve(
            "kraken",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP 500 internal server error",
        ),
        ve(
            "kraken",
            "503",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="HTTP 503 service unavailable",
        ),
    ],
    "kraken-futures": [
        ve(
            "kraken-futures",
            "apiKeyAuthorizationError",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key auth error — missing or invalid key",
        ),
        ve(
            "kraken-futures",
            "invalidArgument",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid argument in request",
        ),
        ve(
            "kraken-futures",
            "marketUnavailable",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Market temporarily unavailable",
        ),
        ve(
            "kraken-futures",
            "wouldNotReducePosition",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order would not reduce position",
        ),
        ve(
            "kraken-futures",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP 429 rate limit exceeded",
        ),
        ve(
            "kraken-futures",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="HTTP 401 unauthorized",
        ),
    ],
}
