"""Venue error classifications for DeFi protocols."""

from __future__ import annotations

from enum import StrEnum

from ._types import ErrorAction, VenueErrorClassification, ve


class DefiAlertType(StrEnum):
    """Canonical DeFi alert type enum.

    Used by alerting-service DeFi rules to classify alert categories.
    """

    HEALTH_FACTOR_CRITICAL = "health_factor_critical"
    WEETH_DEPEG = "weeth_depeg"
    AAVE_UTILIZATION_SPIKE = "aave_utilization_spike"
    FUNDING_RATE_FLIP = "funding_rate_flip"
    FEATURE_STALE = "feature_stale"


class DefiErrorCode:
    """Known DeFi error codes for structured error classification.

    These codes are used by UDEI connectors (aave.py, etc.) to classify
    on-chain revert reasons into structured error codes. Execution-service
    routes on the code prefix (FAIL/RETRY/SKIP) via classify_venue_error().

    Each constant aligns with the aave_v3 venue error classifications in
    VENUE_ERRORS_DEFI below.
    """

    INSUFFICIENT_COLLATERAL = "INSUFFICIENT_COLLATERAL"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    NO_COLLATERAL_DEPOSITED = "NO_COLLATERAL_DEPOSITED"
    ASSET_NOT_SUPPORTED = "ASSET_NOT_SUPPORTED"
    ZERO_AMOUNT = "ZERO_AMOUNT"
    TX_REVERTED = "TX_REVERTED"
    GAS_ESTIMATION_FAILED = "GAS_ESTIMATION_FAILED"
    SLIPPAGE_EXCEEDED = "SLIPPAGE_EXCEEDED"
    FLASH_LOAN_RECEIVER_INVALID = "FLASH_LOAN_RECEIVER_INVALID"
    FLASH_LOAN_INSUFFICIENT_LIQUIDITY = "FLASH_LOAN_INSUFFICIENT_LIQUIDITY"
    NO_OUTSTANDING_DEBT = "NO_OUTSTANDING_DEBT"
    BORROW_CAP_EXCEEDED = "BORROW_CAP_EXCEEDED"
    SUPPLY_CAP_EXCEEDED = "SUPPLY_CAP_EXCEEDED"


VENUE_ERRORS_DEFI: dict[str, list[VenueErrorClassification]] = {
    "balancer": [
        ve(
            "balancer",
            "BAL#001",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — caller not authorised",
        ),
        ve(
            "balancer",
            "BAL#304",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Swap limit exceeded",
        ),
        ve(
            "balancer",
            "BAL#508",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool paused",
        ),
        ve(
            "balancer",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "balancer",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "balancer",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "balancer",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "balancer",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "curve": [
        ve(
            "curve",
            "SLIPPAGE_TOO_HIGH",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage exceeds allowed tolerance",
        ),
        ve(
            "curve",
            "POOL_IMBALANCED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Pool reserves severely imbalanced — retry later",
        ),
        ve(
            "curve",
            "RPC_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="JSON-RPC error from Ethereum node",
        ),
        ve(
            "curve",
            "TIMEOUT",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="RPC call timed out",
        ),
        ve(
            "curve",
            "CONNECTION_ERROR",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Network connection failure to RPC endpoint",
        ),
        ve(
            "curve",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "curve",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "curve",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "curve",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "curve",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="API server error",
        ),
    ],
    "ethena": [
        ve(
            "ethena",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "ethena",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ethena",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "ethena",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "ethena",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "euler": [
        ve(
            "euler",
            "E_INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral insufficient for borrow",
        ),
        ve(
            "euler",
            "E_BORROW_ISOLATION_VIOLATION",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow violates isolation mode",
        ),
        ve(
            "euler",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — malformed query or invalid parameters",
        ),
        ve(
            "euler",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "euler",
            "ADAPTER_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Adapter implementation error (e.g. missing method)",
        ),
        ve(
            "euler",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "euler",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "euler",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "fluid": [
        ve(
            "fluid",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "fluid",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "fluid",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "fluid",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "fluid",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "etherfi": [
        ve(
            "etherfi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "etherfi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "etherfi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "etherfi",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "etherfi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "lido": [
        ve(
            "lido",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "lido",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "lido",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "lido",
            "WITHDRAWAL_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Withdrawal request not found",
        ),
        ve(
            "lido",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "lido",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "morpho": [
        ve(
            "morpho",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Collateral value below required threshold",
        ),
        ve(
            "morpho",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — malformed GraphQL query or invalid parameters",
        ),
        ve(
            "morpho",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "morpho",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "morpho",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "morpho",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "morpho",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Morpho subgraph not found or unavailable",
        ),
    ],
    "uniswap_v2": [
        ve(
            "uniswap_v2",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pair has insufficient liquidity",
        ),
        ve(
            "uniswap_v2",
            "INSUFFICIENT_OUTPUT_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Output amount below minimum — slippage exceeded",
        ),
        ve(
            "uniswap_v2",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Subgraph not found or invalid ID",
        ),
        ve(
            "uniswap_v2",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid, malformed, or not found",
        ),
        ve(
            "uniswap_v2",
            "QUERY_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="GraphQL query syntax or schema error",
        ),
        ve(
            "uniswap_v2",
            "INDEXING_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Subgraph indexing in progress or stale",
        ),
        ve(
            "uniswap_v2",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "uniswap_v2",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "uniswap_v2",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v2",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "uniswap_v2",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v3": [
        ve(
            "uniswap_v3",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pool tick range has no liquidity",
        ),
        ve(
            "uniswap_v3",
            "TOO_LITTLE_RECEIVED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Slippage tolerance exceeded",
        ),
        ve(
            "uniswap_v3",
            "PRICE_SLIPPAGE_CHECK",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="sqrtPriceLimitX96 violated",
        ),
        ve(
            "uniswap_v3",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Subgraph not found or invalid ID",
        ),
        ve(
            "uniswap_v3",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid, malformed, or not found",
        ),
        ve(
            "uniswap_v3",
            "QUERY_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="GraphQL query syntax or schema error",
        ),
        ve(
            "uniswap_v3",
            "INDEXING_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Subgraph indexing in progress or stale",
        ),
        ve(
            "uniswap_v3",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "uniswap_v3",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "uniswap_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v3",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "uniswap_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "uniswap_v4": [
        ve(
            "uniswap_v4",
            "INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook or pool has no liquidity",
        ),
        ve(
            "uniswap_v4",
            "HOOK_DELTA_EXCEEDS_SWAP_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Hook delta exceeds swap amount",
        ),
        ve(
            "uniswap_v4",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Subgraph not found or invalid ID",
        ),
        ve(
            "uniswap_v4",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid, malformed, or not found",
        ),
        ve(
            "uniswap_v4",
            "QUERY_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="GraphQL query syntax or schema error",
        ),
        ve(
            "uniswap_v4",
            "INDEXING_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Subgraph indexing in progress or stale",
        ),
        ve(
            "uniswap_v4",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "uniswap_v4",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "uniswap_v4",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "uniswap_v4",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "uniswap_v4",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "aave_v3": [
        ve(
            "aave_v3",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Health factor below 1 — liquidation risk",
        ),
        ve(
            "aave_v3",
            "INSUFFICIENT_BALANCE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Token balance too low for the requested operation",
        ),
        ve(
            "aave_v3",
            "NO_COLLATERAL_DEPOSITED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No collateral deposited — cannot borrow",
        ),
        ve(
            "aave_v3",
            "ASSET_NOT_SUPPORTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Token not supported by AAVE V3 pool",
        ),
        ve(
            "aave_v3",
            "ZERO_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Operation amount must be greater than zero",
        ),
        ve(
            "aave_v3",
            "TX_REVERTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="On-chain transaction reverted",
        ),
        ve(
            "aave_v3",
            "GAS_ESTIMATION_FAILED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Gas estimation failed — node may be congested",
        ),
        ve(
            "aave_v3",
            "SLIPPAGE_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Slippage tolerance exceeded during execution",
        ),
        ve(
            "aave_v3",
            "FLASH_LOAN_RECEIVER_INVALID",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Flash loan receiver is not a valid contract",
        ),
        ve(
            "aave_v3",
            "FLASH_LOAN_INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Insufficient pool liquidity for flash loan amount",
        ),
        ve(
            "aave_v3",
            "NO_OUTSTANDING_DEBT",
            retry=False,
            reconnect=False,
            action=ErrorAction.SKIP,
            desc="No outstanding debt to repay — operation is a no-op",
        ),
        ve(
            "aave_v3",
            "BORROW_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow cap for asset reached",
        ),
        ve(
            "aave_v3",
            "SUPPLY_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Supply cap for asset reached",
        ),
        ve(
            "aave_v3",
            "PRICE_ORACLE_SENTINEL",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Oracle price feed stale — retry",
        ),
        ve(
            "aave_v3",
            "SUBGRAPH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Subgraph not found or invalid ID",
        ),
        ve(
            "aave_v3",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key invalid, malformed, or not found",
        ),
        ve(
            "aave_v3",
            "QUERY_ERROR",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="GraphQL query syntax or schema error",
        ),
        ve(
            "aave_v3",
            "INDEXING_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Subgraph indexing in progress or stale",
        ),
        ve(
            "aave_v3",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "aave_v3",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "aave_v3",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "aave_v3",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "aave_v3",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "aave_plasma": [
        ve(
            "aave_plasma",
            "INSUFFICIENT_COLLATERAL",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Health factor below 1 — liquidation risk",
        ),
        ve(
            "aave_plasma",
            "INSUFFICIENT_BALANCE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Token balance too low for the requested operation",
        ),
        ve(
            "aave_plasma",
            "NO_COLLATERAL_DEPOSITED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No collateral deposited — cannot borrow",
        ),
        ve(
            "aave_plasma",
            "ASSET_NOT_SUPPORTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Token not supported by AAVE Plasma pool",
        ),
        ve(
            "aave_plasma",
            "ZERO_AMOUNT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Operation amount must be greater than zero",
        ),
        ve(
            "aave_plasma",
            "TX_REVERTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="On-chain transaction reverted",
        ),
        ve(
            "aave_plasma",
            "GAS_ESTIMATION_FAILED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Gas estimation failed — node may be congested",
        ),
        ve(
            "aave_plasma",
            "SLIPPAGE_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Slippage tolerance exceeded during execution",
        ),
        ve(
            "aave_plasma",
            "FLASH_LOAN_RECEIVER_INVALID",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Flash loan receiver is not a valid contract",
        ),
        ve(
            "aave_plasma",
            "FLASH_LOAN_INSUFFICIENT_LIQUIDITY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Insufficient pool liquidity for flash loan amount",
        ),
        ve(
            "aave_plasma",
            "NO_OUTSTANDING_DEBT",
            retry=False,
            reconnect=False,
            action=ErrorAction.SKIP,
            desc="No outstanding debt to repay — operation is a no-op",
        ),
        ve(
            "aave_plasma",
            "BORROW_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Borrow cap for asset reached",
        ),
        ve(
            "aave_plasma",
            "SUPPLY_CAP_EXCEEDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Supply cap for asset reached",
        ),
        ve(
            "aave_plasma",
            "PRICE_ORACLE_SENTINEL",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Oracle price feed stale — retry",
        ),
        ve(
            "aave_plasma",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "aave_plasma",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "aave_plasma",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "aave_plasma",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
        ve(
            "aave_plasma",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
    "instadapp": [
        ve(
            "instadapp",
            "DS_PROXY_EXEC_FAILED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="DSProxy execution failed — revert in spell",
        ),
        ve(
            "instadapp",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "instadapp",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "instadapp",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "instadapp",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
        ve(
            "instadapp",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "defillama": [
        ve(
            "defillama",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "defillama",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "defillama",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "defillama",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Protocol or chain not found",
        ),
        ve(
            "defillama",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "defillama",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
        ve(
            "defillama",
            "-32603",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="RPC internal error — retry",
        ),
    ],
}
