"""Venue error classifications for prediction markets, sports betting, and sports data platforms."""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_SPORTS: dict[str, list[VenueErrorClassification]] = {
    # ── Sports data sources ──────────────────────────────────────────────
    "api_football": [
        ve(
            "api_football",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "api_football",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "api_football",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "api_football",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "api_football",
            "FREE_PLAN_DATE_LIMIT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Free plans do not have access to this date",
        ),
        ve(
            "api_football",
            "SEASON_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Wrong season parameter — use season start year not current year",
        ),
        ve(
            "api_football",
            "LEAGUE_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid league ID",
        ),
        ve(
            "api_football",
            "RATE_LIMIT_DAILY",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Daily request limit exceeded (100 free / 7500 pro)",
        ),
        ve(
            "api_football",
            "FIXTURE_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No fixtures for date/league combination",
        ),
        # ── Raw JSON-envelope error-dict KEYS (root-cause fix, 2026-07-13) ──
        # API-Football signals plan/quota/auth/param errors as HTTP 200 +
        # {"errors": {<key>: "<message>"}, "response": []} — the dict's own
        # KEY (not the codes above, which nothing in instruments-service ever
        # actually produced) is what api_football.py's ``_raise_on_api_errors``
        # now threads through as ``error_key`` (see ApiFootballAdapter
        # ApiFootballResponseError.error_key). These are the keys API-Football
        # itself documents/emits.
        ve(
            "api_football",
            "plan",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Current plan does not have access to this endpoint/date range",
        ),
        ve(
            "api_football",
            "token",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid or missing API token",
        ),
        ve(
            "api_football",
            "requests",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Daily request quota exceeded",
        ),
    ],
    "odds_api": [
        ve(
            "odds_api",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "odds_api",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "odds_api",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "odds_api",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "odds_api",
            "KEY_DEACTIVATED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="API key is deactivated — cancellation or failed payment",
        ),
        ve(
            "odds_api",
            "QUOTA_EXHAUSTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="x-requests-remaining reached 0",
        ),
        ve(
            "odds_api",
            "SPORT_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid sport key",
        ),
        ve(
            "odds_api",
            "INVALID_REGION",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unsupported region code",
        ),
        ve(
            "odds_api",
            "SUBSCRIPTION_EXPIRED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Plan subscription lapsed",
        ),
    ],
    "footystats": [
        ve(
            "footystats",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "footystats",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "footystats",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "footystats",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "footystats",
            "QUOTA_EXHAUSTED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="request_remaining reached 0 in metadata",
        ),
        ve(
            "footystats",
            "INVALID_LEAGUE_ID",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unrecognized league ID",
        ),
        ve(
            "footystats",
            "INVALID_DATE_FORMAT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Wrong date format in request",
        ),
    ],
    "understat": [
        ve(
            "understat",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "understat",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "understat",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "understat",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "understat",
            "PAGE_STRUCTURE_CHANGED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="JSON.parse pattern not found in HTML — scraping regex outdated",
        ),
        ve(
            "understat",
            "LEAGUE_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="404 on league page",
        ),
        ve(
            "understat",
            "MATCH_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="404 on match page",
        ),
        ve(
            "understat",
            "JSON_DECODE_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Hex-encoded JSON failed to decode",
        ),
        ve(
            "understat",
            "SCRAPE_BLOCKED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="403 or captcha page returned",
        ),
    ],
    "transfermarkt": [
        ve(
            "transfermarkt",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "transfermarkt",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "transfermarkt",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "transfermarkt",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "transfermarkt",
            "APIFY_ACTOR_FAILED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Apify actor run status != SUCCEEDED",
        ),
        ve(
            "transfermarkt",
            "APIFY_TIMEOUT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Apify actor did not finish within timeout",
        ),
        ve(
            "transfermarkt",
            "RAPIDAPI_SUBSCRIPTION_EXPIRED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="RapidAPI 403 — subscription expired",
        ),
        ve(
            "transfermarkt",
            "APIFY_DATASET_EMPTY",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Apify actor produced no results",
        ),
        ve(
            "transfermarkt",
            "RAPIDAPI_ENDPOINT_CHANGED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="404 on RapidAPI wrapper — endpoint URL changed",
        ),
    ],
    "open_meteo": [
        ve(
            "open_meteo",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "open_meteo",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "open_meteo",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "open_meteo",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "open_meteo",
            "INVALID_COORDINATES",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Latitude/longitude out of range",
        ),
        ve(
            "open_meteo",
            "DATE_OUT_OF_RANGE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Date too far in past or future",
        ),
        ve(
            "open_meteo",
            "VARIABLE_NOT_AVAILABLE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Requested weather variable not available for location",
        ),
    ],
    "soccer_football_info": [
        ve(
            "soccer_football_info",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "soccer_football_info",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "soccer_football_info",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "soccer_football_info",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "soccer_football_info",
            "RAPIDAPI_SUBSCRIPTION_EXPIRED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="RapidAPI 403 — subscription expired",
        ),
        ve(
            "soccer_football_info",
            "ENDPOINT_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Wrong URL path — e.g. /api/v1/leagues/ does not exist",
        ),
        ve(
            "soccer_football_info",
            "GZIP_DECODE_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Response decompression failed",
        ),
        ve(
            "soccer_football_info",
            "PAGINATION_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Paginated response needs more pages",
        ),
    ],
    "pinnacle": [
        ve(
            "pinnacle",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "pinnacle",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid credentials",
        ),
        ve(
            "pinnacle",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "pinnacle",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "pinnacle",
            "INSUFFICIENT_PERMISSIONS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Account does not have API access",
        ),
        ve(
            "pinnacle",
            "ACCOUNT_SUSPENDED",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Pinnacle account suspended",
        ),
        ve(
            "pinnacle",
            "SPORT_NOT_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Invalid sport ID",
        ),
        ve(
            "pinnacle",
            "LINE_NOT_AVAILABLE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Odds line not available for event",
        ),
    ],
    "odds_engine": [
        ve("odds_engine", "400", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Bad request"),
        ve("odds_engine", "401", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Unauthorized"),
        ve("odds_engine", "403", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Forbidden"),
        ve("odds_engine", "429", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Rate limit exceeded"),
        ve("odds_engine", "500", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Internal server error"),
        ve(
            "odds_engine",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
    "opticodds": [
        ve("opticodds", "400", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Bad request"),
        ve("opticodds", "401", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Unauthorized"),
        ve("opticodds", "403", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Forbidden"),
        ve("opticodds", "429", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Rate limit exceeded"),
        ve("opticodds", "500", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Internal server error"),
        ve("opticodds", "503", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Service unavailable"),
    ],
    "matchbook": [
        ve("matchbook", "400", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Bad request"),
        ve("matchbook", "401", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Unauthorized"),
        ve("matchbook", "403", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Forbidden"),
        ve("matchbook", "429", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Rate limit exceeded"),
        ve("matchbook", "500", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Internal server error"),
        ve("matchbook", "503", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Service unavailable"),
    ],
    "metabet": [
        ve("metabet", "400", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Bad request"),
        ve("metabet", "401", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Unauthorized"),
        ve("metabet", "403", retry=False, reconnect=False, action=ErrorAction.FAIL, desc="Forbidden"),
        ve("metabet", "429", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Rate limit exceeded"),
        ve("metabet", "500", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Internal server error"),
        ve("metabet", "503", retry=True, reconnect=False, action=ErrorAction.RETRY, desc="Service unavailable"),
    ],
    # ── Prediction markets & sports betting ──────────────────────────────
    "polymarket": [
        ve(
            "polymarket",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "polymarket",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key or signature",
        ),
        ve(
            "polymarket",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "polymarket",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "betfair": [
        ve(
            "betfair",
            "INVALID_SESSION_INFORMATION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Session token invalid or expired — reauthenticate",
        ),
        ve(
            "betfair",
            "NO_SESSION",
            retry=False,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="No active session — reauthenticate",
        ),
        ve(
            "betfair",
            "TOO_MUCH_DATA",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Response too large — reduce request scope",
        ),
        ve(
            "betfair",
            "SERVICE_BUSY",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Betfair API service busy — retry with backoff",
        ),
        ve(
            "betfair",
            "TIMEOUT_ERROR",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Request timed out on Betfair side",
        ),
        ve(
            "betfair",
            "REQUEST_SIZE_EXCEEDS_LIMIT",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Request payload exceeds size limit",
        ),
        ve(
            "betfair",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="HTTP rate limit exceeded",
        ),
        ve(
            "betfair",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "betfair",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "betfair",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "kalshi": [
        ve(
            "kalshi",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "kalshi",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid or expired token",
        ),
        ve(
            "kalshi",
            "403",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Forbidden — insufficient permissions",
        ),
        ve(
            "kalshi",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid order parameters",
        ),
        ve(
            "kalshi",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "kalshi",
            "MARKET_NOT_OPEN",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Market is not open for trading",
        ),
        ve(
            "kalshi",
            "INSUFFICIENT_FUNDS",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Account balance insufficient for order",
        ),
        ve(
            "kalshi",
            "TRADES_FETCH_FAILED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Transport error during trades fetch — connection/timeout/OS error",
        ),
    ],
}
