"""Venue error classifications for TradFi data providers."""

from __future__ import annotations

from ._types import ErrorAction, VenueErrorClassification, ve

VENUE_ERRORS_TRADFI: dict[str, list[VenueErrorClassification]] = {
    "tardis": [
        ve(
            "tardis",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized",
        ),
        ve(
            "tardis",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "tardis",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Server error",
        ),
    ],
    "yahoo_finance": [
        ve(
            "yahoo_finance",
            "RATE_LIMIT_EXCEEDED",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate",
        ),
        ve(
            "yahoo_finance",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Too many requests",
        ),
    ],
    "ibkr": [
        ve(
            "ibkr",
            "100",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Market data farm",
        ),
        ve(
            "ibkr",
            "1100",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Connectivity lost",
        ),
        ve(
            "ibkr",
            "1300",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Order rejected",
        ),
    ],
    "databento": [
        ve(
            "databento",
            "RATE_LIMIT",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit",
        ),
        ve(
            "databento",
            "AUTH_FAILURE",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Auth failed",
        ),
        ve(
            "databento",
            "CONNECTION_RESET",
            retry=True,
            reconnect=True,
            action=ErrorAction.RECONNECT,
            desc="Reset",
        ),
    ],
    "barchart": [
        ve(
            "barchart",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "barchart",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "barchart",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid symbol or parameter",
        ),
        ve(
            "barchart",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "barchart",
            "NO_DATA_FOUND",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for symbol",
        ),
    ],
    "fred": [
        ve(
            "fred",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "fred",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid series ID or parameter",
        ),
        ve(
            "fred",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid API key",
        ),
        ve(
            "fred",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "ecb": [
        ve(
            "ecb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ecb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid key or flow",
        ),
        ve(
            "ecb",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="No data found for series",
        ),
        ve(
            "ecb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "ecb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service temporarily unavailable",
        ),
    ],
    "ofr": [
        ve(
            "ofr",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "ofr",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request",
        ),
        ve(
            "ofr",
            "404",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Dataset or series not found",
        ),
        ve(
            "ofr",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
    ],
    "openbb": [
        ve(
            "openbb",
            "429",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Rate limit exceeded",
        ),
        ve(
            "openbb",
            "401",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Unauthorized — invalid token",
        ),
        ve(
            "openbb",
            "400",
            retry=False,
            reconnect=False,
            action=ErrorAction.FAIL,
            desc="Bad request — invalid parameters",
        ),
        ve(
            "openbb",
            "500",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Internal server error",
        ),
        ve(
            "openbb",
            "503",
            retry=True,
            reconnect=False,
            action=ErrorAction.RETRY,
            desc="Service unavailable",
        ),
    ],
}
