"""Internal API contracts — schemas for data flowing between services.

Covers:
- ``events``       : Lifecycle event envelopes, all 11+ event types, per-type metadata
- ``domain``       : Instrument records, market ticks, order books, OHLCV, candles
- ``execution``    : Orders, fills, execution instructions, execution results
- ``signals``      : Strategy instructions, DeFi signals, GCS output records
- ``risk``         : Risk metrics, alerts, exposure summaries, pre-trade checks, positions
- ``features``     : Delta-one feature vectors, vol surface, futures term structure
- ``ml``           : Model metadata, inference requests/results, training jobs
- ``health``       : Health status, dependency checks, circuit breakers, error envelopes
- ``config``       : Config store records, change notifications, active pointers
- ``pubsub``       : Typed Pub/Sub message bodies for every internal topic
"""

from unified_api_contracts.internal.config import (
    ConfigChangeNotification,
    ConfigStoreActivePointer,
    ConfigStoreMetadata,
    ConfigStoreRecord,
    ConfigValidationResponse,
    ConfigValidationResult,
)
from unified_api_contracts.internal.domain import (
    CanonicalOrderBook,
    CanonicalTrade,
    DerivativeTicker,
    InstrumentRecord,
    InstrumentType,
    LiquidationRecord,
    MarketTrade,
    OhlcvBar,
    OptionType,
    OrderBookSnapshot5,
    ProcessedCandle,
    QuoteRecord,
)
from unified_api_contracts.internal.events import (
    AuthFailureDetails,
    AuthFailureEvent,
    ConfigChangedDetails,
    ConfigChangedEvent,
    DataBroadcastDetails,
    EventMetadata,
    EventSeverity,
    FailedDetails,
    FailedEvent,
    LifecycleEventEnvelope,
    LifecycleEventType,
    PersistenceCompletedDetails,
    PersistenceStartedDetails,
    ProcessingCompletedDetails,
    ProcessingStartedDetails,
    PubSubLifecycleEventMessage,
    SecretAccessedDetails,
    SecretAccessedEvent,
    ServiceMode,
    StartedDetails,
    StartedEvent,
    ValidationCompletedDetails,
    ValidationStartedDetails,
)
from unified_api_contracts.internal.execution import (
    BenchmarkType,
    CandleCloseWarningMessage,
    CanonicalFill,
    CanonicalOrder,
    ExecutionInstruction,
    ExecutionResult,
    ExecutionStatus,
    FillEventPubSubPayload,
    ManualInstructionRequest,
    ManualInstructionResponse,
    OperationType,
    OrderSide,
    OrderStatus,
    OrderSubmittedMessage,
    OrderType,
    SLHitMessage,
    TimeInForce,
    TPHitMessage,
)
from unified_api_contracts.internal.features import (
    DeltaOneFeatureRecord,
    FeatureSnapshotRequest,
    FuturesTermStructureRecord,
    OptionsIvRecord,
)
from unified_api_contracts.internal.health import (
    CircuitBreakerEvent,
    CircuitBreakerState,
    CircuitBreakerStateEnum,
    ComponentHealth,
    DependencyFailure,
    DependencyReport,
    DependencyStatus,
    EnhancedError,
    ErrorCategory,
    ErrorContext,
    ErrorRecoveryStrategy,
    ErrorSeverity,
    HealthStatusEnum,
    ServiceHealthStatus,
)
from unified_api_contracts.internal.ml import (
    InferenceRequest,
    InferenceResult,
    MLConfigDict,
    ModelMetadata,
    ModelType,
    ModelVariantConfig,
    TargetType,
    TrainingJobRequest,
    TrainingJobResult,
    TrainingPeriod,
)
from unified_api_contracts.internal.pubsub import (
    CircuitBreakerEventMessage,
    DerivativeTickerMessage,
    ExecutionResultMessage,
    FeatureUpdateMessage,
    FillEventMessage,
    HealthAlertMessage,
    InternalPubSubTopic,
    LiquidationMessage,
    MarketTickMessage,
    MLPredictionMessage,
    OrderRequestMessage,
    PositionUpdateMessage,
    PubSubMessageEnvelope,
    RiskAlertMessage,
    ServiceLifecycleEventMessage,
    StrategySignalMessage,
)
from unified_api_contracts.internal.risk import (
    AccountState,
    AlertContextData,
    AlertMessage,
    AlertType,
    Balance,
    ExposureSummary,
    InternalPosition,
    MarginState,
    PositionSide,
    PreTradeCheckRequest,
    PreTradeCheckResponse,
    RiskMetrics,
    RiskPosition,
    RiskStatus,
)
from unified_api_contracts.internal.signals import (
    DeFiSignal,
    DeFiSignalRecord,
    InstructionRecord,
    StrategyInstruction,
)
from unified_api_contracts.internal.sor import (
    SorChildOrder,
    SorExecutionSummary,
    SorRouteDecision,
    SorTwapSlice,
    SorVenueCapacity,
    SorVenueScore,
)

__all__ = [
    # risk
    "AccountState",
    "AlertContextData",
    "AlertMessage",
    "AlertType",
    # events
    "AuthFailureDetails",
    "AuthFailureEvent",
    "Balance",
    # execution
    "BenchmarkType",
    "CandleCloseWarningMessage",
    "CanonicalFill",
    "CanonicalOrder",
    # domain
    "CanonicalOrderBook",
    "CanonicalTrade",
    # health
    "CircuitBreakerEvent",
    # pubsub
    "CircuitBreakerEventMessage",
    "CircuitBreakerState",
    "CircuitBreakerStateEnum",
    "ComponentHealth",
    # config
    "ConfigChangeNotification",
    "ConfigChangedDetails",
    "ConfigChangedEvent",
    "ConfigStoreActivePointer",
    "ConfigStoreMetadata",
    "ConfigStoreRecord",
    "ConfigValidationResponse",
    "ConfigValidationResult",
    "DataBroadcastDetails",
    # signals
    "DeFiSignal",
    "DeFiSignalRecord",
    # features
    "DeltaOneFeatureRecord",
    "DependencyFailure",
    "DependencyReport",
    "DependencyStatus",
    "DerivativeTicker",
    "DerivativeTickerMessage",
    "EnhancedError",
    "ErrorCategory",
    "ErrorContext",
    "ErrorRecoveryStrategy",
    "ErrorSeverity",
    "EventMetadata",
    "EventSeverity",
    "ExecutionInstruction",
    "ExecutionResult",
    "ExecutionResultMessage",
    "ExecutionStatus",
    "ExposureSummary",
    "FailedDetails",
    "FailedEvent",
    "FeatureSnapshotRequest",
    "FeatureUpdateMessage",
    "FillEventMessage",
    "FillEventPubSubPayload",
    "FuturesTermStructureRecord",
    "HealthAlertMessage",
    "HealthStatusEnum",
    # ml
    "InferenceRequest",
    "InferenceResult",
    "InstructionRecord",
    "InstrumentRecord",
    "InstrumentType",
    "InternalPosition",
    "InternalPubSubTopic",
    "LifecycleEventEnvelope",
    "LifecycleEventType",
    "LiquidationMessage",
    "LiquidationRecord",
    "MLConfigDict",
    "MLPredictionMessage",
    "ManualInstructionRequest",
    "ManualInstructionResponse",
    "MarginState",
    "MarketTickMessage",
    "MarketTrade",
    "ModelMetadata",
    "ModelType",
    "ModelVariantConfig",
    "OhlcvBar",
    "OperationType",
    "OptionType",
    "OptionsIvRecord",
    "OrderBookSnapshot5",
    "OrderRequestMessage",
    "OrderSide",
    "OrderStatus",
    "OrderSubmittedMessage",
    "OrderType",
    "PersistenceCompletedDetails",
    "PersistenceStartedDetails",
    "PositionSide",
    "PositionUpdateMessage",
    "PreTradeCheckRequest",
    "PreTradeCheckResponse",
    "ProcessedCandle",
    "ProcessingCompletedDetails",
    "ProcessingStartedDetails",
    "PubSubLifecycleEventMessage",
    "PubSubMessageEnvelope",
    "QuoteRecord",
    "RiskAlertMessage",
    "RiskMetrics",
    "RiskPosition",
    "RiskStatus",
    "SLHitMessage",
    "SecretAccessedDetails",
    "SecretAccessedEvent",
    "ServiceHealthStatus",
    "ServiceLifecycleEventMessage",
    "ServiceMode",
    # sor
    "SorChildOrder",
    "SorExecutionSummary",
    "SorRouteDecision",
    "SorTwapSlice",
    "SorVenueCapacity",
    "SorVenueScore",
    "StartedDetails",
    "StartedEvent",
    "StrategyInstruction",
    "StrategySignalMessage",
    "TPHitMessage",
    "TargetType",
    "TimeInForce",
    "TrainingJobRequest",
    "TrainingJobResult",
    "TrainingPeriod",
    "ValidationCompletedDetails",
    "ValidationStartedDetails",
]
