"""CF-18 schema-attribute completeness regression suite (V3; operator
ratification 2026-06-11 decision #2 — CITADEL, carry ALL source columns).

Two layers:

1. **Registry round-trip + alias hygiene** — every ``SchemaSpec`` resolves via
   ``find_schema`` (unique ``(asset_group, data_type)`` key), no duplicate
   canonical names, no alias shadowing a canonical name within a spec.
2. **Source-column completeness fixtures** — the per-(asset_group, data_type,
   venue) column sets below are the UNIONED ACTUAL prod parquet footers
   sampled 2026-06-11 by ``migration_schema_completeness.py`` riding the
   ``orphan_sweep_<ag>.parquet`` object lists (3-5 objects per cell, real GCS
   ``market-data-tick-{defi,tradfi,pred}-prd`` buckets). The previously-RED
   cells (prediction/trades/POLYMARKET's 11 dropped columns, the 7 defi
   dex_pool_swaps/lending_indices cells, tradfi/options_chain/CME) and every
   previously contract-less data_type MUST be fully carried — a regression
   here means a source column would be silently truncated on the G4
   migration (the "forced v10" failure mode this gate exists to prevent).

The carried-set semantics (canonical names ∪ ``source_aliases``) mirror the
audit script via :func:`carried_column_names` — the matching SSOT lives HERE
in UAC so the migrator's rename map and the audit's verdict cannot drift.

Plan ref: ``plans/active/migration_verification_orphan_safety_2026_06_10.md``
§ V3/CF-18.
"""

from __future__ import annotations

import pytest

from unified_api_contracts.registry.schema_spec import (
    SCHEMA_SPEC_REGISTRY,
    SchemaSpec,
    carried_column_names,
    find_schema,
)

# Mirror of the audit's ``_PARTITION_AND_META_COLUMNS`` (hive path keys +
# writer/manifest bookkeeping — never part of a data_type's column contract).
_PARTITION_AND_META_COLUMNS: frozenset[str] = frozenset(
    {
        "asset_group",
        "category",
        "venue",
        "chain",
        "instrument_type",
        "instrument_id",
        "data_type",
        "day",
        "date",
        "pipeline_mode",
        "source",
        "transport",
        "available_at",
        "schema_version",
        "league_id",
        "canonical_question_group",
        "feature_group",
        "feature_group_version",
        "timeframe",
    }
)

# Unioned ACTUAL prod parquet footer columns per sampled cell (2026-06-11).
_SAMPLED_SOURCE_COLUMNS: dict[tuple[str, str, str], set[str]] = {
    ("defi", "dex_pool_state", "CURVE"): {
        "amount_in",
        "amount_in_usd",
        "amount_out",
        "amount_out_usd",
        "block_number",
        "chain",
        "data_source",
        "data_type",
        "date",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "pool_address",
        "pool_balances",
        "timestamp",
        "token_in",
        "token_in_address",
        "token_out",
        "token_out_address",
        "total_liquidity_tokens",
        "tx_hash",
        "venue",
        "virtual_price",
    },
    ("defi", "dex_pool_state", "UNISWAP_V2"): {
        "amount0",
        "amount0_in",
        "amount0_out",
        "amount1",
        "amount1_in",
        "amount1_out",
        "amountUSD",
        "block_number",
        "chain",
        "data_source",
        "data_type",
        "date",
        "hourlyTxns",
        "hourlyVolumeToken0",
        "hourlyVolumeToken1",
        "hourlyVolumeUSD",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "pair_address",
        "reserve0",
        "reserve1",
        "reserveUSD",
        "sender",
        "timestamp",
        "to",
        "token0_address",
        "token0_symbol",
        "token1_address",
        "token1_symbol",
        "tx_hash",
        "venue",
    },
    ("defi", "dex_pool_state", "UNISWAP_V3"): {
        "amount0",
        "amount1",
        "amountUSD",
        "block_number",
        "chain",
        "close",
        "data_source",
        "data_type",
        "date",
        "feeGrowthGlobal0X128",
        "feeGrowthGlobal1X128",
        "feesUSD",
        "high",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidity",
        "low",
        "open",
        "pool_address",
        "sqrtPrice",
        "sqrtPriceX96",
        "tick",
        "timestamp",
        "token0Price",
        "token1Price",
        "tvlUSD",
        "tx_hash",
        "venue",
        "volumeToken0",
        "volumeToken1",
        "volumeUSD",
    },
    ("defi", "dex_pool_state", "UNISWAP_V4"): {
        "amount0",
        "amount1",
        "amountUSD",
        "block_number",
        "chain",
        "close",
        "data_source",
        "data_type",
        "date",
        "high",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidity",
        "low",
        "open",
        "pool_id",
        "sender",
        "sqrtPrice",
        "sqrtPriceX96",
        "tick",
        "timestamp",
        "token0Price",
        "token0_address",
        "token0_symbol",
        "token1Price",
        "token1_address",
        "token1_symbol",
        "tvlUSD",
        "txCount",
        "tx_hash",
        "venue",
        "volumeToken0",
        "volumeToken1",
        "volumeUSD",
    },
    ("defi", "dex_pool_swaps", "CURVE"): {
        "amount_in",
        "amount_in_usd",
        "amount_out",
        "amount_out_usd",
        "block_number",
        "chain",
        "data_source",
        "data_type",
        "date",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "pool_address",
        "pool_balances",
        "timestamp",
        "token_in",
        "token_in_address",
        "token_out",
        "token_out_address",
        "total_liquidity_tokens",
        "tx_hash",
        "venue",
        "virtual_price",
    },
    ("defi", "dex_pool_swaps", "UNISWAP_V2"): {
        "amount0",
        "amount0_in",
        "amount0_out",
        "amount1",
        "amount1_in",
        "amount1_out",
        "amountUSD",
        "block_number",
        "chain",
        "data_source",
        "data_type",
        "date",
        "hourlyTxns",
        "hourlyVolumeToken0",
        "hourlyVolumeToken1",
        "hourlyVolumeUSD",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "pair_address",
        "reserve0",
        "reserve1",
        "reserveUSD",
        "sender",
        "timestamp",
        "to",
        "token0_address",
        "token0_symbol",
        "token1_address",
        "token1_symbol",
        "tx_hash",
        "venue",
    },
    ("defi", "dex_pool_swaps", "UNISWAP_V3"): {
        "amount0",
        "amount1",
        "amountUSD",
        "block_number",
        "chain",
        "close",
        "data_source",
        "data_type",
        "date",
        "feeGrowthGlobal0X128",
        "feeGrowthGlobal1X128",
        "feesUSD",
        "high",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidity",
        "low",
        "open",
        "pool_address",
        "sqrtPrice",
        "sqrtPriceX96",
        "tick",
        "timestamp",
        "token0Price",
        "token1Price",
        "tvlUSD",
        "tx_hash",
        "venue",
        "volumeToken0",
        "volumeToken1",
        "volumeUSD",
    },
    ("defi", "dex_pool_swaps", "UNISWAP_V4"): {
        "amount0",
        "amount1",
        "amountUSD",
        "block_number",
        "chain",
        "close",
        "data_source",
        "data_type",
        "date",
        "high",
        "id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidity",
        "low",
        "open",
        "pool_id",
        "sender",
        "sqrtPrice",
        "sqrtPriceX96",
        "tick",
        "timestamp",
        "token0Price",
        "token0_address",
        "token0_symbol",
        "token1Price",
        "token1_address",
        "token1_symbol",
        "tvlUSD",
        "txCount",
        "tx_hash",
        "venue",
        "volumeToken0",
        "volumeToken1",
        "volumeUSD",
    },
    ("defi", "dex_pool_state", "ORCA"): {
        "chain",
        "data_type",
        "fee_apr_day",
        "fee_apr_month",
        "fee_apr_week",
        "fee_rate_bps",
        "instrument_id",
        "instrument_type",
        "pool_id",
        "price",
        "protocol",
        "symbol",
        "tick_spacing",
        "timestamp",
        "token_a",
        "token_b",
        "tvl_usd",
        "venue",
        "volume_month",
        "volume_usd",
        "volume_week",
    },
    ("defi", "dex_pool_state", "RAYDIUM"): {
        "chain",
        "data_type",
        "fee_apr_day",
        "fee_rate_bps",
        "instrument_id",
        "instrument_type",
        "pool_id",
        "pool_type",
        "price",
        "protocol",
        "symbol",
        "timestamp",
        "token_a",
        "token_b",
        "tvl_usd",
        "venue",
        "volume_usd",
    },
    ("defi", "dex_pool_swaps", "AERODROME_V3"): {
        "amount0",
        "amount1",
        "amount_usd",
        "available_at",
        "chain",
        "data_type",
        "fee_rate_bps",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "protocol",
        "recipient",
        "sender",
        "swap_id",
        "symbol",
        "tick",
        "timestamp",
        "token_a",
        "token_b",
        "venue",
    },
    ("defi", "dex_pool_swaps", "BALANCER"): {
        "amount_in",
        "amount_out",
        "amount_usd",
        "available_at",
        "caller",
        "chain",
        "data_type",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "pool_name",
        "protocol",
        "swap_id",
        "symbol",
        "timestamp",
        "token_in",
        "token_out",
        "user",
        "venue",
    },
    ("defi", "dex_pool_swaps", "CAMELOT_V3"): {
        "amount0",
        "amount1",
        "amount_usd",
        "available_at",
        "chain",
        "data_type",
        "fee_rate_bps",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "protocol",
        "recipient",
        "sender",
        "swap_id",
        "symbol",
        "tick",
        "timestamp",
        "token_a",
        "token_b",
        "venue",
    },
    ("defi", "dex_pool_swaps", "PANCAKESWAP_V3"): {
        "amount0",
        "amount1",
        "amount_usd",
        "available_at",
        "chain",
        "data_type",
        "fee_rate_bps",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "protocol",
        "recipient",
        "sender",
        "swap_id",
        "symbol",
        "tick",
        "timestamp",
        "token_a",
        "token_b",
        "venue",
    },
    ("defi", "dex_pool_swaps", "SUSHISWAP"): {
        "amount_in",
        "amount_in_usd",
        "amount_out",
        "amount_out_usd",
        "available_at",
        "chain",
        "data_type",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "pool_name",
        "protocol",
        "sender",
        "swap_id",
        "symbol",
        "timestamp",
        "token_in",
        "token_out",
        "tx_hash",
        "venue",
    },
    ("defi", "dex_pool_swaps", "SUSHISWAP_V3"): {
        "amount_in",
        "amount_in_usd",
        "amount_out",
        "amount_out_usd",
        "available_at",
        "chain",
        "data_type",
        "instrument_id",
        "instrument_type",
        "pair_address",
        "pool_address",
        "pool_id",
        "pool_name",
        "protocol",
        "sender",
        "swap_id",
        "symbol",
        "timestamp",
        "token_in",
        "token_out",
        "tx_hash",
        "venue",
    },
    ("defi", "lending_indices", "KAMINO"): {
        "apy",
        "chain",
        "data_type",
        "instrument_id",
        "instrument_type",
        "market_id",
        "protocol",
        "reward_apy",
        "supply_apy",
        "symbol",
        "timestamp",
        "tvl_usd",
        "venue",
    },
    ("defi", "lending_indices", "MARGINFI"): {
        "apy",
        "chain",
        "data_quality",
        "data_type",
        "instrument_id",
        "instrument_type",
        "market_id",
        "protocol",
        "reward_apy",
        "supply_apy",
        "symbol",
        "timestamp",
        "tvl_usd",
        "venue",
    },
    ("defi", "lending_indices", "SOLEND"): {
        "apy",
        "chain",
        "data_type",
        "instrument_id",
        "instrument_type",
        "market_id",
        "protocol",
        "reward_apy",
        "supply_apy",
        "symbol",
        "timestamp",
        "tvl_usd",
        "venue",
    },
    ("defi", "lst_rates", "MARINADE"): {
        "apy",
        "chain",
        "data_type",
        "exchange_rate",
        "instrument_id",
        "instrument_type",
        "protocol",
        "quote_asset",
        "symbol",
        "timestamp",
        "token",
        "total_staked",
        "venue",
    },
    ("defi", "oracle_prices", "AAVE_V3"): {
        "block_number",
        "borrow_rate_apy",
        "chain",
        "data_source",
        "data_type",
        "date",
        "emode_category_id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidation_bonus",
        "liquidation_threshold",
        "liquidity_index",
        "liquidity_rate_apy",
        "ltv",
        "oracle_price",
        "oracle_price_usd",
        "price_usd",
        "reserve_factor",
        "stable_borrow_rate_apy",
        "supply_rate_apy",
        "timestamp",
        "token",
        "total_borrow",
        "total_supply",
        "utilization_rate",
        "variable_borrow_index",
        "variable_borrow_rate_apy",
        "venue",
    },
    ("defi", "oracle_prices", "ETHENA"): {
        "chain",
        "data_type",
        "date",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "price_usd",
        "source",
        "timestamp",
        "venue",
    },
    ("defi", "oracle_prices", "ETHERFI"): {
        "block_number",
        "chain",
        "daily_yield_pct",
        "data_quality",
        "data_source",
        "data_type",
        "date",
        "eth_price_usd",
        "exchange_rate_eth",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "oracle_price",
        "price_usd",
        "reward_per_eeth",
        "reward_token",
        "reward_type",
        "timestamp",
        "token",
        "venue",
    },
    ("defi", "oracle_prices", "LIDO"): {
        "block_number",
        "chain",
        "data_source",
        "data_type",
        "date",
        "eth_price_usd",
        "exchange_rate_eth",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "oracle_price",
        "price_usd",
        "timestamp",
        "token",
        "venue",
    },
    ("defi", "rate_indices", "AAVE_V3"): {
        "block_number",
        "borrow_rate_apy",
        "chain",
        "data_source",
        "data_type",
        "date",
        "emode_category_id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidation_bonus",
        "liquidation_threshold",
        "liquidity_index",
        "liquidity_rate_apy",
        "ltv",
        "oracle_price",
        "oracle_price_usd",
        "price_usd",
        "reserve_factor",
        "stable_borrow_rate_apy",
        "supply_rate_apy",
        "timestamp",
        "token",
        "total_borrow",
        "total_supply",
        "utilization_rate",
        "variable_borrow_index",
        "variable_borrow_rate_apy",
        "venue",
    },
    ("defi", "rate_indices", "MORPHO"): {
        "borrow_apy",
        "borrow_index",
        "chain",
        "data_type",
        "date",
        "input_token_price_usd",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "supply_apy",
        "supply_index",
        "timestamp",
        "total_borrow",
        "total_supply",
        "tvl_usd",
        "utilization_rate",
        "venue",
    },
    ("defi", "rewards", "EIGENLAYER"): {
        "amount",
        "amount_eth",
        "amount_usd",
        "block_number",
        "data_type",
        "date",
        "earner",
        "eigenlayer_tvl_usd",
        "instrument_id",
        "token_address",
        "token_symbol",
        "usd_price",
        "venue",
    },
    ("defi", "rewards", "ETHERFI"): {
        "block_number",
        "chain",
        "daily_yield_pct",
        "data_quality",
        "data_source",
        "data_type",
        "date",
        "eth_price_usd",
        "exchange_rate_eth",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "oracle_price",
        "price_usd",
        "reward_per_eeth",
        "reward_token",
        "reward_type",
        "timestamp",
        "token",
        "venue",
    },
    ("defi", "risk_params", "AAVE_V3"): {
        "block_number",
        "borrow_rate_apy",
        "chain",
        "data_source",
        "data_type",
        "date",
        "emode_category_id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidation_bonus",
        "liquidation_threshold",
        "liquidity_index",
        "liquidity_rate_apy",
        "ltv",
        "oracle_price",
        "oracle_price_usd",
        "price_usd",
        "reserve_factor",
        "stable_borrow_rate_apy",
        "supply_rate_apy",
        "timestamp",
        "token",
        "total_borrow",
        "total_supply",
        "utilization_rate",
        "variable_borrow_index",
        "variable_borrow_rate_apy",
        "venue",
    },
    ("defi", "utilization", "AAVE_V3"): {
        "block_number",
        "borrow_rate_apy",
        "chain",
        "data_source",
        "data_type",
        "date",
        "emode_category_id",
        "instrument_id",
        "instrument_key",
        "instrument_type",
        "liquidation_bonus",
        "liquidation_threshold",
        "liquidity_index",
        "liquidity_rate_apy",
        "ltv",
        "oracle_price",
        "oracle_price_usd",
        "price_usd",
        "reserve_factor",
        "stable_borrow_rate_apy",
        "supply_rate_apy",
        "timestamp",
        "token",
        "total_borrow",
        "total_supply",
        "utilization_rate",
        "variable_borrow_index",
        "variable_borrow_rate_apy",
        "venue",
    },
    ("tradfi", "ohlcv_15m", ""): {"close", "high", "instrument_key", "low", "open", "ts_event", "ts_init", "volume"},
    ("tradfi", "ohlcv_15m", "CBOE"): {
        "close",
        "data_type",
        "high",
        "instrument_key",
        "low",
        "open",
        "phase",
        "session",
        "symbol",
        "ts_event",
        "ts_init",
        "volume",
    },
    ("tradfi", "ohlcv_1m", ""): {
        "close",
        "high",
        "instrument_key",
        "low",
        "open",
        "symbol",
        "timestamp",
        "ts_event",
        "ts_init",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_1m", "CBOE"): {
        "close",
        "high",
        "instrument_key",
        "low",
        "open",
        "symbol",
        "timestamp",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_1m", "CME"): {
        "available_at",
        "close",
        "data_type",
        "high",
        "instrument_id",
        "instrument_type",
        "lifecycle_phase",
        "low",
        "open",
        "phase",
        "publisher_id",
        "rtype",
        "session",
        "symbol",
        "timestamp",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_1m", "ICE"): {
        "close",
        "data_type",
        "high",
        "instrument_id",
        "instrument_type",
        "low",
        "open",
        "phase",
        "publisher_id",
        "rtype",
        "session",
        "symbol",
        "timestamp",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_1m", "NASDAQ"): {
        "close",
        "data_type",
        "high",
        "instrument_id",
        "instrument_type",
        "low",
        "open",
        "phase",
        "publisher_id",
        "rtype",
        "session",
        "symbol",
        "timestamp",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_1m", "NYSE"): {
        "close",
        "data_type",
        "high",
        "instrument_id",
        "instrument_type",
        "low",
        "open",
        "phase",
        "publisher_id",
        "rtype",
        "session",
        "symbol",
        "timestamp",
        "underlying",
        "volume",
    },
    ("tradfi", "ohlcv_24h", ""): {"close", "high", "instrument_key", "low", "open", "ts_event", "ts_init", "volume"},
    ("tradfi", "ohlcv_24h", "FX"): {
        "close",
        "data_type",
        "high",
        "instrument_type",
        "low",
        "open",
        "symbol",
        "timestamp",
        "underlying",
        "venue",
        "volume",
    },
    ("tradfi", "options_chain", "CME"): {
        "close",
        "data_type",
        "high",
        "instrument_key",
        "low",
        "open",
        "ts_event",
        "ts_init",
        "underlying",
        "volume",
    },
    ("tradfi", "tbbo", "CME"): {
        "action",
        "amount",
        "ask_ct_00",
        "ask_px_00",
        "ask_sz_00",
        "bid_ct_00",
        "bid_px_00",
        "bid_sz_00",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "tbbo", "ICE"): {
        "action",
        "ask_ct_00",
        "ask_px_00",
        "ask_sz_00",
        "bid_ct_00",
        "bid_px_00",
        "bid_sz_00",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "size",
        "symbol",
        "ts_event",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "tbbo", "NASDAQ"): {
        "action",
        "amount",
        "ask_ct_00",
        "ask_px_00",
        "ask_sz_00",
        "bid_ct_00",
        "bid_px_00",
        "bid_sz_00",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "tbbo", "NYSE"): {
        "action",
        "amount",
        "ask_ct_00",
        "ask_px_00",
        "ask_sz_00",
        "bid_ct_00",
        "bid_px_00",
        "bid_sz_00",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "trades", "CME"): {
        "action",
        "amount",
        "available_at",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "lifecycle_phase",
        "phase",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "session",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "trades", "ICE"): {
        "action",
        "amount",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "trades", "NASDAQ"): {
        "action",
        "amount",
        "available_at",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "lifecycle_phase",
        "phase",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "session",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("tradfi", "trades", "NYSE"): {
        "action",
        "amount",
        "data_type",
        "depth",
        "flags",
        "instrument_id",
        "instrument_type",
        "price",
        "publisher_id",
        "rtype",
        "sequence",
        "side",
        "symbol",
        "timestamp",
        "ts_in_delta",
        "underlying",
    },
    ("prediction", "trades", "POLYMARKET"): {
        "amount",
        "asset",
        "asset_group",
        "chain",
        "conditionId",
        "condition_id",
        "data_source",
        "data_type",
        "instrument_id",
        "instrument_type",
        "market_type",
        "outcome",
        "outcomeIndex",
        "price",
        "resolution_period",
        "side",
        "symbol",
        "timestamp",
        "transactionHash",
        "underlying",
    },
}

# The exact column lists the 2026-06-11 CF-18 runs reported as RED (dropped).
_PREVIOUSLY_RED: dict[tuple[str, str, str], set[str]] = {
    ("prediction", "trades", "POLYMARKET"): {
        "amount",
        "asset",
        "conditionId",
        "data_source",
        "market_type",
        "outcomeIndex",
        "resolution_period",
        "symbol",
        "timestamp",
        "transactionHash",
        "underlying",
    },
    ("tradfi", "options_chain", "CME"): {
        "close",
        "high",
        "instrument_key",
        "low",
        "open",
        "ts_event",
        "ts_init",
        "volume",
    },
    ("defi", "lending_indices", "KAMINO"): {
        "apy",
        "market_id",
        "protocol",
        "reward_apy",
        "supply_apy",
        "timestamp",
        "tvl_usd",
    },
    ("defi", "lending_indices", "MARGINFI"): {
        "apy",
        "data_quality",
        "market_id",
        "protocol",
        "reward_apy",
        "supply_apy",
        "timestamp",
        "tvl_usd",
    },
    ("defi", "dex_pool_swaps", "UNISWAP_V3"): {
        "amountUSD",
        "close",
        "data_source",
        "feeGrowthGlobal0X128",
        "feeGrowthGlobal1X128",
        "feesUSD",
        "high",
        "id",
        "instrument_key",
        "liquidity",
        "low",
        "open",
        "sqrtPrice",
        "sqrtPriceX96",
        "tick",
        "timestamp",
        "token0Price",
        "token1Price",
        "tvlUSD",
        "volumeToken0",
        "volumeToken1",
        "volumeUSD",
    },
    ("defi", "dex_pool_swaps", "CURVE"): {
        "amount_in",
        "amount_in_usd",
        "amount_out",
        "amount_out_usd",
        "data_source",
        "instrument_key",
        "pool_balances",
        "timestamp",
        "token_in",
        "token_in_address",
        "token_out",
        "token_out_address",
        "total_liquidity_tokens",
        "virtual_price",
    },
}


def _dropped(spec: SchemaSpec, source_columns: set[str]) -> set[str]:
    """The audit's RED condition: non-meta source columns absent from the
    carried set (canonical names ∪ source_aliases)."""
    carried = carried_column_names(spec)
    return {c for c in source_columns if c not in _PARTITION_AND_META_COLUMNS and c not in carried}


class TestRegistryRoundTrip:
    def test_every_spec_resolves_via_find_schema(self) -> None:
        for spec in SCHEMA_SPEC_REGISTRY:
            resolved = find_schema(spec.asset_group, spec.data_type)
            assert resolved is spec, f"find_schema round-trip failed for {spec.asset_group}/{spec.data_type}"

    def test_registry_keys_unique(self) -> None:
        keys = [(s.asset_group, s.data_type) for s in SCHEMA_SPEC_REGISTRY]
        assert len(keys) == len(set(keys)), "duplicate (asset_group, data_type) shadows find_schema"

    def test_find_schema_accepts_string_asset_group(self) -> None:
        assert find_schema("prediction", "trades") is not None
        assert find_schema("defi", "utilization") is not None
        assert find_schema("tradfi", "trades") is not None

    @pytest.mark.parametrize(
        ("asset_group", "data_type"),
        sorted({(ag, dt) for (ag, dt, _v) in _SAMPLED_SOURCE_COLUMNS}),
    )
    def test_every_sampled_data_type_has_a_spec(self, asset_group: str, data_type: str) -> None:
        """The 2026-06-11 coverage gaps (defi rewards/risk_params/utilization/
        dex_pool_state/dex_pools/dex_swaps/lst_rates/oracle_prices/rate_indices,
        tradfi trades/tbbo/ohlcv_*, prediction trades) stay closed."""
        if not data_type:
            pytest.skip("blank legacy data_type axis — not a contract key")
        assert find_schema(asset_group, data_type) is not None


class TestAliasHygiene:
    def test_no_duplicate_canonical_names(self) -> None:
        for spec in SCHEMA_SPEC_REGISTRY:
            names = [c.name for c in spec.columns]
            assert len(names) == len(set(names)), f"duplicate canonical column in {spec.asset_group}/{spec.data_type}"

    def test_alias_never_shadows_canonical_name(self) -> None:
        """An alias duplicating a canonical name in the same spec would be the
        cosmetic-GREEN antipattern (camelCase kept as a parallel column)."""
        for spec in SCHEMA_SPEC_REGISTRY:
            canonical = {c.name for c in spec.columns}
            for col in spec.columns:
                overlap = set(col.source_aliases) & canonical
                assert not overlap, (
                    f"{spec.asset_group}/{spec.data_type}.{col.name} aliases {overlap} shadow canonical columns"
                )

    def test_carried_includes_aliases(self) -> None:
        spec = find_schema("prediction", "trades")
        assert spec is not None
        carried = carried_column_names(spec)
        assert {"condition_id", "conditionId", "outcome_index", "outcomeIndex"} <= carried

    def test_prediction_trades_carries_market_question_metadata(self) -> None:
        """title/slug/event_slug added 2026-07-28 (operator ruling 2026-07-25,
        prediction_polymarket_legacy_dual_write_trees_metadata_loss_2026_07_24.md)
        — market-question metadata with no surviving copy elsewhere. Trader-PII
        fields (proxy_wallet/name/pseudonym/bio/profile_image) stay excluded."""
        spec = find_schema("prediction", "trades")
        assert spec is not None
        carried = carried_column_names(spec)
        assert {"title", "slug", "event_slug", "eventSlug"} <= carried
        pii_fields = {"proxy_wallet", "name", "pseudonym", "bio", "profile_image"}
        assert pii_fields.isdisjoint(carried)


class TestSourceColumnCompleteness:
    @pytest.mark.parametrize(
        ("asset_group", "data_type", "venue"),
        sorted(_SAMPLED_SOURCE_COLUMNS),
    )
    def test_no_silent_truncation(self, asset_group: str, data_type: str, venue: str) -> None:
        """Every non-meta column physically present in the sampled prod
        parquets is carried by the v9 contract (CF-18 GREEN, per cell)."""
        if not data_type:
            pytest.skip("blank legacy data_type axis — not a contract key")
        spec = find_schema(asset_group, data_type)
        assert spec is not None, f"no SchemaSpec for {asset_group}/{data_type}"
        dropped = _dropped(spec, _SAMPLED_SOURCE_COLUMNS[(asset_group, data_type, venue)])
        assert not dropped, f"RED {asset_group}/{data_type}/{venue} — dropped: {sorted(dropped)}"

    @pytest.mark.parametrize(("asset_group", "data_type", "venue"), sorted(_PREVIOUSLY_RED))
    def test_previously_red_columns_now_carried(self, asset_group: str, data_type: str, venue: str) -> None:
        """Pins the exact 2026-06-11 RED lists — the operator-ratified
        'no acked drops' decision (#2) regression guard."""
        spec = find_schema(asset_group, data_type)
        assert spec is not None
        dropped = _dropped(spec, _PREVIOUSLY_RED[(asset_group, data_type, venue)])
        assert not dropped, f"previously-RED columns dropped again: {sorted(dropped)}"
